Update build-ffmpeg

diff --git a/shell/ffmpeg/build-ffmpeg b/shell/ffmpeg/build-ffmpeg
--- a/shell/ffmpeg/build-ffmpeg
+++ b/shell/ffmpeg/build-ffmpeg
@@ -232,6 +232,68 @@ download()
 
 }
 
+download_git()
+{
+    dl_path="${packages}"
+    dl_url="${1}"
+    dl_file="${2}"
+    tdir="${dl_path}/${dl_file}"
+
+    # first download attempt
+    if [ ! -d "${tdir}" ]; then
+        echo "Downloading ${dl_file}"
+        sudo git clone -q "${dl_url}" "${tdir}"
+
+        # try download once more if first attempt failed
+        ec="${?}"
+        if [ "${ec}" -ne '0' ]; then
+            echo
+            echo "Failed to download ${2}. Exitcode ${ec}. Retrying in 10 seconds"
+            echo
+            read -t 10 -p 'Press enter to skip waiting.'
+            echo
+            sudo git clone -q "${dl_url}" "${tdir}"
+        fi
+
+        # check if second download attempt was successful
+        ec="${?}"
+        if [ "${ec}" -ne '0' ]; then
+            echo
+            echo "Failed to download ${2}. Exitcode ${ec}"
+            echo
+            exit 1
+        fi
+
+        echo 'Download Complete...'
+        echo
+    else
+        echo "${dl_file} is already downloaded."
+    fi
+
+    cd "${tdir}" || (
+        echo 'Script error!'
+        echo
+        echo "Unable to change the working directory to ${}"
+        echo
+        exit 1
+    )
+}
+
+github_api_fn()
+{
+    # SCRAPE GITHUB WEBSITE FOR LATEST REPO VERSION
+    net_timeout='5'
+    github_repo="${1}"
+    curl_cmd=$(curl -m "${net_timeout}" --request GET \
+        --url "https://api.github.com/" --header "Authorization: Bearer <github token>" \
+        --header "X-GitHub-Api-Version: 2022-11-28" \
+        -Ls "https://api.github.com/repos/${github_repo}/releases?per_page=1")
+    if [ "${?}" -eq '0' ]; then
+        github_ver=$(echo "${curl_cmd}" | jq -r '.[].tag_name')
+        github_ver=${github_ver#v}
+    fi
+}
+
 error_fn()
 {
     echo
@@ -779,12 +841,13 @@ else
     cnf_ops+=('--enable-gmp' '--enable-gnutls')
 fi
 
-if build 'cmake' '3.26.0'; then
-    download 'https://github.com/Kitware/CMake/releases/download/v3.26.0/cmake-3.26.0.tar.gz'
+github_api_fn 'Kitware/CMake' 2>/dev/null
+if build 'cmake' "${github_ver}"; then
+    download_git 'https://github.com/Kitware/CMake.git' "cmake-${github_ver}"
     execute ./configure --prefix="${workspace}" --parallel="${cpus}" -- -DCMAKE_USE_OPENSSL='OFF'
     execute make "-j${cpus}"
     execute make install
-    build_done 'cmake' '3.26.0'
+    build_done 'cmake' "${github_ver}"
 fi
 
 ##
