Update build-ffmpeg

diff --git a/shell/ffmpeg/build-ffmpeg b/shell/ffmpeg/build-ffmpeg
--- a/shell/ffmpeg/build-ffmpeg
+++ b/shell/ffmpeg/build-ffmpeg
@@ -2,24 +2,24 @@
 
 ##########################################################################
 ##
-##  GitHub: https://github.com/slyfox1186/script-repo
+##  GITHUB: https://github.com/slyfox1186/script-repo
 ##
-##  Forked from: https://github.com/markus-perl/ffmpeg-build-script/
+##  FORKED FROM: https://github.com/markus-perl/ffmpeg-build-script/
 ##
-##  Target Distro: Ubuntu Jammy 22.04.1 ( x86_x64 )
+##  TARGET DISTRO: UBUNTU JAMMY 22.04.1 ( x86_x64 )
 ##
-##  Purpose: To build FFmpeg from source code with addon development
-##           libraries also compiled from source code to ensure the
-##           latest in extra functionality.
+##  PURPOSE: TO BUILD FFMPEG FROM SOURCE CODE WITH ADDON DEVELOPMENT
+##           LIBRARIES ALSO COMPILED FROM SOURCE CODE TO ENSURE THE
+##           LATEST IN EXTRA FUNCTIONALITY.
 ##
-##  CUDA: If the CUDA libraries are not installed (for Geforce cards only)
-##        the user will be prompted for the script to install them so that
-##        hardware acceleration is enabled when building FFmpeg at the
-##        script's end.
+##  CUDA: IF THE CUDA LIBRARIES ARE NOT INSTALLED (FOR GEFORCE CARDS ONLY)
+##        THE USER WILL BE PROMPTED FOR THE SCRIPT TO INSTALL THEM SO THAT
+##        HARDWARE ACCELERATION IS ENABLED WHEN BUILDING FFMPEG AT THE
+##        SCRIPT'S END.
 ##
-##  Updated: 02.18.23
+##  UPDATED: 02.18.23
 ##
-##  Version: 2.21
+##  VERSION: 2.21
 ##
 ##########################################################################
 
@@ -38,8 +38,8 @@ fi
 ##
 
 progname="${0:2}"
-# Master branch snapshot
-ffmpeg_ver='N-110004-g1231003c3c'
+# THE FFMPEG VERSION WILL BE THE LATEST AVAILABLE WHEN RUNNING GIT CLONE
+ffmpeg_ver='latest'
 cuda_ver='12.1'
 script_ver='2.21'
 packages="${PWD}"/packages
@@ -250,7 +250,7 @@ execute()
     fi
 }
 
-# build command function
+# BUILD COMMAND FUNCTION
 build()
 {
     echo
@@ -292,7 +292,7 @@ library_exists()
     return 0
 }
 
-# confirm a build has completed function
+# CONFIRM A BUILD HAS COMPLETED FUNCTION
 build_done() { echo "${2}" > "${packages}/${1}.done"; }
 
 verify_binary_type()
@@ -313,7 +313,7 @@ verify_binary_type()
     esac
 }
 
-# cleanup all files function
+# CLEANUP ALL FILES FUNCTION
 cleanup()
 {
     remove_dir "${packages}"
@@ -322,7 +322,7 @@ cleanup()
     echo
 }
 
-# function to determine if a package is installed or not
+# FUNCTION TO DETERMINE IF A PACKAGE IS INSTALLED OR NOT
 installed() { return $(dpkg-query -W -f '${Status}\n' "${1}" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}'); }
 
 cuda_fail_fn()
@@ -372,9 +372,7 @@ gpu_arch_fn()
     fi
 }
 
-
-
-# print the options available when manually running the script
+# PRINT THE OPTIONS AVAILABLE WHEN MANUALLY RUNNING THE SCRIPT
 usage()
 {
     echo "Usage: ${progname} [OPTIONS]"
@@ -672,9 +670,6 @@ else
         cuda_add_fn
     elif [[ "${cuda_choice}" -eq '2' ]]; then
         echo
-        echo 'Continuing the build...'
-        sleep 2
-        echo
     fi
 fi
 
@@ -968,7 +963,7 @@ if ${nonfree}; then
 fi
 
 if build 'av1' 'b3e0d3e'; then
-  # libaom b3e0d3e == v3.6.0
+  # libaom b3e0d3e1 == v3.6.0
     download 'https://aomedia.googlesource.com/aom/+archive/b3e0d3e9c031bedbab10be456c55359d4be82d27.tar.gz' 'av1.tar.gz' 'av1'
     make_dir "${packages}/aom_build"
     cd "${packages}"/aom_build || exit 1
@@ -1004,16 +999,16 @@ if command_exists 'python3'; then
             execute ninja -C build install
             build_done 'lv2' '1.18.10'
         fi
-        if build 'waflib' 'aeef9f5'; then
-            download 'https://gitlab.com/drobilla/autowaf/-/archive/aeef9f5fdf416d9b68c61c75de7dae409f1ac6a4/autowaf-aeef9f5fdf416d9b68c61c75de7dae409f1ac6a4.tar.bz2' 'autowaf-aeef9f5.tar.bz2'
-            build_done 'waflib' 'aeef9f5'
+        if build 'waflib' 'aeef9f5f'; then
+            download 'https://gitlab.com/drobilla/autowaf/-/archive/aeef9f5fdf416d9b68c61c75de7dae409f1ac6a4/autowaf-aeef9f5fdf416d9b68c61c75de7dae409f1ac6a4.tar.bz2' 'autowaf-aeef9f5f.tar.bz2'
+            build_done 'waflib' 'aeef9f5f'
         fi
-        if build 'serd' 'b4ac1ec'; then
-            download 'https://gitlab.com/drobilla/serd/-/archive/b4ac1ec675b79cd05ed7ff2eda8f41002f3a51ef/serd-b4ac1ec675b79cd05ed7ff2eda8f41002f3a51ef.tar.bz2' 'serd-b4ac1ec.tar.bz2'
+        if build 'serd' '61d53637'; then
+            download 'https://gitlab.com/drobilla/serd/-/archive/61d53637dc62d15f9b3d1fa9e69891313c465c35/serd-61d53637dc62d15f9b3d1fa9e69891313c465c35.tar.bz2' 'serd-61d53637.tar.bz2'
             execute meson build --prefix="${workspace}" --buildtype='release' --default-library='static' --libdir="${workspace}"/lib
             execute ninja -C build
             execute ninja -C build install
-            build_done 'serd' 'b4ac1ec'
+            build_done 'serd' '61d53637'
         fi
         if build 'pcre' '8.45'; then
             download 'https://cfhcable.dl.sourceforge.net/project/pcre/pcre/8.45/pcre-8.45.tar.bz2' 'pcre-8.45.tar.bz2'
@@ -1029,13 +1024,12 @@ if command_exists 'python3'; then
             execute ninja -C build install
             build_done 'sord' '0.16.14'
         fi
-        if build 'sratom' '58418e5'; then
-            download 'https://gitlab.com/lv2/sratom/-/archive/58418e5be2a491faa44d6d1c8d57052b1444814a/sratom-58418e5be2a491faa44d6d1c8d57052b1444814a.tar.bz2'  'sratom-58418e5.tar.bz2'
-            # download 'https://gitlab.com/lv2/sratom/-/archive/v0.6.14/sratom-v0.6.14.tar.gz' 'sratom-v0.6.14.tar.gz'
+        if build 'sratom' 'f1f063c8'; then
+            download 'https://gitlab.com/lv2/sratom/-/archive/f1f063c8e170b2a6350eedf68c4859b974d85d5e/sratom-f1f063c8e170b2a6350eedf68c4859b974d85d5e.tar.bz2'  'sratom-f1f063c8.tar.bz2'
             execute meson build --prefix="${workspace}" --buildtype='release' --default-library='static' --libdir="${workspace}"/lib
             execute ninja -C build
             execute ninja -C build install
-            build_done 'sratom' '58418e5'
+            build_done 'sratom' 'f1f063c8'
         fi
         if build 'lilv' '0.24.20'; then
             download 'https://gitlab.com/lv2/lilv/-/archive/v0.24.20/lilv-v0.24.20.tar.gz' 'lilv-v0.24.20.tar.gz'
@@ -1123,7 +1117,7 @@ if ${nonfree}; then
 fi
 
 ##
-## image libraries
+## IMAGE LIBRARIES
 ##
 
 if build 'libtiff' '4.5.0'; then
@@ -1145,7 +1139,8 @@ if build 'libpng' '1.6.39'; then
 fi
 
 if build 'libwebp' '1.2.2'; then
-    # libwebp can fail to compile on Ubuntu if these flags were left set to CFLAGS
+    # LIBWEBP CAN FAIL TO COMPILE ON UBUNTU IF THESE FLAGS WERE LEFT SET TO CFLAGS
+    # SO FAR VERSION 1.3.0 AND 1.2.4 FAILES TO BUILD SUCCESFULLY
     CPPFLAGS=
     download 'https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.2.2.tar.gz' 'libwebp-1.2.2.tar.gz'
     execute ./configure --prefix="${workspace}" --disable-shared --enable-static --disable-dependency-tracking \
@@ -1197,11 +1192,12 @@ fi
 #####################
 
 if which 'nvcc' &>/dev/null ; then
-    if build 'nv-codec' '8.1.24.14'; then
-        download 'https://github.com/FFmpeg/nv-codec-headers/releases/download/n8.1.24.14/nv-codec-headers-8.1.24.14.tar.gz'
+    if build 'nv-codec' '12.0.16.0'; then
+        # PRIOR VERSION USED '8.1.24.14'
+        download 'https://github.com/FFmpeg/nv-codec-headers/releases/download/n12.0.16.0/nv-codec-headers-12.0.16.0.tar.gz'
         execute make PREFIX="${workspace}"
         execute make install PREFIX="${workspace}"
-        build_done 'nv-codec' '8.1.24.14'
+        build_done 'nv-codec' '12.0.16.0'
     fi
     CFLAGS+=' -I/usr/local/cuda-12.0/include'
     LDFLAGS+=' -L/usr/local/cuda-12.0/lib64'
@@ -1246,9 +1242,9 @@ if [ -d "${packages}/ffmpeg-latest" ]; then
 fi
 
 # CLONE FFMPEG FROM THE LATEST GIT RELEASE
-build 'ffmpeg' 'latest'
-git clone -q 'https://github.com/FFmpeg/FFmpeg.git' "${packages}/ffmpeg-latest"
-cd "${packages}/ffmpeg-latest" || exit 1
+build 'ffmpeg' "${ffmpeg_ver}"
+git clone -q 'https://github.com/FFmpeg/FFmpeg.git' "${packages}/ffmpeg-${ffmpeg_ver}"
+cd "${packages}/ffmpeg-${ffmpeg_ver}" || exit 1
 # shellcheck disable=SC2086
 ./configure \
     "${cnf_ops[@]}" \
