Update build-ffmpeg

diff --git a/shell/ffmpeg/build-ffmpeg b/shell/ffmpeg/build-ffmpeg
--- a/shell/ffmpeg/build-ffmpeg
+++ b/shell/ffmpeg/build-ffmpeg
@@ -38,7 +38,7 @@ fi
 
 script_ver='3.2'
 progname="${0:2}"
-ffmpeg_ver='6.0'
+ffmpeg_ver='n5.1.3'
 cuda_ver='12.1'
 packages="$PWD"/packages
 workspace="$PWD"/workspace
@@ -81,6 +81,14 @@ fail_fn()
     echo 'Please create a support ticket'
     echo
     echo 'https://github.com/slyfox1186/script-repo/issues'
+    echo
+    exit 1
+}
+
+fail_pkg_fn()
+{
+    echo
+    echo "The '$1' package is not installed. It is required for this script to run."
     echo
     exit 1
 }
@@ -182,11 +190,7 @@ download()
                 echo
                 echo "The script failed to download \"$1\" two times and will exit the build"
                 echo
-                echo 'Please create a support ticket'
-                echo
-                echo 'https://github.com/slyfox1186/script-repo/issues'
-                echo
-                exit 1
+                fail_fn
             fi
         fi
         echo 'Download Completed'
@@ -201,13 +205,13 @@ download()
         if ! tar -xf "$dl_path/$dl_file" -C "$dl_path/$target_dir" &>/dev/null; then
             echo "Failed to extract $dl_file"
             echo
-            exit 1
+            fail_fn
         fi
     else
         if ! tar -xf "$dl_path/$dl_file" -C "$dl_path/$target_dir" --strip-components 1 &>/dev/null; then
             echo "Failed to extract $dl_file"
             echo
-            exit 1
+            fail_fn
         fi
     fi
 
@@ -218,7 +222,7 @@ download()
         echo
         echo "Unable to change the working directory to $target_dir"
         echo
-        exit 1
+        fail_fn
     )
 }
 
@@ -343,7 +347,7 @@ git_ver_fn()
 
     v_url="$1"
     v_tag="$2"
- 
+
     if [ -n "$3" ]; then
         v_flag="$3"
     fi
@@ -354,7 +358,7 @@ git_ver_fn()
 
         return 0
     fi
-    
+
 
     if [  "$v_flag" = 'T' ] && [  "$v_tag" = '1' ]; then
         url_tag='git_1_fn' gv_url='tags'
@@ -377,7 +381,7 @@ git_ver_fn()
         7)          url_tag='git_7_fn';;
     esac
 
-    case "$v_tag" in 
+    case "$v_tag" in
         2)          url_tag='git_2_fn';;
         3)          url_tag='git_3_fn';;
         4)          url_tag='git_4_fn';;
@@ -398,7 +402,7 @@ execute()
         echo
         echo "Failed to Execute $*" >&2
         echo
-        exit 1
+        fail_fn
     fi
 }
 
@@ -557,7 +561,7 @@ while (($# > 0)); do
     *)
         usage
         echo
-        exit 1
+        fail_fn
         ;;
     esac
 done
@@ -565,8 +569,6 @@ done
 if [ -z "$bflag" ]; then
     if [ -z "$cflag" ]; then
         usage
-        echo
-        exit 1
     fi
     exit 0
 fi
@@ -589,7 +591,7 @@ mkdir -p "$packages"
 mkdir -p "$workspace"
 
 # set global variables
-JAVA_HOME='/usr/lib/jvm/java-19-openjdk-amd64/bin'
+JAVA_HOME='/usr/lib/jvm/java-17-openjdk-amd64'
 export JAVA_HOME
 
 # libbluray requries that this variable be set
@@ -613,39 +615,35 @@ $workspace/lib/pkgconfig:\
 "
 export PKG_CONFIG_PATH
 
-LD_LIBRARY_PATH="$workspace\lib\pkgconfig"
+LD_LIBRARY_PATH="$workspace/lib/pkgconfig"
 export LD_LIBRARY_PATH
 
 if ! command_exists 'make'; then
-    echo 'The '\''make'\'' package is not installed. It is required for this script to run.'
-    echo
-    exit 1
+    fail_pkg_fn 'make'
 fi
 
 if ! command_exists 'g++'; then
-    echo 'The '\''g++'\'' package is not installed. It is required for this script to run.'
-    echo
-    exit 1
+    fail_pkg_fn 'g++'
 fi
 
 if ! command_exists 'curl'; then
-    echo 'The '\''curl'\'' package is not installed. It is required for this script to run.'
-    echo
-    exit 1
+    fail_pkg_fn 'curl'
 fi
 
 if ! command_exists 'jq'; then
-    echo 'The '\''jq'\'' package is not installed. It is required for this script to run.'
-    echo
-    exit 1
+    fail_pkg_fn 'jq'
 fi
 
 if ! command_exists 'cargo'; then
-    echo 'The '\''cargo'\'' command was not found. rav1e encoder will not be available.'
+    echo 'The '\''cargo'\'' command was not found.'
+    echo
+    echo 'The rav1e encoder will not be available.'
 fi
 
 if ! command_exists 'python3'; then
-    echo 'The '\''python3'\'' command was not found. The '\''Lv2'\'' filter and '\''dav1d'\'' decoder will not be available.'
+    echo 'The '\''python3'\'' command was not found.'
+    echo
+    echo 'The '\''Lv2'\'' filter and '\''dav1d'\'' decoder will not be available.'
 fi
 
 cuda_fn()
@@ -708,10 +706,13 @@ cuda_fn()
     sudo apt -y install cuda
 
     # CHECK IF THE CUDA FOLDER EXISTS TO ENSURE IT WAS INSTALLED
-    if [ ! -d "/usr/local/cuda-$cuda_ver/bin" ]; then
+    iscuda="$(sudo find /usr/local/ -type f -name nvcc)"
+    cudaPATH="$(sudo find /usr/local/ -type f -name nvcc | grep -Eo '^.*\/bi[n]?')"
+
+    if [ -z "$cudaPATH" ]; then
         cuda_fail_fn
     else
-        PATH="$PATH:/usr/local/cuda-$cuda_ver/bin"
+        PATH="$PATH:$cudaPATH"
         export PATH
     fi
 }
@@ -729,7 +730,7 @@ build_pkgs_fn()
     pkgs=(ant g++ gcc gtk-doc-tools help2man javacc jq junit \
           libcairo2-dev libcdio-paranoia-dev libcurl4-gnutls-dev \
           libglib2.0-dev libmusicbrainz5-dev libtinyxml2-dev \
-          libudfread-dev openjdk-19-jdk pkg-config ragel)
+          openjdk-17-jdk pkg-config ragel)
 
     for pkg in ${pkgs[@]}
     do
@@ -741,10 +742,14 @@ build_pkgs_fn()
     if [ -n "$missing_pkgs" ]; then
         for pkg in "$missing_pkgs"
         do
-            sudo apt install $pkg
+            if sudo apt install $pkg; then
+                echo 'The required development packages were installed.'
+            else
+                echo 'The required development packages failed to install'
+                echo
+                exit 1
+            fi
         done
-        echo 'The required development packages were installed.'
-    else
         echo 'The required development packages are already installed.'
     fi
 }
@@ -784,7 +789,10 @@ install_cuda_fn()
 {
     local cuda_ans cuda_choice
 
-    if ! which 'nvcc' &>/dev/null ; then
+    iscuda="$(sudo find /usr/local/ -type f -name nvcc)"
+    cudaPATH="$(sudo find /usr/local/ -type f -name nvcc | grep -Eo '^.*\/bi[n]?')"
+
+    if [ -z "$iscuda" ]; then
         echo
         echo 'The cuda-sdk-toolkit isn'\''t installed or it is not in $PATH'
         echo '==============================================================='
@@ -802,7 +810,7 @@ install_cuda_fn()
             cuda_add_fn
         elif [[ "$cuda_ans" -eq '2' ]]; then
             if [ -d '/usr/local/cuda-12.1/bin' ]; then
-                PATH="$PATH:/usr/local/cuda-12.1/bin"
+                PATH="$PATH:$cudaPATH"
                 export PATH
             else
                 echo 'The script was unable to add cuda to your $PATH because the required folder was not found: /usr/local/cuda-12.1/bin'
@@ -835,6 +843,8 @@ install_cuda_fn()
             cuda_fn
             cuda_add_fn
         elif [[ "$cuda_choice" -eq '2' ]]; then
+            PATH="$PATH:$cudaPATH"
+            export PATH
             echo 'Continuing the build...'
         else
             echo
@@ -872,7 +882,7 @@ fi
 
 git_ver_fn 'freedesktop/pkg-config' '1' 'T'
 if build 'pkg-config' "${g_ver_pkg}"; then
-    download "https://pkgconfig.freedesktop.org/releases/$g_ver.tar.gz" "$g_ver.tar.gz"
+    download "https://pkgconfig.freedesktop.org/releases/$g_ver.tar.gz" "$g_ver_pkg.tar.gz"
     execute ./configure --silent --prefix="$workspace" --with-pc-path="$workspace"/lib/pkgconfig/ --with-internal-glib
     execute make "-j$cpus"
     execute make install
@@ -1010,7 +1020,7 @@ if command_exists 'python3'; then
         if build 'dav1d' "$videolan_sver"; then
             download "https://code.videolan.org/videolan/dav1d/-/archive/$videolan_ver/$videolan_ver.tar.gz" "dav1d-$videolan_sver.tar.gz"
             make_dir build
-            execute meson setup build --prefix="$workspace" --buildtype='release' --default-library='static' --libdir="$workspace"/lib
+            execute meson setup build --prefix="$workspace" --buildtype='Release' --default-library='static' --libdir="$workspace"/lib
             execute ninja -C build
             execute ninja -C build install
             build_done 'dav1d' "$videolan_sver"
@@ -1023,7 +1033,8 @@ git_ver_fn '24327400' '4'
 if build 'svtav1' "$gitlab_ver"; then
     download "https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v$gitlab_ver/SVT-AV1-v$gitlab_ver.tar.bz2" "SVT-AV1-$gitlab_ver.tar.bz2"
     cd "$PWD/Build/linux" || exit 1
-    execute cmake -DCMAKE_INSTALL_PREFIX="$workspace" -DENABLE_SHARED='OFF' -DBUILD_SHARED_LIBS='OFF' ../.. -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE='Release' -DENABLE_EXAMPLES='OFF'
+    execute cmake -DCMAKE_INSTALL_PREFIX="$workspace" -DENABLE_SHARED='OFF' -DBUILD_SHARED_LIBS='OFF' \
+        ../.. -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE='Release' -DENABLE_EXAMPLES='OFF'
     execute make "-j$cpus"
     execute make install
     execute cp 'SvtAv1Enc.pc' "$workspace"/lib/pkgconfig/
@@ -1098,7 +1109,9 @@ EOF
 
         execute make install
 
-        if [ -n "$LDEXEFLAGS" ]; then sed -i.backup 's/-lgcc_s/-lgcc_eh/g' "$workspace"/lib/pkgconfig/x265.pc; fi
+        if [ -n "$LDEXEFLAGS" ]; then
+            sed -i.backup 's/-lgcc_s/-lgcc_eh/g' "$workspace"/lib/pkgconfig/x265.pc
+        fi
 
         build_done 'x265' "${gitlab_ver:0:7}"
     fi
@@ -1112,7 +1125,7 @@ if build 'SVT-HEVC' "$g_ver"; then
     cd "$PWD"/Build || exit 1
     execute cmake .. -DCMAKE_INSTALL_PREFIX="$workspace" -DENABLE_SHARED='OFF' -DBUILD_SHARED_LIBS='OFF' -DCMAKE_BUILD_TYPE='Release'
     execute make "-j$cpus"
-    execute make install    
+    execute make install
     build_done 'SVT-HEVC' "$g_ver"
 fi
 
@@ -1185,9 +1198,9 @@ cnf_ops+=('--enable-libzimg')
 git_ver_fn 'AOMediaCodec/libavif' '1' 'R'
 if build 'avif' "$g_ver"; then
     download "$g_url" "avif-$g_ver.tar.gz"
-    execute cmake -DCMAKE_INSTALL_PREFIX="$workspace" -DCMAKE_INSTALL_LIBDIR='lib' -DCMAKE_INSTALL_BINDIR='bin' \
-        -DCMAKE_INSTALL_INCLUDEDIR='include' -DENABLE_SHARED='OFF' -DBUILD_SHARED_LIBS='OFF' -DENABLE_STATIC='ON' -DAVIF_ENABLE_WERROR='OFF' \
-        -DAVIF_CODEC_DAV1D='ON' "$avif_tag" -DAVIF_CODEC_AOM='ON' -DAVIF_BUILD_APPS='ON'
+    execute cmake -DCMAKE_INSTALL_PREFIX="$workspace" -DENABLE_SHARED='OFF' -DBUILD_SHARED_LIBS='OFF' \
+        -DENABLE_STATIC='ON' -DAVIF_ENABLE_WERROR='OFF' -DAVIF_CODEC_DAV1D='ON' -DAVIF_CODEC_AOM='ON' \
+        -DAVIF_BUILD_APPS='ON' "$avif_tag"
     execute make "-j$cpus"
     execute make install
     build_done 'avif' "$g_ver"
@@ -1202,7 +1215,7 @@ if command_exists 'python3'; then
         git_ver_fn 'lv2/lv2' '1' 'T'
         if build 'lv2' "$g_ver"; then
             download "$g_url" "lv2-$g_ver.tar.gz"
-            execute meson setup build --prefix="$workspace" --buildtype='release' --default-library='static' --libdir="$workspace"/lib
+            execute meson setup build --prefix="$workspace" --buildtype='Release' --default-library='static' --libdir="$workspace"/lib
             execute ninja -C build
             execute ninja -C build install
             build_done 'lv2' "$g_ver"
@@ -1213,7 +1226,7 @@ if command_exists 'python3'; then
         fi
         if build 'serd' '61d53637'; then
             download 'https://gitlab.com/drobilla/serd/-/archive/61d53637dc62d15f9b3d1fa9e69891313c465c35/serd-61d53637dc62d15f9b3d1fa9e69891313c465c35.tar.bz2' 'serd-61d53637.tar.bz2'
-            execute meson setup build --prefix="$workspace" --buildtype='release' --default-library='static' --libdir="$workspace"/lib
+            execute meson setup build --prefix="$workspace" --buildtype='Release' --default-library='static' --libdir="$workspace"/lib
             execute ninja -C build
             execute ninja -C build install
             build_done 'serd' '61d53637'
@@ -1227,21 +1240,21 @@ if command_exists 'python3'; then
         fi
         if build 'zix' '262d4a15'; then
             download 'https://gitlab.com/drobilla/zix/-/archive/262d4a1522c38be0588746e874159da5c7bb457d/zix-262d4a1522c38be0588746e874159da5c7bb457d.tar.bz2' 'zix-262d4a15.tar.gz'
-            execute meson setup build --prefix="$workspace" --buildtype='release' --default-library='static' --libdir="$workspace"/lib
+            execute meson setup build --prefix="$workspace" --buildtype='Release' --default-library='static' --libdir="$workspace"/lib
             execute ninja -C build
             execute ninja -C build install
             build_done 'zix' '262d4a15'
         fi
         if build 'sord' '0.16.14'; then
             download 'http://download.drobilla.net/sord-0.16.14.tar.xz' 'sord-0.16.14.tar.gz'
-            execute meson setup build --prefix="$workspace" --buildtype='release' --default-library='static' --libdir="$workspace"/lib
+            execute meson setup build --prefix="$workspace" --buildtype='Release' --default-library='static' --libdir="$workspace"/lib
             execute ninja -C build
             execute ninja -C build install
             build_done 'sord' '0.16.14'
         fi
         if build 'sratom' 'b1643412'; then
             download 'https://gitlab.com/lv2/sratom/-/archive/b1643412ef03f41fc174f076daff39ade0999bf2/sratom-b1643412ef03f41fc174f076daff39ade0999bf2.tar.bz2'  'sratom-b1643412.tar.bz2'
-            execute meson setup build --prefix="$workspace" --buildtype='release' --default-library='static' --libdir="$workspace"/lib
+            execute meson setup build --prefix="$workspace" --buildtype='Release' --default-library='static' --libdir="$workspace"/lib
             execute ninja -C build
             execute ninja -C build install
             build_done 'sratom' 'b1643412'
@@ -1249,7 +1262,7 @@ if command_exists 'python3'; then
         git_ver_fn '11853176' '4'
         if build 'lilv' "$gitlab_ver"; then
             download "https://gitlab.com/lv2/lilv/-/archive/v0.24.20/lilv-v0.24.20.tar.gz" "lilv-0.24.20.tar.gz"
-            execute meson setup build --prefix="$workspace" --buildtype='release' --default-library='static' --libdir="$workspace"/lib
+            execute meson setup build --prefix="$workspace" --buildtype='Release' --default-library='static' --libdir="$workspace"/lib
             execute ninja -C build
             execute ninja -C build install
             build_done 'lilv' "$gitlab_ver"
@@ -1355,17 +1368,6 @@ if build 'libtiff' "$gitlab_ver"; then
     build_done 'libtiff' "$gitlab_ver"
 fi
 
-git_ver_fn '7950' '5'
-if build 'freetype' "$gitlab_ver"; then
-    download "https://gitlab.freedesktop.org/freetype/freetype/-/archive/$gitlab_ver/freetype-$gitlab_ver.tar.bz2" "freetype-$gitlab_ver.tar.bz2"
-    execute ./autogen.sh
-    make_dir build
-    execute meson setup build --prefix="$workspace" --buildtype='release' --default-library='static' --libdir="$workspace"/lib
-    execute ninja -C build
-    execute ninja -C build install
-    build_done 'freetype' "$gitlab_ver"
-fi
-
 if build 'libpng' "$g_ver"; then
     download "$g_url" "libpng-$g_ver.tar.gz"
     export LDFLAGS="$LDFLAGS"
@@ -1398,6 +1400,16 @@ cnf_ops+=('--enable-libwebp')
 ##
 ## other libraries
 ##
+
+git_ver_fn '363' '2'
+if build 'udfread' "$videolan_sver"; then
+    download "https://code.videolan.org/videolan/libudfread/-/archive/$videolan_ver/libudfread-$videolan_ver.tar.bz2" "udfread-$videolan_sver.tar.bz2"
+    execute autoreconf -fiv
+    execute ./configure --prefix="$workspace" --disable-shared --enable-static
+    execute make "-j$cpus"
+    execute make install
+    build_done 'udfread' "$videolan_sver"
+fi
 
 git_ver_fn '206' '2'
 if build 'libbluray' "$videolan_sver"; then
@@ -1447,7 +1459,7 @@ if command_exists 'meson'; then
     if build 'harfbuzz' "$g_ver"; then
         download "$g_url" "harfbuzz-$g_ver.tar.gz"
         execute ./autogen.sh
-        execute meson setup build --prefix="$workspace" --buildtype='release' --default-library='static' --libdir="$workspace"/lib
+        execute meson setup build --prefix="$workspace" --buildtype='Release' --default-library='static' --libdir="$workspace"/lib
         execute ./configure --prefix="$workspace" --disable-shared --enable-static
         execute ninja -C build
         execute ninja -C build install
@@ -1469,7 +1481,7 @@ if build 'fribidi' "$g_ver"; then
     download "$g_url" "fribidi-$g_ver.tar.gz"
     execute ./autogen.sh
     make_dir build
-    execute meson setup build --prefix="$workspace" --buildtype='release' --default-library='static' --libdir="$workspace"/lib
+    execute meson setup build --prefix="$workspace" --buildtype='Release' --default-library='static' --libdir="$workspace"/lib
         execute ninja -C build
         execute ninja -C build install
     build_done 'fribidi' "$g_ver"
@@ -1614,7 +1626,7 @@ fi
 
 # CLONE FFMPEG FROM THE LATEST GIT RELEASE
 build 'ffmpeg' "$ffmpeg_ver"
-download "https://github.com/FFmpeg/FFmpeg/archive/refs/heads/release/$ffmpeg_ver.tar.gz" "FFmpeg-release-$ffmpeg_ver.tar.gz"
+download "https://github.com/FFmpeg/FFmpeg/archive/refs/tags/$ffmpeg_ver.tar.gz" "FFmpeg-$ffmpeg_ver.tar.gz"
 ./configure \
     "${cnf_ops[@]}" \
     --disable-debug \
