Update build-ffmpeg

diff --git a/shell/ffmpeg/build-ffmpeg b/shell/ffmpeg/build-ffmpeg
--- a/shell/ffmpeg/build-ffmpeg
+++ b/shell/ffmpeg/build-ffmpeg
@@ -261,6 +261,101 @@ download_git()
     )
 }
 
+download_aria2()
+{
+    dl_path="$packages"
+    dl_url="$1"
+    dl_file="$2"
+    target_dir="$dl_path/$dl_file"
+
+    # first download attempt
+    if [ ! -d "$target_dir" ]; then
+        echo "Downloading $dl_file"
+        if ! aria2c -X16 -J16 -s16 --no-conf --out="$target_dir" "$dl_url"; then
+            echo
+            echo "The script failed to download \"$dl_file\" and will try again in 10 seconds"
+            sleep 10
+            echo
+            if ! aria2c -X16 -J16 -s16 --no-conf  --out="$target_dir" "$dl_url"; then
+                echo
+                echo "The script failed to download \"$dl_file\" two times and will exit the build"
+                fail_fn
+            fi
+        fi
+        echo 'Download Complete'
+        echo
+    else
+        echo "$dl_file is already downloaded"
+    fi
+
+    cd "$target_dir" || (
+        echo 'Script error!'
+        echo
+        echo "Unable to change the working directory to $target_dir"
+        fail_fn
+    )
+}
+
+download()
+{
+    dl_path="$packages"
+    dl_file="${2:-"${1##*/}"}"
+
+    if [[ "$dl_file" =~ tar. ]]; then
+        target_dir="${dl_file%.*}"
+        target_dir="${3:-"${target_dir%.*}"}"
+    else
+        target_dir="${3:-"${dl_file%.*}"}"
+    fi
+
+    if [ ! -f "$dl_path/$dl_file" ]; then
+        echo "Downloading $1 as $dl_file"
+        if ! curl -Lso "$dl_path/$dl_file" "$1"; then
+            echo
+            echo "The script failed to download \"$1\" and will try again in 10 seconds"
+            sleep 10
+            echo
+            if ! curl -Lso "$dl_path/$dl_file" "$1"; then
+                echo
+                echo "The script failed to download \"$1\" two times and will exit the build"
+                echo
+                fail_fn
+            fi
+        fi
+        echo 'Download Completed'
+        echo
+    else
+        echo "$dl_file is already downloaded"
+    fi
+
+    make_dir "$dl_path/$target_dir"
+
+    if [ -n "$3" ]; then
+        if ! tar -xf "$dl_path/$dl_file" -C "$dl_path/$target_dir" &>/dev/null; then
+            echo "Failed to extract $dl_file"
+            echo
+            fail_fn
+        fi
+    else
+        if ! tar -xf "$dl_path/$dl_file" -C "$dl_path/$target_dir" --strip-components 1 &>/dev/null; then
+            echo "Failed to extract $dl_file"
+            echo
+            fail_fn
+        fi
+    fi
+
+    echo "File extracted: $dl_file"
+
+    cd "$dl_path/$target_dir" || (
+        echo 'Script error!'
+        echo
+        echo "Unable to change the working directory to $target_dir"
+        echo
+        fail_fn
+    )
+}
+
+
 # PULL THE LATEST VERSIONS OF EACH PACKAGE FROM THE WEBSITE API
 net_timeout='10'
 
@@ -269,7 +364,13 @@ git_1_fn()
     # SCRAPE GITHUB WEBSITE FOR LATEST REPO VERSION
     github_repo="$1"
     github_url="$2"
-    curl_cmd=$(curl -m "$net_timeout" -sSL "https://api.github.com/repos/$github_repo/$github_url?per_page=1")
+    curl_cmd=$(curl \
+        -m "$net_timeout" \
+        --request GET \
+        --url "https://api.github.com/slyfox1186" \
+        --header "Authorization: Bearer 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" \
+        --header "X-GitHub-Api-Version: 2022-11-28" \
+        -sSL "https://api.github.com/repos/$github_repo/$github_url?per_page=1")
     if [ "$?" -eq '0' ]; then
         g_ver=$(echo "$curl_cmd" | jq -r '.[0].name')
         g_ver=${g_ver#v}
@@ -378,7 +479,13 @@ git_11_fn()
     # SCRAPE GITHUB WEBSITE FOR LATEST REPO VERSION
     github_repo="$1"
     github_url="$2"
-    if curl_cmd=$(curl -m "$net_timeout" -sSL "https://api.github.com/repos/$github_repo/$github_url?"); then
+    if curl_cmd=$(curl \
+        -m "$net_timeout" \
+        --request GET \
+        --url "https://api.github.com/slyfox1186" \
+        --header "Authorization: Bearer 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" \
+        --header "X-GitHub-Api-Version: 2022-11-28" \
+        -sSL "https://api.github.com/repos/$github_repo/$github_url?"); then
         g_full=$(echo "$curl_cmd" | jq -r '.')
         g_ver=$(echo "$curl_cmd" | jq -r '.[0].name')
         g_url=$(echo "$curl_cmd" | jq -r '.[0].tarball_url')
@@ -499,9 +606,15 @@ library_exists()
     return 0
 }
 
-build_done() { echo "$2" > "$packages/$1.done"; }
+build_done()
+{
+    echo "$2" > "$packages/$1.done"
+}
 
-installed() { return $(dpkg-query -W -f '${Status}\n' "$1" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}'); }
+installed()
+{
+    return $(dpkg-query -W -f '${Status}\n' "$1" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}')
+}
 
 cuda_fail_fn()
 {
@@ -656,6 +769,7 @@ export PATH
 
 # set the pkg-config path
 PKG_CONFIG_PATH="\
+$packages/pkg-config-0.29.2:\
 $workspace/lib/pkgconfig:\
 /usr/local/lib/x86_64-linux-gnu/pkgconfig:\
 /usr/local/lib/pkgconfig:\
@@ -667,19 +781,10 @@ $workspace/lib/pkgconfig:\
 "
 export PKG_CONFIG_PATH
 
-PKG_CONFIG="\
+LD_LIBRARY_PATH="\
+$packages/pkg-config-0.29.2\
 $workspace/lib/pkgconfig:\
-/usr/local/lib/x86_64-linux-gnu/pkgconfig:\
-/usr/local/lib/pkgconfig:\
-/usr/local/share/pkgconfig:\
-/usr/lib/x86_64-linux-gnu/pkgconfig:\
-/usr/lib/pkgconfig:\
-/usr/share/pkgconfig:\
-/usr/lib64/pkgconfig\
 "
-export PKG_CONFIG
-
-LD_LIBRARY_PATH="$workspace/lib/pkgconfig"
 export LD_LIBRARY_PATH
 
 if ! command_exists 'make'; then
@@ -981,7 +1086,7 @@ if build 'zlib' "$g_ver"; then
 fi
 
 if build 'm4' '1.4.19'; then
-    download 'https://git.savannah.gnu.org/cgit/m4.git/snapshot/m4-1.4.19.tar.gz'
+    download 'https://ftp.gnu.org/gnu/m4/m4-1.4.19.tar.xz'
     execute ./configure --prefix="$workspace"
     execute make -j "$cpus"
     execute make install
@@ -1206,11 +1311,11 @@ if build 'SVT-VP9' "$g_ver"; then
     build_done 'SVT-VP9' "$g_ver"
 fi
 
-git_ver_fn 'webmproject/libvpx' '1' 'T'
+git_ver_fn 'webmproject/libvpx' '11' 'T'
 if build 'libvpx' "$g_ver"; then
     download "$g_url" "libvpx-$g_ver.tar.gz"
-    execute ./configure --prefix="$workspace" --disable-unit-tests --disable-shared --disable-examples --as='yasm'
-    execute make -j "$cpus"
+    execute ./configure --prefix="${workspace}" --disable-unit-tests --disable-shared --disable-examples --as='yasm'
+    execute make "-j${cpus}"
     execute make install
     build_done 'libvpx' "$g_ver"
 fi
@@ -1682,7 +1787,7 @@ fi
 
 git_ver_fn 'GPUOpen-LibrariesAndSDKs/AMF' '1' 'T'
 if build 'amf' "$g_ver"; then
-    download "$g_url" "AMF-$g_ver.tar.gz"
+    download_aria2 "$g_url" "AMF-$g_ver.tar.gz"
     execute rm -rf "$workspace"/include/AMF
     execute mkdir -p "$workspace"/include/AMF
     execute cp -fr "$packages"/AMF-"$g_ver"/amf/public/include/* "$workspace"/include/AMF/
