Update build-dl-tools

diff --git a/shell/installers/dl-tools/build-dl-tools b/shell/installers/dl-tools/build-dl-tools
--- a/shell/installers/dl-tools/build-dl-tools
+++ b/shell/installers/dl-tools/build-dl-tools
@@ -1,32 +1,28 @@
 #!/bin/bash
 # shellcheck disable=SC2016,SC2034,SC2046,SC2066,SC2068,SC2086,SC2162,SC2317
 
-#################################################################################
+######################################################
 ##
-##  Install the latest WGET and cURL releases from their official repositories.
+##  Install the latest curl release from GitHub
 ##
-##  cURL: https://github.com/curl/curl
-##  WGET: https://ftp.gnu.org/gnu/wget/
-##
-##  Supported OS: Debian Based
+##  Supported OS:
 ##  - Debian 10 / 11
 ##  - Ubuntu 22.04 / 20.04 / 18.04
-##  - Other Debian based OS may work as well
 ##
 ##  Updated: 06.05.23
 ##
-##  Script version: 1.0
+##  Script version: 2.0
 ##
-#################################################################################
+######################################################
 
 clear
 
-script_ver='1.0'
+script_ver='2.0'
 cwd="$PWD"/curl-build-script
 packages="$cwd"/packages
 workspace="$cwd"/workspace
 install_dir='/usr/local'
-repo='https://github.com/slyfox1186/script-repo'
+repo='https://github.com/slyfox1186/script-repo/'
 
 #
 # CREATE OUTPUT DIRECTORIES
@@ -48,10 +44,9 @@ fi
 # PRINT BANNER
 #
 
-printf "%s\n%s\n%s\n%s\n" \
-    "WGET + cURL Build Script - v$script_ver" \
+printf "%s\n%s\n%s\n" \
+    "DL-Tools Build Script - v$script_ver" \
     '===============================' \
-    'Supported OS: Debian based (Ubuntu ect.)' \
     "This script will utilize ($cpu_threads) cpu threads for parallel processing to accelerate the build process."
 
 #
@@ -62,12 +57,7 @@ PATH="\
 /usr/lib/ccache:\
 $workspace/bin:\
 $HOME/.local/bin:\
-/usr/local/sbin:\
-/usr/local/bin:\
-/usr/sbin:\
-/usr/bin:\
-/sbin:\
-/bin\
+$PATH\
 "
 export PATH
 
@@ -95,7 +85,7 @@ fail_fn()
     printf "\n%s\n\n%s\n%s\n\n" \
         "$1" \
         'Please submit a support ticket in GitHub.' \
-	"$repo/issues"
+	"$repo"
     exit 1
 }
 
@@ -148,13 +138,14 @@ git_1_fn()
     github_repo="$1"
     github_url="$2"
 
-    if curl_cmd="$(curl -m -sSL https://api.github.com/repos/$github_repo/$github_url)"; then
+    if curl_cmd="$(curl -m "$curl_timeout" -sSL https://api.github.com/repos/$github_repo/$github_url)"; then
         g_url="$(echo "$curl_cmd" | jq -r '.[0].tarball_url' 2>/dev/null)"
         g_ver="$(echo "$curl_cmd" | jq -r '.[0].name' 2>/dev/null)"
         g_ver="${g_ver#cares-}"
         g_ver="${g_ver#nghttp2 v}"
         g_ver="${g_ver#nghttp3 v}"
         g_ver="${g_ver#OpenSSL }"
+        g_ver="${g_ver#release-}"
         g_ver="${g_ver#v}"
     fi
 }
@@ -187,7 +178,6 @@ git_ver_fn()
 execute()
 {
     echo "$ $*"
-
     if ! output=$("$@" 2>&1); then
         fail_fn "Failed to Execute $*"
     fi
@@ -244,6 +234,33 @@ download()
     cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir"
 }
 
+download_git()
+{
+    local dl_path dl_url dl_file target_dir
+
+    dl_path="$packages"
+    dl_url="$1"
+    dl_file="$2"
+    target_dir="$dl_path/$dl_file"
+
+    if [ -d "$target_dir" ]; then
+        sudo rm -fr "$target_dir"
+    fi
+
+    echo "Downloading $dl_url as $dl_file"
+    if ! git clone -q "$dl_url" "$target_dir"; then
+        printf "\n%s\n\n" "The script failed to clone the git repository \"$target_dir\" and will try again in 10 seconds..."
+        sleep 10
+        if ! git clone -q "$dl_url" "$target_dir"; then
+            fail_fn "The script failed to clone \"$target_dir\" twice and will now exit the build."
+        fi
+    else
+        echo -e "Succesfully cloned: $target_dir\\n"
+    fi
+
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir"
+}
+
 build()
 {
     printf "\n%s\n%s\n" \
@@ -275,11 +292,12 @@ pkgs_fn()
 {
     local pkg pkgs missing_pkgs
 
-    pkgs=("$1" autoconf autogen automake build-essential ccache cmake curl git jq lcov libbrotli-dev libc-ares-dev \
-          libcunit1-dev libcurl4-gnutls-dev libec-dev libev-dev libevent-dev libexiv2-27 libgexiv2-2 libgimp2.0 \
-          libgnutls28-dev libgsasl7-dev libjansson-dev libjemalloc-dev libldap-dev libldap2-dev liblzma-dev libmbedtls-dev \
-          libnghttp2-dev libntlm0-dev libpsl-dev librtmp-dev libssh-dev libssh2-1-dev libtool libxml2-dev libzstd-dev m4 \
-          pkg-config python3-pip re2c)
+    pkgs=("$1" autoconf autogen automake autopoint autotools-dev build-essential ccache cmake curl git google-perftools jq lcov 
+          libaria2-0 libaria2-0-dev libbrotli-dev libc-ares-dev libcppunit-dev libcunit1-dev libcurl4-gnutls-dev libec-dev libev-dev 
+          libevent-dev libexiv2-27 libgexiv2-2 libgimp2.0 libgnutls28-dev libgoogle-perftools-dev libgoogle-perftools4 libgsasl7-dev 
+          libjansson-dev libjemalloc-dev libldap-dev libldap2-dev liblzma-dev libmbedtls-dev libnghttp2-dev libntlm0-dev libpsl-dev 
+          librtmp-dev libsqlite3-dev libssh-dev libssh2-1-dev libssl-dev libtool libxml2-dev libzstd-dev m4 pkg-config python3-pip 
+          re2c zlib1g-dev libunistring-dev libp11-kit-dev libp11-kit0 p11-kit-modules p11-kit libgpg-error-dev libuv1-dev libgcrypt20-dev)
 
     for pkg in ${pkgs[@]}
     do
@@ -304,15 +322,19 @@ pkgs_fn()
 # DISCOVER THE SYSTEM OS
 #
 
-pkgs_1='libnghttp3-dev libgsasl-dev libngtcp2-dev libgsasl7-dev'
-pkgs_2='libgsasl7-dev'
+pkgs_jammy='libnghttp3-dev libgsasl-dev libngtcp2-dev libgsasl7-dev'
+pkgs_focal='libgsasl7-dev'
+pkgs_bionic=''
 
 os_test="$(lsb_release -r 2>/dev/null | grep -Eo '[0-9\.]+$')"
 if [ "$os_test" = '23.04' ] || [ "$os_test" = '22.04' ]; then
-    pkgs_fn "$pkgs_1"
+    pkgs_fn "$pkgs_jammy"
     opts_flag='1'
-elif [ "$os_test" = '20.04' ] || [ "$os_test" = '18.04' ]; then
-    pkgs_fn "$pkgs_2"
+elif [ "$os_test" = '20.04' ]; then
+    pkgs_fn "$pkgs_focal"
+    opts_flag='2'
+elif [ "$os_test" = '18.04' ]; then
+    pkgs_fn "$pkgs_bionic"
     opts_flag='2'
 fi
 
@@ -388,9 +410,9 @@ if build 'wget' "$g_ver1"; then
         --with-cares \
         --with-openssl=auto \
         CFLAGS='-Os -ffunction-sections -fdata-sections -fno-unwind-tables -fno-asynchronous-unwind-tables -flto' \
-        CXXFLAGS='-g -O3 -march=native -mtune=native' \
         CPPFLAGS="-I$workspace/include -I/usr/local/include -I/usr/include" \
-        LDFLAGS="-L$workspace/lib64 -L$workspace/lib -L/usr/local/lib64 -L/usr/lib64 -L/usr/local/lib -L/usr/lib -Wl,-s -Wl,-Bsymbolic -Wl,--gc-sections"
+        CXXFLAGS='-g -O3 -march=native -mtune=native' \
+        LDFLAGS="-L/usr/lib/x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu -L/usr/local/lib -L/usr/lib64 -L/usr/lib -L/usr/local/lib -Wl,-s -Wl,-Bsymbolic -Wl,--gc-sections"
     execute make "-j$cpu_threads"
     execute sudo make install
     build_done 'wget' "$g_ver1"
@@ -419,9 +441,9 @@ if build 'curl' "$g_ver"; then
         "${enable_opts[@]}" \
         "${with_opts[@]}" \
         CFLAGS='-Os -ffunction-sections -fdata-sections -fno-unwind-tables -fno-asynchronous-unwind-tables -flto' \
-        CXXFLAGS='-g -O3 -march=native -mtune=native' \
         CPPFLAGS="-I$workspace/include -I/usr/local/include -I/usr/include" \
-        LDFLAGS="-L$workspace/lib64 -L$workspace/lib -L/usr/local/lib64 -L/usr/lib64 -L/usr/local/lib -L/usr/lib -Wl,-s -Wl,-Bsymbolic -Wl,--gc-sections"
+        CXXFLAGS='-g -O3 -march=native -mtune=native' \
+        LDFLAGS="-L/usr/lib/x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu -L/usr/local/lib -L/usr/lib64 -L/usr/lib -L/usr/local/lib -Wl,-s -Wl,-Bsymbolic -Wl,--gc-sections"
     execute make "-j$cpu_threads"
     execute sudo make install
 fi
