remove curly brackets from variables where un-needed

diff --git a/Bash/Installer Scripts/GNU Software/build-binutils b/Bash/Installer Scripts/GNU Software/build-binutils
--- a/Bash/Installer Scripts/GNU Software/build-binutils
+++ b/Bash/Installer Scripts/GNU Software/build-binutils
@@ -30,10 +30,10 @@ fi
 
 script_ver=1.2
 archive_dir=binutils-2.41
-archive_url=https://ftp.gnu.org/gnu/binutils/"${archive_dir}".tar.lz
+archive_url=https://ftp.gnu.org/gnu/binutils/"$archive_dir".tar.lz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/binutils-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/binutils-build-script
 install_dir=/usr/local
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
@@ -46,10 +46,10 @@ sleep 2
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE CC/CXX COMPILERS & THE COMPILER OPTIMIZATION FLAGS
@@ -113,15 +113,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n"                                       \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}"              \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1"              \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -139,7 +139,7 @@ cleanup_fn()
     clear
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 unset choice
@@ -155,7 +155,7 @@ cleanup_fn()
 
 pkgs_fn()
 {
-    pkgs=("${1}" autoconf autoconf-archive autogen automake binutils build-essential ccache cmake curl
+    pkgs=("$1" autoconf autoconf-archive autogen automake binutils build-essential ccache cmake curl
           git libgmp-dev libintl-perl libisl-dev libmpc-dev libmpfr-dev libtool libtool-bin libzstd-dev
           m4 nasm ninja-build texinfo yasm zlib1g-dev zstd gdc-multilib gdc)
 
@@ -213,25 +213,25 @@ fi
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -xf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -244,10 +244,10 @@ printf "%s\n%s\n\n"              \
     '==============================================='
 sleep 1
 
-cd "${cwd}/${archive_dir}" || exit 1
+cd "$cwd/$archive_dir" || exit 1
 autoreconf -fi -I /usr/share/aclocal
 cd build || exit 1
-../configure --prefix="${install_dir}"                                 \
+../configure --prefix="$install_dir"                                 \
              --disable-werror                                          \
              --enable-default-compressed-debug-sections-algorithm=zstd \
              --enable-gold=default                                     \
diff --git a/Bash/Installer Scripts/GNU Software/build-diffutils b/Bash/Installer Scripts/GNU Software/build-diffutils
--- a/Bash/Installer Scripts/GNU Software/build-diffutils
+++ b/Bash/Installer Scripts/GNU Software/build-diffutils
@@ -27,8 +27,8 @@ script_ver=1.1
 archive_dir=diffutils-3.10
 archive_url=https://ftp.gnu.org/gnu/diffutils/diffutils-3.10.tar.xz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/diffutils-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/diffutils-build-script
 install_dir=/usr/local
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
@@ -41,10 +41,10 @@ printf "%s\n%s\n\n" \
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE C + CPP COMPILERS
@@ -108,7 +108,7 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
@@ -125,7 +125,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' answer
 
     case "${answer}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -164,25 +164,25 @@ fi
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -xf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -190,10 +190,10 @@ fi
 # BUILD PROGRAM FROM SOURCE
 #
 
-cd "${cwd}/${archive_dir}" || exit 1
+cd "$cwd/$archive_dir" || exit 1
 autoreconf -fi
 cd build || exit 1
-../configure --prefix="${install_dir}"       \
+../configure --prefix="$install_dir"       \
              --{build,host}=x86_64-linux-gnu \
              --disable-nls                   \
              --enable-threads=posix
@@ -203,7 +203,7 @@ if ! sudo make install; then
     exit 1
 fi
 
-sudo ldconfig "${install_dir}/lib"
+sudo ldconfig "$install_dir/lib"
 
 # PROMPT USER TO CLEAN UP FILES
 cleanup_fn
diff --git a/Bash/Installer Scripts/GNU Software/build-glibc b/Bash/Installer Scripts/GNU Software/build-glibc
--- a/Bash/Installer Scripts/GNU Software/build-glibc
+++ b/Bash/Installer Scripts/GNU Software/build-glibc
@@ -25,10 +25,10 @@ fi
 
 script_ver=1.0
 archive_dir=glibc-2.38
-archive_url=https://ftp.gnu.org/gnu/glibc/"${archive_dir}".tar.xz
+archive_url=https://ftp.gnu.org/gnu/glibc/"$archive_dir".tar.xz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/glibc-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/glibc-build-script
 install_dir=/usr
 pc_type=x86_64-linux-gnu
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
@@ -43,10 +43,10 @@ sleep 2
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE CC/CXX COMPILERS & THE COMPILER OPTIMIZATION FLAGS
@@ -93,7 +93,7 @@ PKG_CONFIG_PATH="\
 /usr/local/share/pkgconfig:\
 /usr/lib64/pkgconfig:\
 /usr/lib/pkgconfig:\
-/usr/lib/${install_dir}/pkgconfig:\
+/usr/lib/$install_dir/pkgconfig:\
 /usr/share/pkgconfig:\
 /lib64/pkgconfig:\
 /lib/pkgconfig:\
@@ -167,15 +167,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n"                                       \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}"              \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1"              \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -192,7 +192,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -211,7 +211,7 @@ cleanup_fn()
 
 pkgs_fn()
 {
-    pkgs=("${1}" autoconf autoconf-archive autogen automake build-essential ccache cmake curl git libltdl-dev)
+    pkgs=("$1" autoconf autoconf-archive autogen automake build-essential ccache cmake curl git libltdl-dev)
     
     for i in ${pkgs[@]}
     do
@@ -233,25 +233,25 @@ pkgs_fn()
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -xf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -262,10 +262,10 @@ fi
 latest_linux_dir="$(sudo find /usr/src -type d -name 'linux-headers-*-amd64' | head -n1)"
 latest_linux_short_ver="$(echo "${latest_linux_dir}" | grep -Eo '[0-9\.]+' | head -n1)"
 
-cd "${cwd}/${archive_dir}" || exit 1
+cd "$cwd/$archive_dir" || exit 1
 autoreconf -fi
 cd build || exit 1
-../configure --prefix="${install_dir}"
+../configure --prefix="$install_dir"
 --{build,host}="${pc_type}"
 --allow-time-setting
 --disable-fortify-source
diff --git a/Bash/Installer Scripts/GNU Software/build-gnutls b/Bash/Installer Scripts/GNU Software/build-gnutls
--- a/Bash/Installer Scripts/GNU Software/build-gnutls
+++ b/Bash/Installer Scripts/GNU Software/build-gnutls
@@ -42,11 +42,11 @@ fi
 
 script_ver=1.0
 archive_dir=guile-gnutls-4.0.0
-archive_url=https://ftp.gnu.org/gnu/gnutls/${archive_dir}.tar.gz
+archive_url=https://ftp.gnu.org/gnu/gnutls/$archive_dir.tar.gz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
+archive_name="$archive_dir.tar.${archive_ext}"
 install_dir=/usr/local
-cwd="${PWD}"/gnutls-build-script
+cwd="$PWD"/gnutls-build-script
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
 
@@ -58,10 +58,10 @@ printf "%s\n%s\n\n" \
 # CREATE THE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE C + CPP COMPILERS
@@ -125,15 +125,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -150,7 +150,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -169,7 +169,7 @@ cleanup_fn()
 
 pkgs_fn()
 {
-    pkgs=("${1}" autoconf autoconf-archive autogen automake binutils build-essential ccache
+    pkgs=("$1" autoconf autoconf-archive autogen automake binutils build-essential ccache
           cmake curl guile-3.0-dev git libgmp-dev libintl-perl libtool libtool-bin m4 nasm
           ninja-build texinfo zlib1g-dev yasm)
 
@@ -193,25 +193,25 @@ pkgs_fn()
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE THE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT THE ARCHIVE FILES
 #
 
-if ! tar -xf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -219,10 +219,10 @@ fi
 # BUILD GnuTLS FROM IT'S SOURCE CODE
 #
 
-cd "${cwd}/${archive_dir}" || exit 1
+cd "$cwd/$archive_dir" || exit 1
 autoreconf -fi
 cd build || exit 1
-../configure --prefix="${install_dir}"            \
+../configure --prefix="$install_dir"            \
              --{build,host}=x86_64-linux-gnu      \
              --disable-nls                        \
              --enable-static                      \
diff --git a/Bash/Installer Scripts/GNU Software/build-imath b/Bash/Installer Scripts/GNU Software/build-imath
--- a/Bash/Installer Scripts/GNU Software/build-imath
+++ b/Bash/Installer Scripts/GNU Software/build-imath
@@ -44,8 +44,8 @@ script_ver=1.0
 archive_dir=imath-3.1.9
 archive_url=https://github.com/AcademySoftwareFoundation/Imath/archive/refs/tags/v3.1.9.tar.gz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/imath-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/imath-build-script
 install_dir=/usr/local
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
@@ -58,10 +58,10 @@ printf "%s\n%s\n\n" \
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE C + CPP COMPILERS
@@ -125,15 +125,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -150,7 +150,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -167,7 +167,7 @@ cleanup_fn()
 # INSTALL REQUIRED APT PACKAGES
 #
 
-pkgs=("${1}" autoconf autoconf-archive autogen automake binutils build-essential ccache cmake curl
+pkgs=("$1" autoconf autoconf-archive autogen automake binutils build-essential ccache cmake curl
       git libtool libtool-bin m4 nasm ninja-build texinfo zlib1g-dev yasm)
 
 for i in ${pkgs[@]}
@@ -188,25 +188,25 @@ fi
 # DOWNLOAD ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -xf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -214,8 +214,8 @@ fi
 # BUILD PROGRAM FROM SOURCE
 #
 
-cd "${cwd}/${archive_dir}" || exit 1
-cmake -B build -DCMAKE_INSTALL_PREFIX="${install_dir}" \
+cd "$cwd/$archive_dir" || exit 1
+cmake -B build -DCMAKE_INSTALL_PREFIX="$install_dir" \
                -DCMAKE_BUILD_TYPE=Release              \
                -G Ninja -Wno-dev
 ninja "-j$(nproc --all)" -C build
diff --git a/Bash/Installer Scripts/GNU Software/build-systemd b/Bash/Installer Scripts/GNU Software/build-systemd
--- a/Bash/Installer Scripts/GNU Software/build-systemd
+++ b/Bash/Installer Scripts/GNU Software/build-systemd
@@ -27,8 +27,8 @@ script_ver=1.2
 archive_dir=systemd-253
 archive_url=https://github.com/systemd/systemd/archive/refs/tags/v253.tar.gz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/systemd-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/systemd-build-script
 install_dir=/usr/local
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
@@ -41,10 +41,10 @@ printf "%s\n%s\n\n" \
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE C + CPP COMPILERS
@@ -123,15 +123,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -148,7 +148,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -165,7 +165,7 @@ cleanup_fn()
 # INSTALL REQUIRED APT PACKAGES
 #
 
-pkgs=("${1}" autoconf autoconf-archive autogen automake binutils bpftool build-essential ccache clang cmake curl git gnu-efi golang-gir-gio-2.0-dev golang-gir-gobject-2.0-dev
+pkgs=("$1" autoconf autoconf-archive autogen automake binutils bpftool build-essential ccache clang cmake curl git gnu-efi golang-gir-gio-2.0-dev golang-gir-gobject-2.0-dev
       gperf jekyll kexec-tools libacl1-dev libapparmor-dev libaudit-dev libbinutils libblkid-dev libblkid1 libbpf-dev libbz2-dev libcap-dev
       libcryptsetup-dev libcryptsetup12 libcurl4-openssl-dev libdbus-1-dev libdrpm-dev libdw-dev libfdisk-dev libfido2-dev libglib2.0-dev
       libgnutls28-dev libidn11-dev libidn2-0-dev libidn2-dev libiptc-dev libkrb5-dev libkmod-dev liblz4-dev libmicrohttpd-dev libmount-dev libnacl-dev libnss-myhostname
@@ -193,25 +193,25 @@ fi
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -xf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -219,8 +219,8 @@ fi
 # BUILD PROGRAM FROM SOURCE
 #
 
-cd "${cwd}/${archive_dir}" || exit 1
-meson setup build --prefix="${install_dir}" \
+cd "$cwd/$archive_dir" || exit 1
+meson setup build --prefix="$install_dir" \
                   --buildtype=release       \
                   --default-library=both    \
                   --strip                   \
diff --git a/Bash/Installer Scripts/GitHub Projects/Download Tools/build-dl-tools b/Bash/Installer Scripts/GitHub Projects/Download Tools/build-dl-tools
--- a/Bash/Installer Scripts/GitHub Projects/Download Tools/build-dl-tools
+++ b/Bash/Installer Scripts/GitHub Projects/Download Tools/build-dl-tools
@@ -41,9 +41,9 @@ fi
 
 script_ver=1.2
 install_prefix=/usr/local
-cwd="${PWD}"/download-tools-build-script
-packages="${cwd}"/packages
-workspace="${cwd}"/workspace
+cwd="$PWD"/download-tools-build-script
+packages="$cwd"/packages
+workspace="$cwd"/workspace
 pc_type=x86_64-linux-gnu
 if [ -d '/usr/local/ssl/certs' ]; then
     cert_dir='/usr/local/ssl/certs'
@@ -51,7 +51,7 @@ else
     cert_dir=/etc/ssl/certs
 fi
 pem_file=cacert.pem
-pem_out="${cert_dir}/${pem_file}"
+pem_out="${cert_dir}/$pem_file"
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
 debug=OFF
@@ -60,7 +60,7 @@ debug=OFF
 # CREATE OUTPUT DIRECTORY
 #
 
-mkdir -p "${packages}" "${workspace}"
+mkdir -p "$packages" "$workspace"
 
 #
 # SET THE CC/CXX COMPILERS & THE COMPILER OPTIMIZATION FLAGS
@@ -105,15 +105,15 @@ export PATH
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
 /usr/local/lib/pkgconfig:\
-/usr/local/lib/${install_dir}/pkgconfig:\
+/usr/local/lib/$install_dir/pkgconfig:\
 /usr/local/share/pkgconfig:\
 /usr/lib64/pkgconfig:\
 /usr/lib/pkgconfig:\
-/usr/lib/${install_dir}/pkgconfig:\
+/usr/lib/$install_dir/pkgconfig:\
 /usr/share/pkgconfig:\
 /lib64/pkgconfig:\
 /lib/pkgconfig:\
-/lib/${install_dir}pkgconfig\
+/lib/$install_dirpkgconfig\
 "
 export PKG_CONFIG_PATH
 
@@ -224,7 +224,7 @@ printf "%s\n%s\n%s\n" \
 
 PATH="\
 /usr/lib/ccache:\
-${workspace}/bin:\
+$workspace/bin:\
 ${HOME}/.cargo/bin:\
 ${HOME}/.local/bin:\
 /usr/local/sbin:\
@@ -239,11 +239,11 @@ ${HOME}/.local/bin:\
 export PATH
 
 PKG_CONFIG_PATH="\
-${workspace}/usr/lib/pkgconfig:\
-${workspace}/lib64/pkgconfig:\
-${workspace}/lib/pkgconfig:\
-${workspace}/lib/x86_64-linux-gnu/pkgconfig:\
-${workspace}/share/pkgconfig:\
+$workspace/usr/lib/pkgconfig:\
+$workspace/lib64/pkgconfig:\
+$workspace/lib/pkgconfig:\
+$workspace/lib/x86_64-linux-gnu/pkgconfig:\
+$workspace/share/pkgconfig:\
 /usr/local/lib64/pkgconfig:\
 /usr/local/lib/pkgconfig:\
 /usr/local/lib/x86_64-linux-gnu/pkgconfig:\
@@ -267,9 +267,9 @@ export PKG_CONFIG_PATH
 fail_fn()
 {
     printf "\n%s\n%s\n%s\n\n" \
-        "${1}" \
+        "$1" \
         'You can enable the script'\''s debugging feature by changing the variable "debug" to "ON"' \
-        "To report a bug visit: ${web_repo}/issues"
+        "To report a bug visit: $web_repo/issues"
     exit 1
 }
 
@@ -277,7 +277,7 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
@@ -293,7 +293,7 @@ cleanup_fn()
     clear
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      clear;;
         *)
                 unset choice
@@ -341,12 +341,12 @@ git_1_fn()
 {
     local curl_cmd github_repo github_url
 
-    github_repo="${1}"
-    github_url="${2}"
+    github_repo="$1"
+    github_url="$2"
 
-    if curl_cmd="$(curl -A "${user_agent}" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
-        g_ver="$(echo "${curl_cmd}" | jq -r '.[0].name' 2>/dev/null)"
-        g_url="$(echo "${curl_cmd}" | jq -r '.[0].tarball_url' 2>/dev/null)"
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
+        g_ver="$(echo "$curl_cmd" | jq -r '.[0].name' 2>/dev/null)"
+        g_url="$(echo "$curl_cmd" | jq -r '.[0].tarball_url' 2>/dev/null)"
         g_ver="${g_ver#cares-}"
         g_ver="${g_ver#aria2 }"
         g_ver="${g_ver#nghttp2 v}"
@@ -362,11 +362,11 @@ git_ver_fn()
 {
     local v_flag v_url v_tag url_tag t_url
 
-    v_url="${1}"
-    v_tag="${2}"
+    v_url="$1"
+    v_tag="$2"
 
-    if [ -n "${3}" ]; then
-        v_flag="${3}"
+    if [ -n "$3" ]; then
+        v_flag="$3"
         case "${v_flag}" in
             T)      t_url=tags;;
             R)      t_url=releases;;
@@ -382,12 +382,12 @@ execute()
     echo "$ ${*}"
 
     if [ "${debug}" = 'ON' ]; then
-        if ! output=$("${@}"); then
+        if ! output=$("$@"); then
             notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
             fail_fn "Failed to execute: ${*}"
         fi
     else
-        if ! output=$("${@}" 2>&1); then
+        if ! output=$("$@" 2>&1); then
             notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
             fail_fn "Failed to execute: ${*}"
         fi
@@ -396,102 +396,102 @@ execute()
 
 download()
 {
-    dl_path="${packages}"
-    dl_url="${1}"
+    dl_path="$packages"
+    dl_url="$1"
     dl_file="${2:-"${1##*/}"}"
 
-    if [[ "${dl_file}" =~ tar. ]]; then
+    if [[ "$dl_file" =~ tar. ]]; then
         output_dir="${dl_file%.*}"
         output_dir="${3:-"${output_dir%.*}"}"
     else
         output_dir="${3:-"${dl_file%.*}"}"
     fi
 
-    target_file="${dl_path}/${dl_file}"
-    target_dir="${dl_path}/${output_dir}"
+    target_file="$dl_path/$dl_file"
+    target_dir="$dl_path/$output_dir"
 
     if [ -f "${target_file}" ]; then
-        echo "The file \"${dl_file}\" is already downloaded."
+        echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"${dl_file}\""
-        if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
-            printf "\n%s\n\n" "The script failed to download \"${dl_file}\" and will try again in 10 seconds..."
+        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
+        if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+            printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
-                fail_fn "The script failed to download \"${dl_file}\" twice and will now exit. Line: ${LINENO}"
+            if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit. Line: ${LINENO}"
             fi
         fi
         echo 'Download Completed'
     fi
 
-    if [ -d "${target_dir}" ]; then
-        sudo rm -fr "${target_dir}"
+    if [ -d "$target_dir" ]; then
+        sudo rm -fr "$target_dir"
     fi
-    mkdir -p "${target_dir}"
+    mkdir -p "$target_dir"
 
-    if [ -n "${3}" ]; then
-        if ! tar -xf "${target_file}" -C "${target_dir}" 2>/dev/null >/dev/null; then
+    if [ -n "$3" ]; then
+        if ! tar -xf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script. Line: ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
         fi
     else
-        if ! tar -xf "${target_file}" -C "${target_dir}" --strip-components 1 2>/dev/null >/dev/null; then
+        if ! tar -xf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script. Line: ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
         fi
     fi
 
-    printf "%s\n\n" "File extracted: ${dl_file}"
+    printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}. Line: ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: ${LINENO}"
 }
 
 download_git()
 {
     local dl_path dl_url dl_file target_dir
 
-    dl_path="${packages}"
-    dl_url="${1}"
+    dl_path="$packages"
+    dl_url="$1"
     dl_file="${2:-"${1##*/}"}"
     dl_file="${dl_file//\./-}"
-    target_dir="${dl_path}/${dl_file}"
+    target_dir="$dl_path/$dl_file"
 
-    if [ -n "${3}" ]; then
-        output_dir="${dl_path}/${3}"
-        target_dir="${output_dir}"
+    if [ -n "$3" ]; then
+        output_dir="$dl_path/$3"
+        target_dir="$output_dir"
     fi
 
-    if [ -d "${target_dir}" ]; then
-        sudo rm -fr "${target_dir}"
+    if [ -d "$target_dir" ]; then
+        sudo rm -fr "$target_dir"
     fi
 
-    echo "Downloading ${dl_url} as ${dl_file}"
+    echo "Downloading ${dl_url} as $dl_file"
 
-    if ! git clone -q "${dl_url}" "${target_dir}"; then
-        printf "\n%s\n\n" "The script failed to clone the directory \"${target_dir}\" and will try again in 10 seconds..."
+    if ! git clone -q "${dl_url}" "$target_dir"; then
+        printf "\n%s\n\n" "The script failed to clone the directory \"$target_dir\" and will try again in 10 seconds..."
         sleep 10
-        if ! git clone -q "${dl_url}" "${target_dir}"; then
-            fail_fn "The script failed to clone the directory \"${target_dir}\" twice and will now exit the buildLine: ${LINENO}"
+        if ! git clone -q "${dl_url}" "$target_dir"; then
+            fail_fn "The script failed to clone the directory \"$target_dir\" twice and will now exit the buildLine: ${LINENO}"
         fi
     else
-        printf "%s\n\n" "Successfully cloned: ${target_dir}"
+        printf "%s\n\n" "Successfully cloned: $target_dir"
     fi
 
-    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}. Line: ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: ${LINENO}"
 }
 
 build()
 {
     printf "\n%s\n%s\n" \
-        "building ${1} - version ${2}" \
+        "building $1 - version $2" \
         '===================================='
 
-    if [ -f "${packages}/${1}.done" ]; then
-        if grep -Fx "${2}" "${packages}/${1}.done" > /dev/null; then
-            echo "${1} version ${2} already built. Remove ${packages}/${1}.done lockfile to rebuild it."
+    if [ -f "$packages/$1.done" ]; then
+        if grep -Fx "$2" "$packages/$1.done" > /dev/null; then
+            echo "$1 version $2 already built. Remove $packages/$1.done lockfile to rebuild it."
             return 1
         else
-            echo "${1} is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove ${packages}/${1}.done lockfile."
+            echo "$1 is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove $packages/$1.done lockfile."
             return 1
         fi
     fi
@@ -501,12 +501,12 @@ build()
 
 build_done()
 {
-    echo "${2}" > "${packages}/${1}.done"
+    echo "$2" > "$packages/$1.done"
 }
 
 installed()
 {
-    return $(dpkg-query -W -f '${Status}\n' "${1}" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}')
+    return $(dpkg-query -W -f '${Status}\n' "$1" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}')
 }
 
 #
@@ -517,7 +517,7 @@ pkgs_fn()
 {
     local pkg pkgs missing_pkgs
 
-    pkgs=("${1}" apt-transport-https apt-utils autoconf autoconf-archive autogen automake
+    pkgs=("$1" apt-transport-https apt-utils autoconf autoconf-archive autogen automake
           autopoint autotools-dev build-essential bzip2 ca-certificates ccache clang cmake
           curl default-jdk-headless gfortran git google-perftools graphviz jq lcov libaria2-0
           libaria2-0-dev libc-ares-dev libcppunit-dev libcunit1-dev libcurl4 libcurl4-gnutls-dev
@@ -591,8 +591,8 @@ if [ ! -f "${pem_out}" ]; then
     printf "%s\n%s\n\n" \
         'Download the latest security certificate' \
         '================================================'
-    curl -A "${user_agent}" -Lso "${packages}/${pem_file}" "https://curl.se/ca/${pem_file}"
-    sudo cp -f "${packages}/${pem_file}" "${pem_out}"
+    curl -A "$user_agent" -Lso "$packages/$pem_file" "https://curl.se/ca/$pem_file"
+    sudo cp -f "$packages/$pem_file" "${pem_out}"
 fi
 
 #
@@ -602,7 +602,7 @@ fi
 
 if build 'pkg-config' '0.29.2'; then
     download "https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz"
-    execute ./configure --prefix="${workspace}" \
+    execute ./configure --prefix="$workspace" \
                         --with-pc-path="${PKG_CONFIG_PATH}"
     execute make "-j${cpu_threads}"
     execute make install
@@ -611,32 +611,32 @@ fi
 
 
 git_ver_fn 'madler/zlib' '1' 'T'
-if build 'zlib' "${g_ver}"; then
-    download "${g_url}" "zlib-${g_ver}.tar.gz"
-    execute ./configure --prefix="${workspace}"
+if build 'zlib' "$g_ver"; then
+    download "${g_url}" "zlib-$g_ver.tar.gz"
+    execute ./configure --prefix="$workspace"
     execute make "-j${cpu_threads}"
     execute make install
-    build_done 'zlib' "${g_ver}"
+    build_done 'zlib' "$g_ver"
 fi
 
 git_ver_fn 'akheron/jansson' '1' 'T'
-if build 'jansson' "${g_ver}"; then
-    download "${g_url}" "jansson-${g_ver}.tar.gz"
+if build 'jansson' "$g_ver"; then
+    download "${g_url}" "jansson-$g_ver.tar.gz"
     execute autoreconf -fi
-    execute ./configure --prefix="${workspace}" \
+    execute ./configure --prefix="$workspace" \
                         --disable-shared
     execute make "-j${cpu_threads}"
     execute make install
-    build_done 'jansson' "${g_ver}"
+    build_done 'jansson' "$g_ver"
 fi
 
 if build 'gsasl' '2.2.0'; then
     download 'https://ftp.gnu.org/gnu/gsasl/gsasl-2.2.0.tar.gz' 'gsasl-2.2.0.tar.gz'
-    execute ./configure --prefix="${workspace}"                \
+    execute ./configure --prefix="$workspace"                \
                          --disable-gtk-doc                     \
                          --disable-shared                      \
                          --disable-year2038                    \
-                         --with-libiconv-prefix="${workspace}" \
+                         --with-libiconv-prefix="$workspace" \
                          --with-openssl=auto
     execute make "-j${cpu_threads}"
     execute make install
@@ -646,35 +646,35 @@ fi
 git_ver_fn 'c-ares/c-ares' '1' 'R'
 g_ver="${g_ver//cares-/}"
 g_tag="${g_ver//\./_}"
-if build 'c-ares' "${g_ver}"; then
-    download "${g_url}" "c-ares-${g_ver}.tar.gz"
+if build 'c-ares' "$g_ver"; then
+    download "${g_url}" "c-ares-$g_ver.tar.gz"
     execute autoupdate
     execute autoreconf -fi
-    execute ./configure --prefix="${workspace}" \
+    execute ./configure --prefix="$workspace" \
                          --disable-shared       \
                          --disable-warnings     \
                          --enable-optimize="${CFLAGS}"
     execute make "-j${cpu_threads}"
     execute make install
-    build_done 'c-ares' "${g_ver}"
+    build_done 'c-ares' "$g_ver"
 fi
 
 git_ver_fn 'pcre2project/pcre2' '1' 'T'
-if build 'pcre2' "${g_ver}"; then
-    download "${g_url}" "pcre2-${g_ver}.tar.gz"
+if build 'pcre2' "$g_ver"; then
+    download "${g_url}" "pcre2-$g_ver.tar.gz"
     execute ./autogen.sh
-    execute ./configure --prefix="${workspace}" \
+    execute ./configure --prefix="$workspace" \
                         --disable-shared
     execute make "-j${cpu_threads}"
     execute make install
-    build_done 'pcre2' "${g_ver}"
+    build_done 'pcre2' "$g_ver"
 fi
 
 git_ver_fn 'jemalloc/jemalloc' '1' 'T'
-if build 'jemalloc' "${g_ver}"; then
-    download "${g_url}" "jemalloc-${g_ver}.tar.gz"
+if build 'jemalloc' "$g_ver"; then
+    download "${g_url}" "jemalloc-$g_ver.tar.gz"
     execute ./autogen.sh
-    execute ./configure --prefix="${workspace}"  \
+    execute ./configure --prefix="$workspace"  \
                          --disable-debug         \
                          --disable-doc           \
                          --disable-fill          \
@@ -687,14 +687,14 @@ if build 'jemalloc' "${g_ver}"; then
                          --enable-xmalloc
     execute make "-j${cpu_threads}"
     execute make install
-    build_done 'jemalloc' "${g_ver}"
+    build_done 'jemalloc' "$g_ver"
 fi
 
 git_ver_fn 'google/brotli' '1' 'T'
 if build 'brotli' '1.0.9'; then
     download 'https://github.com/google/brotli/archive/refs/tags/v1.0.9.tar.gz' 'brotli-1.0.9.tar.gz'
     execute cmake -B build                              \
-                  -DCMAKE_INSTALL_PREFIX="${workspace}" \
+                  -DCMAKE_INSTALL_PREFIX="$workspace" \
                   -DCMAKE_BUILD_TYPE=Release            \
                   -DBUILD_SHARED_LIBS=OFF               \
                   -DBUILD_TESTING=OFF                   \
@@ -714,7 +714,7 @@ if build 'wget' 'latest'; then
         execute sudo update-ca-certificates
     fi
     execute autoreconf -fi
-    ./configure --prefix="${install_prefix}" \
+    ./configure --prefix="$install_prefix" \
                  --enable-threads            \
                  --with-cares                \
                  --with-metalink             \
@@ -730,10 +730,10 @@ fi
 #
 
 git_ver_fn 'curl/curl' '1' 'R'
-if build 'curl' "${g_ver}"; then
-    download "https://curl.se/download/curl-${g_ver}.tar.xz"
+if build 'curl' "$g_ver"; then
+    download "https://curl.se/download/curl-$g_ver.tar.xz"
     dopts=('--disable-'{get-easy-options,shared,verbose,versioned-symbols})
-    eopts=('--enable-'{alt-svc,ares="${workspace}",cookies})
+    eopts=('--enable-'{alt-svc,ares="$workspace",cookies})
     eopts+=('--enable-'{dict,dnsshuffle,doh,file,ftp,gopher})
     eopts+=('--enable-'{headers-api,hsts,http,http-auth,imap})
     eopts+=('--enable-'{ipv6,ldap,ldaps,libcurl-option,libgcc,manual})
@@ -744,7 +744,7 @@ if build 'curl' "${g_ver}"; then
     wopts=('--with-'{gnutls='/usr/include',libssh2,nghttp2='/usr/include',nghttp3='/usr/include'})
     wopts+=('--with-'{ca-bundle="${pem_out}",ca-fallback,ca-path="${cert_dir}",secure-transport})
     execute autoreconf -fi
-    ./configure --prefix="${install_prefix}" \
+    ./configure --prefix="$install_prefix" \
                 "${dopts[@]}"                \
                 "${eopts[@]}"                \
                 "${wopts[@]}"                \
@@ -752,7 +752,7 @@ if build 'curl' "${g_ver}"; then
                  LIBS="$(pkg-config --libs libnghttp3)"
     execute make "-j${cpu_threads}"
     execute sudo make install
-    build_done 'curl' "${g_ver}"
+    build_done 'curl' "$g_ver"
 fi
 
 #
@@ -766,7 +766,7 @@ if build 'aria2' '1.36.0'; then
     execute sed -i 's/1, 16/1, 128/g' 'src/OptionHandlerFactory.cc'
     mkdir build
     cd build || exit 1
-    ../configure --prefix="${install_dir}"               \
+    ../configure --prefix="$install_dir"               \
                  --{build,host,target}="${pc_type}"      \
                  --disable-nls                           \
                  --disable-shared                        \
diff --git a/Bash/Installer Scripts/GitHub Projects/build-aria2 b/Bash/Installer Scripts/GitHub Projects/build-aria2
--- a/Bash/Installer Scripts/GitHub Projects/build-aria2
+++ b/Bash/Installer Scripts/GitHub Projects/build-aria2
@@ -39,10 +39,10 @@ fi
 script_ver=1.8
 archive_ver=1.37.0
 archive_dir="aria2-${archive_ver}"
-archive_url="https://github.com/aria2/aria2/releases/download/release-${archive_ver}/${archive_dir}.tar.xz"
+archive_url="https://github.com/aria2/aria2/releases/download/release-${archive_ver}/$archive_dir.tar.xz"
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/aria2-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/aria2-build-script
 install_dir=/usr/local
 # MAKE SURE WE LOCATES AND THEN USE THE CORRECT ARIA2 LIBRARY DIRECTORY AND EXTRA LIBS
 openssl_lib_dir="$(pkg-config --variable=libdir openssl)"
@@ -59,16 +59,16 @@ web_repo=https://github.com/slyfox1186/script-repo
 
 box_out_banner_aria2()
 {
-    input_char=$(echo "${@}" | wc -c)
+    input_char=$(echo "$@" | wc -c)
     line=$(for i in $(seq 0 ${input_char}); do printf '-'; done)
     tput bold
-    line="$(tput setaf 3)${line}"
+    line="$(tput setaf 3)$line"
     space="${line//-/ }"
-    echo " ${line}"
+    echo " $line"
     printf '|' ; echo -n "${space}" ; printf "%s\n" '|';
-    printf '| ' ;tput setaf 4; echo -n "${@}"; tput setaf 3 ; printf "%s\n" ' |';
+    printf '| ' ;tput setaf 4; echo -n "$@"; tput setaf 3 ; printf "%s\n" ' |';
     printf '|' ; echo -n "${space}" ; printf "%s\n" '|';
-    echo " ${line}"
+    echo " $line"
     tput sgr 0
 }
 box_out_banner_aria2 "Aria2 Build Script - v${script_ver}"
@@ -81,28 +81,25 @@ sleep 2
 
 find_lsb_release="$(sudo find /usr/bin/ -type f -name 'lsb_release')"
 
-if [ -f '/etc/os-release' ]; then
-    . '/etc/os-release'
+if [ -f /etc/os-release ]; then
+    . /etc/os-release
     OS_TMP="$NAME"
-    VER_TMP="$VERSION_ID"
     CODENAME="$VERSION_CODENAME"
     OS="$(echo "${OS_TMP}" | awk '{print $1}')"
-    VER="$(echo "${VER_TMP}" | awk '{print $1}')"
 elif [ -n "${find_lsb_release}" ]; then
     OS="$(lsb_release -d | awk '{print $2}')"
-    VER="$(lsb_release -r | awk '{print $2}')"
 else
-    fail_fn "Failed to define the \$OS and/or \$VER variables. Line: ${LINENO}"
+    fail_fn "Failed to define the \$OS variable. Line: ${LINENO}"
 fi
 
 #
 # CREATE THE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE CC/CXX COMPILERS & THE COMPILER OPTIMIZATION FLAGS
@@ -112,7 +109,7 @@ CC=gcc
 CXX=g++
 CFLAGS='-g -O3 -pipe -march=native'
 CXXFLAGS="${CFLAGS}"
-CPPFLAGS="-I${install_dir}/include/x86_64-linux-gnu"
+CPPFLAGS="-I$install_dir/include/x86_64-linux-gnu"
 export CC CXX CFLAGS CPPFLAGS CXXFLAGS
 
 #
@@ -161,16 +158,16 @@ exit_fn()
     printf "%s\n\n%s\n%s\n\n"                                     \
         'The script has completed'                                \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n\n%s\n\n%s\n\n%s\n\n"                              \
-        "${1}"                                                   \
+        "$1"                                                   \
         'Please create a support ticket so I can work on a fix.' \
-        "${web_repo}/issues"
+        "$web_repo/issues"
     exit 1
 }
 
@@ -199,7 +196,7 @@ cleanup_fn()
     clear
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      clear;;
         *)
                 unset choice
@@ -213,8 +210,8 @@ cleanup_fn()
 # INSTALL THE LATEST CA CERTS FROM CURL'S OFFICIAL WEBSITE
 #
 
-curl -A "${user_agent}" -Lso "${cwd}/${pem_file}" "https://curl.se/ca/${pem_file}"
-if ! sudo mv "${cwd}/${pem_file}" "${certs_dir}/${pem_file}"; then
+curl -A "$user_agent" -Lso "$cwd/$pem_file" "https://curl.se/ca/$pem_file"
+if ! sudo mv "$cwd/$pem_file" "$certs_dir/$pem_file"; then
     fail_fn "Failed to move cacert.pem. Line: ${LINENO}"
 fi
 
@@ -245,18 +242,18 @@ fi
 # BUILD JEMALLOC FROM SOURCE CODE
 #
 
-if [ -d "${cwd}/jemalloc-5.3.0" ]; then
-    sudo rm -fr "${cwd}/jemalloc-5.3.0"
+if [ -d "$cwd/jemalloc-5.3.0" ]; then
+    sudo rm -fr "$cwd/jemalloc-5.3.0"
 fi
-mkdir -p "${cwd}/jemalloc-5.3.0/build"
+mkdir -p "$cwd/jemalloc-5.3.0/build"
 
 #
 # DOWNLOAD JEMALLOC SOURCE CODE
 #
 
-if [ ! -f "${cwd}/jemalloc-5.3.0.tar.bz2" ]; then
-    if ! curl -A "${user_agent}" -m 10 -Lso "${cwd}/jemalloc-5.3.0.tar.bz2" 'https://github.com/jemalloc/jemalloc/releases/download/5.3.0/jemalloc-5.3.0.tar.bz2'; then
-        fail_fn "Failed to download the file: ${cwd}/jemalloc-5.3.0.tar.bz2. Line: ${LINENO}"
+if [ ! -f "$cwd/jemalloc-5.3.0.tar.bz2" ]; then
+    if ! curl -A "$user_agent" -m 10 -Lso "$cwd/jemalloc-5.3.0.tar.bz2" 'https://github.com/jemalloc/jemalloc/releases/download/5.3.0/jemalloc-5.3.0.tar.bz2'; then
+        fail_fn "Failed to download the file: $cwd/jemalloc-5.3.0.tar.bz2. Line: ${LINENO}"
     fi
 fi
 
@@ -264,20 +261,20 @@ fi
 # EXTRACT JEMALLOC INTO OUTPUT DIRECTORY
 #
 
-if ! tar -jxf "${cwd}/jemalloc-5.3.0.tar.bz2" -C "${cwd}/jemalloc-5.3.0" --strip-components 1; then
-    fail_fn "Failed to extract: ${cwd}/jemalloc-5.3.0.tar.bz2"
+if ! tar -jxf "$cwd/jemalloc-5.3.0.tar.bz2" -C "$cwd/jemalloc-5.3.0" --strip-components 1; then
+    fail_fn "Failed to extract: $cwd/jemalloc-5.3.0.tar.bz2"
 fi
 
 #
 # CD INTO OUTPUT DIRECTORY AND CONFIGURE JEMALLOC
 #
 
-cd "${cwd}/jemalloc-5.3.0" || exit 1
+cd "$cwd/jemalloc-5.3.0" || exit 1
 extracmds1=('--disable-'{debug,doc,fill,log,shared,prof,stats})
 extracmds2=('--enable-'{autogen,static,xmalloc})
 ./autogen.sh
 cd build || exit 1
-../configure --prefix="${install_dir}" \
+../configure --prefix="$install_dir" \
              "${extracmds1[@]}"        \
              "${extracmds2[@]}"
 echo
@@ -293,18 +290,18 @@ fi
 # BUILD GCRYPT-ERROR FROM SOURCE CODE
 #
 
-if [ -d "${cwd}/gcrypt-error-1.47" ]; then
-    sudo rm -fr "${cwd}/gcrypt-error-1.47"
+if [ -d "$cwd/gcrypt-error-1.47" ]; then
+    sudo rm -fr "$cwd/gcrypt-error-1.47"
 fi
-mkdir -p "${cwd}/gcrypt-error-1.47/build"
+mkdir -p "$cwd/gcrypt-error-1.47/build"
 
 #
 # DOWNLOAD GCRYPT-ERROR SOURCE CODE
 #
 
-if [ ! -f "${cwd}/gcrypt-error-1.47.tar.bz2" ]; then
-    if ! curl -A "${user_agent}" -m 10 -Lso "${cwd}/gcrypt-error-1.47.tar.bz2" 'https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.47.tar.bz2'; then
-        fail_fn "Failed to download the file: ${cwd}/gcrypt-error-1.47.tar.bz2. Line: ${LINENO}"
+if [ ! -f "$cwd/gcrypt-error-1.47.tar.bz2" ]; then
+    if ! curl -A "$user_agent" -m 10 -Lso "$cwd/gcrypt-error-1.47.tar.bz2" 'https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.47.tar.bz2'; then
+        fail_fn "Failed to download the file: $cwd/gcrypt-error-1.47.tar.bz2. Line: ${LINENO}"
     fi
 fi
 
@@ -312,18 +309,18 @@ fi
 # EXTRACT GCRYPT-ERROR INTO OUTPUT DIRECTORY
 #
 
-if ! tar -jxf "${cwd}/gcrypt-error-1.47.tar.bz2" -C "${cwd}/gcrypt-error-1.47" --strip-components 1; then
-    fail_fn "Failed to extract: ${cwd}/gcrypt-error-1.47.tar.bz2"
+if ! tar -jxf "$cwd/gcrypt-error-1.47.tar.bz2" -C "$cwd/gcrypt-error-1.47" --strip-components 1; then
+    fail_fn "Failed to extract: $cwd/gcrypt-error-1.47.tar.bz2"
 fi
 
 #
 # CD INTO OUTPUT DIRECTORY AND CONFIGURE GCRYPT-ERROR
 #
 
-cd "${cwd}/gcrypt-error-1.47" || exit 1
+cd "$cwd/gcrypt-error-1.47" || exit 1
 ./autogen.sh
 cd build || exit 1
-../configure --prefix="${install_dir}"         \
+../configure --prefix="$install_dir"         \
              --disable-doc                     \
              --disable-languages               \
              --disable-nls                     \
@@ -347,25 +344,25 @@ fi
 # CREATE THE ARIA2 OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # DOWNLOAD THE ARIA2 SOURCE CODE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -m 10 -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -m 10 -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # EXTRACT THE ARIA2 SOURCE CODE INTO THE OUTPUT DIRECTORY
 #
 
-if ! tar -xf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    fail_fn "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    fail_fn "Failed to extract: $cwd/${archive_name}"
 fi
 
 #
@@ -376,17 +373,17 @@ printf "\n%s\n%s\n\n"                      \
     "Build Aria2 - version ${archive_ver}" \
     '==============================================='
 
-cd "${cwd}/${archive_dir}" || exit 1
+cd "$cwd/$archive_dir" || exit 1
 # INCREASE THE MAX NUMBER OF CONNECTIONS FROM 16 TO 128
 sed -i 's/1, 16/1, 128/g' 'src/OptionHandlerFactory.cc'
 cd build || exit 1
-../configure --prefix="${install_dir}"                         \
+../configure --prefix="$install_dir"                         \
              --disable-nls                                     \
              --disable-shared                                  \
              --disable-werror                                  \
              --enable-libaria2                                 \
              --enable-static                                   \
-             --with-ca-bundle="${certs_dir}/${pem_file}"       \
+             --with-ca-bundle="$certs_dir/$pem_file"       \
              --with-libiconv-prefix=/usr                       \
              --with-libintl-prefix=/usr                        \
              --with-libuv                                      \
diff --git a/Bash/Installer Scripts/GitHub Projects/build-clang-16 b/Bash/Installer Scripts/GitHub Projects/build-clang-16
--- a/Bash/Installer Scripts/GitHub Projects/build-clang-16
+++ b/Bash/Installer Scripts/GitHub Projects/build-clang-16
@@ -26,7 +26,7 @@ fi
 
 script_ver=1.2
 progname="${0}"
-cwd="${PWD}"/clang-16-build-script
+cwd="$PWD"/clang-16-build-script
 install_prefix=/usr/local
 pc_type=x86_64-linux-gnu
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
@@ -37,8 +37,8 @@ debug=OFF # CHANGE THIS VARIABLE TO "ON" FOR HELP WITH TROUBLESHOOTING UNEXPECTE
 # CREATE OUTPUT DIRECTORIES
 #
 
-if [ ! -d "${cwd}" ]; then
-    mkdir -p "${cwd}"
+if [ ! -d "$cwd" ]; then
+    mkdir -p "$cwd"
 fi
 
 #
@@ -106,16 +106,16 @@ exit_fn()
     printf "\n%s\n\n%s\n%s\n\n"                                    \
         'The script has completed'                                \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n\n%s\n\n%s\n\n%s\n\n"      \
-        "${1}"                           \
+        "$1"                           \
         'To report a bug please visit: ' \
-        "${web_repo}/issues"
+        "$web_repo/issues"
     exit 1
 }
 
@@ -130,7 +130,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      clear;;
         *)
                 clear
@@ -146,8 +146,8 @@ cleanup_fn()
 create_soft_link_fn()
 {
     clear
-    if [ -f "${install_prefix}"/bin/clang++ ] && [ ! -f "${install_prefix}"/bin/clang++-16 ]; then
-        if ! sudo ln -s "${install_prefix}"/bin/clang++ "${install_prefix}"/bin/clang++-16; then
+    if [ -f "$install_prefix"/bin/clang++ ] && [ ! -f "$install_prefix"/bin/clang++-16 ]; then
+        if ! sudo ln -s "$install_prefix"/bin/clang++ "$install_prefix"/bin/clang++-16; then
             printf "\n%s\n\n" "Failed to create the clang++ soft link. Line: ${LINENO}"
         fi
     fi
@@ -157,19 +157,19 @@ show_ver_fn()
 {
     printf "%s\n\n" 'The installed clang version is:'
 
-    if [ -f "${install_prefix}"/bin/clang-16 ]; then
+    if [ -f "$install_prefix"/bin/clang-16 ]; then
         printf "%s\n" 'clang-16:'
-        "${install_prefix}"/bin/clang-16 --version
+        "$install_prefix"/bin/clang-16 --version
         echo
     fi
 
-    if [ -f "${install_prefix}"/bin/clang++-16 ]; then
+    if [ -f "$install_prefix"/bin/clang++-16 ]; then
         printf "%s\n" 'clang++-16:'
-        "${install_prefix}"/bin/clang++-16 --version
+        "$install_prefix"/bin/clang++-16 --version
         echo
-    elif [ -f "${install_prefix}"/bin/clang++ ]; then
+    elif [ -f "$install_prefix"/bin/clang++ ]; then
         printf "%s\n" 'clang-++:'
-        "${install_prefix}"/bin/clang++ --version
+        "$install_prefix"/bin/clang++ --version
         echo
     fi
 }
@@ -179,12 +179,12 @@ execute()
     echo "$ ${*}"
 
     if [ "${debug}" = 'ON' ]; then
-        if ! output="$("${@}")"; then
+        if ! output="$("$@")"; then
             notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
             fail_fn "Failed to execute: ${*}"
         fi
     else
-        if ! output="$("${@}" 2>&1)"; then
+        if ! output="$("$@" 2>&1)"; then
             notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
             fail_fn "Failed to execute: ${*}"
         fi
@@ -194,83 +194,83 @@ execute()
 build()
 {
     printf "\n%s\n%s\n" \
-        "Building ${1} - version ${2}" \
+        "Building $1 - version $2" \
         '=========================================='
 
-    if [ -f "${cwd}/${1}.done" ]; then
-        if grep -Fx "${2}" "${cwd}/${1}.done" >/dev/null; then
-            echo "${1} version ${2} already built. Remove ${cwd}/${1}.done lockfile to rebuild it."
+    if [ -f "$cwd/$1.done" ]; then
+        if grep -Fx "$2" "$cwd/$1.done" >/dev/null; then
+            echo "$1 version $2 already built. Remove $cwd/$1.done lockfile to rebuild it."
             return 1
         fi
     fi
     return 0
 }
 
-build_done() { echo "${2}" > "${cwd}/${1}.done"; }
+build_done() { echo "$2" > "$cwd/$1.done"; }
 
 download()
 {
-    dl_path="${cwd}"
-    dl_url="${1}"
+    dl_path="$cwd"
+    dl_url="$1"
     dl_file="${2:-"${1##*/}"}"
 
-    if [[ "${dl_file}" =~ tar. ]]; then
+    if [[ "$dl_file" =~ tar. ]]; then
         output_dir="${dl_file%.*}"
         output_dir="${3:-"${output_dir%.*}"}"
     else
         output_dir="${3:-"${dl_file%.*}"}"
     fi
 
-    target_file="${dl_path}/${dl_file}"
-    target_dir="${dl_path}/${output_dir}"
+    target_file="$dl_path/$dl_file"
+    target_dir="$dl_path/$output_dir"
 
     if [ -f "${target_file}" ]; then
-        echo "The file \"${dl_file}\" is already downloaded."
+        echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"${dl_file}\""
-        if ! wget --show-progress -U "${user_agent}" -cqO "${target_file}" "${dl_url}"; then
-            printf "\n%s\n\n" "The script failed to download \"${dl_file}\" and will try again in 10 seconds..."
+        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
+        if ! wget --show-progress -U "$user_agent" -cqO "${target_file}" "${dl_url}"; then
+            printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! wget --show-progress -U "${user_agent}" -cqO "${target_file}" "${dl_url}"; then
-                fail_fn "The script failed to download \"${dl_file}\" twice and will now exit. Line: ${LINENO}"
+            if ! wget --show-progress -U "$user_agent" -cqO "${target_file}" "${dl_url}"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit. Line: ${LINENO}"
             fi
         fi
         printf "\n%s\n\n" 'Download completed'
     fi
 
-    if [ -d "${target_dir}" ]; then
-        sudo rm -fr "${target_dir}"
+    if [ -d "$target_dir" ]; then
+        sudo rm -fr "$target_dir"
     fi
 
-    mkdir -p "${target_dir}"
+    mkdir -p "$target_dir"
 
-    if [ -n "${3}" ]; then
-        if ! tar -xf "${target_file}" -C "${target_dir}" 2>/dev/null >/dev/null; then
+    if [ -n "$3" ]; then
+        if ! tar -xf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script. Line: ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
         fi
     else
-        if ! tar -xf "${target_file}" -C "${target_dir}" --strip-components 1 2>/dev/null >/dev/null; then
+        if ! tar -xf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script. Line: ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
         fi
     fi
 
-    printf "%s\n\n" "File extracted: ${dl_file}"
+    printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}. Line: ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: ${LINENO}"
 }
 
 git_1_fn()
 {
     local curl_cmd github_repo github_url
 
-    github_repo="${1}"
-    github_url="${2}"
+    github_repo="$1"
+    github_url="$2"
 
-    if curl_cmd="$(curl -A "${user_agent}" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
-        g_ver="$(echo "${curl_cmd}" | jq -r '.[1].name' 2>/dev/null)"
-        g_url="$(echo "${curl_cmd}" | jq -r '.[1].tarball_url' 2>/dev/null)"
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
+        g_ver="$(echo "$curl_cmd" | jq -r '.[1].name' 2>/dev/null)"
+        g_url="$(echo "$curl_cmd" | jq -r '.[1].tarball_url' 2>/dev/null)"
         g_ver="${g_ver#llvmorg-}"
     fi
 }
@@ -279,8 +279,8 @@ git_ver_fn()
 {
     local t_flag v_flag v_url
 
-    v_url="${1}"
-    v_flag="${2}"
+    v_url="$1"
+    v_flag="$2"
 
     case "${v_flag}" in
             R)      t_flag=releases;;
@@ -327,16 +327,16 @@ sudo ldconfig 2>/dev/null
 clear
 box_out_banner()
 {
-    input_char=$(echo "${@}" | wc -c)
+    input_char=$(echo "$@" | wc -c)
     line=$(for i in $(seq 0 ${input_char}); do printf '-'; done)
     tput bold
-    line="$(tput setaf 3)${line}"
+    line="$(tput setaf 3)$line"
     space=${line//-/ }
-    echo " ${line}"
+    echo " $line"
     printf '|' ; echo -n "${space}" ; printf "%s\n" '|';
-    printf '| ' ;tput setaf 4; echo -n "${@}"; tput setaf 3 ; printf "%s\n" ' |';
+    printf '| ' ;tput setaf 4; echo -n "$@"; tput setaf 3 ; printf "%s\n" ' |';
     printf '|' ; echo -n "${space}" ; printf "%s\n" '|';
-    echo " ${line}"
+    echo " $line"
     tput sgr 0
 }
 box_out_banner "Clang Build Script - version ${script_ver}"
@@ -346,7 +346,7 @@ if build 'llvm' '16.0.6'; then
     project_pkgs='clang;clang-tools-extra'
     runtime_pkgs='libcxx;libcxxabi;libunwind;compiler-rt'
     cmake -S llvm -B build                           \
-          -DCMAKE_INSTALL_PREFIX="${install_prefix}" \
+          -DCMAKE_INSTALL_PREFIX="$install_prefix" \
           -DCMAKE_BUILD_TYPE=Release                 \
           -DBUILD_SHARED_LIBS=OFF                    \
           -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON       \
diff --git a/Bash/Installer Scripts/GitHub Projects/build-libgcrypt b/Bash/Installer Scripts/GitHub Projects/build-libgcrypt
--- a/Bash/Installer Scripts/GitHub Projects/build-libgcrypt
+++ b/Bash/Installer Scripts/GitHub Projects/build-libgcrypt
@@ -28,9 +28,9 @@ fi
 
 script_ver=1.0
 install_prefix=/usr/local
-cwd="${PWD}"/gcrypt-build-script
-packages="${cwd}"/packages
-workspace="${cwd}"/workspace
+cwd="$PWD"/gcrypt-build-script
+packages="$cwd"/packages
+workspace="$cwd"/workspace
 pc_type=x86_64-linux-gnu
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
@@ -40,7 +40,7 @@ debug=OFF
 # CREATE OUTPUT DIRECTORIES
 #
 
-mkdir -p "${packages}" "${workspace}"
+mkdir -p "$packages" "$workspace"
 
 #
 # GET CPU CORE COUNT FOR PARALLEL PROCESSING
@@ -63,8 +63,8 @@ export CC=gcc CXX=g++
 #
 
 export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -march=native'
-CPPFLAGS="-I${workspace}/include -I/usr/local/include -I/usr/include"
-LDFLAGS="-L${workspace}/lib64 -L${workspace}/lib -L${workspace}/lib/x86_64-linux-gnu -L/usr/local/lib64"
+CPPFLAGS="-I$workspace/include -I/usr/local/include -I/usr/include"
+LDFLAGS="-L$workspace/lib64 -L$workspace/lib -L$workspace/lib/x86_64-linux-gnu -L/usr/local/lib64"
 LDFLAGS+=' -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib64 -L/usr/lib -L/lib64 -L/lib'
 export CPPFLAGS LDFLAGS
 
@@ -101,11 +101,11 @@ ${HOME}/.local/bin:\
 export PATH
 
 PKG_CONFIG_PATH="\
-${workspace}/usr/lib/pkgconfig:\
-${workspace}/lib64/pkgconfig:\
-${workspace}/lib/pkgconfig:\
-${workspace}/lib/x86_64-linux-gnu/pkgconfig:\
-${workspace}/share/pkgconfig:\
+$workspace/usr/lib/pkgconfig:\
+$workspace/lib64/pkgconfig:\
+$workspace/lib/pkgconfig:\
+$workspace/lib/x86_64-linux-gnu/pkgconfig:\
+$workspace/share/pkgconfig:\
 /usr/local/lib64/pkgconfig:\
 /usr/local/lib/pkgconfig:\
 /usr/local/lib/x86_64-linux-gnu/pkgconfig:\
@@ -129,9 +129,9 @@ export PKG_CONFIG_PATH
 fail_fn()
 {
     printf "\n%s\n%s\n%s\n\n" \
-        "${1}" \
+        "$1" \
         'You can enable the script'\''s debugging feature by changing the variable "debug" to "ON"' \
-        "To report a bug visit: ${web_repo}/issues"
+        "To report a bug visit: $web_repo/issues"
     exit 1
 }
 
@@ -139,7 +139,7 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
@@ -155,7 +155,7 @@ cleanup_fn()
     clear
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      clear;;
         *)
                 unset choice
@@ -172,12 +172,12 @@ git_1_fn()
 {
     local curl_cmd github_repo github_url
 
-    github_repo="${1}"
-    github_url="${2}"
+    github_repo="$1"
+    github_url="$2"
 
-    if curl_cmd="$(curl -A "${user_agent}" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
-        g_ver="$(echo "${curl_cmd}" | jq -r '.[0].name' 2>/dev/null)"
-        g_url="$(echo "${curl_cmd}" | jq -r '.[0].tarball_url' 2>/dev/null)"
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
+        g_ver="$(echo "$curl_cmd" | jq -r '.[0].name' 2>/dev/null)"
+        g_url="$(echo "$curl_cmd" | jq -r '.[0].tarball_url' 2>/dev/null)"
         g_ver="${g_ver#cares-}"
         g_ver="${g_ver#aria2 }"
         g_ver="${g_ver#nghttp2 v}"
@@ -193,11 +193,11 @@ git_ver_fn()
 {
     local v_flag v_url v_tag url_tag t_url
 
-    v_url="${1}"
-    v_tag="${2}"
+    v_url="$1"
+    v_tag="$2"
 
-    if [ -n "${3}" ]; then
-        v_flag="${3}"
+    if [ -n "$3" ]; then
+        v_flag="$3"
         case "${v_flag}" in
             T)      t_url=tags;;
             R)      t_url=releases;;
@@ -213,12 +213,12 @@ execute()
     echo "$ ${*}"
 
     if [ "${debug}" = 'ON' ]; then
-        if ! output=$("${@}"); then
+        if ! output=$("$@"); then
             notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
             fail_fn "Failed to execute: ${*}"
         fi
     else
-        if ! output=$("${@}" 2>&1); then
+        if ! output=$("$@" 2>&1); then
             notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
             fail_fn "Failed to execute: ${*}"
         fi
@@ -227,68 +227,68 @@ execute()
 
 download()
 {
-    dl_path="${packages}"
-    dl_url="${1}"
+    dl_path="$packages"
+    dl_url="$1"
     dl_file="${2:-"${1##*/}"}"
 
-    if [[ "${dl_file}" =~ tar. ]]; then
+    if [[ "$dl_file" =~ tar. ]]; then
         output_dir="${dl_file%.*}"
         output_dir="${3:-"${output_dir%.*}"}"
     else
         output_dir="${3:-"${dl_file%.*}"}"
     fi
 
-    target_file="${dl_path}/${dl_file}"
-    target_dir="${dl_path}/${output_dir}"
+    target_file="$dl_path/$dl_file"
+    target_dir="$dl_path/$output_dir"
 
     if [ -f "${target_file}" ]; then
-        echo "The file \"${dl_file}\" is already downloaded."
+        echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"${dl_file}\""
-        if ! wget -U "${user_agent}" -cqO "${target_file}" "${dl_url}"; then
-            printf "\n%s\n\n" "The script failed to download \"${dl_file}\" and will try again in 10 seconds..."
+        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
+        if ! wget -U "$user_agent" -cqO "${target_file}" "${dl_url}"; then
+            printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! wget -U "${user_agent}" -cqO "${target_file}" "${dl_url}"; then
-                fail_fn "The script failed to download \"${dl_file}\" twice and will now exit. Line: ${LINENO}"
+            if ! wget -U "$user_agent" -cqO "${target_file}" "${dl_url}"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit. Line: ${LINENO}"
             fi
         fi
         echo 'Download Completed'
     fi
 
-    if [ -d "${target_dir}" ]; then
-        sudo rm -fr "${target_dir}"
+    if [ -d "$target_dir" ]; then
+        sudo rm -fr "$target_dir"
     fi
-    mkdir -p "${target_dir}"
+    mkdir -p "$target_dir"
 
-    if [ -n "${3}" ]; then
-        if ! tar -xf "${target_file}" -C "${target_dir}" 2>/dev/null >/dev/null; then
+    if [ -n "$3" ]; then
+        if ! tar -xf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script. Line: ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
         fi
     else
-        if ! tar -xf "${target_file}" -C "${target_dir}" --strip-components 1 2>/dev/null >/dev/null; then
+        if ! tar -xf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script. Line: ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
         fi
     fi
 
-    printf "%s\n\n" "File extracted: ${dl_file}"
+    printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}. Line: ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: ${LINENO}"
 }
 
 build()
 {
     printf "\n%s\n%s\n" \
-        "building ${1} - version ${2}" \
+        "building $1 - version $2" \
         '===================================='
 
-    if [ -f "${packages}/${1}.done" ]; then
-        if grep -Fx "${2}" "${packages}/${1}.done" > /dev/null; then
-            echo "${1} version ${2} already built. Remove ${packages}/${1}.done lockfile to rebuild it."
+    if [ -f "$packages/$1.done" ]; then
+        if grep -Fx "$2" "$packages/$1.done" > /dev/null; then
+            echo "$1 version $2 already built. Remove $packages/$1.done lockfile to rebuild it."
             return 1
         else
-            echo "${1} is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove ${packages}/${1}.done lockfile."
+            echo "$1 is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove $packages/$1.done lockfile."
             return 1
         fi
     fi
@@ -298,12 +298,12 @@ build()
 
 build_done()
 {
-    echo "${2}" > "${packages}/${1}.done"
+    echo "$2" > "$packages/$1.done"
 }
 
 installed()
 {
-    return $(dpkg-query -W -f '${Status}\n' "${1}" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}')
+    return $(dpkg-query -W -f '${Status}\n' "$1" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}')
 }
 
 #
@@ -339,7 +339,7 @@ fi
 if build 'libgpg-error' '1.47'; then
     download 'https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.47.tar.bz2' 'libgpg-error-1.47.tar.bz2'
     execute ./autogen.sh
-    execute ./configure --prefix="${install_prefix}" \
+    execute ./configure --prefix="$install_prefix" \
                         --{build,host}="${pc_type}"  \
                         --disable-doc                \
                         --disable-nls                \
@@ -353,17 +353,17 @@ if build 'libgpg-error' '1.47'; then
                         --with-pic
     execute make "-j${cpu_threads}"
     execute sudo make install
-    execute sudo cp -f 'src/gpg-error-config' "${install_prefix}"/bin
+    execute sudo cp -f 'src/gpg-error-config' "$install_prefix"/bin
     build_done 'libgpg-error' '1.47'
 fi
 
 if build 'libgcrypt' '1.8.10-LTS'; then
     download 'https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.10.tar.bz2' 'libgcrypt-1.8.10-LTS.tar.bz2'
     execute ./autogen.sh
-    ./configure --prefix="${install_prefix}"                   \
+    ./configure --prefix="$install_prefix"                   \
                 --{build,host}="${pc_type}"                    \
                 --enable-static                                \
-                --with-libgpg-error-prefix="${install_prefix}" \
+                --with-libgpg-error-prefix="$install_prefix" \
                 --with-pic
     execute make "-j${cpu_threads}"
     execute sudo make install
diff --git a/Bash/Installer Scripts/GitHub Projects/build-libpng b/Bash/Installer Scripts/GitHub Projects/build-libpng
--- a/Bash/Installer Scripts/GitHub Projects/build-libpng
+++ b/Bash/Installer Scripts/GitHub Projects/build-libpng
@@ -25,7 +25,7 @@ fi
 #
 
 script_ver=1.1
-cwd="${PWD}"/libpng-build-script
+cwd="$PWD"/libpng-build-script
 install_dir=/usr/local
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
@@ -39,10 +39,10 @@ printf "\n%s\n%s\n\n" \
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE C+CPP COMPILERS
@@ -106,15 +106,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -131,7 +131,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -147,18 +147,18 @@ cleanup_fn()
 build()
 {
     printf "\n%s\n%s\n" \
-        "building ${1} - version ${2}" \
+        "building $1 - version $2" \
         '===================================='
 
-    if [ -f "${cwd}/${1}.done" ]; then
-        if grep -Fx "${2}" "${cwd}/${1}.done" >/dev/null; then
-            echo "${1} version ${2} already built. Remove ${cwd}/${1}.done lockfile to rebuild it."
+    if [ -f "$cwd/$1.done" ]; then
+        if grep -Fx "$2" "$cwd/$1.done" >/dev/null; then
+            echo "$1 version $2 already built. Remove $cwd/$1.done lockfile to rebuild it."
             return 1
         elif ${latest}; then
-            echo "${1} is oudebugtdated and will be rebuilt using version ${2}"
+            echo "$1 is oudebugtdated and will be rebuilt using version $2"
             return 0
         else
-            echo "${1} is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove ${cwd}/${1}.done lockfile."
+            echo "$1 is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove $cwd/$1.done lockfile."
             return 1
         fi
     fi
@@ -170,12 +170,12 @@ execute()
     echo "$ ${*}"
 
     if [ "${debug}" = 'ON' ]; then
-        if ! output=$("${@}"); then
+        if ! output=$("$@"); then
             notify-send 5000 "Failed to execute: ${*}"
             fail_fn "Failed to execute: ${*}"
         fi
     else
-        if ! output=$("${@}" 2>&1); then
+        if ! output=$("$@" 2>&1); then
             notify-send 5000 "Failed to execute: ${*}"
             fail_fn "Failed to execute: ${*}"
         fi
@@ -184,55 +184,55 @@ execute()
 
 download()
 {
-    dl_path="${cwd}"
-    dl_url="${1}"
+    dl_path="$cwd"
+    dl_url="$1"
     dl_file="${2:-"${1##*/}"}"
 
-    if [[ "${dl_file}" =~ tar. ]]; then
+    if [[ "$dl_file" =~ tar. ]]; then
         output_dir="${dl_file%.*}"
         output_dir="${3:-"${output_dir%.*}"}"
     else
         output_dir="${3:-"${dl_file%.*}"}"
     fi
 
-    target_file="${dl_path}/${dl_file}"
-    target_dir="${dl_path}/${output_dir}"
+    target_file="$dl_path/$dl_file"
+    target_dir="$dl_path/$output_dir"
 
     if [ -f "${target_file}" ]; then
-        echo "The file \"${dl_file}\" is already downloaded."
+        echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"${dl_file}\""
-        if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
-            printf "\n%s\n\n" "The script failed to download \"${dl_file}\" and will try again in 10 seconds..."
+        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
+        if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+            printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
-                fail_fn "The script failed to download \"${dl_file}\" twice and will now exit:Line ${LINENO}"
+            if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit:Line ${LINENO}"
             fi
         fi
         echo 'Download Completed'
     fi
 
-    if [ -d "${target_dir}" ]; then
-        sudo rm -fr "${target_dir}"
+    if [ -d "$target_dir" ]; then
+        sudo rm -fr "$target_dir"
     fi
 
-    mkdir -p "${target_dir}"
+    mkdir -p "$target_dir"
 
-    if [ -n "${3}" ]; then
-        if ! tar -xf "${target_file}" -C "${target_dir}" 2>/dev/null >/dev/null; then
+    if [ -n "$3" ]; then
+        if ! tar -xf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script:Line ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line ${LINENO}"
         fi
     else
-        if ! tar -xf "${target_file}" -C "${target_dir}" --strip-components 1 2>/dev/null >/dev/null; then
+        if ! tar -xf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script:Line ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line ${LINENO}"
         fi
     fi
 
-    printf "%s\n\n" "File extracted: ${dl_file}"
+    printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}:Line ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir:Line ${LINENO}"
 }
 
 #
@@ -261,7 +261,7 @@ pkgs_fn()
     fi
 }
 
-build_done() { echo "${2}" > "${cwd}/${1}.done"; }
+build_done() { echo "$2" > "$cwd/$1.done"; }
 
 #
 # INSTALL APT PACKAGES
@@ -277,7 +277,7 @@ if build 'libpng' '1.6.40'; then
     download 'https://github.com/glennrp/libpng/archive/refs/tags/v1.6.40.tar.gz' 'libpng-1.6.40.tar.gz'
     execute autoupdate
     execute autoreconf -fi
-    execute ./configure --prefix="${install_dir}"                 \
+    execute ./configure --prefix="$install_dir"                 \
                          --{build,host}=x86_64-linux-gnu          \
                          --disable-shared                         \
                          --enable-hardware-optimizations          \
diff --git a/Bash/Installer Scripts/GitHub Projects/build-libxml2 b/Bash/Installer Scripts/GitHub Projects/build-libxml2
--- a/Bash/Installer Scripts/GitHub Projects/build-libxml2
+++ b/Bash/Installer Scripts/GitHub Projects/build-libxml2
@@ -25,7 +25,7 @@ fi
 #
 
 script_ver=1.1
-cwd="${PWD}"/libxml2-build-script
+cwd="$PWD"/libxml2-build-script
 install_dir=/usr/local
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo='https://github.com/slyfox1186/script-repo'
@@ -40,10 +40,10 @@ sleep 2
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE C+CPP COMPILERS
@@ -107,15 +107,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n"                                       \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}"              \
-        "To report a bug create an issue at ${web_repo}/issues"
+        "$1"              \
+        "To report a bug create an issue at $web_repo/issues"
     exit 1
 }
 
@@ -132,7 +132,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 unset choice
@@ -145,15 +145,15 @@ cleanup_fn()
 build()
 {
     printf "\n%s\n%s\n"                \
-        "Building ${1} - version ${2}" \
+        "Building $1 - version $2" \
         '===================================='
 
-    if [ -f "${cwd}/${1}.done" ]; then
-        if grep -Fx "${2}" "${cwd}/${1}.done" >/dev/null; then
-            echo "${1} version ${2} already built. Remove ${cwd}/${1}.done lockfile to rebuild it."
+    if [ -f "$cwd/$1.done" ]; then
+        if grep -Fx "$2" "$cwd/$1.done" >/dev/null; then
+            echo "$1 version $2 already built. Remove $cwd/$1.done lockfile to rebuild it."
             return 1
         else
-            echo "${1} is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove ${cwd}/${1}.done lockfile."
+            echo "$1 is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove $cwd/$1.done lockfile."
             return 1
         fi
     fi
@@ -165,12 +165,12 @@ execute()
     echo "$ ${*}"
 
     if [ "${debug}" = 'ON' ]; then
-        if ! output=$("${@}"); then
+        if ! output=$("$@"); then
             notify-send 5000 "Failed to execute: ${*}" 2>/dev/null
             fail_fn "Failed to execute: ${*}"
         fi
     else
-        if ! output=$("${@}" 2>&1); then
+        if ! output=$("$@" 2>&1); then
             notify-send 5000 "Failed to execute: ${*}" 2>/dev/null
             fail_fn "Failed to execute: ${*}"
         fi
@@ -179,67 +179,67 @@ execute()
 
 download()
 {
-    dl_path="${cwd}"
-    dl_url="${1}"
+    dl_path="$cwd"
+    dl_url="$1"
     dl_file="${2:-"${1##*/}"}"
 
-    if [[ "${dl_file}" =~ tar. ]]; then
+    if [[ "$dl_file" =~ tar. ]]; then
         output_dir="${dl_file%.*}"
         output_dir="${3:-"${output_dir%.*}"}"
     else
         output_dir="${3:-"${dl_file%.*}"}"
     fi
 
-    target_file="${dl_path}/${dl_file}"
-    target_dir="${dl_path}/${output_dir}"
+    target_file="$dl_path/$dl_file"
+    target_dir="$dl_path/$output_dir"
 
     if [ -f "${target_file}" ]; then
-        echo "The file \"${dl_file}\" is already downloaded."
+        echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"${dl_file}\""
-        if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
-            printf "\n%s\n\n" "The script failed to download \"${dl_file}\" and will try again in 10 seconds..."
+        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
+        if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+            printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
-                fail_fn "The script failed to download \"${dl_file}\" twice and will now exit:Line ${LINENO}"
+            if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit:Line ${LINENO}"
             fi
         fi
         echo 'Download Completed'
     fi
 
-    if [ -d "${target_dir}" ]; then
-        sudo rm -fr "${target_dir}"
+    if [ -d "$target_dir" ]; then
+        sudo rm -fr "$target_dir"
     fi
 
-    mkdir -p "${target_dir}"
+    mkdir -p "$target_dir"
 
-    if [ -n "${3}" ]; then
-        if ! tar -xf "${target_file}" -C "${target_dir}" 2>/dev/null >/dev/null; then
+    if [ -n "$3" ]; then
+        if ! tar -xf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script:Line ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line ${LINENO}"
         fi
     else
-        if ! tar -xf "${target_file}" -C "${target_dir}" --strip-components 1 2>/dev/null >/dev/null; then
+        if ! tar -xf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script:Line ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line ${LINENO}"
         fi
     fi
 
-    printf "%s\n\n" "File extracted: ${dl_file}"
+    printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}:Line ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir:Line ${LINENO}"
 }
 
 git_1_fn()
 {
-    web_repo="${1}"
-    url="${2}"
-    if curl_cmd="$(curl -A "${user_agent}" -m 10 -sSL "https://gitlab.gnome.org/api/v4/projects/${web_repo}/repository/${url}" | jq -r '.[0].name')"; then
+    web_repo="$1"
+    url="$2"
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://gitlab.gnome.org/api/v4/projects/$web_repo/repository/${url}" | jq -r '.[0].name')"; then
         g_ver="${curl_cmd#v}"
     fi
 }
 
-build_done() { echo "${2}" > "${cwd}/${1}.done"; }
+build_done() { echo "$2" > "$cwd/$1.done"; }
 
 #
 # INSTALL REQUIRED APT PACKAGES
@@ -269,11 +269,11 @@ fi
 #
 
 git_1_fn '1665' 'tags'
-if build 'libxml2' "${g_ver}"; then
-    download "https://gitlab.gnome.org/GNOME/libxml2/-/archive/v${g_ver}/libxml2-v${g_ver}.tar.bz2" "libxml2-${g_ver}.tar.bz2"
+if build 'libxml2' "$g_ver"; then
+    download "https://gitlab.gnome.org/GNOME/libxml2/-/archive/v$g_ver/libxml2-v$g_ver.tar.bz2" "libxml2-$g_ver.tar.bz2"
     CFLAGS+=' -DNOLIBTOOL'
     execute ./autogen.sh
-    execute cmake -B build -DCMAKE_install_dir="${install_dir}" \
+    execute cmake -B build -DCMAKE_install_dir="$install_dir" \
                            -DCMAKE_EXPORT_COMPILE_COMMANDS=OFF  \
                            -DCMAKE_VERBOSE_MAKEFILE=OFF         \
                            -DBUILD_SHARED_LIBS=ON               \
@@ -289,7 +289,7 @@ if build 'libxml2' "${g_ver}"; then
                            -G Ninja -Wno-dev
     execute ninja "-j$(nproc --all)" -C build
     execute sudo ninja "-j$(nproc --all)" -C build install
-    build_done 'libxml2' "${g_ver}"
+    build_done 'libxml2' "$g_ver"
 fi
 
 # PROMPT USER TO CLEAN UP FILES
diff --git a/Bash/Installer Scripts/GitHub Projects/build-tools b/Bash/Installer Scripts/GitHub Projects/build-tools
--- a/Bash/Installer Scripts/GitHub Projects/build-tools
+++ b/Bash/Installer Scripts/GitHub Projects/build-tools
@@ -36,7 +36,7 @@ fi
 #
 
 script_ver=2.8
-cwd="${PWD}"/build-tools-script
+cwd="$PWD"/build-tools-script
 install_dir=/usr/local
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
@@ -66,7 +66,7 @@ fi
 # CREATE OUTPUT DIRECTORIES
 #
 
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE CC/CXX COMPILERS & THE COMPILER OPTIMIZATION FLAGS
@@ -114,7 +114,7 @@ PKG_CONFIG_PATH="\
 /usr/local/share/pkgconfig:\
 /usr/lib64/pkgconfig:\
 /usr/lib/pkgconfig:\
-/usr/lib/${install_dir}/pkgconfig:\
+/usr/lib/$install_dir/pkgconfig:\
 /usr/share/pkgconfig:\
 /lib64/pkgconfig:\
 /lib/pkgconfig:\
@@ -131,16 +131,16 @@ exit_fn()
     printf "\n%s\n\n%s\n%s\n\n"                                   \
         'The script has completed'                                \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n\n%s\n\n%s\n\n%s\n\n"                  \
-        "${1}"                                       \
+        "$1"                                       \
         'To report a bug please create an issue at:' \
-        "${web_repo}/issues"
+        "$web_repo/issues"
     exit 1
 }
 
@@ -155,7 +155,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' answer
 
     case "${answer}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      return 0;;
         *)
                 unset answer
@@ -188,12 +188,12 @@ execute()
     echo "$ ${*}"
 
     if [ "${debug}" = 'ON' ]; then
-        if ! output="$("${@}")"; then
+        if ! output="$("$@")"; then
             notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
             fail_fn "Failed to execute: ${*}"
         fi
     else
-        if ! output="$("${@}" 2>&1)"; then
+        if ! output="$("$@" 2>&1)"; then
             notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
             fail_fn "Failed to execute: ${*}"
         fi
@@ -202,134 +202,134 @@ execute()
 
 download()
 {
-    dl_path="${cwd}"
-    dl_url="${1}"
+    dl_path="$cwd"
+    dl_url="$1"
     dl_file="${2:-"${1##*/}"}"
 
-    if [[ "${dl_file}" =~ tar. ]]; then
+    if [[ "$dl_file" =~ tar. ]]; then
         output_dir="${dl_file%.*}"
         output_dir="${3:-"${output_dir%.*}"}"
     else
         output_dir="${3:-"${dl_file%.*}"}"
     fi
 
-    target_file="${dl_path}/${dl_file}"
-    target_dir="${dl_path}/${output_dir}"
+    target_file="$dl_path/$dl_file"
+    target_dir="$dl_path/$output_dir"
 
     if [ -f "${target_file}" ]; then
-        echo "The file \"${dl_file}\" is already downloaded."
+        echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"${dl_file}\""
-        if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
-            printf "\n%s\n\n" "The script failed to download \"${dl_file}\" and will try again in 10 seconds..."
+        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
+        if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+            printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
-                fail_fn "The script failed to download \"${dl_file}\" twice and will now exit:Line ${LINENO}"
+            if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit:Line ${LINENO}"
             fi
         fi
         echo 'Download Completed'
     fi
 
-    if [ -d "${target_dir}" ]; then
-        sudo rm -fr "${target_dir}"
+    if [ -d "$target_dir" ]; then
+        sudo rm -fr "$target_dir"
     fi
-    mkdir -p "${target_dir}"
+    mkdir -p "$target_dir"
 
-    if [ -n "${3}" ]; then
-        if ! tar -xf "${target_file}" -C "${target_dir}" 2>/dev/null >/dev/null; then
+    if [ -n "$3" ]; then
+        if ! tar -xf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script:Line ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line ${LINENO}"
         fi
     else
-        if ! tar -xf "${target_file}" -C "${target_dir}" --strip-components 1 2>/dev/null >/dev/null; then
+        if ! tar -xf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script:Line ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line ${LINENO}"
         fi
     fi
 
-    printf "%s\n\n" "File extracted: ${dl_file}"
+    printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}:Line ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir:Line ${LINENO}"
 }
 
 download_git()
 {
     local dl_path dl_url dl_file target_dir
 
-    dl_path="${cwd}"
-    dl_url="${1}"
+    dl_path="$cwd"
+    dl_url="$1"
     dl_file="${2:-"${1##*/}"}"
     dl_file="${dl_file//\./-}"
-    target_dir="${dl_path}/${dl_file}"
+    target_dir="$dl_path/$dl_file"
 
-    if [ -n "${3}" ]; then
-        output_dir="${dl_path}/${3}"
-        target_dir="${output_dir}"
+    if [ -n "$3" ]; then
+        output_dir="$dl_path/$3"
+        target_dir="$output_dir"
     fi
 
-    if [ -d "${target_dir}" ]; then
-        sudo rm -fr "${target_dir}"
+    if [ -d "$target_dir" ]; then
+        sudo rm -fr "$target_dir"
     fi
 
-    echo "Downloading ${dl_url} as ${dl_file}"
+    echo "Downloading ${dl_url} as $dl_file"
 
-    if ! git clone -q "${dl_url}" "${target_dir}"; then
-        printf "\n%s\n\n" "The script failed to clone the directory \"${target_dir}\" and will try again in 10 seconds..."
+    if ! git clone -q "${dl_url}" "$target_dir"; then
+        printf "\n%s\n\n" "The script failed to clone the directory \"$target_dir\" and will try again in 10 seconds..."
         sleep 10
-        if ! git clone -q "${dl_url}" "${target_dir}"; then
-            fail_fn "The script failed to clone the directory \"${target_dir}\" twice and will now exit the build. Line: ${LINENO}"
+        if ! git clone -q "${dl_url}" "$target_dir"; then
+            fail_fn "The script failed to clone the directory \"$target_dir\" twice and will now exit the build. Line: ${LINENO}"
         fi
     else
-        printf "%s\n\n" "Successfully cloned: ${target_dir}"
+        printf "%s\n\n" "Successfully cloned: $target_dir"
     fi
 
-    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}. Line: ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: ${LINENO}"
 }
 
 build()
 {
     printf "\n%s\n%s\n" \
-        "Building ${1} - version ${2}" \
+        "Building $1 - version $2" \
         '===================================='
 
-    if [ -f "${cwd}/${1}.done" ]; then
-        if grep -Fx "${2}" "${cwd}/${1}.done" >/dev/null; then
-            echo "${1} version ${2} already built. Remove ${cwd}/${1}.done lockfile to rebuild it."
+    if [ -f "$cwd/$1.done" ]; then
+        if grep -Fx "$2" "$cwd/$1.done" >/dev/null; then
+            echo "$1 version $2 already built. Remove $cwd/$1.done lockfile to rebuild it."
             return 1
         elif "${latest}"; then
-            echo "${1} is outdated and will be rebuilt using version ${2}"
+            echo "$1 is outdated and will be rebuilt using version $2"
             return 0
         else
-            echo "${1} is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove ${cwd}/${1}.done lockfile."
+            echo "$1 is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove $cwd/$1.done lockfile."
             return 1
         fi
     fi
     return 0
 }
 
-build_done() { echo "${2}" > "${cwd}/${1}.done"; }
+build_done() { echo "$2" > "$cwd/$1.done"; }
 
 git_1_fn()
 {
     local curl_cmd github_repo github_url g_sver g_sver1
 
     # SCRAPE GITHUB'S API FOR THE LATEST REPO VERSION
-    github_repo="${1}"
-    github_url="${2}"
+    github_repo="$1"
+    github_url="$2"
     cnt=0
 
-    if curl_cmd="$(curl -A "${user_agent}" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
-        g_sver="$(echo "${curl_cmd}" | jq -r '.[0].tag_name' 2>/dev/null)"
-        g_sver1="$(echo "${curl_cmd}" | jq -r '.[0].name' 2>/dev/null)"
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
+        g_sver="$(echo "$curl_cmd" | jq -r '.[0].tag_name' 2>/dev/null)"
+        g_sver1="$(echo "$curl_cmd" | jq -r '.[0].name' 2>/dev/null)"
         g_ver="${g_sver#v}"
         g_ver1="${g_sver1#v}"
         ((cnt++))
     fi
 
     get_str_end='-rc[0-9]'
-    while [[ ${g_ver} =~ ${get_str_end}$ ]]
+    while [[ $g_ver =~ ${get_str_end}$ ]]
     do
-        if curl_cmd="$(curl -A "${user_agent}" -m 10 -sSL "https://gitlab.kitware.com/api/v4/projects/${gitlab_repo}/repository/${github_url}" | jq -r '.[$cnt].name')"; then
+        if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://gitlab.kitware.com/api/v4/projects/${gitlab_repo}/repository/${github_url}" | jq -r '.[$cnt].name')"; then
             g_ver="${curl_cmd#v}"
             ((cnt++))
         fi  
@@ -338,19 +338,19 @@ git_1_fn()
 
 git_2_fn()
 {
-    gitlab_repo="${1}"
-    github_url="${2}"
+    gitlab_repo="$1"
+    github_url="$2"
     cnt=0
     
-    if curl_cmd="$(curl -A "${user_agent}" -m 10 -sSL "https://gitlab.kitware.com/api/v4/projects/${gitlab_repo}/repository/${github_url}" | jq -r ".[$cnt].name")"; then
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://gitlab.kitware.com/api/v4/projects/${gitlab_repo}/repository/${github_url}" | jq -r ".[$cnt].name")"; then
         g_ver="${curl_cmd#v}"
         ((cnt++))
     fi
     
     get_str_end='-rc[0-9]'
-    while [[ ${g_ver} =~ ${get_str_end}$ ]]
+    while [[ $g_ver =~ ${get_str_end}$ ]]
     do
-        if curl_cmd="$(curl -A "${user_agent}" -m 10 -sSL "https://gitlab.kitware.com/api/v4/projects/${gitlab_repo}/repository/${github_url}" | jq -r ".[$cnt].name")"; then
+        if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://gitlab.kitware.com/api/v4/projects/${gitlab_repo}/repository/${github_url}" | jq -r ".[$cnt].name")"; then
             g_ver="${curl_cmd#v}"
         fi
         ((cnt++))
@@ -361,11 +361,11 @@ git_ver_fn()
 {
     local t_flag u_flag v_flag v_tag v_url
 
-    v_url="${1}"
-    v_tag="${2}"
+    v_url="$1"
+    v_tag="$2"
 
-    if [ -n "${3}" ]; then
-        v_flag="${3}"
+    if [ -n "$3" ]; then
+        v_flag="$3"
         case "${v_flag}" in
                 R)      t_flag=releases;;
                 T)      t_flag=tags;;
@@ -471,41 +471,41 @@ esac
 
 # CHECK IF THE LATEST RELEASE IS A 'RC' AKA RELEASE CANDIDATE AND IF SO GO BACK TO THE PREVIOUS STABLE RELEASE
 git_ver_fn '541' '2' 'T'
-if build 'cmake' "${g_ver}"; then
-    download "https://gitlab.kitware.com/cmake/cmake/-/archive/v${g_ver}/cmake-v${g_ver}.tar.bz2" "cmake-${g_ver}.tar.bz2"
-    execute ./bootstrap --prefix="${install_dir}"   \
+if build 'cmake' "$g_ver"; then
+    download "https://gitlab.kitware.com/cmake/cmake/-/archive/v$g_ver/cmake-v$g_ver.tar.bz2" "cmake-$g_ver.tar.bz2"
+    execute ./bootstrap --prefix="$install_dir"   \
                         --enable-ccache             \
                         --parallel="$(nproc --all)" \
                         --qt-gui
     execute make "-j${cpu_threads}"
     execute sudo make install
-    build_done 'cmake' "${g_ver}"
+    build_done 'cmake' "$g_ver"
 fi
 
 git_ver_fn 'ninja-build/ninja' '1' 'T'
-if build 'ninja' "${g_ver1}"; then
-    download "https://codeload.github.com/ninja-build/ninja/tar.gz/refs/tags/v${g_ver1}" "ninja-${g_ver1}.tar.gz"
+if build 'ninja' "$g_ver1"; then
+    download "https://codeload.github.com/ninja-build/ninja/tar.gz/refs/tags/v$g_ver1" "ninja-$g_ver1.tar.gz"
     re2c_path="$(type -P re2c)"
     execute cmake -B build                             \
-                  -DCMAKE_install_dir="${install_dir}" \
+                  -DCMAKE_install_dir="$install_dir" \
                   -DCMAKE_BUILD_TYPE=Release           \
                   -DRE2C="${re2c_path}"                \
                   -DBUILD_TESTING=OFF                  \
                   -Wno-dev
     execute make "-j${cpu_threads}" -C build
     execute sudo make -C build install
-    build_done 'ninja' "${g_ver1}"
+    build_done 'ninja' "$g_ver1"
 fi
 
 if [[ "${OS}" == 'Arch' ]]; then
     sudo pacman -Sq --needed --noconfirm meson 2>&1
 else
     git_ver_fn 'mesonbuild/meson' '1' 'T'
-    if build 'meson' "${g_ver1}"; then
-        download "https://codeload.github.com/mesonbuild/meson/tar.gz/refs/tags/${g_ver1}" "meson-${g_ver1}.tar.gz"
+    if build 'meson' "$g_ver1"; then
+        download "https://codeload.github.com/mesonbuild/meson/tar.gz/refs/tags/$g_ver1" "meson-$g_ver1.tar.gz"
         execute python3 setup.py build
-        execute sudo python3 setup.py install --prefix="${install_dir}"
-        build_done 'meson' "${g_ver1}"
+        execute sudo python3 setup.py install --prefix="$install_dir"
+        build_done 'meson' "$g_ver1"
     fi
 fi
 
@@ -517,12 +517,12 @@ if [[ "${OS}" == 'Arch' ]]; then
 else
     if build 'golang' '1.21.5'; then
         download 'https://go.dev/dl/go1.21.5.linux-amd64.tar.gz' 'golang-1.21.5.tar.gz'
-        execute sudo cp -f 'bin/go' 'bin/gofmt' "${install_dir}"/bin
-        if [ -d  "${install_dir}"/go ]; then
-            sudo rm -fr "${install_dir}"/go
+        execute sudo cp -f 'bin/go' 'bin/gofmt' "$install_dir"/bin
+        if [ -d  "$install_dir"/go ]; then
+            sudo rm -fr "$install_dir"/go
         fi
-        sudo mkdir -p "${install_dir}"/go
-        GOROOT="${install_dir}"/go
+        sudo mkdir -p "$install_dir"/go
+        GOROOT="$install_dir"/go
         PATH="${PATH}:${GOROOT}/bin"
         export GOROOT PATH
         build_done 'golang' '1.21.5'
