Update build-texinfo

diff --git a/Bash/Installer Scripts/GNU Software/build-texinfo b/Bash/Installer Scripts/GNU Software/build-texinfo
--- a/Bash/Installer Scripts/GNU Software/build-texinfo
+++ b/Bash/Installer Scripts/GNU Software/build-texinfo
@@ -2,13 +2,13 @@
 
 ###########################################################################################################
 ##
-##  GitHub Script: https://github.com/slyfox1186/script-repo/edit/main/Bash/Installer%20Scripts/GNU%20Software/build-texinfo
+##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GNU%20Software/build-texinfo
 ##
 ##  Purpose: Build GNU texinfo
 ##
-##  Updated: 08.03.23
+##  Updated: 08.04.23
 ##
-##  Script version: 1.1
+##  Script version: 1.0
 ##
 ###########################################################################################################
 
@@ -23,12 +23,13 @@ fi
 # SET VARIABLES
 #
 
-script_ver=1.1
-archive_dir=texinfo-7.0.3
-archive_url=https://ftp.gnu.org/gnu/texinfo/texinfo-7.0.3.tar.xz
+script_ver=1.0
+archive_dir=texinfo-7.0
+archive_url=https://ftp.gnu.org/gnu/texinfo/texinfo-7.0.tar.xz
 archive_ext="${archive_url//*.}"
 cwd="$PWD"/texinfo-build-script
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
+repo=https://github.com/slyfox1186/script-repo
 
 printf "\n%s\n%s\n\n" \
     "texinfo build script - v$script_ver" \
@@ -49,7 +50,7 @@ fi
 export CC=gcc CXX=g++
 
 #
-# EXPORT COMPILER OPTIMIZATION FLAGS
+# SET COMPILER OPTIMIZATION FLAGS
 #
 
 export {CFLAGS,CXXFLAGS}='-g -O3 -march=native'
@@ -98,15 +99,25 @@ export PKG_CONFIG_PATH
 
 exit_fn()
 {
-    printf "\n%s\n\n" 'The script has completed.'
+    printf "\n%s\n\n%s\n\n" \
+        'Make sure to star this repository to show your support!' \
+        "$repo"
     exit 0
+}
+
+fail_fn()
+{
+    printf "\n%s\n\n%s\n\n" \
+        "$1" \
+        "To report a bug create an issue at: $repo/issues"
+    exit 1
 }
 
 cleanup_fn()
 {
-    local choice
+    local choice dpkg_list
 
-    printf "\n%s\n%s\n%s\n\n%s\n%s\n\n" \
+    printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
         '============================================' \
         '  Do you want to clean up the build files?  ' \
         '============================================' \
@@ -128,39 +139,25 @@ cleanup_fn()
     esac
 }
 
-
-fail_fn()
-{
-    printf "%s\n\n" "$1"
-    exit 1
-}
-
 #
 # INSTALL REQUIRED APT PACKAGES
 #
 
 pkgs_fn()
 {
-    pkgs=("$1" apt-transport-https apt-utils autoconf autogen automake autopoint autotools-dev build-essential bzip2
-          ca-certificates ccache clang cmake curl gfortran git google-perftools graphviz jq lcov libaria2-0 libaria2-0-dev
-          libc-ares-dev libcppunit-dev libcunit1-dev libcurl4 libcurl4-openssl-dev libdmalloc-dev libec-dev libedit-dev
-          libev-dev libevent-dev libexiv2-27 libexpat1-dev libgcc-12-dev libgcrypt20-dev libgexiv2-2 libgimp2.0 libgmp3-dev
-          libgpg-error-dev libgtk-4-doc libgpgme-dev libicu-dev libjemalloc-dev libkrb5-3 libldap2-dev libldap-dev liblttng-ust-dev
-          liblzma-dev libmbedtls-dev libnghttp2-dev libntlm0-dev libparted-dev libpng-dev libpsl-dev librtmp-dev librust-bzip2-dev
-          librust-openssl-dev libsqlite3-dev libssh2-1-dev libssh-dev libssl-dev libtinfo5 libtinfo-dev libtool libtool-bin
-          libunistring-dev libunwind8 libuv1-dev libxml2-dev lzip libzstd-dev m4 nettle-dev openjdk-17-jdk-headless openssh-server
-          pkg-config python3-dev python3-numpy python3-packaging python3-pip python3-pytest python3-setuptools python3-wheel
-          re2c rsync unzip valgrind zip zlib1g-dev)
+    pkgs=("$1" autoconf autogen automake binutils bison build-essential bzip2 ccache curl
+          libc6-dev libintl-perl libjson-xs-perl libpth-dev libtool libtool-bin lzip lzma-dev
+          texinfo nasm texinfo zlib1g-dev yasm)
 
     for i in ${pkgs[@]}
     do
         missing_pkg="$(dpkg -l | grep -o "$i")"
-
+    
         if [ -z "$missing_pkg" ]; then
             missing_pkgs+=" $i"
         fi
     done
-
+    
     if [ -n "$missing_pkgs" ]; then
         sudo apt -y install $missing_pkgs
         sudo apt -y autoremove
@@ -173,11 +170,13 @@ pkgs_fn()
 #
 
 if [ -f /usr/local/bin/iconv ]; then
+    pkgs_fn
     iconv_prefix=/usr/local
 elif [ -f /usr/bin/iconv ]; then
+    pkgs_fn
     iconv_prefix=/usr
 else
-    pkgs_fn 'libiconv-hook-dev'
+    pkgs_fn 'libiconv-hook-dev libiconv-hook1'
     iconv_prefix=/usr
 fi
 
@@ -226,18 +225,22 @@ autoreconf -fi
 cd build || exit 1
 ../configure --prefix=/usr/local                    \
              --{build,host}="$pc_type"              \
+             --disable-install-warnings             \
              --disable-nls                          \
+             --enable-perl-xs                       \
              --enable-threads=posix                 \
+             --with-dmalloc                         \
              --with-libiconv-prefix="$iconv_prefix" \
              --with-libintl-prefix=/usr
 make "-j$(nproc --all)"
 if ! sudo make install; then
-    echo
-    read -p 'Failure. Press enter to continue.'
-    clear
     make distclean
+    printf "\n%s\n\n" 'Failed to install texinfo.'
     exit 1
 fi
 
-unset archive_dir archive_ext archive_name archive_url CC CXX i missing_pkg missing_pkgs pc_type pem_target pkgs script_ver
-sudo rm -fr "$cwd"
+# PROMPT USER TO CLEAN UP FILES
+cleanup_fn
+
+# SHOW EXIT MESSAGE
+exit_fn
