Update build-m4

diff --git a/Bash/Installer Scripts/GNU Software/build-m4 b/Bash/Installer Scripts/GNU Software/build-m4
--- a/Bash/Installer Scripts/GNU Software/build-m4
+++ b/Bash/Installer Scripts/GNU Software/build-m4
@@ -1,21 +1,14 @@
 #!/usr/bin/env bash
 
-#########################################################################################################################
-##
 ##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GNU%20Software/build-m4
-##
 ##  Purpose: build gnu m4
-##
-##  Updated: 08.19.23
-##7
-##  Script version: 1.1
-##
-#########################################################################################################################
+##  Updated: 02.20.24
+##  Script version: 1.2
 
 clear
 
-if [ "${EUID}" -ne '0' ]; then
-    printf "%s\n\n" 'You must run this script with root/sudo.'
+if [ "$EUID" -ne 0 ]; then
+    printf "%s\n\n" "You must run this script with root/sudo."
     exit 1
 fi
 
@@ -23,50 +16,38 @@ fi
 # SET THE VARIABLES
 #
 
-script_ver=1.1
+script_ver=1.2
 archive_dir=m4-latest
 archive_url=https://ftp.gnu.org/gnu/m4/m4-latest.tar.xz
 archive_ext="${archive_url//*.}"
 archive_name="$archive_dir.tar.${archive_ext}"
-cwd="$PWD"/m4-build-script
+cwd="$PWD/m4-build-script"
 install_dir=/usr/local
-user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
 
 printf "%s\n%s\n\n" \
     "m4 build script - v${script_ver}" \
-    '==============================================='
+    "==============================================="
 
-#
 # CREATE OUTPUT DIRECTORY
-#
-
 if [ -d "$cwd" ]; then
     rm -fr "$cwd"
 fi
 mkdir -p "$cwd"
 
-#
-# SET THE C + CPP COMPILERS
-#
+# SET THE C + CPP COMPILERS AND THE COMPILER OPTIMIZATION FLAGS
+CC=gcc
+CXX=g++
+CFLAGS="-g -O3 -pipe -march=native"
+CXXFLAGS="-g -O3 -pipe -march=native"
+export CC CFLAGS CXX CXXFLAGS
 
-export CC=gcc CXX=g++
-
-#
-# SET COMPILER OPTIMIZATION FLAGS
-#
-
-export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -march=native'
-
-#
 # SET THE PATH VARIABLE
-#
-
 PATH="\
 /usr/lib/ccache:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
+$HOME/perl5/bin:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -81,10 +62,7 @@ ${HOME}/.local/bin:\
 "
 export PATH
 
-#
 # SET THE PKG_CONFIG_PATH VARIABLE
-#
-
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
 /usr/local/lib/pkgconfig:\
@@ -100,14 +78,11 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
-#
 # CREATE FUNCTIONS
-#
-
 exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        'Make sure to star this repository to show your support!' \
+        "Make sure to star this repository to show your support!" \
         "$web_repo"
     exit 0
 }
@@ -115,7 +90,7 @@ exit_fn()
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "$1" \
+        "Error: $1" \
         "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
@@ -125,40 +100,38 @@ cleanup_fn()
     local choice
 
     printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
-        '============================================' \
-        '  Do you want to clean up the build files?  ' \
-        '============================================' \
-        '[1] Yes' \
-        '[2] No'
-    read -p 'Your choices are (1 or 2): ' choice
+        "============================================" \
+        "  Do you want to clean up the build files?  " \
+        "============================================" \
+        "[1] Yes" \
+        "[2] No"
+    read -p "Your choices are (1 or 2): " choice
 
-    case "${choice}" in
-        1)      rm -fr "$cwd";;
-        2)      echo;;
+    case "$choice" in
+        1)      rm -fr "$cwd" ;;
+        2)      return ;;
         *)
-                clear
-                printf "%s\n\n" 'Bad user input. Reverting script...'
-                sleep 3
                 unset choice
-                clear
+                echo
                 cleanup_fn
                 ;;
     esac
 }
 
-#
 # INSTALL REQUIRED APT PACKAGES
-#
-
-pkgs=(autoconf autoconf-archive autogen automake binutils bison build-essential bzip2 ccache curl
-      libc6-dev libpth-dev libtool libtool-bin lzip lzma-dev m4 nasm texinfo zlib1g-dev yasm)
+pkgs=(
+    "autoconf" "autoconf-archive" "autogen" "automake" "binutils" "bison"
+    "build-essential" "bzip2" "ccache" "curl" "libc6-dev" "libpth-dev"
+    "libtool" "libtool-bin" "lzip" "lzma-dev" "m4" "nasm" "texinfo" "zlib1g-dev"
+    "yasm"
+)
 
 for i in ${pkgs[@]}
 do
-    missing_pkg="$(dpkg -l | grep -o "${i}")"
+    missing_pkg="$(dpkg -l | grep -o "$i")"
 
-    if [ -z "${missing_pkg}" ]; then
-        missing_pkgs+=" ${i}"
+    if [ -z "$missing_pkg" ]; then
+        missing_pkgs+=" $i"
     fi
 done
 
@@ -167,36 +140,24 @@ if [ -n "$missing_pkgs" ]; then
     apt -y autoremove
 fi
 
-#
 # DOWNLOAD THE ARCHIVE FILE
-#
-
-if [ ! -f "$cwd/${archive_name}" ]; then
-    curl -A "$user_agent" -m 10 -Lso "$cwd/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/$archive_name" ]; then
+    curl -Lso "$cwd/$archive_name" "${archive_url}"
 fi
 
-#
 # CREATE OUTPUT DIRECTORY
-#
-
 if [ -d "$cwd/$archive_dir" ]; then
     rm -fr "$cwd/$archive_dir"
 fi
 mkdir -p "$cwd/$archive_dir/build"
 
-#
 # EXTRACT ARCHIVE FILES
-#
-
-if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
+if ! tar -xf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/$archive_name"
     exit 1
 fi
 
-#
 # BUILD PROGRAM FROM SOURCE
-#
-
 cd "$cwd/$archive_dir/build" || exit 1
 ../configure --prefix="$install_dir" \
              --disable-nls             \
@@ -206,7 +167,7 @@ cd "$cwd/$archive_dir/build" || exit 1
              --with-dmalloc
 make "-j$(nproc --all)"
 if ! make install; then
-    fail_fn "Failed to execute: make install. Line: ${LINENO}"
+    fail_fn "Failed to execute: make install. Line: $LINENO"
     exit 1
 fi
 
