Update build-parallel

diff --git a/Bash/Installer Scripts/GNU Software/build-parallel b/Bash/Installer Scripts/GNU Software/build-parallel
--- a/Bash/Installer Scripts/GNU Software/build-parallel
+++ b/Bash/Installer Scripts/GNU Software/build-parallel
@@ -1,22 +1,20 @@
 #!/usr/bin/env bash
 
-##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GNU%20Software/build-parallel
-##  Purpose: Build GNU parallel
-##  Updated: 02.20.24
-##  Script version: 1.0
+# GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GNU%20Software/build-parallel
+# Purpose: Build GNU parallel
+# Updated: 03.07.24
+# Script version: 2.0
 
-clear
+set -e  # Exit on error
 
 if [ "$EUID" -ne 0 ]; then
-    printf "%s\n\n" "You must run this script with root/sudo."
+    echo
+    echo "You must run this script with root/sudo."
     exit 1
 fi
 
-#
 # SET THE VARIABLES
-#
-
-script_ver=1.0
+script_ver=2.0
 archive_dir=parallel-latest
 archive_url=https://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2
 archive_ext="${archive_url//*.}"
@@ -29,18 +27,17 @@ echo "parallel build script - v$script_ver"
 echo "==============================================="
 
 # CREATE OUTPUT DIRECTORY
-[ -d "$cwd" ] && rm -fr "$cwd"
+rm -fr "$cwd"
 mkdir -p "$cwd"
 
-# SET THE C + CPP COMPILERS AND THE COMPILER OPTIMIZATION FLAGS
+SET COMPILER FLAGS
 CC=gcc
 CXX=g++
 CFLAGS="-g -O3 -pipe -march=native"
 CXXFLAGS="-g -O3 -pipe -march=native"
-export CC CFLAGS CXX CXXFLAGS
 
-# SET THE PATH VARIABLE
-PATH="\
+# SET ENVIRONMENT VARIABLES
+export PATH="\
 /usr/lib/ccache:\
 $HOME/perl5/bin:\
 $HOME/.cargo/bin:\
@@ -48,19 +45,13 @@ $HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
-/usr/local/bin:\
-/usr/sbin:\
+/usr/local/bin:/usr/sbin:\
 /usr/bin:\
 /sbin:\
-/bin:\
-/usr/local/games:\
-/usr/games:\
-/snap/bin\
+/bin\
 "
-export PATH
 
-# SET THE PKG_CONFIG_PATH VARIABLE
-PKG_CONFIG_PATH="\
+export PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
 /usr/local/lib/pkgconfig:\
 /usr/local/lib/x86_64-linux-gnu/pkgconfig:\
@@ -73,102 +64,54 @@ PKG_CONFIG_PATH="\
 /lib/pkgconfig:\
 /lib/x86_64-linux-gnu/pkgconfig\
 "
-export PKG_CONFIG_PATH
 
-# CREATE FUNCTIONS
-exit_fn()
-{
-    printf "\n%s\n\n%s\n\n" \
-        "Make sure to star this repository to show your support!" \
-        "$web_repo"
-    exit 0
+FUNCTIONS
+exit_fn() {
+    echo
+    echo "\n%s\n\n%s\n\n"
+    echo "Make sure to star this repository to show your support!"
+    echo "$web_repo"
+    echo
 }
 
-fail_fn()
-{
-    printf "\n%s\n\n%s\n\n" \
-        "Error: $1" \
-        "To report a bug create an issue at: $web_repo/issues"
-    exit 1
+fail_fn() {
+    echo
+    echo "Error: $1"
+    echo "To report a bug create an issue at: $web_repo/issues"
+    echo
+exit 1
 }
 
-cleanup_fn()
-{
-    local choice
-
-    printf "\n%s\n%s\n%s\n\n%s\n%s\n\n" \
-        "============================================" \
-        "  Do you want to clean up the build files?  " \
-        "============================================" \
-        "[1] Yes" \
-        "[2] No"
-    read -p "Your choices are (1 or 2): " choice
-
+cleanup_fn() {
+    read -p "Do you want to clean up the build files? [y/N] " choice
     case "$choice" in
-        1)      rm -fr "$cwd" ;;
-        2)      return ;;
-        *)
-                unset choice
-                echo
-                cleanup_fn
-                ;;
+        y|Y ) rm -fr "$cwd" ;;
+        * ) ;;
     esac
 }
 
-# INSTALL REQUIRED APT PACKAGES
+# INSTALL DEPENDENCIES
 pkgs=(
     "autoconf" "autoconf-archive" "autogen" "automake" "binutils" "bison"
     "build-essential" "bzip2" "ccache" "curl" "libc6-dev" "libpth-dev"
     "libtool" "libtool-bin" "lzip" "lzma-dev" "m4" "nasm" "texinfo" "zlib1g-dev"
     "yasm"
 )
+apt install -y "${pkgs[@]}"
 
-for i in ${pkgs[@]}
-do
-    missing_pkg="$(dpkg -l | grep -o "$i")"
-
-    if [ -z "$missing_pkg" ]; then
-        missing_pkgs+=" $i"
-    fi
-done
-
-if [ -n "$missing_pkgs" ]; then
-    apt install $missing_pkgs
-fi
-
-# DOWNLOAD THE ARCHIVE FILE
-if [ ! -f "$cwd/$archive_name" ]; then
-    curl -Lso "$cwd/$archive_name" "$archive_url"
-fi
-
-# CREATE OUTPUT DIRECTORY
-if [ -d "$cwd/$archive_dir" ]; then
-    rm -fr "$cwd/$archive_dir"
-fi
+# DOWNLOAD SOURCE
+curl -sSfLo "$cwd/$archive_name" "$archive_url"
 mkdir -p "$cwd/$archive_dir/build"
+tar -jxf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1
 
-# EXTRACT ARCHIVE FILES
-if ! tar -jxf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: $cwd/$archive_name"
-    exit 1
-fi
-
-# BUILD PROGRAM FROM SOURCE
+# BUILD
 cd "$cwd/$archive_dir/build" || exit 1
 ../configure --prefix "$install_dir"
-echo
-if ! make "-j$(nproc --all)"; then
-    fail_fn "Failed to execute: make -j$(nproc --all). Line: $LINENO"
-    exit 1
-fi
-echo
-if ! make install; then
-    fail_fn "Failed to execute: make install. Line: $LINENO"
-    exit 1
-fi
+make "-j$(nproc --all)"
+make install
 
-# PROMPT USER TO CLEAN UP FILES
+# PROMPT CLEANUP
 cleanup_fn
 
-# SHOW EXIT MESSAGE
+# EXIT MESSAGE
 exit_fn
