Update build-wget

diff --git a/Bash/Installer Scripts/GNU Software/build-wget b/Bash/Installer Scripts/GNU Software/build-wget
--- a/Bash/Installer Scripts/GNU Software/build-wget
+++ b/Bash/Installer Scripts/GNU Software/build-wget
@@ -81,15 +81,25 @@ export PKG_CONFIG_PATH
 
 exit_fn()
 {
-    printf "\n%s\n\n" 'The script has completed.'
+    printf "\n%s\n\n%s\n\n" \
+        'Make sure to star this repository to show your support!' \
+        "$repo"
     exit 0
+}
+
+fail_fn()
+{
+    printf "\n%s\n\n%s\n\n" \
+        "$1" \
+        "To report a bug create an issue at: $repo/issues"
+    exit 1
 }
 
 cleanup_fn()
 {
     local choice
 
-    printf "\n%s\n%s\n%s\n\n%s\n%s\n\n" \
+    printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
         '============================================' \
         '  Do you want to clean up the build files?  ' \
         '============================================' \
@@ -109,13 +119,6 @@ cleanup_fn()
                 cleanup_fn
                 ;;
     esac
-}
-
-
-fail_fn()
-{
-    printf "%s\n\n" "$1"
-    exit 1
 }
 
 #
@@ -206,10 +209,11 @@ fi
 # BUILD PROGRAM FROM SOURCE
 #
 
-cd "$cwd/$archive_dir" || exit 1
 if which update-ca-certificates &>/dev/null; then
     sudo update-ca-certificates 2>/dev/null
 fi
+
+cd "$cwd/$archive_dir" || exit 1
 autoreconf -fi
 cd build || exit 1
 ../configure --prefix=/usr/local                    \
@@ -240,5 +244,8 @@ if ! sudo make install; then
     exit 1
 fi
 
-unset archive_dir archive_ext archive_name archive_url CC CXX i missing_pkg missing_pkgs pc_type pem_target pkgs script_ver
-sudo rm -fr "$cwd"
+# PROMPT USER TO CLEAN UP FILES
+cleanup_fn
+
+# SHOW EXIT MESSAGE
+exit_fn
