updated code

diff --git a/Bash/Installer Scripts/GNU Software/build-imath b/Bash/Installer Scripts/GNU Software/build-imath
--- a/Bash/Installer Scripts/GNU Software/build-imath
+++ b/Bash/Installer Scripts/GNU Software/build-imath
@@ -1,9 +1,26 @@
-#!/usr/bin/env bash
+#!/usr/bin/env bash 
+
+###########################################################################################################
+##
+##  GitHub Script: https://github.com/slyfox1186/script-repo/edit/main/Bash/Installer%20Scripts/GNU%20Software/build-imath
+##
+##  Purpose: Build GNU Grep
+##
+##  Updated: 08.13.23
+##
+##  Script version: 1.2
+##
+###########################################################################################################
 
 clear
 
+if [ "${EUID}" -eq '0' ]; then
+    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+    exit 1
+fi
+
 #
-# SET PROGRAM NAME + VERSION
+# SET VARIABLES
 #
 
 script_ver=1.0
@@ -12,6 +29,7 @@ archive_url=https://github.com/AcademySoftwareFoundation/Imath/archive/refs/tags
 archive_ext="${archive_url//*.}"
 cwd="${PWD}"/imath-build-script
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36'
+repo=https://github.com/slyfox1186/script-repo
 
 printf "%s\n%s\n\n" \
     "iMath Build Script - v${script_ver}" \
@@ -21,11 +39,11 @@ printf "%s\n%s\n\n" \
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ ! -d "${cwd}" ]; then
-    mkdir -p "${cwd}"
+if [ -d "${cwd}" ]; then
+    sudo rm -fr "${cwd}"
 fi
+mkdir -p "${cwd}"
 
-#
 # SET THE C+CPP COMPILERS
 #
 
@@ -189,7 +207,7 @@ cmake -B build -DCMAKE_INSTALL_PREFIX=/usr/local \
 ninja "-j$(nproc --all)" -C build
 if ! sudo ninja "-j$(nproc --all)" -C build install; then
     ninja build clean
-    printf "\n%s\n\n" 'Failed to install imath.'
+    printf "\n%s\n\n" 'Failed to execute .'
     exit 1
 fi
 
