Update build-pkg-config

diff --git a/Bash/Installer Scripts/GNU Software/build-pkg-config b/Bash/Installer Scripts/GNU Software/build-pkg-config
--- a/Bash/Installer Scripts/GNU Software/build-pkg-config
+++ b/Bash/Installer Scripts/GNU Software/build-pkg-config
@@ -1,16 +1,34 @@
 #!/usr/bin/env bash
 
+###########################################################################################################
+##
+##  GitHub Script: https://github.com/slyfox1186/script-repo/edit/main/Bash/Installer%20Scripts/GNU%20Software/build-pkg-config
+##
+##  Purpose: Build GNU pkg-config
+##
+##  Updated: 08.01.23
+##
+##  Script version: 1.1
+##
+###########################################################################################################
+
 clear
 
+if [ "$EUID" -eq '0' ]; then
+    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+    exit 1
+fi
+
 #
-# SET PROGRAM NAME + VERSION
+# SET VARIABLES
 #
 
-script_ver=1.0
+script_ver=1.1
 archive_dir=pkg-config-0.29.2
 archive_url=https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
 archive_ext="${archive_url//*.}"
 cwd="$PWD"/pkg-config-build-script
+repo=https://github.com/slyfox1186/script-repo
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
 
 printf "\n%s\n%s\n\n" \
@@ -88,22 +106,25 @@ export PKG_CONFIG_PATH
 
 exit_fn()
 {
-    printf "\n%s\n\n" 'The script has completed.'
+    printf "\n%s\n\n%s\n\n" \
+        'Make sure to star this repository to show your support!' \
+        "$repo"
     exit 0
 }
 
-
 fail_fn()
 {
-    printf "%s\n\n" "$1"
+    printf "\n%s\n\n%s\n\n" \
+        "$1" \
+        "To report a bug create an issue at: $repo/issues"
     exit 1
 }
 
 cleanup_fn()
 {
-    local choice
+    local choice dpkg_list
 
-    printf "\n%s\n%s\n%s\n\n%s\n%s\n\n" \
+    printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
         '============================================' \
         '  Do you want to clean up the build files?  ' \
         '============================================' \
@@ -180,7 +201,7 @@ mkdir -p "$cwd/$archive_dir/build"
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -xf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
+if ! tar -zxf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
     printf "%s\n\n" "Failed to extract: $cwd/$archive_name"
     exit 1
 fi
@@ -190,9 +211,9 @@ fi
 #
 
 cd "$cwd/$archive_dir/build" || exit 1
-../configure --prefix=/usr               \
-             --{build,host}="$pc_type"   \
-             --with-internal-glib        \
+../configure --prefix=/usr             \
+             --{build,host}="$pc_type" \
+             --with-internal-glib      \
              --with-pc-path="$PKG_CONFIG_PATH"
 make "-j$(nproc --all)"
 if ! sudo make install; then
@@ -201,7 +222,8 @@ if ! sudo make install; then
     exit 1
 fi
 
-# CLEANUP FILES
+# PROMPT USER TO CLEAN UP FILES
 cleanup_fn
+
 # SHOW EXIT MESSAGE
 exit_fn
