remove curly brackets from variables where un-needed

diff --git a/Bash/Installer Scripts/GNU Software/build-autoconf b/Bash/Installer Scripts/GNU Software/build-autoconf
--- a/Bash/Installer Scripts/GNU Software/build-autoconf
+++ b/Bash/Installer Scripts/GNU Software/build-autoconf
@@ -27,8 +27,8 @@ script_ver=1.1
 archive_dir=autoconf-latest
 archive_url=https://ftp.gnu.org/gnu/autoconf/autoconf-latest.tar.xz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/autoconf-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/autoconf-build-script
 install_dir=/usr/local
 pc_type=x86_64-linux-gnu
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
@@ -42,10 +42,10 @@ printf "%s\n%s\n\n" \
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE C + CPP COMPILERS
@@ -109,15 +109,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -134,7 +134,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -174,25 +174,25 @@ fi
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -xf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -200,10 +200,10 @@ fi
 # BUILD PROGRAM FROM SOURCE
 #
 
-cd "${cwd}/${archive_dir}" || exit 1
+cd "$cwd/$archive_dir" || exit 1
 autoreconf -fi
 cd build || exit 1
-../configure --prefix="${install_dir}"       \
+../configure --prefix="$install_dir"       \
              --{build,host}="${pc_type}"
 echo
 if ! make "-j$(nproc --all)"; then
diff --git a/Bash/Installer Scripts/GNU Software/build-automake b/Bash/Installer Scripts/GNU Software/build-automake
--- a/Bash/Installer Scripts/GNU Software/build-automake
+++ b/Bash/Installer Scripts/GNU Software/build-automake
@@ -25,10 +25,10 @@ fi
 
 script_ver=1.0
 archive_dir=automake-1.16.5
-archive_url=https://ftp.gnu.org/gnu/automake/"${archive_dir}".tar.xz
+archive_url=https://ftp.gnu.org/gnu/automake/"$archive_dir".tar.xz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/automake-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/automake-build-script
 install_dir=/usr/local
 pc_type=x86_64-linux-gnu
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
@@ -43,10 +43,10 @@ sleep 2
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE CC/CXX COMPILERS & THE COMPILER OPTIMIZATION FLAGS
@@ -56,8 +56,8 @@ CC=gcc
 CXX=g++
 CFLAGS='-g -O3 -pipe -march=native'
 CXXFLAGS="${CFLAGS}"
-CPPFLAGS="-I${install_dir}/include -I${install_dir}/include/x86_64-linux-gnu"
-LDFLAGS="-L${install_dir}/lib64 -L${install_dir}/lib -L${install_dir}/lib/x86_64-linux-gnu"
+CPPFLAGS="-I$install_dir/include -I$install_dir/include/x86_64-linux-gnu"
+LDFLAGS="-L$install_dir/lib64 -L$install_dir/lib -L$install_dir/lib/x86_64-linux-gnu"
 export CC CXX CFLAGS CPPFLAGS CXXFLAGS LDFLAGS
 
 #
@@ -105,15 +105,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -131,7 +131,7 @@ cleanup_fn()
     clear
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 unset choice
@@ -168,25 +168,25 @@ fi
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -Jxf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -Jxf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -194,10 +194,10 @@ fi
 # BUILD PROGRAM FROM SOURCE
 #
 
-cd "${cwd}/${archive_dir}" || exit 1
+cd "$cwd/$archive_dir" || exit 1
 autoreconf -fi
 cd build || exit 1
-../configure --prefix="${install_dir}"   \
+../configure --prefix="$install_dir"   \
              --{build,host}="${pc_type}" \
              --enable-silent-rules
 echo
diff --git a/Bash/Installer Scripts/GNU Software/build-gawk b/Bash/Installer Scripts/GNU Software/build-gawk
--- a/Bash/Installer Scripts/GNU Software/build-gawk
+++ b/Bash/Installer Scripts/GNU Software/build-gawk
@@ -25,10 +25,10 @@ fi
 
 script_ver=1.3
 archive_dir=gawk-5.3.0
-archive_url=https://ftp.gnu.org/gnu/gawk/"${archive_dir}".tar.lz
+archive_url=https://ftp.gnu.org/gnu/gawk/"$archive_dir".tar.lz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/gawk-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/gawk-build-script
 install_dir=/usr/local
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
@@ -41,10 +41,10 @@ printf "%s\n%s\n\n" \
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE CC/CXX COMPILERS & THE COMPILER OPTIMIZATION FLAGS
@@ -54,7 +54,7 @@ CC=gcc
 CXX=g++
 CFLAGS='-g -O3 -pipe -march=native'
 CXXFLAGS="${CFLAGS}"
-CPPFLAGS="-I${install_dir}/include/x86_64-linux-gnu"
+CPPFLAGS="-I$install_dir/include/x86_64-linux-gnu"
 export CC CXX CFLAGS CPPFLAGS CXXFLAGS
 
 #
@@ -102,15 +102,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -127,7 +127,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -165,25 +165,25 @@ fi
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -xf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -191,10 +191,10 @@ fi
 # BUILD PROGRAM FROM SOURCE
 #
 
-cd "${cwd}/${archive_dir}" || exit 1
+cd "$cwd/$archive_dir" || exit 1
 autoreconf -fi
 cd build || exit 1
-../configure --prefix="${install_dir}"       \
+../configure --prefix="$install_dir"       \
              --{build,host}=x86_64-linux-gnu \
              --disable-nls
 
diff --git a/Bash/Installer Scripts/GNU Software/build-libtool b/Bash/Installer Scripts/GNU Software/build-libtool
--- a/Bash/Installer Scripts/GNU Software/build-libtool
+++ b/Bash/Installer Scripts/GNU Software/build-libtool
@@ -25,10 +25,10 @@ fi
 
 script_ver=1.1
 archive_dir=libtool-2.4.7
-archive_url=https://ftp.gnu.org/gnu/libtool/"${archive_dir}".tar.xz
+archive_url=https://ftp.gnu.org/gnu/libtool/"$archive_dir".tar.xz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/libtool-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/libtool-build-script
 install_dir=/usr/local
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
@@ -42,10 +42,10 @@ sleep 2
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE CC/CXX COMPILERS & THE COMPILER OPTIMIZATION FLAGS
@@ -167,15 +167,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -192,7 +192,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -211,7 +211,7 @@ cleanup_fn()
 
 pkgs_fn()
 {
-    pkgs=("${1}" autoconf autoconf-archive autogen automake build-essential ccache cmake curl git libltdl-dev)
+    pkgs=("$1" autoconf autoconf-archive autogen automake build-essential ccache cmake curl git libltdl-dev)
     
     for i in ${pkgs[@]}
     do
@@ -233,25 +233,25 @@ pkgs_fn()
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -xf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -259,9 +259,9 @@ fi
 # BUILD PROGRAM FROM SOURCE
 #
 
-cd "${cwd}/${archive_dir}" || exit 1
+cd "$cwd/$archive_dir" || exit 1
 cd build || exit 1
-../configure --prefix="${install_dir}"       \
+../configure --prefix="$install_dir"       \
              --{build,host}=x86_64-linux-gnu \
              --enable-ltdl-install             
 make "-j$(nproc --all)"
diff --git a/Bash/Installer Scripts/GNU Software/build-nettle b/Bash/Installer Scripts/GNU Software/build-nettle
--- a/Bash/Installer Scripts/GNU Software/build-nettle
+++ b/Bash/Installer Scripts/GNU Software/build-nettle
@@ -44,8 +44,8 @@ script_ver=1.1
 archive_dir=nettle-3.9.1
 archive_url=https://ftp.gnu.org/gnu/nettle/nettle-3.9.1.tar.gz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/nettle-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/nettle-build-script
 install_dir=/usr/local
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
@@ -58,10 +58,10 @@ printf "%s\n%s\n\n" \
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE C + CPP COMPILERS
@@ -125,15 +125,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -150,7 +150,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -169,7 +169,7 @@ cleanup_fn()
 
 pkgs_fn()
 {
-    pkgs=("${1}" apt-transport-https apt-utils autoconf autoconf-archive autogen automake autopoint autotools-dev build-essential bzip2
+    pkgs=("$1" apt-transport-https apt-utils autoconf autoconf-archive autogen automake autopoint autotools-dev build-essential bzip2
           ca-certificates ccache clang cmake curl gfortran git google-perftools graphviz jq lcov libaria2-0 libaria2-0-dev
           libc-ares-dev libcppunit-dev libcunit1-dev libcurl4 libcurl4-openssl-dev libdmalloc-dev libec-dev libedit-dev
           libev-dev libevent-dev libexiv2-27 libexpat1-dev libgcc-12-dev libgcrypt20-dev libgexiv2-2 libgimp2.0 libgmp3-dev
@@ -200,25 +200,25 @@ pkgs_fn()
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -xf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -238,10 +238,10 @@ lib_dirs='/usr/local/lib:/usr/lib64:/usr/lib:/usr/local/cuda-12.2/nvvm/lib64:/us
 lib_dirs+=':/usr/i686-w64-mingw32/lib:/usr/lib/xen-4.17/lib:/usr/lib/llvm-14/lib:/usr/x86_64-linux-gnu/lib'
 lib_dirs+=':/usr/x86_64-w64-mingw32/lib:/usr/share/lintian/lib:/usr/share/gitk/lib:/usr/share/texinfo/lib:/usr/share/git-gui/lib'
 
-cd "${cwd}/${archive_dir}" || exit 1
+cd "$cwd/$archive_dir" || exit 1
 autoreconf -fi
 cd build || exit 1
-../configure --prefix="${install_dir}"             \
+../configure --prefix="$install_dir"             \
              --disable-documentation               \
              --with-lib-path="${lib_dirs}"         \
              --with-include-path="${include_dirs}" \
diff --git a/Bash/Installer Scripts/GNU Software/build-pkg-config-arm b/Bash/Installer Scripts/GNU Software/build-pkg-config-arm
--- a/Bash/Installer Scripts/GNU Software/build-pkg-config-arm
+++ b/Bash/Installer Scripts/GNU Software/build-pkg-config-arm
@@ -27,8 +27,8 @@ script_ver=1.3
 archive_dir=pkg-config-0.29.2
 archive_url=https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/pkg-config-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/pkg-config-build-script
 install_dir=/usr
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
@@ -41,10 +41,10 @@ printf "%s\n%s\n\n" \
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE C + CPP COMPILERS
@@ -108,15 +108,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -133,7 +133,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -150,7 +150,7 @@ cleanup_fn()
 # INSTALL REQUIRED APT PACKAGES
 #
 
-pkgs=("${1}" autoconf autoconf-archive autogen automake build-essential ca-certificates ccache clang curl
+pkgs=("$1" autoconf autoconf-archive autogen automake build-essential ca-certificates ccache clang curl
       libaria2-0 libaria2-0-dev libc-ares-dev libdmalloc-dev libgcrypt20-dev libgmp-dev libgnutls28-dev
       libgpg-error-dev libjemalloc-dev libmbedtls-dev libnghttp2-dev librust-openssl-dev libsqlite3-dev
       libssh2-1-dev libssh-dev libssl-dev libxml2-dev pkg-config zlib1g-dev)
@@ -174,25 +174,25 @@ fi
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -zxf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -zxf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -200,8 +200,8 @@ fi
 # BUILD PROGRAM FROM SOURCE
 #
 
-cd "${cwd}/${archive_dir}/build" || exit 1
-../configure --prefix="${install_dir}"           \
+cd "$cwd/$archive_dir/build" || exit 1
+../configure --prefix="$install_dir"           \
              --enable-indirect-deps              \
              --with-internal-glib                \
              --with-pc-path="${PKG_CONFIG_PATH}" \
diff --git a/Bash/Installer Scripts/GNU Software/build-readline b/Bash/Installer Scripts/GNU Software/build-readline
--- a/Bash/Installer Scripts/GNU Software/build-readline
+++ b/Bash/Installer Scripts/GNU Software/build-readline
@@ -27,8 +27,8 @@ script_ver=1.1
 archive_dir=readline-8.2
 archive_url=https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/readline-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/readline-build-script
 install_dir=/usr/local
 pc_type=x86_64-linux-gnu
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
@@ -43,10 +43,10 @@ sleep 2
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE C + CPP COMPILERS
@@ -110,15 +110,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -135,7 +135,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 unset choice
@@ -151,7 +151,7 @@ cleanup_fn()
 
 pkgs_fn()
 {
-    pkgs=("${1}" autoconf autoconf-archive autogen automake autopoint autotools-dev build-essential bzip2
+    pkgs=("$1" autoconf autoconf-archive autogen automake autopoint autotools-dev build-essential bzip2
           ccache curl git libaudit-dev libintl-perl libtool libtool-bin lzip pkg-config
           valgrind zlib1g-dev librust-polling-dev)
 
@@ -175,25 +175,25 @@ pkgs_fn()
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -zxf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -zxf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -201,17 +201,17 @@ fi
 # DOWNLOAD PATCH TO FIX SHELL CRASH DUE TO INVALID LOCALE SPECIFICATION
 #
 
-curl -A "${user_agent}" -Lso 'fix-invalid-locale-specification.patch' 'https://www.linuxfromscratch.org/patches/downloads/readline/readline-8.2-upstream_fix-1.patch'
+curl -A "$user_agent" -Lso 'fix-invalid-locale-specification.patch' 'https://www.linuxfromscratch.org/patches/downloads/readline/readline-8.2-upstream_fix-1.patch'
 
 #
 # BUILD PROGRAM FROM SOURCE
 #
 
-cd "${cwd}/${archive_dir}" || exit 1
+cd "$cwd/$archive_dir" || exit 1
 autoreconf -fi
 patch --ignore-whitespace --posix --verbose -R -p1 -i 'fix-invalid-locale-specification.patch'
 cd build || exit 1
-../configure --prefix="${install_dir}"   \
+../configure --prefix="$install_dir"   \
              --{build,host}="${pc_type}" \
              --disable-install-examples  \
              --disable-shared            \
@@ -222,7 +222,7 @@ if ! sudo make install; then
     exit 1
 fi
 
-sudo ldconfig "${install_dir}"/lib
+sudo ldconfig "$install_dir"/lib
 
 # PROMPT USER TO CLEAN UP FILES
 cleanup_fn
diff --git a/Bash/Installer Scripts/GNU Software/build-util-linux-THIS-BROKE-MY-PC-USE-AT-OWN-RISK b/Bash/Installer Scripts/GNU Software/build-util-linux-THIS-BROKE-MY-PC-USE-AT-OWN-RISK
--- a/Bash/Installer Scripts/GNU Software/build-util-linux-THIS-BROKE-MY-PC-USE-AT-OWN-RISK
+++ b/Bash/Installer Scripts/GNU Software/build-util-linux-THIS-BROKE-MY-PC-USE-AT-OWN-RISK
@@ -25,10 +25,10 @@ fi
 
 script_ver=1.1
 archive_dir=util-linux-2.39.2
-archive_url=https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.39/${archive_dir}.tar.xz
+archive_url=https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.39/$archive_dir.tar.xz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/util-linux-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/util-linux-build-script
 install_dir=/usr
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
@@ -41,10 +41,10 @@ printf "%s\n%s\n\n" \
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE C + CPP COMPILERS
@@ -109,15 +109,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -134,7 +134,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -147,7 +147,7 @@ cleanup_fn()
     esac
 }
 
-installed() { return $(dpkg-query -W -f '${Status}\n' "${1}" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}'); }
+installed() { return $(dpkg-query -W -f '${Status}\n' "$1" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}'); }
 
 #
 # INSTALL REQUIRED APT PACKAGES
@@ -184,25 +184,25 @@ fi
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -xf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -212,11 +212,11 @@ fi
 
 extralists=(blkid,fdisk,losetup,mount,nsenter,sfdisk,umount,unshare)
 
-cd "${cwd}/${archive_dir}" || exit 1
+cd "$cwd/$archive_dir" || exit 1
 export AL_OPTS='-I/usr/share/aclocal'
 ./autogen.sh
 cd build || exit 1
-../configure --prefix="${install_dir}"                               \
+../configure --prefix="$install_dir"                               \
              --{build,host}=x86_64-linux-gnu                         \
              --disable-nls                                           \
              --disable-werror                                        \
diff --git a/Bash/Installer Scripts/GitHub Projects/build-garbage-collector b/Bash/Installer Scripts/GitHub Projects/build-garbage-collector
--- a/Bash/Installer Scripts/GitHub Projects/build-garbage-collector
+++ b/Bash/Installer Scripts/GitHub Projects/build-garbage-collector
@@ -27,8 +27,8 @@ script_ver=1.0
 archive_dir=gc-8.2.4
 archive_url=https://github.com/ivmai/bdwgc/releases/download/v8.2.4/gc-8.2.4.tar.gz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/garbage-collector-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/garbage-collector-build-script
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
 
@@ -40,8 +40,8 @@ printf "\n%s\n%s\n\n" \
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ ! -d "${cwd}" ]; then
-    mkdir -p "${cwd}"
+if [ ! -d "$cwd" ]; then
+    mkdir -p "$cwd"
 fi
 
 #
@@ -86,15 +86,15 @@ export PATH
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
 /usr/local/lib/pkgconfig:\
-/usr/local/lib/"${install_dir}"/pkgconfig:\
+/usr/local/lib/"$install_dir"/pkgconfig:\
 /usr/local/share/pkgconfig:\
 /usr/lib64/pkgconfig:\
 /usr/lib/pkgconfig:\
-/usr/lib/"${install_dir}"/pkgconfig:\
+/usr/lib/"$install_dir"/pkgconfig:\
 /usr/share/pkgconfig:\
 /lib64/pkgconfig:\
 /lib/pkgconfig:\
-/lib/"${install_dir}"/pkgconfig\
+/lib/"$install_dir"/pkgconfig\
 "
 export PKG_CONFIG_PATH
 
@@ -106,15 +106,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -131,7 +131,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -174,25 +174,25 @@ pkgs_fn()
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -zxf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -zxf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -200,7 +200,7 @@ fi
 # BUILD PROGRAM FROM SOURCE
 #
 
-cd "${cwd}/${archive_dir}" || exit 1
+cd "$cwd/$archive_dir" || exit 1
 autoreconf -fi
 cd build || exit 1
 ../configure --prefix=/usr/local             \
diff --git a/Bash/Installer Scripts/GitHub Projects/build-git b/Bash/Installer Scripts/GitHub Projects/build-git
--- a/Bash/Installer Scripts/GitHub Projects/build-git
+++ b/Bash/Installer Scripts/GitHub Projects/build-git
@@ -27,10 +27,10 @@ fi
 
 script_ver=1.3
 archive_dir=2.43.0
-archive_url=https://github.com/git/git/archive/refs/tags/v"${archive_dir}".tar.gz
+archive_url=https://github.com/git/git/archive/refs/tags/v"$archive_dir".tar.gz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/git-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/git-build-script
 install_dir=/usr
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
@@ -44,10 +44,10 @@ sleep 2
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE CC/CXX COMPILERS & OPTIMIZATION FLAGS
@@ -91,13 +91,13 @@ export PATH
 PKG_CONFIG_PATH="\
 /lib64/pkgconfig:\
 /lib/pkgconfig:\
-/lib/${install_dir}/pkgconfig:\
+/lib/$install_dir/pkgconfig:\
 /usr/lib64/pkgconfig:\
 /usr/lib/pkgconfig:\
-/usr/lib/${install_dir}/pkgconfig:\
+/usr/lib/$install_dir/pkgconfig:\
 /usr/local/lib64/pkgconfig:\
 /usr/local/lib/pkgconfig:\
-/usr/local/lib/${install_dir}/pkgconfig:\
+/usr/local/lib/$install_dir/pkgconfig:\
 /usr/share/pkgconfig\
 "
 export PKG_CONFIG_PATH
@@ -110,15 +110,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n"                                       \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}"              \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1"              \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -135,7 +135,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 unset choice
@@ -188,25 +188,25 @@ pip install --user asciidoc &>/dev/null
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}"
+mkdir -p "$cwd/$archive_dir"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -zxf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -zxf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -214,9 +214,9 @@ fi
 # BUILD PROGRAM FROM SOURCE
 #
 
-cd "${cwd}/${archive_dir}" || exit 1
+cd "$cwd/$archive_dir" || exit 1
 make "-j$(nproc --all)" configure
-./configure --prefix="${install_dir}"
+./configure --prefix="$install_dir"
 
 if ! make "-j$(nproc --all)" all doc; then
     fail_fn "Failed to execute: make -j$(nproc --all) all doc. Line: ${LINENO}"
diff --git a/Bash/Installer Scripts/GitHub Projects/build-libhwy b/Bash/Installer Scripts/GitHub Projects/build-libhwy
--- a/Bash/Installer Scripts/GitHub Projects/build-libhwy
+++ b/Bash/Installer Scripts/GitHub Projects/build-libhwy
@@ -28,9 +28,9 @@ fi
 
 script_ver=1.0
 install_prefix=/usr/local
-cwd="${PWD}"/libhwy-build-script
-packages="${cwd}"/packages
-workspace="${cwd}"/workspace
+cwd="$PWD"/libhwy-build-script
+packages="$cwd"/packages
+workspace="$cwd"/workspace
 pc_type=x86_64-linux-gnu
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
@@ -40,7 +40,7 @@ debug=OFF
 # CREATE OUTPUT DIRECTORIES
 #
 
-mkdir -p "${packages}" "${workspace}"
+mkdir -p "$packages" "$workspace"
 
 #
 # GET CPU CORE COUNT FOR PARALLEL PROCESSING
@@ -64,8 +64,8 @@ export CC=gcc CXX=g++
 
 CFLAGS='-g -O3 -pipe -march=native'
 CXXFLAGS="${CFLAGS}"
-CPPFLAGS="-I${workspace}/include -I/usr/local/include -I/usr/include"
-LDFLAGS="-L${workspace}/lib64 -L${workspace}/lib -L${workspace}/lib/x86_64-linux-gnu -L/usr/local/lib64"
+CPPFLAGS="-I$workspace/include -I/usr/local/include -I/usr/include"
+LDFLAGS="-L$workspace/lib64 -L$workspace/lib -L$workspace/lib/x86_64-linux-gnu -L/usr/local/lib64"
 LDFLAGS+=' -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib64 -L/usr/lib -L/lib64 -L/lib'
 MAKEFLAGS="-j$(nproc --all)"
 export CFLAGS CPPFLAGS CXXFLAGS LDFLAGS MAKEFLAGS
@@ -103,11 +103,11 @@ ${HOME}/.local/bin:\
 export PATH
 
 PKG_CONFIG_PATH="\
-${workspace}/usr/lib/pkgconfig:\
-${workspace}/lib64/pkgconfig:\
-${workspace}/lib/pkgconfig:\
-${workspace}/lib/x86_64-linux-gnu/pkgconfig:\
-${workspace}/share/pkgconfig:\
+$workspace/usr/lib/pkgconfig:\
+$workspace/lib64/pkgconfig:\
+$workspace/lib/pkgconfig:\
+$workspace/lib/x86_64-linux-gnu/pkgconfig:\
+$workspace/share/pkgconfig:\
 /usr/local/lib64/pkgconfig:\
 /usr/local/lib/pkgconfig:\
 /usr/local/lib/x86_64-linux-gnu/pkgconfig:\
@@ -131,9 +131,9 @@ export PKG_CONFIG_PATH
 fail_fn()
 {
     printf "\n%s\n%s\n%s\n\n" \
-        "${1}" \
+        "$1" \
         'You can enable the script'\''s debugging feature by changing the variable "debug" to "ON"' \
-        "To report a bug visit: ${web_repo}/issues"
+        "To report a bug visit: $web_repo/issues"
     exit 1
 }
 
@@ -141,7 +141,7 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
@@ -157,7 +157,7 @@ cleanup_fn()
     clear
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      clear;;
         *)
                 unset choice
@@ -174,18 +174,18 @@ git_1_fn()
 {
     local curl_cmd github_repo github_url
 
-    github_repo="${1}"
-    github_url="${2}"
+    github_repo="$1"
+    github_url="$2"
 
-    if curl_cmd="$(curl -A "${user_agent}" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
-        g_ver="$(echo "${curl_cmd}" | jq -r '.[0].name' 2>/dev/null)"
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
+        g_ver="$(echo "$curl_cmd" | jq -r '.[0].name' 2>/dev/null)"
     fi
 
 }
 
 git_ver_fn()
 {
-    git_1_fn "${1}" 'releases' 2>/dev/null
+    git_1_fn "$1" 'releases' 2>/dev/null
 }
 
 execute()
@@ -193,12 +193,12 @@ execute()
     echo "$ ${*}"
 
     if [ "${debug}" = 'ON' ]; then
-        if ! output=$("${@}"); then
+        if ! output=$("$@"); then
             notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
             fail_fn "Failed to execute: ${*}"
         fi
     else
-        if ! output=$("${@}" 2>&1); then
+        if ! output=$("$@" 2>&1); then
             notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
             fail_fn "Failed to execute: ${*}"
         fi
@@ -207,102 +207,102 @@ execute()
 
 download()
 {
-    dl_path="${packages}"
-    dl_url="${1}"
+    dl_path="$packages"
+    dl_url="$1"
     dl_file="${2:-"${1##*/}"}"
 
-    if [[ "${dl_file}" =~ tar. ]]; then
+    if [[ "$dl_file" =~ tar. ]]; then
         output_dir="${dl_file%.*}"
         output_dir="${3:-"${output_dir%.*}"}"
     else
         output_dir="${3:-"${dl_file%.*}"}"
     fi
 
-    target_file="${dl_path}/${dl_file}"
-    target_dir="${dl_path}/${output_dir}"
+    target_file="$dl_path/$dl_file"
+    target_dir="$dl_path/$output_dir"
 
     if [ -f "${target_file}" ]; then
-        echo "The file \"${dl_file}\" is already downloaded."
+        echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"${dl_file}\""
-        if ! wget -U "${user_agent}" -cqO "${target_file}" "${dl_url}"; then
-            printf "\n%s\n\n" "The script failed to download \"${dl_file}\" and will try again in 10 seconds..."
+        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
+        if ! wget -U "$user_agent" -cqO "${target_file}" "${dl_url}"; then
+            printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! wget -U "${user_agent}" -cqO "${target_file}" "${dl_url}"; then
-                fail_fn "The script failed to download \"${dl_file}\" twice and will now exit. Line: ${LINENO}"
+            if ! wget -U "$user_agent" -cqO "${target_file}" "${dl_url}"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit. Line: ${LINENO}"
             fi
         fi
         echo 'Download Completed'
     fi
 
-    if [ -d "${target_dir}" ]; then
-        sudo rm -fr "${target_dir}"
+    if [ -d "$target_dir" ]; then
+        sudo rm -fr "$target_dir"
     fi
-    mkdir -p "${target_dir}"
+    mkdir -p "$target_dir"
 
-    if [ -n "${3}" ]; then
-        if ! tar -zxf "${target_file}" -C "${target_dir}" 2>/dev/null >/dev/null; then
+    if [ -n "$3" ]; then
+        if ! tar -zxf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script. Line: ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
         fi
     else
-        if ! tar -zxf "${target_file}" -C "${target_dir}" --strip-components 1 2>/dev/null >/dev/null; then
+        if ! tar -zxf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script. Line: ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
         fi
     fi
 
-    printf "%s\n\n" "File extracted: ${dl_file}"
+    printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}. Line: ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: ${LINENO}"
 }
 
 download_git()
 {
     local dl_path dl_url dl_file target_dir
 
-    dl_path="${packages}"
-    dl_url="${1}"
+    dl_path="$packages"
+    dl_url="$1"
     dl_file="${2:-"${1##*/}"}"
     dl_file="${dl_file//\./-}"
-    target_dir="${dl_path}/${dl_file}"
+    target_dir="$dl_path/$dl_file"
 
-    if [ -n "${3}" ]; then
-        output_dir="${dl_path}/${3}"
-        target_dir="${output_dir}"
+    if [ -n "$3" ]; then
+        output_dir="$dl_path/$3"
+        target_dir="$output_dir"
     fi
 
-    if [ -d "${target_dir}" ]; then
-        sudo rm -fr "${target_dir}"
+    if [ -d "$target_dir" ]; then
+        sudo rm -fr "$target_dir"
     fi
 
-    echo "Downloading ${dl_url} as ${dl_file}"
+    echo "Downloading ${dl_url} as $dl_file"
 
-    if ! git clone -q "${dl_url}" "${target_dir}"; then
-        printf "\n%s\n\n" "The script failed to clone the directory \"${target_dir}\" and will try again in 10 seconds..."
+    if ! git clone -q "${dl_url}" "$target_dir"; then
+        printf "\n%s\n\n" "The script failed to clone the directory \"$target_dir\" and will try again in 10 seconds..."
         sleep 10
-        if ! git clone -q "${dl_url}" "${target_dir}"; then
-            fail_fn "The script failed to clone the directory \"${target_dir}\" twice and will now exit the buildLine: ${LINENO}"
+        if ! git clone -q "${dl_url}" "$target_dir"; then
+            fail_fn "The script failed to clone the directory \"$target_dir\" twice and will now exit the buildLine: ${LINENO}"
         fi
     else
-        printf "%s\n\n" "Successfully cloned: ${target_dir}"
+        printf "%s\n\n" "Successfully cloned: $target_dir"
     fi
 
-    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}. Line: ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: ${LINENO}"
 }
 
 build()
 {
     printf "\n%s\n%s\n" \
-        "building ${1} - version ${2}" \
+        "building $1 - version $2" \
         '===================================='
 
-    if [ -f "${packages}/${1}.done" ]; then
-        if grep -Fx "${2}" "${packages}/${1}.done" > /dev/null; then
-            echo "${1} version ${2} already built. Remove ${packages}/${1}.done lockfile to rebuild it."
+    if [ -f "$packages/$1.done" ]; then
+        if grep -Fx "$2" "$packages/$1.done" > /dev/null; then
+            echo "$1 version $2 already built. Remove $packages/$1.done lockfile to rebuild it."
             return 1
         else
-            echo "${1} is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove ${packages}/${1}.done lockfile."
+            echo "$1 is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove $packages/$1.done lockfile."
             return 1
         fi
     fi
@@ -312,12 +312,12 @@ build()
 
 build_done()
 {
-    echo "${2}" > "${packages}/${1}.done"
+    echo "$2" > "$packages/$1.done"
 }
 
 installed()
 {
-    return $(dpkg-query -W -f '${Status}\n' "${1}" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}')
+    return $(dpkg-query -W -f '${Status}\n' "$1" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}')
 }
 
 find_lsb_release="$(sudo find /usr -type f -name 'lsb_release')"
@@ -415,12 +415,12 @@ fi
 #
 
 git_ver_fn 'google/highway' 'R'
-if build 'libhwy' "${g_ver}"; then
-    download "https://github.com/google/highway/archive/refs/tags/${g_ver}.tar.gz" "libhwy-${g_ver}.tar.gz"
+if build 'libhwy' "$g_ver"; then
+    download "https://github.com/google/highway/archive/refs/tags/$g_ver.tar.gz" "libhwy-$g_ver.tar.gz"
     CFLAGS+=' -DHWY_COMPILE_ALL_ATTAINABLE'
     CXXFLAGS+=' -DHWY_COMPILE_ALL_ATTAINABLE'
     execute cmake -B build                                   \
-                  -DCMAKE_INSTALL_PREFIX="${install_prefix}" \
+                  -DCMAKE_INSTALL_PREFIX="$install_prefix" \
                   -DCMAKE_BUILD_TYPE=Release                 \
                   -DHWY_ENABLE_TESTS=OFF                     \
                   -DHWY_SYSTEM_GTEST=OFF                     \
@@ -430,7 +430,7 @@ if build 'libhwy' "${g_ver}"; then
                   -G Ninja -Wno-dev
     execute ninja "-j${cpu_threads}" -C build
     execute sudo ninja "-j${cpu_threads}" -C build install
-    build_done 'libhwy' "${g_ver}"
+    build_done 'libhwy' "$g_ver"
 fi
 
 # LDCONFIG MUST BE RUN NEXT IN ORDER TO UPDATE FILE CHANGES OR THE VERSION COMMANDS MIGHT NOT WORK
diff --git a/Bash/Installer Scripts/GitHub Projects/build-openssl-lts b/Bash/Installer Scripts/GitHub Projects/build-openssl-lts
--- a/Bash/Installer Scripts/GitHub Projects/build-openssl-lts
+++ b/Bash/Installer Scripts/GitHub Projects/build-openssl-lts
@@ -37,13 +37,13 @@ fi
 
 script_ver=3.1.4
 archive_dir=openssl-3.1.4
-archive_url="https://www.openssl.org/source/${archive_dir}.tar.gz"
+archive_url="https://www.openssl.org/source/$archive_dir.tar.gz"
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/openssl-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/openssl-build-script
 install_dir=/usr/local/ssl
-ssl_dir="${install_dir}"
-cert_dir="${install_dir}"/certs
+ssl_dir="$install_dir"
+cert_dir="$install_dir"/certs
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
 
@@ -56,10 +56,10 @@ sleep 2
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE CC/CXX COMPILERS & THE COMPILER OPTIMIZATION FLAGS
@@ -74,7 +74,7 @@ CPPFLAGS='-I/usr/local/include -I/usr/include'
 LDFLAGS='-L/usr/local/ssl/lib -L/usr/local/lib64 -L/usr/local/lib'
 LDFLAGS+=' -L/usr/lib/x86_64-linux-gnu -L/usr/lib64 -L/usr/lib -L/lib64 -L/lib'
 LDLIBS="${LDFLAGS}"
-LD_LIBRARY_PATH="${install_dir}/lib64:${LD_LIBRARY_PATH}"
+LD_LIBRARY_PATH="$install_dir/lib64:${LD_LIBRARY_PATH}"
 export CC CXX CFLAGS CPPFLAGS CXXFLAGS LDFLAGS LD_LIBRARY_PATH LDLIBS SHARED_CFLAG
 
 #
@@ -127,16 +127,16 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n"                                       \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n\n%s\n\n%s\n\n%s\n\n"                  \
-        "${1}"                                       \
+        "$1"                                       \
         'To report a bug please create an issue at:' \
-        "${web_repo}/issues"
+        "$web_repo/issues"
     exit 1
 }
 
@@ -153,7 +153,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 unset choice
@@ -262,25 +262,25 @@ fi
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    wget -U "${user_agent}" -cqO "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    wget -U "$user_agent" -cqO "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -zxf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -zxf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -288,12 +288,12 @@ fi
 # BUILD PROGRAM FROM SOURCE
 #
 
-cd "${cwd}/${archive_dir}/build" || exit 1
+cd "$cwd/$archive_dir/build" || exit 1
 ../Configure linux-x86_64-clang                          \
              -DOPENSSL_USE_IPV6=0                        \
-             -Wl,-rpath="${install_dir}"/lib64           \
+             -Wl,-rpath="$install_dir"/lib64           \
              -Wl,--enable-new-dtags                      \
-             --prefix="${install_dir}"                   \
+             --prefix="$install_dir"                   \
              --openssldir="${ssl_dir}"                   \
              --release                                   \
              --with-zlib-include=/usr/include            \
@@ -335,13 +335,13 @@ if [ ! -d "${cert_dir}" ]; then
 fi
 
 # DOWNLOAD THE LATEST CACERT.PEM FILE FROM THE OFFICIAL CURL WEBSITE
-if ! curl -A "${user_agent}" -Lso "${cwd}"/cacert.pem 'https://curl.se/ca/cacert.pem'; then
+if ! curl -A "$user_agent" -Lso "$cwd"/cacert.pem 'https://curl.se/ca/cacert.pem'; then
     fail_fn "Failed to download the latest \"cacert.pem\" file. Line: ${LINENO}"
 fi
 
 # MOVE THE PEM FILE TO THE NEWLY CREATED CERTS DIRECTORY
-if ! sudo mv "${cwd}"/cacert.pem "${cert_dir}"/cacert.pem; then
-    fail_fn "Failed to move file: ${cwd}/cacert.pem >> ${cert_dir}/cacert.pem. Line: ${LINENO}"
+if ! sudo mv "$cwd"/cacert.pem "${cert_dir}"/cacert.pem; then
+    fail_fn "Failed to move file: $cwd/cacert.pem >> ${cert_dir}/cacert.pem. Line: ${LINENO}"
 else
     # COPY THE PEM FILE AS A CRT FILE IN THE SPECIAL CA-CERTIFICATES FOLDER SO THE COMMAND WILL FIND AND USE IT WHEN IT IS EXECUTED
     sudo cp "${cert_dir}"/cacert.pem '/usr/local/share/ca-certificates/curl-cacert.crt'
@@ -356,7 +356,7 @@ sudo c_rehash .
 sudo update-ca-certificates
 
 # RUN LDCONFIG TO UPDATE THE LINKER LIBRARY SEARCH PATH TO INCLUDE THE OPENSSL LIB64 DIRECTORY
-echo "${install_dir}/lib64" | sudo tee '/etc/ld.so.conf.d/openssl-compiled.conf' >/dev/null
+echo "$install_dir/lib64" | sudo tee '/etc/ld.so.conf.d/openssl-compiled.conf' >/dev/null
 sudo ldconfig
 
 # ADD THE NEW OPENSSL BIN TO THE USER'S ~/.bashrc FILE IF NOT ALREADY PRESENT
@@ -364,7 +364,7 @@ regex_str=':\\$'
 get_str="$(grep -o '/usr/sbin:\\' "${HOME}"/.bashrc 2>/dev/null)"
 
 if ! grep -o '/usr/local/ssl/bin' "${HOME}"/.bashrc &>/dev/null; then
-    if [[ "${get_str}" =~ ${regex_str} ]]; then
+    if [[ "${get_str}" =~ $regex_str ]]; then
         sed -i '\/usr\/sbin:\\/i \/usr\/local\/ssl\/bin:\\' "${HOME}"/.bashrc
     else
         sed -i 's/\/usr\/sbin:/\/usr\/local\/ssl\/bin:\/usr\/sbin:/g' "${HOME}"/.bashrc
diff --git a/Bash/Installer Scripts/GitHub Projects/build-openssl-sts b/Bash/Installer Scripts/GitHub Projects/build-openssl-sts
--- a/Bash/Installer Scripts/GitHub Projects/build-openssl-sts
+++ b/Bash/Installer Scripts/GitHub Projects/build-openssl-sts
@@ -28,13 +28,13 @@ fi
 
 script_ver=1.3
 archive_dir=openssl-1.1.1w
-archive_url=https://www.openssl.org/source/"${archive_dir}".tar.gz
+archive_url=https://www.openssl.org/source/"$archive_dir".tar.gz
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
-cwd="${PWD}"/openssl-build-script
+archive_name="$archive_dir.tar.${archive_ext}"
+cwd="$PWD"/openssl-build-script
 install_dir=/usr/local
-ssl_dir="${install_dir}"
-cert_dir="${install_dir}"/certs
+ssl_dir="$install_dir"
+cert_dir="$install_dir"/certs
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
 
@@ -62,10 +62,10 @@ fi
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}" ]; then
-    sudo rm -fr "${cwd}"
+if [ -d "$cwd" ]; then
+    sudo rm -fr "$cwd"
 fi
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE CC/CXX COMPILERS & THE COMPILER OPTIMIZATION FLAGS
@@ -132,16 +132,16 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n"                                         \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n\n%s\n\n%s\n\n%s\n\n"                  \
-        "${1}"                                       \
+        "$1"                                       \
         'To report a bug please create an issue at:' \
-        "${web_repo}/issues"
+        "$web_repo/issues"
     exit 1
 }
 
@@ -158,7 +158,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 unset choice
@@ -237,34 +237,34 @@ clear
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    wget -U "${user_agent}" -cqO "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    wget -U "$user_agent" -cqO "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -zxf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    fail_fn "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -zxf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    fail_fn "Failed to extract: $cwd/${archive_name}"
 fi
 
 #
 # BUILD PROGRAM FROM SOURCE
 #
 
-cd "${cwd}/${archive_dir}" || exit 1
+cd "$cwd/$archive_dir" || exit 1
 cd build || exit 1
-../config --prefix="${install_dir}"                 \
+../config --prefix="$install_dir"                 \
           --openssldir="${ssl_dir}"                 \
           --release                                 \
           --with-zlib-include=/usr/include          \
@@ -300,7 +300,7 @@ fi
 
 # IF UBUNTU IS THE CURRENT OS THEN YOU MUST CREATE A SOFT LINK FOR OPENSSL TO FUNCTION
 case "${OS}" in
-    Ubuntu)     sudo ln -sf '/usr/lib64/libcrypto.so.3' "/lib/${install_dir}/";;
+    Ubuntu)     sudo ln -sf '/usr/lib64/libcrypto.so.3' "/lib/$install_dir/";;
 esac
 
 #
@@ -317,13 +317,13 @@ if [ ! -d "${cert_dir}" ]; then
 fi
 
 # DOWNLOAD THE LATEST CACERT.PEM FILE FROM THE OFFICIAL CURL WEBSITE
-if ! curl -A "${user_agent}" -Lso "${cwd}"/cacert.pem 'https://curl.se/ca/cacert.pem'; then
+if ! curl -A "$user_agent" -Lso "$cwd"/cacert.pem 'https://curl.se/ca/cacert.pem'; then
     fail_fn "Failed to download the latest \"cacert.pem\" file. Line: ${LINENO}"
 fi
 
 # MOVE THE PEM FILE TO THE NEWLY CREATED CERTS DIRECTORY
-if ! sudo mv "${cwd}"/cacert.pem "${cert_dir}"/cacert.pem; then
-    fail_fn "Failed to move file: ${cwd}/cacert.pem >> ${cert_dir}/cacert.pem. Line: ${LINENO}"
+if ! sudo mv "$cwd"/cacert.pem "${cert_dir}"/cacert.pem; then
+    fail_fn "Failed to move file: $cwd/cacert.pem >> ${cert_dir}/cacert.pem. Line: ${LINENO}"
 fi
 
 # COPY THE PEM FILE AS A CRT FILE IN THE SPECIAL CA-CERTIFICATES FOLDER SO THE COMMAND WILL FIND AND USE IT WHEN IT IS EXECUTED
@@ -361,11 +361,11 @@ else
 fi
 
 # RUN LDCONFIG TO UPDATE THE LINKER LIBRARY SEARCH PATH TO INCLUDE THE OPENSSL LIB64 DIRECTORY
-if ! curl -A "${user_agent}" -Lso "${cwd}/ld-linker-search-paths.sh" 'https://raw.githubusercontent.com/slyfox1186/script-repo/main/Bash/Misc/ld-linker-search-paths.sh'; then
-    printf "\n%s\n\n" "Failed to download: ${cwd}/ld-linker-search-paths.sh. Line: ${LINENO}"
+if ! curl -A "$user_agent" -Lso "$cwd/ld-linker-search-paths.sh" 'https://raw.githubusercontent.com/slyfox1186/script-repo/main/Bash/Misc/ld-linker-search-paths.sh'; then
+    printf "\n%s\n\n" "Failed to download: $cwd/ld-linker-search-paths.sh. Line: ${LINENO}"
     exit 1
 fi
-sudo bash "${cwd}/ld-linker-search-paths.sh"
+sudo bash "$cwd/ld-linker-search-paths.sh"
 
 # ADD THE NEW OPENSSL BIN TO THE USER'S ~/.bashrc FILE IF NOT ALREADY PRESENT
 if ! grep -o '/usr/local/ssl/bin' "${HOME}"/.bashrc &>/dev/null; then
diff --git a/Bash/Installer Scripts/GitHub Projects/build-terminator-terminal b/Bash/Installer Scripts/GitHub Projects/build-terminator-terminal
--- a/Bash/Installer Scripts/GitHub Projects/build-terminator-terminal
+++ b/Bash/Installer Scripts/GitHub Projects/build-terminator-terminal
@@ -25,12 +25,12 @@ fi
 #
 
 script_ver=1.0
-cwd="${PWD}"/terminator-build-script
+cwd="$PWD"/terminator-build-script
 install_dir=/usr/local
 archive_dir=terminator-2.1.3
 archive_url=https://salsa.debian.org/python-team/packages/terminator/-/archive/debian/2.1.3-1/terminator-debian-2.1.3-1.tar.bz2
 archive_ext="${archive_url//*.}"
-archive_name="${archive_dir}.tar.${archive_ext}"
+archive_name="$archive_dir.tar.${archive_ext}"
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
 
@@ -42,7 +42,7 @@ printf "\n%s\n%s\n\n" \
 # CREATE OUTPUT DIRECTORY
 #
 
-mkdir -p "${cwd}"
+mkdir -p "$cwd"
 
 #
 # SET THE C+CPP COMPILERS
@@ -107,16 +107,16 @@ exit_fn()
     printf "\n%s\n\n%s\n%s\n\n" \
         'The script has completed' \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n\n%s\n\n%s\n\n%s\n\n" \
-        "${1}" \
+        "$1" \
         'To report a bug please create an issue at:' \
-        "${web_repo}/issues"
+        "$web_repo/issues"
     exit 1
 }
 
@@ -133,7 +133,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -176,25 +176,25 @@ fi
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}"
+mkdir -p "$cwd/$archive_dir"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -xf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
@@ -202,9 +202,9 @@ fi
 # BUILD PROGRAM FROM SOURCE
 #
 
-cd "${cwd}/${archive_dir}" || exit 1
+cd "$cwd/$archive_dir" || exit 1
 python3 setup.py build
-if ! sudo python3 setup.py install --prefix="${install_dir}"                        \
+if ! sudo python3 setup.py install --prefix="$install_dir"                        \
                                    --install-lib=/usr/local/lib                     \
                                    --home="${HOME}"                                 \
                                    --single-version-externally-managed              \
@@ -214,7 +214,7 @@ if ! sudo python3 setup.py install --prefix="${install_dir}"                    
                                    --install-data                                   \
                                    --compile -optimize -O2                          \
                                    --force                                          \
-                                   --record "${cwd}"/terminator-installed-files.txt \
+                                   --record "$cwd"/terminator-installed-files.txt \
                                    --user                                           \
                                    --install-layout=unix; then
     fail_fn "Failed to execute: sudo python3 setup.py install:Line ${LINENO}"
diff --git a/Bash/Installer Scripts/GitHub Projects/build-tilix b/Bash/Installer Scripts/GitHub Projects/build-tilix
--- a/Bash/Installer Scripts/GitHub Projects/build-tilix
+++ b/Bash/Installer Scripts/GitHub Projects/build-tilix
@@ -24,8 +24,8 @@ fi
 #
 
 script_ver=1.2
-cwd="${PWD}"/tilix-build-script
-packages="${cwd}"/packages
+cwd="$PWD"/tilix-build-script
+packages="$cwd"/packages
 schemes_dir="${HOME}"/.config/tilix/schemes
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
@@ -37,16 +37,16 @@ debug=OFF
 
 box_out_banner()
 {
-    input_char=$(echo "${@}" | wc -c)
+    input_char=$(echo "$@" | wc -c)
     line=$(for i in $(seq 0 ${input_char}); do printf '-'; done)
     tput bold
-    line="$(tput setaf 3)${line}"
+    line="$(tput setaf 3)$line"
     space=${line//-/ }
-    echo " ${line}"
+    echo " $line"
     printf '|' ; echo -n "${space}" ; printf "%s\n" '|';
-    printf '| ' ;tput setaf 4; echo -n "${@}"; tput setaf 3 ; printf "%s\n" ' |';
+    printf '| ' ;tput setaf 4; echo -n "$@"; tput setaf 3 ; printf "%s\n" ' |';
     printf '|' ; echo -n "${space}" ; printf "%s\n" '|';
-    echo " ${line}"
+    echo " $line"
     tput sgr 0
 }
 box_out_banner "Tilix Build Script - v${script_ver}"
@@ -55,7 +55,7 @@ box_out_banner "Tilix Build Script - v${script_ver}"
 # CREATE OUTPUT DIRECTORIES
 #
 
-mkdir -p "${packages}" "${schemes_dir}"
+mkdir -p "$packages" "${schemes_dir}"
 
 
 #
@@ -66,15 +66,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -91,7 +91,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' answer
 
     case "${answer}" in
-        1)      sudo rm -fr "${cwd}" "${script_name}";;
+        1)      sudo rm -fr "$cwd" "${script_name}";;
         2)      echo;;
         *)
                 clear
@@ -109,12 +109,12 @@ execute()
     echo "$ ${*}"
 
     if [ "${debug}" = 'ON' ]; then
-        if ! output=$("${@}"); then
+        if ! output=$("$@"); then
             notify-send -t 5000 "Failed to execute: ${*}"
             fail_fn "Failed to execute: ${*}"
         fi
     else
-        if ! output=$("${@}" 2>&1); then
+        if ! output=$("$@" 2>&1); then
             notify-send -t 5000 "Failed to execute: ${*}"
             fail_fn "Failed to execute: ${*}"
         fi
@@ -123,134 +123,134 @@ execute()
 
 download()
 {
-    dl_path="${packages}"
-    dl_url="${1}"
+    dl_path="$packages"
+    dl_url="$1"
     dl_file="${2:-"${1##*/}"}"
 
-    if [[ "${dl_file}" =~ tar. ]]; then
+    if [[ "$dl_file" =~ tar. ]]; then
         output_dir="${dl_file%.*}"
         output_dir="${3:-"${output_dir%.*}"}"
     else
         output_dir="${3:-"${dl_file%.*}"}"
     fi
 
-    target_file="${dl_path}/${dl_file}"
-    target_dir="${dl_path}/${output_dir}"
+    target_file="$dl_path/$dl_file"
+    target_dir="$dl_path/$output_dir"
 
     if [ -f "${target_file}" ]; then
-        echo "The file \"${dl_file}\" is already downloaded."
+        echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"${dl_file}\""
-        if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
-            printf "\n%s\n\n" "The script failed to download \"${dl_file}\" and will try again in 10 seconds..."
+        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
+        if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+            printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
-                fail_fn "The script failed to download \"${dl_file}\" twice and will now exit. Line: ${LINENO}"
+            if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit. Line: ${LINENO}"
             fi
         fi
         echo 'Download Completed'
     fi
 
-    if [ -d "${target_dir}" ]; then
-        sudo rm -fr "${target_dir}"
+    if [ -d "$target_dir" ]; then
+        sudo rm -fr "$target_dir"
     fi
-    mkdir -p "${target_dir}"
+    mkdir -p "$target_dir"
 
-    if [ -n "${3}" ]; then
-        if ! tar -xf "${target_file}" -C "${target_dir}" 2>/dev/null >/dev/null; then
+    if [ -n "$3" ]; then
+        if ! tar -xf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script. Line: ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
         fi
     else
-        if ! tar -xf "${target_file}" -C "${target_dir}" --strip-components 1 2>/dev/null >/dev/null; then
+        if ! tar -xf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script. Line: ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
         fi
     fi
 
-    printf "%s\n\n" "File extracted: ${dl_file}"
+    printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}. Line: ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: ${LINENO}"
 }
 
 download_git()
 {
     local dl_path dl_url dl_file target_dir
 
-    dl_path="${packages}"
-    dl_url="${1}"
+    dl_path="$packages"
+    dl_url="$1"
     dl_file="${2:-"${1##*/}"}"
     dl_file="${dl_file//\./-}"
-    target_dir="${dl_path}/${dl_file}"
+    target_dir="$dl_path/$dl_file"
 
-    if [ -d "${target_dir}" ]; then
-        sudo rm -fr "${target_dir}"
+    if [ -d "$target_dir" ]; then
+        sudo rm -fr "$target_dir"
     fi
 
-    echo "Downloading ${dl_url} as ${dl_file}"
+    echo "Downloading ${dl_url} as $dl_file"
 
-    if ! git clone -q "${dl_url}" "${target_dir}"; then
-        printf "\n%s\n\n" "The script failed to clone the directory \"${target_dir}\" and will try again in 10 seconds..."
+    if ! git clone -q "${dl_url}" "$target_dir"; then
+        printf "\n%s\n\n" "The script failed to clone the directory \"$target_dir\" and will try again in 10 seconds..."
         sleep 10
-        if ! git clone -q "${dl_url}" "${target_dir}"; then
-            fail_fn "The script failed to clone the directory \"${target_dir}\" twice and will now exit the build."
+        if ! git clone -q "${dl_url}" "$target_dir"; then
+            fail_fn "The script failed to clone the directory \"$target_dir\" twice and will now exit the build."
         fi
     else
-        printf "%s\n\n" "Successfully cloned: ${target_dir}"
+        printf "%s\n\n" "Successfully cloned: $target_dir"
     fi
 
-    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir"
 }
 
 download_deb()
 {
-    dl_path="${packages}"
-    dl_url="${1}"
+    dl_path="$packages"
+    dl_url="$1"
     dl_file="${2:-"${1##*/}"}"
 
-    target_file="${dl_path}/${dl_file}"
+    target_file="$dl_path/$dl_file"
 
     if [ -f "${target_file}" ]; then
-        echo "The file \"${dl_file}\" is already downloaded."
+        echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"${dl_file}\""
-        if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
-            printf "\n%s\n\n" "The script failed to download \"${dl_file}\" and will try again in 10 seconds..."
+        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
+        if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+            printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
-                fail_fn "The script failed to download \"${dl_file}\" twice and will now exit."
+            if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit."
             fi
         fi
         echo 'Download Completed'
     fi
 
-    cd "${packages}" || fail_fn "Unable to change the working directory to: ${packages}"
+    cd "$packages" || fail_fn "Unable to change the working directory to: $packages"
 }
 
 build()
 {
     printf "\n%s\n%s\n" \
-        "Building ${1} - version ${2}" \
+        "Building $1 - version $2" \
         '===================================='
 
-    if [ -f "${packages}/${1}.done" ]; then
-        if grep -Fx "${2}" "${packages}/${1}.done" >/dev/null; then
-            echo "${1} version ${2} already built. Remove ${packages}/${1}.done lockfile to rebuild it."
+    if [ -f "$packages/$1.done" ]; then
+        if grep -Fx "$2" "$packages/$1.done" >/dev/null; then
+            echo "$1 version $2 already built. Remove $packages/$1.done lockfile to rebuild it."
             return 1
         elif ${latest}; then
-            echo "${1} is outdated and will be rebuilt using version ${2}"
+            echo "$1 is outdated and will be rebuilt using version $2"
             return 0
         else
-            echo "${1} is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove ${packages}/${1}.done lockfile."
+            echo "$1 is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove $packages/$1.done lockfile."
             return 1
         fi
     fi
     return 0
 }
 
-build_done() { echo "${2}" >"${packages}/${1}.done"; }
+build_done() { echo "$2" >"$packages/$1.done"; }
 
-installed() { return $(dpkg-query -W -f '${Status}\n' "${1}" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}'); }
+installed() { return $(dpkg-query -W -f '${Status}\n' "$1" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}'); }
 
 #
 # INSTALL APT PACKAGES
diff --git a/Bash/Installer Scripts/GitHub Projects/build-yasm b/Bash/Installer Scripts/GitHub Projects/build-yasm
--- a/Bash/Installer Scripts/GitHub Projects/build-yasm
+++ b/Bash/Installer Scripts/GitHub Projects/build-yasm
@@ -43,8 +43,8 @@ fi
 
 script_ver=1.1
 install_dir=/usr/local
-cwd="${PWD}"/yasm-build-script
-packages="${cwd}"/packages
+cwd="$PWD"/yasm-build-script
+packages="$cwd"/packages
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
 debug=OFF # CHANGE THE DEBUG VARIABLE TO "ON" FOR HELP TROUBLESHOOTING ISSUES
@@ -57,8 +57,8 @@ printf "\n%s\n%s\n\n" \
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ ! -d "${cwd}" ]; then
-    mkdir -p "${packages}"
+if [ ! -d "$cwd" ]; then
+    mkdir -p "$packages"
 fi
 
 #
@@ -123,15 +123,15 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${web_repo}"
+        "$web_repo"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${web_repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
@@ -148,7 +148,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -164,15 +164,15 @@ cleanup_fn()
 build()
 {
     printf "\n%s\n%s\n" \
-        "building ${1} - version ${2}" \
+        "building $1 - version $2" \
         '===================================='
 
-    if [ -f "${packages}/${1}.done" ]; then
-        if grep -Fx "${2}" "${packages}/${1}.done" >/dev/null; then
-            echo "${1} version ${2} already built. Remove ${packages}/${1}.done lockfile to rebuild it."
+    if [ -f "$packages/$1.done" ]; then
+        if grep -Fx "$2" "$packages/$1.done" >/dev/null; then
+            echo "$1 version $2 already built. Remove $packages/$1.done lockfile to rebuild it."
             return 1
         else
-            echo "${1} is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove ${packages}/${1}.done lockfile."
+            echo "$1 is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove $packages/$1.done lockfile."
             return 1
         fi
     fi
@@ -184,12 +184,12 @@ execute()
     echo "$ ${*}"
 
     if [ "${debug}" = 'ON' ]; then
-        if ! output=$("${@}"); then
+        if ! output=$("$@"); then
             notify-send 5000 "Failed to execute: ${*}"
             fail_fn "Failed to execute: ${*}"
         fi
     else
-        if ! output=$("${@}" 2>&1); then
+        if ! output=$("$@" 2>&1); then
             notify-send 5000 "Failed to execute: ${*}"
             fail_fn "Failed to execute: ${*}"
         fi
@@ -198,55 +198,55 @@ execute()
 
 download()
 {
-    dl_path="${packages}"
-    dl_url="${1}"
+    dl_path="$packages"
+    dl_url="$1"
     dl_file="${2:-"${1##*/}"}"
 
-    if [[ "${dl_file}" =~ tar. ]]; then
+    if [[ "$dl_file" =~ tar. ]]; then
         output_dir="${dl_file%.*}"
         output_dir="${3:-"${output_dir%.*}"}"
     else
         output_dir="${3:-"${dl_file%.*}"}"
     fi
 
-    target_file="${dl_path}/${dl_file}"
-    target_dir="${dl_path}/${output_dir}"
+    target_file="$dl_path/$dl_file"
+    target_dir="$dl_path/$output_dir"
 
     if [ -f "${target_file}" ]; then
-        echo "The file \"${dl_file}\" is already downloaded."
+        echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"${dl_file}\""
-        if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
-            printf "\n%s\n\n" "The script failed to download \"${dl_file}\" and will try again in 10 seconds..."
+        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
+        if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+            printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
-                fail_fn "The script failed to download \"${dl_file}\" twice and will now exit."
+            if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit."
             fi
         fi
         echo 'Download Completed'
     fi
 
-    if [ -d "${target_dir}" ]; then
-        sudo rm -fr "${target_dir}"
+    if [ -d "$target_dir" ]; then
+        sudo rm -fr "$target_dir"
     fi
 
-    mkdir -p "${target_dir}"
+    mkdir -p "$target_dir"
 
-    if [ -n "${3}" ]; then
-        if ! tar -xf "${target_file}" -C "${target_dir}" 2>/dev/null >/dev/null; then
+    if [ -n "$3" ]; then
+        if ! tar -xf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script."
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script."
         fi
     else
-        if ! tar -xf "${target_file}" -C "${target_dir}" --strip-components 1 2>/dev/null >/dev/null; then
+        if ! tar -xf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script."
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script."
         fi
     fi
 
-    printf "%s\n\n" "File extracted: ${dl_file}"
+    printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir"
 }
 
 git_1_fn()
@@ -254,11 +254,11 @@ git_1_fn()
     local curl_cmd github_repo github_url
 
     # SCRAPE GITHUB WEBSITE FOR THE LATEST REPO VERSION
-    github_repo="${1}"
-    github_url="${2}"
+    github_repo="$1"
+    github_url="$2"
 
-    if curl_cmd="$(curl -A "${user_agent}" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
-        g_ver="$(echo "${curl_cmd}" | jq -r '.[0].name' 2>/dev/null)"
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
+        g_ver="$(echo "$curl_cmd" | jq -r '.[0].name' 2>/dev/null)"
         g_ver="${g_ver#v}"
     fi
 }
@@ -267,8 +267,8 @@ git_ver_fn()
 {
     local t_flag v_flag v_url
 
-    v_url="${1}"
-    v_flag="${2}"
+    v_url="$1"
+    v_flag="$2"
 
     case "${v_flag}" in
             B)      t_flag=branches;;
@@ -305,7 +305,7 @@ pkgs_fn()
     fi
 }
 
-build_done() { echo "${2}" > "${packages}/${1}.done"; }
+build_done() { echo "$2" > "$packages/$1.done"; }
 
 #
 # BUILD PROGRAM FROM SOURCE
@@ -314,7 +314,7 @@ build_done() { echo "${2}" > "${packages}/${1}.done"; }
 if build 'yasm' '1.3.0'; then
     download 'https://github.com/yasm/yasm/archive/refs/tags/v1.3.0.tar.gz' 'yasm-1.3.0.tar.gz'
     execute autoreconf -fi
-    execute cmake -B build -DCMAKE_install_dir="${install_dir}" \
+    execute cmake -B build -DCMAKE_install_dir="$install_dir" \
                            -DCMAKE_BUILD_TYPE=Release           \
                            -DBUILD_SHARED_LIBS=OFF              \
                            -G Ninja -Wno-dev
