Update build-all-gnu

diff --git a/Bash/Installer Scripts/GNU Software/build-all-gnu b/Bash/Installer Scripts/GNU Software/build-all-gnu
--- a/Bash/Installer Scripts/GNU Software/build-all-gnu
+++ b/Bash/Installer Scripts/GNU Software/build-all-gnu
@@ -1,117 +1,124 @@
 #!/usr/bin/env bash
 
-# GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GNU%20Software/build-parallel
-# Purpose: Build GNU parallel
-# Updated: 03.07.24
-# Script version: 2.0
+clear
 
-set -e  # Exit on error
+cwd="$PWD/build-all-gnu-master"
+web_repo="https://github.com/slyfox1186/script-repo"
 
-if [ "$EUID" -ne 0 ]; then
-    echo
-    echo "You must run this script with root/sudo."
-    exit 1
+if [ ! -d "$cwd/completed" ]; then
+    mkdir -p "$cwd/completed"
 fi
 
-# SET THE VARIABLES
-script_ver=2.0
-archive_dir=parallel-latest
-archive_url=https://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2
-archive_ext="${archive_url//*.}"
-archive_name="$archive_dir.tar.$archive_ext"
-cwd="$PWD/parallel-build-script"
-install_dir=/usr/local
-web_repo=https://github.com/slyfox1186/script-repo
-
-echo "parallel build script - v$script_ver"
-echo "==============================================="
-
-# CREATE OUTPUT DIRECTORY
-rm -fr "$cwd"
-mkdir -p "$cwd"
-
-SET COMPILER FLAGS
-CC=gcc
-CXX=g++
-CFLAGS="-g -O3 -pipe -march=native"
-CXXFLAGS="-g -O3 -pipe -march=native"
-
-# SET ENVIRONMENT VARIABLES
-export PATH="\
-/usr/lib/ccache:\
-$HOME/perl5/bin:\
-$HOME/.cargo/bin:\
-$HOME/.local/bin:\
-/usr/local/sbin:\
-/usr/local/cuda/bin:\
-/usr/local/x86_64-linux-gnu/bin:\
-/usr/local/bin:/usr/sbin:\
-/usr/bin:\
-/sbin:\
-/bin\
-"
-
-export PKG_CONFIG_PATH="\
-/usr/local/lib64/pkgconfig:\
-/usr/local/lib/pkgconfig:\
-/usr/local/lib/x86_64-linux-gnu/pkgconfig:\
-/usr/local/share/pkgconfig:\
-/usr/lib64/pkgconfig:\
-/usr/lib/pkgconfig:\
-/usr/lib/x86_64-linux-gnu/pkgconfig:\
-/usr/share/pkgconfig:\
-/lib64/pkgconfig:\
-/lib/pkgconfig:\
-/lib/x86_64-linux-gnu/pkgconfig\
-"
-
-FUNCTIONS
 exit_fn() {
-    echo
-    echo "\n%s\n\n%s\n\n"
-    echo "Make sure to star this repository to show your support!"
-    echo "$web_repo"
-    echo
+    printf "\n%s\n\n%s\n\n" \
+        "Make sure to star this repository to show your support!" \
+        "$web_repo"
+    exit 0
 }
 
 fail_fn() {
-    echo
-    echo "Error: $1"
-    echo "To report a bug create an issue at: $web_repo/issues"
-    echo
-exit 1
+    printf "\n%s\n\n%s\n\n" \
+        "$1" \
+        "To report a bug create an issue at: $web_repo/issues"
+    exit 1
 }
 
 cleanup_fn() {
-    read -p "Do you want to clean up the build files? [y/N] " choice
-    case "$choice" in
-        y|Y ) rm -fr "$cwd" ;;
-        * ) ;;
+    local answer
+
+    printf "\n%s\n%s\n%s\n\n%s\n%s\n\n" \
+        "============================================" \
+        "  Do you want to clean up the build files?  " \
+        "============================================" \
+        "[1] Yes" \
+        "[2] No"
+    read -p "Your choices are (1 or 2): " answer
+
+    case "$answer" in
+        1)  sudo rm -fr "$cwd" "${0}" ;;
+        2)  echo ;;
+        *)  printf "\n%s\n\n" "Bad user input. Re-asking question..."
+            sleep 3
+            clear
+            cleanup_fn
+            ;;
     esac
 }
 
-# INSTALL DEPENDENCIES
 pkgs=(
-    "autoconf" "autoconf-archive" "autogen" "automake" "binutils" "bison"
-    "build-essential" "bzip2" "ccache" "curl" "libc6-dev" "libpth-dev"
-    "libtool" "libtool-bin" "lzip" "lzma-dev" "m4" "nasm" "texinfo" "zlib1g-dev"
-    "yasm"
+    asciidoc autogen autoconf autoconf-archive automake binutils bison build-essential bzip2 ccache cmake
+    curl libc6-dev libintl-perl libpth-dev libtool libtool-bin lzip lzma-dev m4 meson nasm ninja-build
+    texinfo xmlto yasm zlib1g-dev
 )
-apt install -y "${pkgs[@]}"
 
-# DOWNLOAD SOURCE
-curl -sSfLo "$cwd/$archive_name" "$archive_url"
-mkdir -p "$cwd/$archive_dir/build"
-tar -jxf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1
+for i in "${pkgs[@]}"
+do
+    if ! dpkg -l | grep -q "$i"; then
+        missing_pkgs+=("$i")
+    fi
+done
 
-# BUILD
-cd "$cwd/$archive_dir/build" || exit 1
-../configure --prefix "$install_dir"
-make "-j$(nproc --all)"
-make install
+if [ "${#missing_pkgs[@]}" -ne 0 ]; then
+    sudo apt install "${missing_pkgs[@]}"
+    sudo apt -y autoremove
+    clear
+fi
 
-# PROMPT CLEANUP
+install_scripts_fn() {
+    local i
+    clear
+
+    for i in *.sh
+    do
+        if bash "$i"; then
+            mv "$i" completed
+            printf "\n%s\n\n" "Script finished: $i"
+        else
+            fail_fn "Failed to install: $i"
+        fi
+        sleep 2
+    done
+}
+
+install_choice_fn() {
+    local answer
+
+    printf "\n%s\n\n%s\n\n%s\n%s\n\n" \
+        "Do you want to install all of the scripts now?" \
+        "You must manually remove any scripts you do not want to install before continuing." \
+        "[1] Yes" \
+        "[2] No"
+    read -p "Your choices are (1 or 2): " answer
+
+    case "$answer" in
+        1)  install_scripts_fn ;;
+        2)  exit_fn ;;
+        *)  printf "%s\n\n" "Bad user input... Resetting script."
+            sleep 3
+            clear
+            install_choice_fn
+            ;;
+    esac
+}
+
+cd "$cwd" || exit 1
+
+scripts=(
+    attr autoconf bash binutils coreutils dbus diffutils emacs eog gawk gcc gettext-libiconv gnutls grep gzip
+    imath isl libtool m4 make nano ncurses nettle pkg-config readline sed systemd tar texinfo wget
+)
+
+for script in "${scripts[@]}"
+do
+    wget --show-progress -cq "https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GNU%20Software/build-${script}"
+    mv "build-${script}" "$(printf "%02d" "${#scripts[@]}")-build-${script}"
+done
+
+# ASK THE USER IF THEY WANT TO INSTALL ALL OF THE SCRIPTS
+install_choice_fn
+
+# CLEANUP THE FILES
 cleanup_fn
 
-# EXIT MESSAGE
+# SHOW THE EXIT MESSAGE
 exit_fn
