Update build-all-gnu-safer-archlinux

diff --git a/Bash/Installer Scripts/GNU Software/build-all-gnu-safer-archlinux b/Bash/Installer Scripts/GNU Software/build-all-gnu-safer-archlinux
--- a/Bash/Installer Scripts/GNU Software/build-all-gnu-safer-archlinux
+++ b/Bash/Installer Scripts/GNU Software/build-all-gnu-safer-archlinux
@@ -1,22 +1,48 @@
 #!/usr/bin/env bash
 
+##################################################################################################################################################
+##
+##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GNU%20Software/build-all-gnu-safer-arch-script
+##
+##  Purpose: Loops multiple build scripts to optimize efficiency. This is the safer of the two scripts.
+##
+##  Updated: 11.06.23
+##
+##  Script version: 1.0
+##
+##################################################################################################################################################
+
 clear
 
+if [ "${EUID}" -eq '0' ]; then
+    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+    exit 1
+fi
+
+script_ver=1.0
 cwd="${PWD}"/build-all-gnu-safer-arch-script
-workspace="${cwd}"/workspace
 web_repo=https://github.com/slyfox1186/script-repo
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'
 
 if [ -d "${cwd}" ]; then
     sudo rm -fr "${cwd}"
 fi
-mkdir -p "${cwd}"/completed
+mkdir -p "${cwd}"/completed "${cwd}"/failed
 
 cd "${cwd}" || exit 1
 
+#
+# PRINT THE SCRIPT BANNER
+#
+
+printf "%s\n%s\n\n"                                      \
+    "Build All GNU Safer ArchLinux Script - version ${script_ver}" \
+    '============================================================'
+sleep 2
+
 exit_fn()
 {
-    printf "\n%s\n\n%s\n\n" \
+    printf "\n%s\n\n%s\n\n"                                       \
         'Make sure to star this repository to show your support!' \
         "${web_repo}"
     exit 0
@@ -25,34 +51,9 @@ exit_fn()
 fail_fn()
 {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
+        "${1}"              \
         "To report a bug create an issue at: ${web_repo}/issues"
     exit 1
-}
-
-cleanup_fn()
-{
-    local answer
-
-    printf "\n%s\n%s\n%s\n\n%s\n%s\n\n" \
-        '============================================' \
-        '  Do you want to clean up the build files?  ' \
-        '============================================' \
-        '[1] Yes' \
-        '[2] No'
-    read -p 'Your choices are (1 or 2): ' answer
-
-    case "${answer}" in
-        1)      sudo rm -fr "${cwd}"; clear;;
-        2)      echo;;
-        *)
-                printf "\n%s\n\n" 'Bad user input. Re-asking question...'
-                sleep 3
-                unset answer
-                clear
-                cleanup_fn
-                ;;
-    esac
 }
 
 pkgs=(asciidoc autogen autoconf autoconf-archive automake binutils bison base-devel bzip2
@@ -69,38 +70,50 @@ do
 done
 
 if [ -n "${missing_pkgs}" ]; then
-    sudo yes|pacman -S ${missing_pkgs}
+    for pkg in "${missing_pkgs[@]}"
+    do
+        sudo pacman -Sq --noconfirm ${pkg}
+    done
     clear
 fi
 
-dl_files=(m4 autoconf libtool make bash pkg-config sed tar gawk grep nano isl wget)
+scripts=(m4 autoconf libtool bash pkg-config make sed tar gawk grep nano wget)
 cnt=0
 
-for dl_file in ${dl_files[@]}
+for script in ${scripts[@]}
 do
     let cnt=cnt+1
-    wget -U "${user_agent}" --show-progress -cq "https://raw.githubusercontent.com/slyfox1186/script-repo/main/Bash/Installer%20Scripts/GNU%20Software/build-${dl_file}"
-    mv "build-${dl_file}" "0${cnt}-build-${dl_file}"'.sh' 2>/dev/null
+    wget -U "${user_agent}" --show-progress -cq "https://raw.githubusercontent.com/slyfox1186/script-repo/main/Bash/Installer%20Scripts/GNU%20Software/build-${script}"
+    mv "build-${script}" "0${cnt}-build-${script}"'.sh' 2>/dev/null
 done
-unset cnt
+unset cnt script scripts
 
 # RENAME FILES WITH NUMBERS 10 AND HIGHER SO THEY EXECUTE IN THE INTENDED ORDER
-files=(gawk grep nano isl wget)
+scripts=(gawk grep nano wget)
 cnt=9
 
 for i in 1
 do
-    for file in ${files[@]}
+    for script in ${scripts[@]}
     do
         ((cnt++)) # << start counting here
-        mv "0${cnt}-build-${file}" "${cnt}-build-${file}" 2>/dev/null # << move the files, thus renaming them
+        mv "0${cnt}-build-${script}" "${cnt}-build-${script}" 2>/dev/null # << move the files, thus renaming them
     done
 done
 
 clear
 
-find . -maxdepth 1 -type f -iname '*.sh' -exec bash -c "echo '1' | bash '{}'; mv '{}' completed" \;
+for f in $(ls -v)
+do
+    if echo '1' | bash "${f}"; then
+        mv "${f}" 'completed'
+    else
+        mv "${f}" 'failed'
+    fi
+done
 
+# CLEANUP LEFTOVER FILES
 sudo rm -fr "${cwd}"
 
+# DISPLAY EXIT MESSAGE
 exit_fn
