Update build-make

diff --git a/Bash/Installer Scripts/GNU Software/build-make b/Bash/Installer Scripts/GNU Software/build-make
--- a/Bash/Installer Scripts/GNU Software/build-make
+++ b/Bash/Installer Scripts/GNU Software/build-make
@@ -1,16 +1,34 @@
 #!/usr/bin/env bash
 
+###########################################################################################################
+##
+##  GitHub Script: https://github.com/slyfox1186/script-repo/edit/main/Bash/Installer%20Scripts/GNU%20Software/build-make
+##
+##  Purpose: Build GNU Make
+##
+##  Updated: 08.01.23
+##
+##  Script version: 1.1
+##
+###########################################################################################################
+
 clear
 
+if [ "$EUID" -eq '0' ]; then
+    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+    exit 1
+fi
+
 #
-# SET PROGRAM NAME + VERSION
+# SET VARIABLES
 #
 
-script_ver=1.0
+script_ver=1.1
 archive_dir=make-4.4.1
 archive_url=https://ftp.gnu.org/gnu/make/make-4.4.1.tar.lz
 archive_ext="${archive_url//*.}"
 cwd="$PWD"/make-build-script
+repo=https://github.com/slyfox1186/script-repo
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
 
 printf "\n%s\n%s\n\n" \
@@ -26,13 +44,13 @@ if [ ! -d "$cwd" ]; then
 fi
 
 #
-# SET THE C+CPP COMPILERS
+# SET THE C + CPP COMPILERS
 #
 
 export CC=gcc CXX=g++
 
 #
-# EXPORT COMPILER OPTIMIZATION FLAGS
+# SET COMPILER OPTIMIZATION FLAGS
 #
 
 export {CFLAGS,CXXFLAGS}='-g -O3 -march=native'
@@ -63,27 +81,49 @@ $workspace/usr/lib/pkgconfig:\
 "
 
 #
+# SET PATH
+#
+
+PATH="\
+/usr/lib/ccache:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
+/usr/local/sbin:\
+/usr/local/bin:\
+/usr/sbin:\
+/usr/bin:\
+/sbin:\
+/bin:\
+/usr/local/cuda/bin:\
+/snap/bin\
+"
+export PATH
+
+#
 # CREATE FUNCTIONS
 #
 
 exit_fn()
 {
-    printf "\n%s\n\n" 'The script has completed.'
+    printf "\n%s\n\n%s\n\n" \
+        'Make sure to star this repository to show your support!' \
+        "$repo"
     exit 0
 }
 
-
 fail_fn()
 {
-    printf "%s\n\n" "$1"
+    printf "\n%s\n\n%s\n\n" \
+        "$1" \
+        "To report a bug create an issue at: $repo/issues"
     exit 1
 }
 
 cleanup_fn()
 {
-    local choice
+    local choice dpkg_list
 
-    printf "\n%s\n%s\n%s\n\n%s\n%s\n\n" \
+    printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
         '============================================' \
         '  Do you want to clean up the build files?  ' \
         '============================================' \
@@ -109,22 +149,27 @@ cleanup_fn()
 # INSTALL REQUIRED APT PACKAGES
 #
 
-pkgs=(autoconf autogen automake binutils build-essential ccache cmake curl git guile-3.0-dev libdmalloc-dev libdmalloc5 libgmp-dev
-      libintl-perl libmpfr-dev libreadline-dev libsigsegv-dev libtool libtool-bin lzip m4 nasm ninja-build texinfo zlib1g-dev yasm)
-
-for i in ${pkgs[@]}
-do
-    missing_pkg="$(dpkg -l | make $i)"
-
-    if [ -z "$missing_pkg" ]; then
-        missing_pkgs+=" $i"
+pkgs_fn()
+{
+    local i missing_pkg missing_pkgs pkgs 
+    pkgs=(autoconf autogen automake binutils build-essential ccache cmake curl git guile-3.0-dev libdmalloc-dev libdmalloc5 libgmp-dev
+          libintl-perl libmpfr-dev libreadline-dev libsigsegv-dev libtool libtool-bin lzip m4 nasm ninja-build texinfo zlib1g-dev yasm)
+    
+    for i in ${pkgs[@]}
+    do
+        missing_pkg="$(dpkg -l | grep "$i")"
+    
+        if [ -z "$missing_pkg" ]; then
+            missing_pkgs+=" $i"
+        fi
+    done
+    
+    if [ -n "$missing_pkgs" ]; then
+        sudo apt -y install $missing_pkgs
+        sudo apt -y autoremove
+        clear
     fi
-done
-
-if [ -n "$missing_pkgs" ]; then
-    sudo apt -y install $missing_pkgs
-    clear
-fi
+}
 
 #
 # GET PC TYPE
@@ -163,21 +208,36 @@ if ! tar -xf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; t
 fi
 
 #
+# TEST IF LIBICONV WAS MANUALLY INSTALLED OR BY APT
+#
+
+if [ -f /usr/local/bin/iconv ]; then
+    pkgs_fn
+    iconv_prefix=/usr/local
+elif [ -f /usr/bin/iconv ]; then
+    pkgs_fn
+    iconv_prefix=/usr
+else
+    pkgs_fn 'libiconv-hook-dev'
+    iconv_prefix=/usr
+fi
+
+#
 # BUILD PROGRAM FROM SOURCE
 #
 
 cd "$cwd/$archive_dir" || exit 1
 autoreconf -fi
 cd build || exit 1
-../configure --prefix=/usr/local                \
-             --{build,host}="$pc_type"          \
-             --disable-nls                      \
-             --enable-year2038                  \
-             --with-dmalloc                     \
-             --with-guile                       \
-             --with-libiconv-prefix=/usr/local  \
-             --with-libintl-prefix=/usr         \
-             PKG_CONFIG="$(type -P pkg-config)" \
+../configure --prefix=/usr/local                    \
+             --{build,host}="$pc_type"              \
+             --disable-nls                          \
+             --enable-year2038                      \
+             --with-dmalloc                         \
+             --with-guile                           \
+             --with-libiconv-prefix="$iconv_prefix" \
+             --with-libintl-prefix=/usr             \
+             PKG_CONFIG="$(type -P pkg-config)"     \
              PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
 make "-j$(nproc --all)"
 if ! sudo make install; then
@@ -186,5 +246,8 @@ if ! sudo make install; then
     exit 1
 fi
 
-sudo rm -fr "$cwd"
-unset archive_dir archive_ext archive_name archive_url CC CXX i missing_pkg missing_pkgs pc_type pem_target pkgs script_ver
+# PROMPT USER TO CLEAN UP FILES
+cleanup_fn
+
+# SHOW EXIT MESSAGE
+exit_fn
