changes to code formatting

diff --git a/Bash/Installer Scripts/GNU Software/build-gzip b/Bash/Installer Scripts/GNU Software/build-gzip
--- a/Bash/Installer Scripts/GNU Software/build-gzip
+++ b/Bash/Installer Scripts/GNU Software/build-gzip
@@ -1,9 +1,9 @@
-#!/usr/bin/env bash
-# shellcheck disable=SC2162
+#!/Usr/bin/env bash
+# Shellcheck disable=sc2162
 
 ###########################################################################################################################
 ##
-##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GNU%20Software/build-gzip
+##  Github script: https://github.com/slyfox1186/script-repo/blob/main/bash/installer%20scripts/gnu%20software/build-gzip
 ##
 ##  Purpose: build gnu gzip
 ##
@@ -15,59 +15,49 @@
 
 clear
 
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+if [ "$EUID" -eq '0' ]; then
+    echo "You must run this script without root or sudo."
     exit 1
 fi
 
-#
-# SET THE VARIABLES
-#
+# Set the variables
 
 script_ver=1.0
 archive_dir=gzip-1.13
 archive_url=https://ftp.gnu.org/gnu/gzip/$archive_dir.tar.xz
-archive_ext="${archive_url//*.}"
-archive_name="$archive_dir.tar.${archive_ext}"
+archive_ext="$archive_url//*."
+archive_name="$archive_dir.tar.$archive_ext"
 cwd="$PWD"/gzip-build-script
 install_dir=/usr/local
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
 
 printf "%s\n%s\n\n" \
-    "gzip build script - v${script_ver}" \
+    "gzip build script - v$script_ver" \
     '==============================================='
 
-#
-# CREATE OUTPUT DIRECTORY
-#
+# Create output directory
 
 if [ -d "$cwd" ]; then
     sudo rm -fr "$cwd"
 fi
 mkdir -p "$cwd"
 
-#
-# SET THE C + CPP COMPILERS
-#
+# Set the c + cpp compilers
 
 export CC=gcc CXX=g++
 
-#
-# SET COMPILER OPTIMIZATION FLAGS
-#
+# Set compiler optimization flags
 
-export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -march=native'
+export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -fno-plt -march=native'
 
-#
-# SET THE PATH VARIABLE
-#
+# Set the path variable
 
 PATH="\
 /usr/lib/ccache:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
+$HOME/perl5/bin:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -82,9 +72,7 @@ ${HOME}/.local/bin:\
 "
 export PATH
 
-#
-# SET THE PKG_CONFIG_PATH VARIABLE
-#
+# Set the pkg_config_path variable
 
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
@@ -101,28 +89,23 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
-#
-# CREATE FUNCTIONS
-#
+# Create functions
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
         "$web_repo"
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n%s\n\n%s\n\n" \
         "$1" \
         "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local choice
 
     printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
@@ -133,7 +116,7 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "${choice}" in
+    case "$choice" in
         1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
@@ -147,9 +130,7 @@ cleanup_fn()
     esac
 }
 
-#
-# INSTALL REQUIRED APT PACKAGES
-#
+# Install required apt packages
 
 
 pkgs=(autoconf autoconf-archive autogen automake binutils bison build-essential bzip2 ccache curl
@@ -158,10 +139,10 @@ pkgs=(autoconf autoconf-archive autogen automake binutils bison build-essential 
 
 for i in ${pkgs[@]}
 do
-	missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
+	missing_pkg="$(sudo dpkg -l | grep -o "$i")"
 
-	if [ -z "${missing_pkg}" ]; then
-		missing_pkgs+=" ${i}"
+	if [ -z "$missing_pkg" ]; then
+		missing_pkgs+=" $i"
 	fi
 done
 
@@ -171,35 +152,27 @@ if [ -n "$missing_pkgs" ]; then
 	clear
 fi
 
-#
-# DOWNLOAD THE ARCHIVE FILE
-#
+# Download the archive file
 
-if [ ! -f "$cwd/${archive_name}" ]; then
-    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/$archive_name" ]; then
+    curl -A "$user_agent" -Lso "$cwd/$archive_name" "$archive_url"
 fi
 
-#
-# CREATE OUTPUT DIRECTORY
-#
+# Create output directory
 
 if [ -d "$cwd/$archive_dir" ]; then
     sudo rm -fr "$cwd/$archive_dir"
 fi
 mkdir -p "$cwd/$archive_dir/build"
 
-#
-# EXTRACT ARCHIVE FILES
-#
+# Extract archive files
 
-if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
+if ! tar -xf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/$archive_name"
     exit 1
 fi
 
-#
-# BUILD PROGRAM FROM SOURCE
-#
+# Build program from source
 
 cd "$cwd/$archive_dir" || exit 1
 autoreconf -fi
@@ -210,11 +183,11 @@ cd build || exit 1
              --enable-silent-rules
 make "-j$(nproc --all)"
 if ! sudo make install; then
-    fail_fn "Failed to execute: sudo make install:Line ${LINENO}"
+    fail_fn "Failed to execute: sudo make install:Line $LINENO"
 fi
 
-# PROMPT USER TO CLEAN UP FILES
+# Prompt user to clean up files
 cleanup_fn
 
-# SHOW EXIT MESSAGE
+# Show exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GitHub Projects/build-aria2 b/Bash/Installer Scripts/GitHub Projects/build-aria2
--- a/Bash/Installer Scripts/GitHub Projects/build-aria2
+++ b/Bash/Installer Scripts/GitHub Projects/build-aria2
@@ -1,22 +1,22 @@
-#!/usr/bin/env bash
+#!/Usr/bin/env bash
 
-##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-aria2
-##  Purpose: Build aria2 from source code
+##  Github script: https://github.com/slyfox1186/script-repo/blob/main/bash/installer%20scripts/github%20projects/build-aria2
+##  Purpose: build aria2 from source code
 ##  Updated: 03.07.24
 ##  Script version: 2.0
 ##  Features:
 ##            - Static build
-##            - OpenSSL backend
+##            - Openssl backend
 ##            - Increased the max connections from 16 to 128
 ##  Added:
 ##         - Display a menu by passing -h or --help as arguments to the script
 ##         - Build a service by passing an argument to the script
 ##         - Builds everything in temporary directories in the /tmp folder and removes them when done
-##         - Updated Aria2 to the latest version - 1.37.0
-##         - If OpenSSL is manually installed using the build-openssl script then use its certs directory instead of the default.
+##         - Updated aria2 to the latest version - 1.37.0
+##         - If openssl is manually installed using the build-openssl script then use its certs directory instead of the default.
 ##         - Build jemalloc from the latest source code
-##         - RUNPATH to LDFLAGS
-##  Fixed: Soft linking error
+##         - Runpath to ldflags
+##  Fixed: soft linking error
 
 script_ver="2.0"
 echo "GitHub Script for building aria2 from source. Version: $script_ver"
@@ -25,8 +25,8 @@ GREEN='\033[0;32m'
 RED='\033[0;31m'
 NC='\033[0m'
 
-log() { echo -e "${GREEN}[LOG]${NC} $(date +'%Y-%m-%d %H:%M:%S') - $*"; }
-handle_error() { echo -e "${RED}[ERROR]${NC} $(date +'%Y-%m-%d %H:%M:%S') - $*"; exit 1; }
+log() { echo -e "$GREEN[LOG]$NC $(date +'%Y-%m-%d %H:%M:%S') - $*"; }
+handle_error() { echo -e "$RED[ERROR]$NC $(date +'%Y-%m-%d %H:%M:%S') - $*"; exit 1; }
 
 display_help() {
     echo "Usage: $0 [OPTION]..."
@@ -42,8 +42,8 @@ display_help() {
 set_compiler_options() {
     CC="ccache gcc"
     CXX="ccache g++"
-    CFLAGS="-g -O3 -pipe -march=native"
-    CXXFLAGS="-g -O3 -pipe -march=native"
+    CFLAGS="-g -O3 -pipe -fno-plt -march=native"
+    CXXFLAGS="-g -O3 -pipe -fno-plt -march=native"
     export CC CFLAGS CXX CXXFLAGS
 }
 
@@ -58,7 +58,7 @@ install_packages() {
     log "Attempting to install required packages..."
     apt install -y "${pkgs[@]}"
     for pkg in "${pkgs[@]}"; do
-        dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed" || handle_error "Failed to install: $pkg"
+        dpkg-query -W -f='$Status' "$pkg" 2>/dev/null | grep -q "ok installed" || handle_error "Failed to install: $pkg"
     done
     echo
     log "Installation of required packages completed."
@@ -101,7 +101,7 @@ build_libgpg_error() {
     local libgpg_error_version=$(libgpg_latest_release_version "https://gnupg.org/ftp/gcrypt/libgpg-error/")
     local libgpg_error_url="https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-$libgpg_error_version.tar.bz2"
     curl -Ls "$libgpg_error_url" | tar -xj
-    cd "libgpg-error-${libgpg_error_version}"
+    cd "libgpg-error-$libgpg_error_version"
     ./configure --prefix="$temp_dir/libgpg-error"
     make "-j$(nproc)" && make install
     cd ../
diff --git a/Bash/Installer Scripts/GitHub Projects/build-clang-15 b/Bash/Installer Scripts/GitHub Projects/build-clang-15
--- a/Bash/Installer Scripts/GitHub Projects/build-clang-15
+++ b/Bash/Installer Scripts/GitHub Projects/build-clang-15
@@ -1,11 +1,11 @@
-#!/usr/bin/env bash
-# shellcheck disable=SC2162,SC2317
+#!/Usr/bin/env bash
+# Shellcheck disable=sc2162,sc2317
 
 ###########################################################################################################
 ##
-##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-clang-15
+##  Github script: https://github.com/slyfox1186/script-repo/blob/main/bash/installer%20scripts/github%20projects/build-clang-15
 ##
-##  Purpose: Build LLVM-15
+##  Purpose: build llvm-15
 ##
 ##  Updated: 10.12.23
 ##
@@ -15,48 +15,38 @@
 
 clear
 
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+if [ "$EUID" -eq '0' ]; then
+    echo "You must run this script without root or sudo."
     exit 1
 fi
 
-#
-# SET GLOBAL VARIABLES
-#
+# Set global variables
 
 script_ver=1.0
-progname="${0}"
+progname="$0"
 cwd="$PWD"/clang-15-build-script
 install_prefix=/usr/local
 pc_type=$(gcc -dumpmachine)
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
-debug=OFF # CHANGE THIS VARIABLE TO "ON" FOR HELP WITH TROUBLESHOOTING UNEXPECTED ISSUES DURING THE BUILD
+debug=OFF # Change this variable to "on" for help with troubleshooting unexpected issues during the build
 
-#
-# CREATE OUTPUT DIRECTORIES
-#
+# Create output directories
 
 if [ ! -d "$cwd" ]; then
     mkdir -p "$cwd"
 fi
 
-#
-# FIGURE OUT WHICH COMPILERS TO USE
-#
+# Figure out which compilers to use
 
 export CC=clang CXX=clang++
 
-#
-# SET COMPILER OPTIMIZATION FLAGS
-#
+# Set compiler optimization flags
 
-CFLAGS='-g -O3 -pipe -march=native'
-CXXFLAGS='-g -O3 -pipe -march=native'
+CFLAGS='-g -O3 -pipe -fno-plt -march=native'
+CXXFLAGS='-g -O3 -pipe -fno-plt -march=native'
 
-#
-# SET THE AVAILABLE CPU COUNT FOR PARALLEL PROCESSING (SPEEDS UP THE BUILD PROCESS)
-#
+# Set the available cpu count for parallel processing (speeds up the build process)
 
 if [ -f /proc/cpuinfo ]; then
     cpu_threads="$(grep --count ^processor /proc/cpuinfo)"
@@ -66,9 +56,9 @@ fi
 
 PATH="\
 /usr/lib/ccache:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
+$HOME/perl5/bin:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -97,12 +87,9 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
-#
-# CREATE FUNCTIONS
-#
+# Create functions
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n%s\n\n"                                    \
         'The script has completed'                                \
         'Make sure to star this repository to show your support!' \
@@ -110,8 +97,7 @@ exit_fn()
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n\n%s\n\n%s\n\n%s\n\n"      \
         "$1"                           \
         'To report a bug please visit: ' \
@@ -119,8 +105,7 @@ fail_fn()
     exit 1
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local choice
 
     printf "%s\n\n%s\n%s\n\n"                    \
@@ -129,7 +114,7 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "${choice}" in
+    case "$choice" in
         1)      sudo rm -fr "$cwd";;
         2)      clear;;
         *)
@@ -143,18 +128,16 @@ cleanup_fn()
     esac
 }
 
-create_soft_link_fn()
-{
+create_soft_link_fn() {
     clear
     if [ -f "$install_prefix"/bin/clang++ ] && [ ! -f "$install_prefix"/bin/clang++-15 ]; then
         if ! sudo ln -s "$install_prefix"/bin/clang++ "$install_prefix"/bin/clang++-15; then
-            printf "\n%s\n\n" "Failed to create the clang++ soft link. Line: ${LINENO}"
+            printf "\n%s\n\n" "Failed to create the clang++ soft link. Line: $LINENO"
         fi
     fi
 }
 
-show_ver_fn()
-{
+show_ver_fn() {
     printf "%s\n\n" 'The installed clang version is:'
 
     if [ -f "$install_prefix"/bin/clang-15 ]; then
@@ -174,25 +157,23 @@ show_ver_fn()
     fi
 }
 
-execute()
-{
-    echo "$ ${*}"
+execute() {
+    echo "$ $*"
 
-    if [ "${debug}" = 'ON' ]; then
+    if [ "$debug" = 'ON' ]; then
         if ! output="$("$@")"; then
-            notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
-            fail_fn "Failed to execute: ${*}"
+            notify-send -t 5000 "Failed to execute: $*" 2>/dev/null
+            fail_fn "Failed to execute: $*"
         fi
     else
         if ! output="$("$@" 2>&1)"; then
-            notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
-            fail_fn "Failed to execute: ${*}"
+            notify-send -t 5000 "Failed to execute: $*" 2>/dev/null
+            fail_fn "Failed to execute: $*"
         fi
     fi
 }
 
-build()
-{
+build() {
     printf "\n%s\n%s\n" \
         "Building $1 - version $2" \
         '=========================================='
@@ -208,31 +189,30 @@ build()
 
 build_done() { echo "$2" > "$cwd/$1.done"; }
 
-download()
-{
+download() {
     dl_path="$cwd"
     dl_url="$1"
-    dl_file="${2:-"${1##*/}"}"
+    dl_file="$2:-"${1##*/"}"
 
     if [[ "$dl_file" =~ tar. ]]; then
-        output_dir="${dl_file%.*}"
-        output_dir="${3:-"${output_dir%.*}"}"
+        output_dir="$dl_file%.*"
+        output_dir="$3:-"${output_dir%.*"}"
     else
-        output_dir="${3:-"${dl_file%.*}"}"
+        output_dir="$3:-"${dl_file%.*"}"
     fi
 
     target_file="$dl_path/$dl_file"
     target_dir="$dl_path/$output_dir"
 
-    if [ -f "${target_file}" ]; then
+    if [ -f "$target_file" ]; then
         echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
-        if ! wget --show-progress -t 2 -cqO "${target_file}" "${dl_url}"; then
+        echo "Downloading \"$dl_url\" saving as \"$dl_file\""
+        if ! wget --show-progress -t 2 -cqO "$target_file" "$dl_url"; then
             printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! wget --show-progress -t 2 -cqO "${target_file}" "${dl_url}"; then
-                fail_fn "The script failed to download \"$dl_file\" twice and will now exit. Line: ${LINENO}"
+            if ! wget --show-progress -t 2 -cqO "$target_file" "$dl_url"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit. Line: $LINENO"
             fi
         fi
         printf "\n%s\n\n" 'Download completed'
@@ -245,54 +225,50 @@ download()
     mkdir -p "$target_dir"
 
     if [ -n "$3" ]; then
-        if ! tar -xf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
-            sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
+        if ! tar -xf "$target_file" -C "$target_dir" 2>/dev/null >/dev/null; then
+            sudo rm "$target_file"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: $LINENO"
         fi
     else
-        if ! tar -xf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
-            sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
+        if ! tar -xf "$target_file" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
+            sudo rm "$target_file"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: $LINENO"
         fi
     fi
 
     printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: $LINENO"
 }
 
-git_1_fn()
-{
+git_1_fn() {
     local curl_cmd github_repo github_url
 
     github_repo="$1"
     github_url="$2"
 
-    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/$github_repo/$github_url")"; then
         g_ver="$(echo "$curl_cmd" | jq -r '.[1].name' 2>/dev/null)"
         g_url="$(echo "$curl_cmd" | jq -r '.[1].tarball_url' 2>/dev/null)"
-        g_ver="${g_ver#llvmorg-}"
+        g_ver="$g_ver#Llvmorg-"
     fi
 }
 
-git_ver_fn()
-{
+git_ver_fn() {
     local t_flag v_flag v_url
 
     v_url="$1"
     v_flag="$2"
 
-    case "${v_flag}" in
+    case "$v_flag" in
             R)      t_flag=releases;;
             T)      t_flag=tags;;
     esac
 
-    git_1_fn "${v_url}" "${t_flag}" 2>/dev/null
+    git_1_fn "$v_url" "$t_flag" 2>/dev/null
 }
 
-#
-# PRINT THE OPTIONS AVAILABLE WHEN MANUALLY RUNNING THE SCRIPT
-#
+# Print the options available when manually running the script
 
 pkgs=(autoconf autoconf-archive automake autopoint binutils binutils-dev bison
       build-essential ccache clang cmake curl jq libc6 libc6-dev libedit-dev
@@ -300,10 +276,10 @@ pkgs=(autoconf autoconf-archive automake autopoint binutils binutils-dev bison
 
 for i in ${pkgs[@]}
 do
-    missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
+    missing_pkg="$(sudo dpkg -l | grep -o "$i")"
 
-    if [ -z "${missing_pkg}" ]; then
-        missing_pkgs+=" ${i}"
+    if [ -z "$missing_pkg" ]; then
+        missing_pkgs+=" $i"
     fi
 done
 
@@ -314,83 +290,78 @@ else
     printf "%s\n" 'The APT packages are already installed'
 fi
 
-#
-# REFRESH LIBRARYS
-#
+# Refresh librarys
 
 sudo ldconfig 2>/dev/null
 
-#
-# BEGIN BUILDING CLANG
-#
+# Begin building clang
 
 clear
-box_out_banner()
-{
+box_out_banner() {
     input_char=$(echo "$@" | wc -c)
-    line=$(for i in $(seq 0 ${input_char}); do printf '-'; done)
+    line=$(for i in $(seq 0 $input_char); do printf '-'; done)
     tput bold
     line="$(tput setaf 3)$line"
-    space=${line//-/ }
+    space=$line//-/ 
     echo " $line"
-    printf '|' ; echo -n "${space}" ; printf "%s\n" '|';
+    printf '|' ; echo -n "$space" ; printf "%s\n" '|';
     printf '| ' ;tput setaf 4; echo -n "$@"; tput setaf 3 ; printf "%s\n" ' |';
-    printf '|' ; echo -n "${space}" ; printf "%s\n" '|';
+    printf '|' ; echo -n "$space" ; printf "%s\n" '|';
     echo " $line"
     tput sgr 0
 }
-box_out_banner "Clang Build Script - version ${script_ver}"
+box_out_banner "Clang Build Script - version $script_ver"
 
 if build 'llvm' '15.0.7'; then
     download 'https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.7/llvm-project-15.0.7.src.tar.xz' 'llvm-15.0.7.tar.gz'
     project_pkgs='clang;clang-tools-extra'
     runtime_pkgs='libcxx;libcxxabi;libunwind;compiler-rt'
-    cmake -S llvm -B build                           \
+    cmake -S llvm -B build \
           -DCMAKE_INSTALL_PREFIX="$install_prefix" \
-          -DCMAKE_BUILD_TYPE=Release                 \
-          -DBUILD_SHARED_LIBS=OFF                    \
-          -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON       \
-          -DBENCHMARK_ENABLE_TESTING=ON              \
-          -DBENCHMARK_INSTALL_DOCS=OFF               \
-          -DCLANG_INCLUDE_DOCS=OFF                   \
-          -DCMAKE_C_COMPILER="${CC}"                 \
-          -DCMAKE_C_FLAGS="${CFLAGS}"                \
-          -DCMAKE_CXX_COMPILER="${CXX}"              \
-          -DCMAKE_CXX_STANDARD=17                    \
-          -DLLVM_BUILD_BENCHMARKS=OFF                \
-          -DLLVM_BUILD_RUNTIME=ON                    \
-          -DLLVM_BUILD_RUNTIMES=ON                   \
-          -DLLVM_CCACHE_BUILD=ON                     \
-          -DLLVM_ENABLE_CURL=ON                      \
-          -DLLVM_ENABLE_LTO=OFF                      \
-          -DLLVM_ENABLE_OCAMLDOC=OFF                 \
-          -DLLVM_ENABLE_PIC=ON                       \
-          -DLLVM_ENABLE_PROJECTS="${project_pkgs}"   \
-          -DLLVM_ENABLE_RUNTIMES="${runtime_pkgs}"   \
-          -DLLVM_ENABLE_WARNINGS=OFF                 \
-          -DLLVM_HOST_TRIPLE="${pc_type}"            \
-          -DLLVM_INCLUDE_DOCS=OFF                    \
-          -DLLVM_INCLUDE_EXAMPLES=OFF                \
-          -DLLVM_INCLUDE_TESTS=OFF                   \
-          -DLLVM_TARGET_ARCH=HOST                    \
-          -DLLVM_TOOL_CLANG_BUILD=ON                 \
+          -DCMAKE_BUILD_TYPE=Release \
+          -DBUILD_SHARED_LIBS=OFF \
+          -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON \
+          -DBENCHMARK_ENABLE_TESTING=ON \
+          -DBENCHMARK_INSTALL_DOCS=OFF \
+          -DCLANG_INCLUDE_DOCS=OFF \
+          -DCMAKE_C_COMPILER="$CC" \
+          -DCMAKE_C_FLAGS="$CFLAGS" \
+          -DCMAKE_CXX_COMPILER="$CXX" \
+          -DCMAKE_CXX_STANDARD=17 \
+          -DLLVM_BUILD_BENCHMARKS=OFF \
+          -DLLVM_BUILD_RUNTIME=ON \
+          -DLLVM_BUILD_RUNTIMES=ON \
+          -DLLVM_CCACHE_BUILD=ON \
+          -DLLVM_ENABLE_CURL=ON \
+          -DLLVM_ENABLE_LTO=OFF \
+          -DLLVM_ENABLE_OCAMLDOC=OFF \
+          -DLLVM_ENABLE_PIC=ON \
+          -DLLVM_ENABLE_PROJECTS="$project_pkgs" \
+          -DLLVM_ENABLE_RUNTIMES="$runtime_pkgs" \
+          -DLLVM_ENABLE_WARNINGS=OFF \
+          -DLLVM_HOST_TRIPLE="$pc_type" \
+          -DLLVM_INCLUDE_DOCS=OFF \
+          -DLLVM_INCLUDE_EXAMPLES=OFF \
+          -DLLVM_INCLUDE_TESTS=OFF \
+          -DLLVM_TARGET_ARCH=HOST \
+          -DLLVM_TOOL_CLANG_BUILD=ON \
           -G Ninja -Wno-dev
     echo
-    ninja "-j${cpu_threads}" -C build
-    execute sudo ninja "-j${cpu_threads}" -C build install
+    ninja "-j$cpu_threads" -C build
+    execute sudo ninja "-j$cpu_threads" -C build install
 fi
 
-# LDCONFIG MUST BE RUN NEXT IN ORDER TO UPDATE FILE CHANGES OR THE MAGICK COMMAND WILL NOT WORK
+# Ldconfig must be run next in order to update file changes or the magick command will not work
 sudo ldconfig 2>/dev/null
 
-# CREATE A SOFT LINK FROM CLANG++ TO CLANG++-15
+# Create a soft link from clang++ to clang++-15
 create_soft_link_fn
 
-# SHOW THE NEWLY INSTALLED MAGICK VERSION
+# Show the newly installed magick version
 show_ver_fn
 
-# PROMPT THE USER TO CLEAN UP THE BUILD FILES
+# Prompt the user to clean up the build files
 cleanup_fn
 
-# SHOW EXIT MESSAGE
+# Show exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GitHub Projects/build-clang-16 b/Bash/Installer Scripts/GitHub Projects/build-clang-16
--- a/Bash/Installer Scripts/GitHub Projects/build-clang-16
+++ b/Bash/Installer Scripts/GitHub Projects/build-clang-16
@@ -1,21 +1,19 @@
-#!/usr/bin/env bash
-# shellcheck disable=SC2162,SC2317
+#!/Usr/bin/env bash
+# Shellcheck disable=sc2162,sc2317
 
-##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-clang-16
-##  Purpose: Build LLVM-16
+##  Github script: https://github.com/slyfox1186/script-repo/blob/main/bash/installer%20scripts/github%20projects/build-clang-16
+##  Purpose: build llvm-16
 ##  Updated: 01.30.24
 ##  Script version: 1.3
 
 clear
 
 if [ "$EUID" -ne 0 ]; then
-    printf "%s\n\n" "You must run this script with root/sudo."
+    echo "You must run this script with root or sudo."
     exit 1
 fi
 
-#
-# SET GLOBAL VARIABLES
-#
+# Set global variables
 
 script_ver="1.3"
 progname="$0"
@@ -23,27 +21,26 @@ cwd="$PWD/clang-16-build-script"
 install_prefix="/usr/local"
 pc_type="x86_64-linux-gnu"
 web_repo="https://github.com/slyfox1186/script-repo"
-debug="OFF" # CHANGE THIS VARIABLE TO "ON" FOR HELP WITH TROUBLESHOOTING UNEXPECTED ISSUES DURING THE BUILD
+debug="OFF" # Change this variable to "on" for help with troubleshooting unexpected issues during the build
 
-# CREATE OUTPUT DIRECTORIES
+# Create output directories
 mkdir -p "$cwd"
 
-# FIGURE OUT WHICH COMPILERS TO USE
+# Figure out which compilers to use
 export CC="clang" CXX="clang++"
 
-# SET COMPILER OPTIMIZATION FLAGS
+# Set compiler optimization flags
 export CXXFLAGS="$CFLAGS"
 
-# SET THE AVAILABLE CPU COUNT FOR PARALLEL PROCESSING (SPEEDS UP THE BUILD PROCESS)
+# Set the available cpu count for parallel processing (speeds up the build process)
 cpu_threads="$(grep --count ^processor /proc/cpuinfo 2>/dev/null || nproc --all)"
 
 export PATH="/usr/lib/ccache:$HOME/perl5/bin:$HOME/.cargo/bin:$HOME/.local/bin:/usr/local/sbin:/usr/local/cuda/bin:/usr/local/x86_64-linux-gnu/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/snap/bin"
 
 export PKG_CONFIG_PATH="/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/share/pkgconfig:/usr/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:/lib64/pkgconfig:/lib/pkgconfig"
 
-# CREATE FUNCTIONS
-exit_fn()
-{
+# Create functions
+exit_fn() {
     printf "\n%s\n\n%s\n%s\n\n" \
         "The script has completed" \
         "Make sure to star this repository to show your support!" \
@@ -51,8 +48,7 @@ exit_fn()
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n\n%s\n\n%s\n\n%s\n\n" \
         "$1" \
         "To report a bug please visit: " \
@@ -60,8 +56,7 @@ fail_fn()
     exit 1
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local choice
 
     printf "%s\n\n%s\n%s\n\n" \
@@ -70,7 +65,7 @@ cleanup_fn()
         "[2] No"
     read -p "Your choices are (1 or 2): " choice
 
-    case "${choice}" in
+    case "$choice" in
         1)      sudo rm -fr "$cwd";;
         2)      clear;;
         *)
@@ -84,18 +79,16 @@ cleanup_fn()
     esac
 }
 
-create_soft_link_fn()
-{
+create_soft_link_fn() {
     clear
     if [ -f "$install_prefix"/bin/clang++ ] && [ ! -f "$install_prefix"/bin/clang++-16 ]; then
         if ! sudo ln -s "$install_prefix"/bin/clang++ "$install_prefix"/bin/clang++-16; then
-            printf "\n%s\n\n" "Failed to create the clang++ soft link. Line: ${LINENO}"
+            printf "\n%s\n\n" "Failed to create the clang++ soft link. Line: $LINENO"
         fi
     fi
 }
 
-show_ver_fn()
-{
+show_ver_fn() {
     printf "%s\n\n" "The installed clang version is:"
 
     if [ -f "$install_prefix"/bin/clang-16 ]; then
@@ -115,25 +108,23 @@ show_ver_fn()
     fi
 }
 
-execute()
-{
-    echo "$ ${*}"
+execute() {
+    echo "$ $*"
 
-    if [ "${debug}" = "ON" ]; then
+    if [ "$debug" = "ON" ]; then
         if ! output="$("$@")"; then
-            notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
-            fail_fn "Failed to execute: ${*}"
+            notify-send -t 5000 "Failed to execute: $*" 2>/dev/null
+            fail_fn "Failed to execute: $*"
         fi
     else
         if ! output="$("$@" 2>&1)"; then
-            notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
-            fail_fn "Failed to execute: ${*}"
+            notify-send -t 5000 "Failed to execute: $*" 2>/dev/null
+            fail_fn "Failed to execute: $*"
         fi
     fi
 }
 
-build()
-{
+build() {
     printf "\n%s\n%s\n" \
         "Building $1 - version $2" \
         "=========================================="
@@ -149,31 +140,30 @@ build()
 
 build_done() { echo "$2" > "$cwd/$1.done"; }
 
-download()
-{
+download() {
     dl_path="$cwd"
     dl_url="$1"
-    dl_file="${2:-"${1##*/}"}"
+    dl_file="$2:-"${1##*/"}"
 
     if [[ "$dl_file" =~ tar. ]]; then
-        output_dir="${dl_file%.*}"
-        output_dir="${3:-"${output_dir%.*}"}"
+        output_dir="$dl_file%.*"
+        output_dir="$3:-"${output_dir%.*"}"
     else
-        output_dir="${3:-"${dl_file%.*}"}"
+        output_dir="$3:-"${dl_file%.*"}"
     fi
 
     target_file="$dl_path/$dl_file"
     target_dir="$dl_path/$output_dir"
 
-    if [ -f "${target_file}" ]; then
+    if [ -f "$target_file" ]; then
         echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
-        if ! wget --show-progress -t 2 -cqO "${target_file}" "${dl_url}"; then
+        echo "Downloading \"$dl_url\" saving as \"$dl_file\""
+        if ! wget --show-progress -t 2 -cqO "$target_file" "$dl_url"; then
             printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! wget --show-progress -t 2 -cqO "${target_file}" "${dl_url}"; then
-                fail_fn "The script failed to download \"$dl_file\" twice and will now exit. Line: ${LINENO}"
+            if ! wget --show-progress -t 2 -cqO "$target_file" "$dl_url"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit. Line: $LINENO"
             fi
         fi
         printf "\n%s\n\n" "Download completed"
@@ -186,54 +176,50 @@ download()
     mkdir -p "$target_dir"
 
     if [ -n "$3" ]; then
-        if ! tar -zxf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
-            sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
+        if ! tar -zxf "$target_file" -C "$target_dir" 2>/dev/null >/dev/null; then
+            sudo rm "$target_file"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: $LINENO"
         fi
     else
-        if ! tar -zxf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
-            sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
+        if ! tar -zxf "$target_file" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
+            sudo rm "$target_file"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: $LINENO"
         fi
     fi
 
     printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: $LINENO"
 }
 
-git_1_fn()
-{
+git_1_fn() {
     local curl_cmd github_repo github_url
 
     github_repo="$1"
     github_url="$2"
 
-    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/$github_repo/$github_url")"; then
         g_ver="$(echo "$curl_cmd" | jq -r ".[1].name" 2>/dev/null)"
         g_url="$(echo "$curl_cmd" | jq -r ".[1].tarball_url" 2>/dev/null)"
-        g_ver="${g_ver#llvmorg-}"
+        g_ver="$g_ver#Llvmorg-"
     fi
 }
 
-git_ver_fn()
-{
+git_ver_fn() {
     local t_flag v_flag v_url
 
     v_url="$1"
     v_flag="$2"
 
-    case "${v_flag}" in
+    case "$v_flag" in
             R)      t_flag=releases;;
             T)      t_flag=tags;;
     esac
 
-    git_1_fn "${v_url}" "${t_flag}" 2>/dev/null
+    git_1_fn "$v_url" "$t_flag" 2>/dev/null
 }
 
-#
-# PRINT THE OPTIONS AVAILABLE WHEN MANUALLY RUNNING THE SCRIPT
-#
+# Print the options available when manually running the script
 
 pkgs=(
     autoconf autoconf-archive automake autopoint binutils binutils-dev bison
@@ -243,10 +229,10 @@ pkgs=(
 
 for i in ${pkgs[@]}
 do
-    missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
+    missing_pkg="$(sudo dpkg -l | grep -o "$i")"
 
-    if [ -z "${missing_pkg}" ]; then
-        missing_pkgs+=" ${i}"
+    if [ -z "$missing_pkg" ]; then
+        missing_pkgs+=" $i"
     fi
 done
 
@@ -257,32 +243,27 @@ else
     printf "%s\n" "The APT packages are already installed"
 fi
 
-#
-# REFRESH LIBRARYS
-#
+# Refresh librarys
 
 sudo ldconfig 2>/dev/null
 
-#
-# BEGIN BUILDING CLANG
-#
+# Begin building clang
 
 clear
-box_out_banner()
-{
+box_out_banner() {
     input_char=$(echo "$@" | wc -c)
-    line=$(for i in $(seq 0 ${input_char}); do printf "-"; done)
+    line=$(for i in $(seq 0 $input_char); do printf "-"; done)
     tput bold
     line="$(tput setaf 3)$line"
-    space=${line//-/ }
+    space=$line//-/ 
     echo " $line"
-    printf "|" ; echo -n "${space}" ; printf "%s\n" "|";
+    printf "|" ; echo -n "$space" ; printf "%s\n" "|";
     printf "| " ;tput setaf 4; echo -n "$@"; tput setaf 3 ; printf "%s\n" " |";
-    printf "|" ; echo -n "${space}" ; printf "%s\n" "|";
+    printf "|" ; echo -n "$space" ; printf "%s\n" "|";
     echo " $line"
     tput sgr 0
 }
-box_out_banner "Clang Build Script - version ${script_ver}"
+box_out_banner "Clang Build Script - version $script_ver"
 
 if build "llvm" "16.0.6"; then
     download "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/llvm-project-16.0.6.src.tar.xz" "llvm-16.0.6.tar.gz"
@@ -321,17 +302,17 @@ if build "llvm" "16.0.6"; then
     execute sudo ninja -C build install
 fi
 
-# LDCONFIG MUST BE RUN NEXT IN ORDER TO UPDATE FILE CHANGES OR THE MAGICK COMMAND WILL NOT WORK
+# Ldconfig must be run next in order to update file changes or the magick command will not work
 sudo ldconfig 2>/dev/null
 
-# CREATE A SOFT LINK FROM CLANG++ TO CLANG++-16
+# Create a soft link from clang++ to clang++-16
 create_soft_link_fn
 
-# SHOW THE NEWLY INSTALLED MAGICK VERSION
+# Show the newly installed magick version
 show_ver_fn
 
-# PROMPT THE USER TO CLEAN UP THE BUILD FILES
+# Prompt the user to clean up the build files
 cleanup_fn
 
-# SHOW EXIT MESSAGE
+# Show exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GitHub Projects/build-mainline b/Bash/Installer Scripts/GitHub Projects/build-mainline
--- a/Bash/Installer Scripts/GitHub Projects/build-mainline
+++ b/Bash/Installer Scripts/GitHub Projects/build-mainline
@@ -1,13 +1,13 @@
-#!/usr/bin/env bash
-# shellcheck disable=SC2162,SC2317
+#!/Usr/bin/env bash
+# Shellcheck disable=sc2162,sc2317
 
 #############################################################################
 ##
-##  Install Mainline from source code
+##  Install mainline from source code
 ##
-##  Script: https://github.com/slyfox1186/script-repo/edit/main/Bash/Installer%20Scripts/GitHub%20Projects/build-mainline
+##  Script: https://github.com/slyfox1186/script-repo/edit/main/bash/installer%20scripts/github%20projects/build-mainline
 ##
-##  GitHub Repo: https://github.com/bkw777/mainline/tree/master
+##  Github repo: https://github.com/bkw777/mainline/tree/master
 ## 
 ##  Updated: 10.03.23
 ##
@@ -17,58 +17,46 @@
 
 clear
 
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+if [ "$EUID" -eq '0' ]; then
+    echo "You must run this script without root or sudo."
     exit 1
 fi
 
-#
-# SET VARIABLES
-#
+# Set variables
 
 script_ver=1.0
 parent_dir="$PWD"
-cwd="${parent_dir}"/mainline-build-script
+cwd="$parent_dir"/mainline-build-script
 web_repo=https://github.com/slyfox1186/script-repo
 
 printf "%s\n%s\n\n" \
-    "OpenSSL Build Script - v${script_ver}" \
+    "OpenSSL Build Script - v$script_ver" \
     '==============================================='
 
-#
-# CREATE OUTPUT DIRECTORY
-#
+# Create output directory
 
 if [ ! -d "$cwd" ]; then
     mkdir -p "$cwd"
 fi
 
-#
-# SET THE C+CPP COMPILERS
-#
+# Set the c+cpp compilers
 
 export CC=gcc CXX=g++
 
-#
-# EXPORT COMPILER OPTIMIZATION FLAGS
-#
+# Export compiler optimization flags
 
-export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -march=native'
+export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -fno-plt -march=native'
 
-#
-# CREATE FUNCTIONS
-#
+# Create functions
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
         "$web_repo"
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n\n%s\n\n%s\n\n%s\n\n" \
         "$1" \
         'To report a bug please create an issue at:' \
@@ -76,8 +64,7 @@ fail_fn()
     exit 1
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local choice
 
     printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
@@ -88,10 +75,10 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "${choice}" in
+    case "$choice" in
         1)
                 sudo rm -fr "$cwd"
-                cd "${parent_dir}" || exit 1
+                cd "$parent_dir" || exit 1
                 if [ -f "$pem_file" ]; then
                     sudo rm "$pem_file"
                 fi
@@ -108,9 +95,7 @@ cleanup_fn()
     esac
 }
 
-#
-# INSTALL REQUIRED APT PACKAGES
-#
+# Install required apt packages
 
 pkgs=(autoconf autoconf-archive autogen automake build-essential curl
       libtool libtool-bin git-all libgee-0.8-dev libvte-2.91-dev m4
@@ -118,10 +103,10 @@ pkgs=(autoconf autoconf-archive autogen automake build-essential curl
 
 for i in ${pkgs[@]}
 do
-    missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
+    missing_pkg="$(sudo dpkg -l | grep -o "$i")"
 
-    if [ -z "${missing_pkg}" ]; then
-        missing_pkgs+=" ${i}"
+    if [ -z "$missing_pkg" ]; then
+        missing_pkgs+=" $i"
     fi
 done
 
@@ -131,7 +116,7 @@ if [ -n "$missing_pkgs" ]; then
 fi
 unset i missing_pkgs
 
-# CREATE ARCHIVE OUTPUT FOLDER OR CLEAN EXISTING
+# Create archive output folder or clean existing
 if [ ! -d mainline ]; then
     git clone https://github.com/bkw777/mainline.git
 fi
@@ -141,18 +126,18 @@ cd mainline || exit 1
 ls -1A --color --group-directories-first
 echo
 
-# INSTALL MAINLINE
+# Install mainline
 make distclean
 if ! make "-j$(nproc --all)"; then
-    fail_fn "The command \"make -j$(nproc --all)\" failed. Line: ${LINENO}"
+    fail_fn "The command \"make -j$(nproc --all)\" failed. Line: $LINENO"
 fi
 
 if sudo make "-j$(nproc --all)" install; then
-    fail_fn "The command \"sudo make -j$(nproc --all) install\" failed. Line: ${LINENO}"
+    fail_fn "The command \"sudo make -j$(nproc --all) install\" failed. Line: $LINENO"
 fi
 
-# PROMPT USER TO CLEAN UP FILES
+# Prompt user to clean up files
 cleanup_fn
 
-# SHOW EXIT MESSAGE
+# Show exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GitHub Projects/build-openssl-sts b/Bash/Installer Scripts/GitHub Projects/build-openssl-sts
--- a/Bash/Installer Scripts/GitHub Projects/build-openssl-sts
+++ b/Bash/Installer Scripts/GitHub Projects/build-openssl-sts
@@ -1,36 +1,34 @@
-#!/usr/bin/env bash
-# shellcheck source=/dev/null disable=SC1003,SC2068,SC2086,SC2162
+#!/Usr/bin/env bash
+# Shellcheck source=/dev/null disable=sc1003,sc2068,sc2086,sc2162
 
 ####################################################################################
 ##
 ##  Purpose:
-##          - Install OpenSSL (Short Term Support) from the source code.
+##          - Install openssl (short term support) from the source code.
 ##
 ##  Script:
 ##          - Updated: 11.28.23
 ##          - Version: 1.3
 ##
-##  OpenSSL:
+##  Openssl:
 ##          - Version: 1.1.1w
 ##
 ####################################################################################
 
 clear
 
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+if [ "$EUID" -eq '0' ]; then
+    echo "You must run this script without root or sudo."
     exit 1
 fi
 
-#
-# SET VARIABLES
-#
+# Set variables
 
 script_ver=1.3
 archive_dir=openssl-1.1.1w
 archive_url=https://www.openssl.org/source/"$archive_dir".tar.gz
-archive_ext="${archive_url//*.}"
-archive_name="$archive_dir.tar.${archive_ext}"
+archive_ext="$archive_url//*."
+archive_name="$archive_dir.tar.$archive_ext"
 cwd="$PWD"/openssl-build-script
 install_dir=/usr/local
 ssl_dir="$install_dir"
@@ -39,56 +37,48 @@ user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Geck
 web_repo=https://github.com/slyfox1186/script-repo
 
 printf "%s\n%s\n\n"                              \
-    "OpenSSL Lite Build Script - v${script_ver}" \
+    "OpenSSL Lite Build Script - v$script_ver" \
     '==============================================='
 
-#
-# TEST THE OS AND ITS VERSION
-#
+# Test the os and its version
 
 find_lsb_release="$(sudo find /usr/bin/ -type f -name 'lsb_release')"
 
 if [ -f '/etc/os-release' ]; then
     source '/etc/os-release'
     OS_TMP="$NAME"
-    OS="$(echo "${OS_TMP}" | awk '{print $1}')"
-elif [ -n "${find_lsb_release}" ]; then
+    OS="$(echo "$OS_TMP" | awk '{print $1}')"
+elif [ -n "$find_lsb_release" ]; then
     OS="$(lsb_release -d | awk '{print $2}')"
 else
-    fail_fn "Failed to define the \$OS and/or \$VER variables. Line: ${LINENO}"
+    fail_fn "Failed to define the \$OS and/or \$VER variables. Line: $LINENO"
 fi
 
-#
-# CREATE OUTPUT DIRECTORY
-#
+# Create output directory
 
 if [ -d "$cwd" ]; then
     sudo rm -fr "$cwd"
 fi
 mkdir -p "$cwd"
 
-#
-# SET THE CC/CXX COMPILERS & THE COMPILER OPTIMIZATION FLAGS
-#
+# Set the cc/cxx compilers & the compiler optimization flags
 
 CC=gcc
 CXX=g++
-CFLAGS="-D_REENTRANT -m64 -DL_ENDIAN -O3 -fPIC -pipe -march=native"
-CXXFLAGS="${CFLAGS}"
+CFLAGS="-D_REENTRANT -m64 -DL_ENDIAN -O3 -fPIC -pipe -fno-plt -march=native"
+CXXFLAGS="$CFLAGS"
 CPPFLAGS='-I/usr/local/include -I/usr/include'
 LDFLAGS="-Wl,-rpath=/usr/local/lib -Wl,--enable-new-dtags -ldl -L/usr/local/lib64"
 LDFLAGS+=' -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib64 -L/usr/lib -L/lib64 -L/lib'
 export CC CXX CFLAGS CPPFLAGS CXXFLAGS LDFLAGS
 
-#
-# SET THE PATH VARIABLE
-#
+# Set the path variable
 
 PATH="\
 /usr/lib/ccache:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
+$HOME/perl5/bin:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -103,9 +93,7 @@ ${HOME}/.local/bin:\
 "
 export PATH
 
-#
-# SET THE PKG_CONFIG_PATH VARIABLE
-#
+# Set the pkg_config_path variable
 
 PKG_CONFIG_PATH="\
 /usr/share/pkgconfig:\
@@ -124,20 +112,16 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
-#
-# CREATE FUNCTIONS
-#
+# Create functions
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n\n"                                         \
         'Make sure to star this repository to show your support!' \
         "$web_repo"
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n\n%s\n\n%s\n\n%s\n\n"                  \
         "$1"                                       \
         'To report a bug please create an issue at:' \
@@ -145,8 +129,7 @@ fail_fn()
     exit 1
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local choice
 
     printf "\n%s\n%s\n%s\n\n%s\n%s\n\n"                \
@@ -157,7 +140,7 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "${choice}" in
+    case "$choice" in
         1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
@@ -168,16 +151,14 @@ cleanup_fn()
     esac
 }
 
-display_stats_fn()
-{
+display_stats_fn() {
     sudo ldconfig
     clear
     printf "%s\n\n" 'OpenSSL'\''s version output is listed below.'
     "$(type -P openssl)" version -a
 }
 
-pacman_pkgs_fn()
-{
+pacman_pkgs_fn() {
     local arch_pkgs missing_pkg missing_pkgs pkg
     clear
 
@@ -187,10 +168,10 @@ pacman_pkgs_fn()
 
     for pkg in ${arch_pkgs[@]}
     do
-        missing_pkg="$(sudo pacman -Qk | grep -o "${pkg}")"
+        missing_pkg="$(sudo pacman -Qk | grep -o "$pkg")"
 
-        if [ -z "${missing_pkg}" ]; then
-            missing_pkgs+=" ${pkg}"
+        if [ -z "$missing_pkg" ]; then
+            missing_pkgs+=" $pkg"
         fi
     done
 
@@ -199,8 +180,7 @@ pacman_pkgs_fn()
     fi
 }
 
-apt_pkgs_fn()
-{
+apt_pkgs_fn() {
     local arch_pkgs missing_pkg missing_pkgs pkg
     clear
 
@@ -211,10 +191,10 @@ apt_pkgs_fn()
 
     for pkg in ${pkgs[@]}
     do
-        missing_pkg="$(sudo dpkg -l | grep -o "${pkg}")"
+        missing_pkg="$(sudo dpkg -l | grep -o "$pkg")"
 
-        if [ -z "${missing_pkg}" ]; then
-            missing_pkgs+=" ${pkg}"
+        if [ -z "$missing_pkg" ]; then
+            missing_pkgs+=" $pkg"
         fi
     done
 
@@ -223,49 +203,39 @@ apt_pkgs_fn()
     fi
 }
 
-#
-# INSTALL THE REQUIRED PACKAGE MANAGER PACKAGES
-#
+# Install the required package manager packages
 
-case "${OS}" in
+case "$OS" in
     Arch)   pacman_pkgs_fn;;
     *)      apt_pkgs_fn;;
 esac
 clear
 
-#
-# DOWNLOAD THE ARCHIVE FILE
-#
+# Download the archive file
 
-if [ ! -f "$cwd/${archive_name}" ]; then
-    wget -U "$user_agent" -cqO "$cwd/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/$archive_name" ]; then
+    wget -U "$user_agent" -cqO "$cwd/$archive_name" "$archive_url"
 fi
 
-#
-# CREATE OUTPUT DIRECTORY
-#
+# Create output directory
 
 if [ -d "$cwd/$archive_dir" ]; then
     sudo rm -fr "$cwd/$archive_dir"
 fi
 mkdir -p "$cwd/$archive_dir/build"
 
-#
-# EXTRACT ARCHIVE FILES
-#
+# Extract archive files
 
-if ! tar -zxf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
-    fail_fn "Failed to extract: $cwd/${archive_name}"
+if ! tar -zxf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
+    fail_fn "Failed to extract: $cwd/$archive_name"
 fi
 
-#
-# BUILD PROGRAM FROM SOURCE
-#
+# Build program from source
 
 cd "$cwd/$archive_dir" || exit 1
 cd build || exit 1
 ../config --prefix="$install_dir"                 \
-          --openssldir="${ssl_dir}"                 \
+          --openssldir="$ssl_dir"                 \
           --release                                 \
           --with-zlib-include=/usr/include          \
           --with-zlib-lib=/usr/lib/x86_64-linux-gnu \
@@ -284,50 +254,48 @@ cd build || exit 1
           no-ssl2                                   \
           no-tests
  
-# MODIFY THE MAKEFILE USING SED TO ACTIVATE THE RPATH FEATURE OF OPENSSL
+# Modify the makefile using sed to activate the rpath feature of openssl
 
 sed -i 's/linux-x86_64/linux-x86_64-rpath/g' 'Makefile'
 
 echo
 if ! make "-j$(nproc --all)"; then
-    fail_fn "Failed to execute: make -j$(nproc --all). Line: ${LINENO}"
+    fail_fn "Failed to execute: make -j$(nproc --all). Line: $LINENO"
 fi
 
 echo
 if ! sudo make install_sw; then
-    fail_fn "Failed to execute: sudo make install_sw. Line: ${LINENO}"
+    fail_fn "Failed to execute: sudo make install_sw. Line: $LINENO"
 fi
 
-# IF UBUNTU IS THE CURRENT OS THEN YOU MUST CREATE A SOFT LINK FOR OPENSSL TO FUNCTION
-case "${OS}" in
+# If ubuntu is the current os then you must create a soft link for openssl to function
+case "$OS" in
     Ubuntu)     sudo ln -sf '/usr/lib64/libcrypto.so.3' "/lib/$install_dir/";;
 esac
 
-#
-# INSTALL CA CERTS FROM CURL'S OFFICIAL WEBSITE
-#
+# Install ca certs from curl's official website
 
 printf "\n%s\n%s\n\n"                             \
    'Install the latest cURL security certificate' \
    '==================================================='
 
-# CREATE CERTS DIRECTORY IF MISSING
-if [ ! -d "${cert_dir}" ]; then
-    sudo mkdir -p "${cert_dir}"
+# Create certs directory if missing
+if [ ! -d "$cert_dir" ]; then
+    sudo mkdir -p "$cert_dir"
 fi
 
-# DOWNLOAD THE LATEST CACERT.PEM FILE FROM THE OFFICIAL CURL WEBSITE
+# Download the latest cacert.pem file from the official curl website
 if ! curl -A "$user_agent" -Lso "$cwd"/cacert.pem 'https://curl.se/ca/cacert.pem'; then
-    fail_fn "Failed to download the latest \"cacert.pem\" file. Line: ${LINENO}"
+    fail_fn "Failed to download the latest \"cacert.pem\" file. Line: $LINENO"
 fi
 
-# MOVE THE PEM FILE TO THE NEWLY CREATED CERTS DIRECTORY
-if ! sudo mv "$cwd"/cacert.pem "${cert_dir}"/cacert.pem; then
-    fail_fn "Failed to move file: $cwd/cacert.pem >> ${cert_dir}/cacert.pem. Line: ${LINENO}"
+# Move the pem file to the newly created certs directory
+if ! sudo mv "$cwd"/cacert.pem "$cert_dir"/cacert.pem; then
+    fail_fn "Failed to move file: $cwd/cacert.pem >> $cert_dir/cacert.pem. Line: $LINENO"
 fi
 
-# COPY THE PEM FILE AS A CRT FILE IN THE SPECIAL CA-CERTIFICATES FOLDER SO THE COMMAND WILL FIND AND USE IT WHEN IT IS EXECUTED
-if [[ "${OS}" == 'Arch' ]]; then
+# Copy the pem file as a crt file in the special ca-certificates folder so the command will find and use it when it is executed
+if [[ "$OS" == 'Arch' ]]; then
     if ! sudo pacman -Qk | grep -o 'ca-certificates-utils' &>/dev/null; then
         sudo pacman -Sq --needed --noconfirm ca-certificates-utils
     fi
@@ -337,7 +305,7 @@ if [[ "${OS}" == 'Arch' ]]; then
             exit 1
         fi
     fi
-    sudo cp -f "${cert_dir}"/cacert.pem '/usr/share/ca-certificates/trust-source/anchors/curl-cacert.crt'
+    sudo cp -f "$cert_dir"/cacert.pem '/usr/share/ca-certificates/trust-source/anchors/curl-cacert.crt'
     sudo ln -sf /etc/ssl/certs/* '/usr/share/ca-certificates/trust-source/anchors/'
     cd '/usr/share/ca-certificates/trust-source/anchors/' || exit 1
     sudo c_rehash .
@@ -352,7 +320,7 @@ else
             exit 1
         fi
     fi
-    sudo cp -f "${cert_dir}"/cacert.pem '/usr/local/share/ca-certificates/trust-source/anchors/curl-cacert.crt'
+    sudo cp -f "$cert_dir"/cacert.pem '/usr/local/share/ca-certificates/trust-source/anchors/curl-cacert.crt'
     sudo ln -sf /etc/ssl/certs/* '/usr/local/share/ca-certificates/trust-source/anchors/'
     cd '/usr/local/share/ca-certificates/trust-source/anchors/' || exit 1
     sudo c_rehash .
@@ -360,27 +328,27 @@ else
     sudo update-ca-certificates
 fi
 
-# RUN LDCONFIG TO UPDATE THE LINKER LIBRARY SEARCH PATH TO INCLUDE THE OPENSSL LIB64 DIRECTORY
+# Run ldconfig to update the linker library search path to include the openssl lib64 directory
 if ! curl -A "$user_agent" -Lso "$cwd/ld-linker-search-paths.sh" 'https://raw.githubusercontent.com/slyfox1186/script-repo/main/Bash/Misc/ld-linker-search-paths.sh'; then
-    printf "\n%s\n\n" "Failed to download: $cwd/ld-linker-search-paths.sh. Line: ${LINENO}"
+    printf "\n%s\n\n" "Failed to download: $cwd/ld-linker-search-paths.sh. Line: $LINENO"
     exit 1
 fi
 sudo bash "$cwd/ld-linker-search-paths.sh"
 
-# ADD THE NEW OPENSSL BIN TO THE USER'S ~/.bashrc FILE IF NOT ALREADY PRESENT
-if ! grep -o '/usr/local/ssl/bin' "${HOME}"/.bashrc &>/dev/null; then
-    if grep -o '/usr/local/sbin:\\' "${HOME}"/.bashrc &>/dev/null; then
-        sed -i '\/usr\/local\/sbin:\\/i \/usr\/local\/ssl\/bin:\\' "${HOME}"/.bashrc
+# Add the new openssl bin to the user's ~/.bashrc file if not already present
+if ! grep -o '/usr/local/ssl/bin' "$HOME"/.bashrc &>/dev/null; then
+    if grep -o '/usr/local/sbin:\\' "$HOME"/.bashrc &>/dev/null; then
+        sed -i '\/usr\/local\/sbin:\\/i \/usr\/local\/ssl\/bin:\\' "$HOME"/.bashrc
     else
-        sed -i 's/\/usr\/local\/sbin/\/usr\/local\/ssl\/bin:\/usr\/local\/sbin/g' "${HOME}"/.bashrc
+        sed -i 's/\/usr\/local\/sbin/\/usr\/local\/ssl\/bin:\/usr\/local\/sbin/g' "$HOME"/.bashrc
     fi
 fi
 
-# PROMPT USER TO CLEAN UP FILES
+# Prompt user to clean up files
 cleanup_fn
 
-# DISPLAY THE UPDATE OPENSSL STATS
+# Display the update openssl stats
 display_stats_fn
 
-# SHOW EXIT MESSAGE
+# Show exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GitHub Projects/build-openssl-v2 b/Bash/Installer Scripts/GitHub Projects/build-openssl-v2
--- a/Bash/Installer Scripts/GitHub Projects/build-openssl-v2
+++ b/Bash/Installer Scripts/GitHub Projects/build-openssl-v2
@@ -1,8 +1,8 @@
-#!/usr/bin/env bash
+#!/Usr/bin/env bash
 
-## GitHub: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-openssl-v2
-## Purpose: Build any version of OpenSSL. Defaults to the latest version 3.2.x
-## Features: Pass arguments to the script
+## Github: https://github.com/slyfox1186/script-repo/blob/main/bash/installer%20scripts/github%20projects/build-openssl-v2
+## Purpose: build any version of openssl. defaults to the latest version 3.2.x
+## Features: pass arguments to the script
 ## Updated: 03.12.24
 
 usage() {
@@ -18,7 +18,7 @@ usage() {
 }
 
 parse_arguments() {
-    while [[ $# -gt 0 ]]; do
+    while [[ $# -Gt 0 ]]; do
         case "$1" in
             -6|--enable-ipv6)
                 enable_ipv6=true
@@ -68,13 +68,13 @@ install_required_packages() {
 
     local -a missing_packages=()
     for pkg in "${pkgs[@]}"; do
-        if ! dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed"; then
+        if ! dpkg-query -W -f='$Status' "$pkg" 2>/dev/null | grep -q "ok installed"; then
             missing_packages+=("$pkg")
         fi
     done
 
-    if [[ "${#missing_packages[@]}" -gt 0 ]]; then
-        echo "Installing missing packages: ${missing_packages[*]}"
+    if [[ "${#Missing_packages[@]}" -gt 0 ]]; then
+        echo "Installing missing packages: $missing_packages[*]"
         apt install -y "${missing_packages[@]}"
         echo
     else
@@ -84,7 +84,7 @@ install_required_packages() {
 }
 
 set_compiler_flags() {
-    local common_flags="-g -O3 -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2"
+    local common_flags="-g -O3 -pipe -fno-plt -fstack-protector-strong -D_FORTIFY_SOURCE=2"
 
     export CC=clang
     export CXX=clang++
@@ -231,7 +231,7 @@ configure_openssl() {
 
 build_and_install_openssl() {
     echo "Compiling OpenSSL..."
-    make "-j${jobs:-$(nproc --all)}" || fail "Failed to execute: make -j${jobs:-$(nproc --all)}. Line: $LINENO"
+    make "-j$jobs:-$(nproc --all)" || fail "Failed to execute: make -j$jobs:-$(nproc --all). Line: $LINENO"
     echo
     echo "Installing OpenSSL..."
     make install_sw install_fips || fail "Failed to execute: make install_sw install_fips. Line: $LINENO"
@@ -241,8 +241,8 @@ build_and_install_openssl() {
 
 post_installation_tasks() {
     echo "Performing post-installation tasks..."
-    # Add any additional post-installation tasks here
-    # For example, generating OpenSSL certificates, setting up symlinks, etc.
+# Add any additional post-installation tasks here
+# For example, generating openssl certificates, setting up symlinks, etc.
     echo "Post-installation tasks completed."
     echo
 }
@@ -252,7 +252,7 @@ main() {
     local install_dir="/usr/local/ssl"
     local enable_ipv6=false
     local openssl_version
-    local tar_file="$cwd/openssl-${openssl_version}.tar.gz"
+    local tar_file="$cwd/openssl-$openssl_version.tar.gz"
     local src_dir
     local jobs
     local keep_build=false
@@ -270,10 +270,10 @@ main() {
             fail "Failed to detect the latest OpenSSL 3.2.x version. Line: $LINENO"
             exit 1
         fi
-        openssl_version=${openssl_version#openssl-}  # Remove the "openssl-" prefix
+        openssl_version=$openssl_version#Openssl-  # remove the "openssl-" prefix
     fi
 
-    install_dir=${install_dir:-/usr/local/ssl}
+    install_dir=$install_dir:-/usr/local/ssl
     src_dir="$cwd/$openssl_version"
 
     echo
diff --git a/Bash/Installer Scripts/GitHub Projects/build-yasm b/Bash/Installer Scripts/GitHub Projects/build-yasm
--- a/Bash/Installer Scripts/GitHub Projects/build-yasm
+++ b/Bash/Installer Scripts/GitHub Projects/build-yasm
@@ -1,8 +1,8 @@
 PATH="\
 /usr/lib/ccache:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
+$HOME/perl5/bin:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -15,14 +15,14 @@ ${HOME}/.local/bin:\
 /usr/games:\
 /snap/bin\
 "
-export PATH#!/usr/bin/env bash
-# shellcheck disable=SC2162,SC2317
+export PATH#!/Usr/bin/env bash
+# Shellcheck disable=sc2162,sc2317
 
 ###############################################################################################################################
 ##
-##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-yasm
+##  Github script: https://github.com/slyfox1186/script-repo/blob/main/bash/installer%20scripts/github%20projects/build-yasm
 ##
-##  Purpose: Build yasm
+##  Purpose: build yasm
 ##
 ##  Updated: 08.31.23
 ##
@@ -32,14 +32,12 @@ export PATH#!/usr/bin/env bash
 
 clear
 
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+if [ "$EUID" -eq '0' ]; then
+    echo "You must run this script without root or sudo."
     exit 1
 fi
 
-#
-# SET VARIABLES
-#
+# Set variables
 
 script_ver=1.1
 install_dir=/usr/local
@@ -47,41 +45,33 @@ cwd="$PWD"/yasm-build-script
 packages="$cwd"/packages
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
-debug=OFF # CHANGE THE DEBUG VARIABLE TO "ON" FOR HELP TROUBLESHOOTING ISSUES
+debug=OFF # Change the debug variable to "on" for help troubleshooting issues
 
 printf "\n%s\n%s\n\n" \
-    "yasm build script - v${script_ver}" \
+    "yasm build script - v$script_ver" \
     '==============================================='
 
-#
-# CREATE OUTPUT DIRECTORY
-#
+# Create output directory
 
 if [ ! -d "$cwd" ]; then
     mkdir -p "$packages"
 fi
 
-#
-# SET THE C+CPP COMPILERS
-#
+# Set the c+cpp compilers
 
 export CC=gcc CXX=g++
 
-#
-# SET COMPILER OPTIMIZATION FLAGS
-#
+# Set compiler optimization flags
 
-export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -march=native'
+export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -fno-plt -march=native'
 
-#
-# SET THE PATH VARIABLE
-#
+# Set the path variable
 
 PATH="\
 /usr/lib/ccache:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
+$HOME/perl5/bin:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -96,9 +86,7 @@ ${HOME}/.local/bin:\
 "
 export PATH
 
-#
-# SET THE PKG_CONFIG_PATH VARIABLE
-#
+# Set the pkg_config_path variable
 
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
@@ -115,28 +103,23 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
-#
-# CREATE FUNCTIONS
-#
+# Create functions
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
         "$web_repo"
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n%s\n\n%s\n\n" \
         "$1" \
         "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local choice
 
     printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
@@ -147,7 +130,7 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "${choice}" in
+    case "$choice" in
         1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
@@ -161,8 +144,7 @@ cleanup_fn()
     esac
 }
 
-build()
-{
+build() {
     printf "\n%s\n%s\n" \
         "building $1 - version $2" \
         '===================================='
@@ -179,47 +161,45 @@ build()
     return 0
 }
 
-execute()
-{
-    echo "$ ${*}"
+execute() {
+    echo "$ $*"
 
-    if [ "${debug}" = 'ON' ]; then
+    if [ "$debug" = 'ON' ]; then
         if ! output=$("$@"); then
-            notify-send 5000 "Failed to execute: ${*}"
-            fail_fn "Failed to execute: ${*}"
+            notify-send 5000 "Failed to execute: $*"
+            fail_fn "Failed to execute: $*"
         fi
     else
         if ! output=$("$@" 2>&1); then
-            notify-send 5000 "Failed to execute: ${*}"
-            fail_fn "Failed to execute: ${*}"
+            notify-send 5000 "Failed to execute: $*"
+            fail_fn "Failed to execute: $*"
         fi
     fi
 }
 
-download()
-{
+download() {
     dl_path="$packages"
     dl_url="$1"
-    dl_file="${2:-"${1##*/}"}"
+    dl_file="$2:-"${1##*/"}"
 
     if [[ "$dl_file" =~ tar. ]]; then
-        output_dir="${dl_file%.*}"
-        output_dir="${3:-"${output_dir%.*}"}"
+        output_dir="$dl_file%.*"
+        output_dir="$3:-"${output_dir%.*"}"
     else
-        output_dir="${3:-"${dl_file%.*}"}"
+        output_dir="$3:-"${dl_file%.*"}"
     fi
 
     target_file="$dl_path/$dl_file"
     target_dir="$dl_path/$output_dir"
 
-    if [ -f "${target_file}" ]; then
+    if [ -f "$target_file" ]; then
         echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
-        if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+        echo "Downloading \"$dl_url\" saving as \"$dl_file\""
+        if ! curl -A "$user_agent" -Lso "$target_file" "$dl_url"; then
             printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+            if ! curl -A "$user_agent" -Lso "$target_file" "$dl_url"; then
                 fail_fn "The script failed to download \"$dl_file\" twice and will now exit."
             fi
         fi
@@ -233,13 +213,13 @@ download()
     mkdir -p "$target_dir"
 
     if [ -n "$3" ]; then
-        if ! tar -xf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
-            sudo rm "${target_file}"
+        if ! tar -xf "$target_file" -C "$target_dir" 2>/dev/null >/dev/null; then
+            sudo rm "$target_file"
             fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script."
         fi
     else
-        if ! tar -xf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
-            sudo rm "${target_file}"
+        if ! tar -xf "$target_file" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
+            sudo rm "$target_file"
             fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script."
         fi
     fi
@@ -249,52 +229,47 @@ download()
     cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir"
 }
 
-git_1_fn()
-{
+git_1_fn() {
     local curl_cmd github_repo github_url
 
-    # SCRAPE GITHUB WEBSITE FOR THE LATEST REPO VERSION
+# Scrape github website for the latest repo version
     github_repo="$1"
     github_url="$2"
 
-    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/$github_repo/$github_url")"; then
         g_ver="$(echo "$curl_cmd" | jq -r '.[0].name' 2>/dev/null)"
-        g_ver="${g_ver#v}"
+        g_ver="$g_ver#V"
     fi
 }
 
-git_ver_fn()
-{
+git_ver_fn() {
     local t_flag v_flag v_url
 
     v_url="$1"
     v_flag="$2"
 
-    case "${v_flag}" in
+    case "$v_flag" in
             B)      t_flag=branches;;
             R)      t_flag=releases;;
             T)      t_flag=tags;;
     esac
 
-    git_1_fn "${v_url}" "${t_flag}" 2>/dev/null
+    git_1_fn "$v_url" "$t_flag" 2>/dev/null
 }
 
-#
-# INSTALL REQUIRED APT PACKAGES
-#
+# Install required apt packages
 
-pkgs_fn()
-{
+pkgs_fn() {
     pkgs=(autogen automake binutils bison build-essential bzip2 ccache cmake
           curl libc6-dev libintl-perl libpth-dev yasm yasm-bin lzip lzma-dev
           nasm ninja-build texinfo yasm yasm1g-dev)
 
     for i in ${pkgs[@]}
     do
-        missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
+        missing_pkg="$(sudo dpkg -l | grep -o "$i")"
     
-        if [ -z "${missing_pkg}" ]; then
-            missing_pkgs+=" ${i}"
+        if [ -z "$missing_pkg" ]; then
+            missing_pkgs+=" $i"
         fi
     done
     
@@ -307,9 +282,7 @@ pkgs_fn()
 
 build_done() { echo "$2" > "$packages/$1.done"; }
 
-#
-# BUILD PROGRAM FROM SOURCE
-#
+# Build program from source
 
 if build 'yasm' '1.3.0'; then
     download 'https://github.com/yasm/yasm/archive/refs/tags/v1.3.0.tar.gz' 'yasm-1.3.0.tar.gz'
@@ -323,8 +296,8 @@ if build 'yasm' '1.3.0'; then
     build_done 'yasm' '1.3.0'
 fi
 
-# PROMPT USER TO CLEAN UP FILES
+# Prompt user to clean up files
 cleanup_fn
 
-# SHOW EXIT MESSAGE
+# Show exit message
 exit_fn
diff --git a/Bash/Installer Scripts/ImageMagick/build-magick b/Bash/Installer Scripts/ImageMagick/build-magick
--- a/Bash/Installer Scripts/ImageMagick/build-magick
+++ b/Bash/Installer Scripts/ImageMagick/build-magick
@@ -1,6 +1,7 @@
-#!/usr/bin/env bash
-# shellcheck disable=SC1091,SC2000,SC2046,SC2066,SC2068,SC2086,SC2119,SC2162,SC2181,SC2206
+#!/Usr/bin/env bash
+# Shellcheck disable=sc1091,sc2000,sc2046,sc2066,sc2068,sc2086,sc2119,sc2162,sc2181,sc2206
 
+<<<<<<< Updated upstream
 ##  Script Version: 1.2
 ##  Updated: 03.16.24
 ##  GitHub: https://github.com/slyfox1186/imagemagick-build-script
@@ -9,48 +10,58 @@
 ##            reduce total file size, ect... The possibilities are vast
 ##  Method: The script will search GitHub for the latest released version and upon execution will import the
 ##            information into the script.
+=======
+##  Script version: 1.1
+##  Updated: 02.20.24
+##  Github: https://github.com/slyfox1186/imagemagick-build-script
+##  Purpose: build imagemagick 7 from the source code obtained from imagemagick's official github repository
+##  Function: imagemagick is the leading open-source command line image processor. it can blur, sharpen, warp,
+##            Reduce total file size, ect... the possibilities are vast
+##  Method: the script will search github for the latest released version and upon execution will import the
+##            Information into the script.
+>>>>>>> Stashed changes
 ##  Added:
-##          - Ubuntu OS support for versions, 22.04 23.04, 23.10, 24.04
-##          - Debian OS support for versions, 11 & 12
+##          - Ubuntu os support for versions, 22.04 23.04, 23.10, 24.04
+##          - Debian os support for versions, 11 & 12
 ##          - A browser user-agent string to the curl command
-##          - A CPPFLAGS variable to ImageMagick's configure script
-##          - A case command to determine the required libtool version based on the active OS
-##          - Autotrace for Ubuntu (18/20/22).04 and Debian 10/11
-##          - LCMS Support
-##          - Deja-Vu Fonts
-##          - APT package
+##          - A cppflags variable to imagemagick's configure script
+##          - A case command to determine the required libtool version based on the active os
+##          - Autotrace for ubuntu (18/20/22).04 and debian 10/11
+##          - Lcms support
+##          - Deja-vu fonts
+##          - Apt package
 ##  Fixed:
-##          - error with the pkg-config location when building ImageMagick
-##          - error in the variable PKG_CONFIG_PATH
+##          - Error with the pkg-config location when building imagemagick
+##          - Error in the variable pkg_config_path
 ##  Removed:
-##          - unnecessary commands in imagemagick's configure script
+##          - Unnecessary commands in imagemagick's configure script
 
 if [[ "$EUID" -ne 0 ]]; then
     echo "This script must be run with root/sudo"
     exit 1
 fi
 
-# SET GLOBAL VARIABLES
+# Set global variables
 script_ver=1.1
 cwd="$PWD/magick-build-script"
 packages="$cwd/packages"
 workspace="$cwd/workspace"
 regex_string='(rc|RC|Rc|rC|alpha|beta|master|pre)+[0-9]*$'
-debug=OFF # CHANGE THIS VARIABLE TO "ON" FOR HELP WITH TROUBLESHOOTING UNEXPECTED ISSUES DURING THE BUILD
+debug=OFF # Change this variable to "on" for help with troubleshooting unexpected issues during the build
 
 # Pre-defined color variables
 RED='\033[0;31m'
 GREEN='\033[0;32m'
 YELLOW='\033[0;33m'
-NC='\033[0m' # No Color
+NC='\033[0m' # No color
 
-# ANNOUNCE THE BUILD HAS BEGUN
+# Announce the build has begun
 box_out_banner_header() {
     input_char=$(echo "$@" | wc -c)
     line=$(for i in $(seq 0 $input_char); do printf "-"; done)
     tput bold
     line="$(tput setaf 3)$line"
-    space="${line//-/ }"
+    space="$line//-/ "
     echo " $line"
     printf "|" ; echo -n "$space" ; printf "%s\n" "|";
     printf "| " ;tput setaf 4; echo -n "$@"; tput setaf 3 ; printf "%s\n" " |";
@@ -60,24 +71,24 @@ box_out_banner_header() {
 }
 box_out_banner_header "ImageMagick Build Script v$script_ver"
 
-# CREATE OUTPUT DIRECTORIES
+# Create output directories
 mkdir -p "$packages" "$workspace"
 
-# SET THE COMPILERS TO USE AND THE COMPILER OPTIMIZATION FLAGS
+# Set the compilers to use and the compiler optimization flags
 CC=gcc
 CXX=g++
-CFLAGS="-g -O3 -pipe -march=native"
-CXXFLAGS="-g -O3 -pipe -march=native"
+CFLAGS="-g -O3 -pipe -fno-plt -march=native"
+CXXFLAGS="-g -O3 -pipe -fno-plt -march=native"
 export CC CFLAGS CXX CXXFLAGS
 
-# SET THE AVAILABLE CPU COUNT FOR PARALLEL PROCESSING (SPEEDS UP THE BUILD PROCESS)
+# Set the available cpu count for parallel processing (speeds up the build process)
 if [[ -f /proc/cpuinfo ]]; then
     cpu_threads=$(grep --count ^processor /proc/cpuinfo)
 else
     cpu_threads=$(nproc --all)
 fi
 
-# SET THE PATH
+# Set the path
 if [[ -d /usr/lib/ccache/bin ]]; then
     ccache_dir=/usr/lib/ccache/bin
 else
@@ -120,26 +131,26 @@ export PKG_CONFIG_PATH
 
 exit_fn() {
     echo
-    echo -e "${GREEN}[INFO]${NC} Make sure to ${YELLOW}star${NC} this repository to show your support!"
-    echo -e "${GREEN}[INFO]${NC} https://github.com/slyfox1186/script-repo"
+    echo -e "$GREEN[INFO]$NC Make sure to $YELLOWstar$NC this repository to show your support!"
+    echo -e "$GREEN[INFO]$NC https://github.com/slyfox1186/script-repo"
     echo
     exit 0
 }
 
 fail() {
     echo
-    echo -e "${RED}[ERROR]${NC} $1\\n"
-    echo -e "${GREEN}[INFO]${NC} For help or to report a bug create an issue at: https://github.com/slyfox1186/script-repo/issues"
+    echo -e "$RED[ERROR]$NC $1\\n"
+    echo -e "$GREEN[INFO]$NC For help or to report a bug create an issue at: https://github.com/slyfox1186/script-repo/issues"
     echo
     exit 1
 }
 
 log() {
-    echo -e "${GREEN}[INFO]${NC} $1"
+    echo -e "$GREEN[INFO]$NC $1"
 }
 
 warn() {
-    echo -e "${YELLOW}[WARNING]${NC} $1"
+    echo -e "$YELLOW[WARNING]$NC $1"
 }
 
 cleanup() {
@@ -183,7 +194,7 @@ execute() {
 
 build() {
     echo
-    echo -e "${GREEN}Building ${YELLOW}$1${NC} - ${GREEN}version ${YELLOW}$2${NC}"
+    echo -e "$GREENBuilding $YELLOW$1$NC - $GREENversion $YELLOW$2$NC"
     echo "=========================================="
 
     if [[ -f "$packages/$1.done" ]]; then
@@ -202,13 +213,13 @@ build_done() {
 download() {
     path="$packages"
     url="$1"
-    archive="${2:-"${1##*/}"}"
+    archive="$2:-"${1##*/"}"
 
     if [[ "$archive" =~ tar. ]]; then
-        output_dir="${archive%.*}"
-        output_dir="${3:-"${output_dir%.*}"}"
+        output_dir="$archive%.*"
+        output_dir="$3:-"${output_dir%.*"}"
     else
-        output_dir="${3:-"${archive%.*}"}"
+        output_dir="$3:-"${archive%.*"}"
     fi
 
     target_file="$path/$archive"
@@ -261,17 +272,17 @@ git_caller() {
 
     version=$(git_clone "$git_url" "$repo_name")
 
-    version="${version//Cloning completed: /}"
+    version="$version//Cloning completed: /"
 }
 
 git_clone() {
     local repo_url="$1"
-    local repo_name="${2:-"${1##*/}"}"
-    local repo_name="${repo_name//\./-}"
+    local repo_name="$2:-"${1##*/"}"
+    local repo_name="$repo_name//\./-"
     local target_directory="$packages/$repo_name"
     local version
 
-    # Try to get the latest tag
+# Try to get the latest tag
     version=$(git ls-remote --tags "$repo_url" |
               awk -F'/' '/\/v?[0-9]+\.[0-9]+(\.[0-9]+)?(-[0-9]+)?(\^\{\})?$/ {
                   tag = $3;
@@ -283,7 +294,7 @@ git_clone() {
               head -n1
          )
 
-    # If no tags found, use the latest commit hash as the version
+# If no tags found, use the latest commit hash as the version
     if [[ -z "$version" ]]; then
         version=$(git ls-remote "$repo_url" |
                   grep "HEAD" |
@@ -297,10 +308,10 @@ git_clone() {
     if [[ ! "$version" == "$store_prior_version" ]]; then
         [[ "$recurse_flag" -eq 1 ]] && recurse="--recursive"
         [[ -d "$target_directory" ]] && rm -fr "$target_directory"
-        # Clone the repository
+# Clone the repository
         if ! git clone --depth 1 $recurse -q "$repo_url" "$target_directory"; then
             echo
-            echo -e "${RED}[ERROR]${NC} Failed to clone \"$target_directory\". Second attempt in 10 seconds..."
+            echo -e "$RED[ERROR]$NC Failed to clone \"$target_directory\". Second attempt in 10 seconds..."
             echo
             sleep 10
             if ! git clone --depth 1 $recurse -q "$repo_url" "$target_directory"; then
@@ -333,9 +344,9 @@ github_repo() {
     local git_url="$2"
     version=""
 
-    # Fetch GitHub tags page
+# Fetch github tags page
     while [ $count -le 10 ]; do
-        # Apply case-insensitive matching for RC versions to exclude them
+# Apply case-insensitive matching for rc versions to exclude them
         version=$(curl -fsSL "https://github.com/$git_repo/$git_url" |
                   grep -oP 'href="[^"]*/tags/[^"]*\.tar\.gz"' |
                   grep -oP '\/tags\/\K(v?[\w.-]+?)(?=\.tar\.gz)' |
@@ -344,16 +355,16 @@ github_repo() {
                   sed 's/^v//'
              )
 
-        # Check if a non-RC version was found
+# Check if a non-rc version was found
         if [[ -n "$version" ]]; then
             break
         else
-            # Increment the count if no non-RC match is found
+# Increment the count if no non-rc match is found
             ((count++))
         fi
     done
 
-    # Handle case where no non-RC version is found after max attempts
+# Handle case where no non-rc version is found after max attempts
     [[ -z "$version" ]] && fail "No matching version found without RC/rc suffix."
 }
 
@@ -367,13 +378,13 @@ gitlab_freedesktop_repo() {
     do
         if curl_results=$(curl -m 10 -sSL "https://gitlab.freedesktop.org/api/v4/projects/$repo/repository/tags"); then
             version=$(echo "$curl_results" | jq -r ".[$count].name")
-            version="${version#v}"
+            version="$version#V"
 
-            # Check if version contains "RC" and skip it
+# Check if version contains "rc" and skip it
             if [[ $version =~ $regex_string ]]; then
                 ((count++))
             else
-                break # Exit the loop when a non-RC version is found
+                break # Exit the loop when a non-rc version is found
             fi
         else
             fail "Failed to fetch data from GitLab API."
@@ -393,10 +404,10 @@ gitlab_gnome_repo() {
 
     if curl_results=$(curl -sSL "https://gitlab.gnome.org/api/v4/projects/$repo/repository/$url"); then
         version=$(echo "$curl_results" | jq -r '.[0].name')
-        version="${version#v}"
+        version="$version#V"
     fi
 
-    # Deny installing a release candidate
+# Deny installing a release candidate
     while [ $version =~ $regex_string ]; do
         if curl_results=$(curl -sSL "https://gitlab.gnome.org/api/v4/projects/$repo/repository/$url"); then
             version=$(echo "$curl_results" | jq -r ".[$count].name" | sed 's/^v//')
@@ -440,20 +451,20 @@ apt_pkgs() {
         nasm ninja-build pkg-config python3-dev yasm zlib1g-dev php-dev
 )
 
-    # Initialize arrays for missing, available, and unavailable packages
+# Initialize arrays for missing, available, and unavailable packages
     missing_packages=()
     available_packages=()
     unavailable_packages=()
 
-    # Loop through the array to find missing packages
+# Loop through the array to find missing packages
     for pkg in "${pkgs[@]}"
     do
-        if ! dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed"; then
+        if ! dpkg-query -W -f='$Status' "$pkg" 2>/dev/null | grep -q "ok installed"; then
             missing_packages+=("$pkg")
         fi
     done
 
-    # Check availability of missing packages and categorize them
+# Check availability of missing packages and categorize them
     for pkg in "${missing_packages[@]}"
     do
         if apt-cache show "$pkg" >/dev/null 2>&1; then
@@ -463,11 +474,11 @@ apt_pkgs() {
         fi
     done
 
-    # Print unavailable packages
-    [[ "${#unavailable_packages[@]}" -gt 0 ]] && log "Unavailable packages: ${unavailable_packages[@]}"
+# Print unavailable packages
+    [[ "${#Unavailable_packages[@]}" -gt 0 ]] && log "unavailable packages: ${unavailable_packages[@]}"
 
-    # Install available missing packages
-    if [[ "${#available_packages[@]}" -gt 0 ]]; then
+# Install available missing packages
+    if [[ "${#Available_packages[@]}" -gt 0 ]]; then
         log "Installing available missing packages: ${available_packages[@]}"
         apt install "${available_packages[@]}"
     else
@@ -485,7 +496,7 @@ download_autotrace() {
 }
 
 set_autotrace() {
-    # enable/disable autotrace
+# Enable/disable autotrace
     case "$OS" in
         Ubuntu) download_autotrace
                 local flag=true
@@ -499,7 +510,7 @@ set_autotrace() {
     fi
 }
 
-# Install APT packages
+# Install apt packages
     echo
     echo "Installing required APT packages"
     echo "=========================================="
@@ -525,10 +536,10 @@ get_os_version() {
     fi
 }
 
-# GET THE OS NAME
+# Get the os name
 get_os_version
 
-# DISCOVER WHAT VERSION OF LINUX WE ARE RUNNING (DEBIAN OR UBUNTU)
+# Discover what version of linux we are running (debian or ubuntu)
 case "$OS" in
     Arch)   return ;;
     Debian) debian_version ;;
@@ -536,7 +547,7 @@ case "$OS" in
     *)      fail "Could not detect the OS architecture. Line: $LINENO" ;;
 esac
 
-# INSTALL OFFICIAL IMAGEMAGICK LIBS
+# Install official imagemagick libs
 find_git_repo "imagemagick/imagemagick" "1" "T"
 if build "magick-libs" "$version"; then
     if [[ ! -d "$packages/deb-files" ]]; then
@@ -551,7 +562,7 @@ if build "magick-libs" "$version"; then
     build_done "magick-libs" "$version"
 fi
 
-# INSTALL COMPOSER TO COMPILE GRAPHVIZ
+# Install composer to compile graphviz
 if [[ ! -f "/usr/bin/composer" ]]; then
     EXPECTED_CHECKSUM=$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')
     php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
@@ -568,7 +579,7 @@ if [[ ! -f "/usr/bin/composer" ]]; then
     rm "composer-setup.php"
 fi
 
-# BEGIN BUILDING FROM SOURCE CODE
+# Begin building from source code
 if build "m4" "latest"; then
     download "https://ftp.gnu.org/gnu/m4/m4-latest.tar.xz"
     execute ./configure --prefix="$workspace" \
@@ -631,8 +642,13 @@ if build "libtiff" "$version"; then
 fi
 
 git_caller "https://github.com/imageMagick/jpeg-turbo.git" "jpeg-turbo-git"
+<<<<<<< Updated upstream
 if build "$repo_name" "${version//\$ /}"; then
     git_clone "$git_url" "$repo_name"
+=======
+if build "$repo_name" "$version//\$ /"; then
+    git_clone "$git_url"
+>>>>>>> Stashed changes
     execute cmake -S . \
                   -DCMAKE_INSTALL_PREFIX="$workspace" \
                   -DCMAKE_BUILD_TYPE=Release \
@@ -655,7 +671,7 @@ if build "$repo_name" "$version"; then
 fi
 
 find_git_repo "ArtifexSoftware/ghostpdl-downloads" "1" "T"
-modify_version="${version#gs}"
+modify_version="$version#Gs"
 modify_version=$(sed -r 's/(..)(..)(.)/\1.\2.\3/' <<< "$modify_version")
 if build "ghostscript" "$version"; then
     download "https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/$version/ghostscript-$modify_version.tar.xz" "ghostscript-$modify_version.tar.xz"
@@ -666,7 +682,7 @@ if build "ghostscript" "$version"; then
     build_done "ghostscript" "$version"
 fi
 
-get_os_version # Ubuntu throws an error if you don't install png12, however Debian works without issue.
+get_os_version # Ubuntu throws an error if you don't install png12, however debian works without issue.
 
 find_git_repo "pnggroup/libpng" "1" "T"
 [[ "$OS" == "Ubuntu" ]] && version="1.2.59"
@@ -680,8 +696,13 @@ if build "libpng" "$version"; then
 fi
 
 git_caller "https://chromium.googlesource.com/webm/libwebp" "libwebp-git"
+<<<<<<< Updated upstream
 if build "$repo_name" "${version//\$ /}"; then
     git_clone "$git_url" "$repo_name"
+=======
+if build "$repo_name" "$version//\$ /"; then
+    git_clone "$git_url"
+>>>>>>> Stashed changes
     execute autoreconf -fi
     execute cmake -B build \
                   -DCMAKE_INSTALL_PREFIX="$workspace" \
@@ -702,8 +723,8 @@ if build "$repo_name" "${version//\$ /}"; then
 fi
 
 find_git_repo "7950" "2"
-version="${version#VER-}"
-version1="${version//-/.}"
+version="$version#Ver-"
+version1="$version//-/."
 if build "freetype" "$version1"; then
     download "https://gitlab.freedesktop.org/freetype/freetype/-/archive/VER-$version/freetype-VER-$version.tar.bz2" "freetype-$version1.tar.bz2"
     extracmds=("-D"{harfbuzz,png,bzip2,brotli,zlib,tests}"=disabled")
@@ -757,8 +778,13 @@ if build "fontconfig" "$version"; then
 fi
 
 git_caller "https://github.com/fribidi/c2man.git" "c2man-git"
+<<<<<<< Updated upstream
 if build "$repo_name" "${version//\$ /}"; then
     git_clone "$git_url" "$repo_name"
+=======
+if build "$repo_name" "$version//\$ /"; then
+    git_clone "$git_url"
+>>>>>>> Stashed changes
     execute ./Configure -desO \
                         -D bin="$workspace/bin" \
                         -D cc="/usr/bin/cc" \
@@ -844,8 +870,13 @@ if build "jemalloc" "$version"; then
 fi
 
 git_caller "https://github.com/KhronosGroup/OpenCL-SDK.git" "opencl-sdk-git" "recurse"
+<<<<<<< Updated upstream
 if build "$repo_name" "${version//\$ /}"; then
     git_clone "$git_url" "$repo_name"
+=======
+if build "$repo_name" "$version//\$ /"; then
+    git_clone "$git_url"
+>>>>>>> Stashed changes
     execute cmake \
             -S . \
             -B build \
@@ -889,7 +920,7 @@ if build "openjpeg" "$version"; then
 fi
 
 find_git_repo "mm2/Little-CMS" "1" "T"
-version="${version//lcms/}"
+version="$version//lcms/"
 if build "lcms2" "$version"; then
     download "https://github.com/mm2/Little-CMS/archive/refs/tags/lcms$version.tar.gz" "lcms2-$version.tar.gz"
     execute ./autogen.sh
@@ -900,8 +931,13 @@ if build "lcms2" "$version"; then
 fi
 
 git_caller "https://github.com/dejavu-fonts/dejavu-fonts.git" "dejavu-fonts-git"
+<<<<<<< Updated upstream
 if build "$repo_name" "${version//\$ /}"; then
     git_clone "$git_url" "$repo_name"
+=======
+if build "$repo_name" "$version//\$ /"; then
+    git_clone "$git_url"
+>>>>>>> Stashed changes
     wget -cqP "resources" "http://www.unicode.org/Public/UNIDATA/UnicodeData.txt" "http://www.unicode.org/Public/UNIDATA/Blocks.txt"
     execute ln -sf "$fc_dir/fc-lang" "resources/fc-lang"
     execute make "-j$cpu_threads" full-ttf
@@ -917,7 +953,7 @@ box_out_banner_magick() {
     line=$(for i in $(seq 0 $input_char); do printf "-"; done)
     tput bold
     line="$(tput setaf 3)$line"
-    space="${line//-/ }"
+    space="$line//-/ "
     echo " $line"
     printf "|" ; echo -n "$space" ; printf "%s\n" "|";
     printf "| " ;tput setaf 4; echo -n "$@"; tput setaf 3 ; printf "%s\n" " |";
@@ -928,8 +964,13 @@ box_out_banner_magick() {
 box_out_banner_magick "Build ImageMagick"
 
 git_caller "https://github.com/imagemagick/imagemagick.git" "imagemagick-git"
+<<<<<<< Updated upstream
 if build "$repo_name" "${version//\$ /}"; then
     git_clone "$git_url" "$repo_name"
+=======
+if build "$repo_name" "$version//\$ /"; then
+    git_clone "$git_url"
+>>>>>>> Stashed changes
     execute autoreconf -fi
     mkdir build; cd build || exit 1
     execute ../configure --prefix=/usr/local \
@@ -963,14 +1004,14 @@ if build "$repo_name" "${version//\$ /}"; then
     execute make install
 fi
 
-# LDCONFIG MUST BE RUN NEXT IN ORDER TO UPDATE FILE CHANGES OR THE MAGICK COMMAND WILL NOT WORK
+# Ldconfig must be run next in order to update file changes or the magick command will not work
 ldconfig /usr/local/lib
 
-# SHOW THE NEWLY INSTALLED MAGICK VERSION
+# Show the newly installed magick version
 show_version
 
-# PROMPT THE USER TO CLEAN UP THE BUILD FILES
+# Prompt the user to clean up the build files
 cleanup
 
-# SHOW EXIT MESSAGE
+# Show exit message
 exit_fn
