Update build-binutils'

diff --git a/Bash/Installer Scripts/GNU Software/build-binutils b/Bash/Installer Scripts/GNU Software/build-binutils
--- a/Bash/Installer Scripts/GNU Software/build-binutils
+++ b/Bash/Installer Scripts/GNU Software/build-binutils
@@ -1,304 +1,195 @@
 #!/usr/bin/env bash
 
-##  GitHub Script: https://github.com/slyfox1186/script-repo/edit/main/Bash/Installer%20Scripts/GNU%20Software/build-binutils
-##  Purpose: build gnu binutils from source code
-##  Updated: 01.14.24
-##  Script version: 1.3
+# GitHub Script: https://github.com/slyfox1186/script-repo/edit/main/Bash/Installer%20Scripts/GNU%20Software/build-binutils
+# Purpose: build GNU binutils from source code
+# Updated: 01.14.24
+# Script version: 1.3
 
-clear
+set -e
+set -o pipefail
 
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+if [ "${EUID}" -eq 0 ]; then
+    echo "You must run this script WITHOUT root/sudo."
     exit 1
 fi
 
-if ! sudo dpkg -l | grep -o &>/dev/null; then
-    sudo apt -y install lzip
-    clear
-fi
-
-#
 # SET THE VARIABLES
-#
-
 script_ver=1.3
 archive_dir=binutils-2.41
-archive_url=https://ftp.gnu.org/gnu/binutils/"$archive_dir".tar.lz
-archive_ext="${archive_url//*.}"
-archive_name="$archive_dir.tar.${archive_ext}"
-cwd="$PWD"/binutils-build-script
-install_dir=/usr/local/binutils
+archive_url="https://ftp.gnu.org/gnu/binutils/$archive_dir.tar.lz"
+archive_ext="${archive_url##*.}"
+archive_name="$archive_dir.tar.$archive_ext"
+cwd="$PWD/binutils-build-script"
+install_dir='/usr/local/binutils'
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
-web_repo=https://github.com/slyfox1186/script-repo
 
-#
 # CREATE OUTPUT DIRECTORY
-#
-
-if [ -d "$cwd" ]; then
-    sudo rm -fr "$cwd"
-fi
 mkdir -p "$cwd"
+cd "$cwd"
 
-#
 # SET THE CC/CXX COMPILERS & THE COMPILER OPTIMIZATION FLAGS
-#
-
 CC=gcc
 CXX=g++
 CFLAGS='-g -O3 -pipe -march=native'
-CXXFLAGS="${CFLAGS}"
+CXXFLAGS="$CFLAGS"
 CPPFLAGS='-I/usr/local/include -I/usr/include'
 LDFLAGS='-L/usr/local/lib64 -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib64 -L/usr/lib -L/lib64 -L/lib'
 export CC CXX CFLAGS CPPFLAGS CXXFLAGS LDFLAGS
 
-#
-# SET THE PATH VARIABLE
-#
-
 if [ -d /usr/lib/ccache/bin ]; then
-    set_ccache_dir='/usr/lib/ccache/bin'
+    ccache_dir='/usr/lib/ccache/bin'
 else
-    set_ccache_dir='/usr/lib/ccache'
+    ccache_dir='/usr/lib/ccache'
 fi
 
+# SET THE PATH VARIABLE
 PATH="\
-$set_ccache_dir:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
+$ccache_dir:\
+$HOME/perl5/bin:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
-/usr/local/x86_64-linux-gnu/bin:\
 /usr/local/bin:\
 /usr/sbin:\
 /usr/bin:\
-/sbin:\
-/bin:\
-/usr/local/games:\
-/usr/games:\
-/snap/bin\
+/sbin\
 "
 export PATH
 
-#
 # SET THE PKG_CONFIG_PATH VARIABLE
-#
-
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
 /usr/local/lib/pkgconfig:\
-/usr/local/lib/usr/local/pkgconfig:\
-/usr/local/share/pkgconfig:\
-/usr/lib64/pkgconfig:\
-/usr/lib/pkgconfig:\
-/usr/lib/usr/local/pkgconfig:\
 /usr/share/pkgconfig:\
-/lib64/pkgconfig:\
-/lib/pkgconfig:\
-/lib/usr/local/pkgconfig\
+/usr/lib/x86_64-linux-gnu/pkgconfig:\
+/usr/lib/pkgconfig:\
+/lib/x86_64-linux-gnu/pkgconfig:\
+/lib/pkgconfig\
 "
 export PKG_CONFIG_PATH
 
-#
-# CREATE FUNCTIONS
-#
+pkgs_fn() {
+    local missing_packages pkg pkgs available_packages unavailable_packages
 
-exit_fn()
-{
-    printf "\n%s\n\n%s\n\n"                                       \
-        'Make sure to star this repository to show your support!' \
-        "$web_repo"
-    exit 0
-}
+    pkgs=(
+        "$1" alien asciidoc autoconf autoconf-archive automake autopoint binutils bison
+        build-essential cmake curl dbus-x11 flex fontforge gettext gimp-data git gperf
+        imagemagick jq libamd2 libbabl-0.1-0 libc6 libc6-dev libcamd2 libccolamd2
+        libgegl-common libcholmod3 libcolamd2 libfont-ttf-perl libfreetype-dev libgc-dev
+        libgegl-0.4-0 libgimp2.0 libgimp2.0-dev libgl2ps-dev libglib2.0-dev libgraphviz-dev
+        libgs-dev libheif-dev libltdl-dev libmetis5 libnotify-bin libnuma-dev libomp-dev
+        libpango1.0-dev libpaper-dev libpng-dev libpstoedit-dev libraw-dev librsvg2-dev
+        librust-bzip2-dev libsdl2-dev libsuitesparseconfig5 libtcmalloc-minimal4 libticonv-dev
+        libtool libtool-bin libumfpack5 libxml2-dev libzip-dev libzstd-dev m4 meson nasm
+        ninja-build opencl-c-headers opencl-headers php php-cli pstoedit software-properties-common
+        xmlto yasm zlib1g-dev
+)
 
-fail_fn()
-{
-    printf "\n%s\n\n%s\n\n" \
-        "$1"              \
-        "To report a bug create an issue at: $web_repo/issues"
-    exit 1
-}
+    # Initialize arrays for missing, available, and unavailable packages
+    missing_packages=()
+    available_packages=()
+    unavailable_packages=()
 
-cleanup_fn()
-{
-    local choice
-
-    printf "\n%s\n%s\n%s\n\n%s\n%s\n\n"                \
-        '============================================' \
-        '  Do you want to clean up the build files?  ' \
-        '============================================' \
-        '[1] Yes' \
-        '[2] No'
-    read -p 'Your choices are (1 or 2): ' choice
-    clear
-
-    case "${choice}" in
-        1)      sudo rm -fr "$cwd";;
-        2)      echo;;
-        *)
-                unset choice
-                clear
-                cleanup_fn
-                ;;
-    esac
-}
-
-link_fn()
-{
-    local link_names
-
-    cd "$install_dir/bin" || exit 1
-
-    link_names=(
-        addr2line ar as c++filt dwp elfedit gprof gprofng gp-archive gp-collect-app
-        gp-display-html gp-display-src gp-display-text ld ld.bfd ld.gold nm objcopy
-        objdump ranlib readelf size strings strip
-    )
-
-    for name in ${link_names[@]}
+    # Loop through the array to find missing packages
+    for pkg in "${pkgs[@]}"
     do
-        if ! sudo ln -f "$PWD/$name" '/usr/local/bin'; then
-            printf "%s\n\n" "Failed to link $name"
-            exit 1
-        fi
-    done
-}
-
-#
-# INSTALL REQUIRED APT PACKAGES
-#
-
-pkgs_fn()
-{
-    pkgs=("$1" autoconf autoconf-archive autogen automake binutils build-essential ccache cmake curl
-          git libgmp-dev libintl-perl libisl-dev libmpc-dev libmpfr-dev libtool libtool-bin libzstd-dev
-          m4 nasm ninja-build texinfo yasm zlib1g-dev zstd gdc-multilib gdc)
-
-    for pkg in ${pkgs[@]}
-    do
-        missing_pkg="$(sudo dpkg -l | grep -o "${pkg}")"
-
-        if [ -z "${missing_pkg}" ]; then
-            missing_pkgs+=" ${pkg}"
+        if ! dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q 'ok installed'; then
+            missing_packages+=("$pkg")
         fi
     done
 
-    if [ -n "${missing_pkgs}" ]; then
-        sudo apt -y install ${missing_pkgs}
-        sudo apt -y autoremove
-        clear
+    # Check availability of missing packages and categorize them
+    for pkg in "${missing_packages[@]}"
+    do
+        if apt-cache show "$pkg" > /dev/null 2>&1; then
+            available_packages+=("$pkg")
+        else
+            unavailable_packages+=("$pkg")
+        fi
+    done
+
+    # Print unavailable packages
+    if [ "${#unavailable_packages[@]}" -gt 0 ]; then
+        echo "Unavailable packages: ${unavailable_packages[*]}"
+    fi
+
+    # Install available missing packages
+    if [ "${#available_packages[@]}" -gt 0 ]; then
+        echo "Installing available missing packages: ${available_packages[*]}"
+        sudo apt -y install "${available_packages[@]}"
+    else
+        printf "%s\n\n" "No missing packages to install or all missing packages are unavailable."
     fi
 }
 
-#
-# TEST THE OS AND ITS VERSION
-#
+# Function to extract the first word from a string
+get_first_word() { echo "$1" | awk '{print $1}'; }
 
-find_lsb_release="$(sudo find /usr/bin/ -type f -name 'lsb_release')"
-
+# Try to detect the OS using /etc/os-release, fall back to lsb_release if available
 if [ -f '/etc/os-release' ]; then
-    . '/etc/os-release'
-    OS_TMP="$NAME"
-    OS="$(echo "${OS_TMP}" | awk '{print $1}')"
-elif [ -n "${find_lsb_release}" ]; then
-    OS="$(lsb_release -d | awk '{print $2}')"
+    source '/etc/os-release'
+    OS=$(get_first_word "$NAME")
+elif lsb_release -d &> /dev/null; then
+    OS=$(lsb_release -d | awk '{print $2}')
 else
     fail_fn "Failed to define the \$OS and/or \$VER variables. Line: ${LINENO}"
 fi
 
+# Select the package based on the OS
 case "${OS}" in
-    Debian)       pkgs_fn 'libadacgi6-dev';;
-    Ubuntu)       pkgs_fn 'libadacgi4-dev';;
-    *)            pkgs_fn;;
+    Debian)     pkgs_fn 'libadacgi6-dev' ;;
+    Ubuntu)     pkgs_fn 'libadacgi4-dev' ;;
+    *)          pkgs_fn ;;
 esac
 
 #
 # CHECK IF AUTOCONF VERSION 2.69 IS INSTALLED
 #
 
-autoconf_version=$(autoconf --version 2>/dev/null | head -n 1 | awk '{print $NF}')
-if [[ "$autoconf_version" != '2.69' ]]; then
-    wget --show-progress -cqO build-autoconf-2.69 https://raw.githubusercontent.com/slyfox1186/script-repo/main/Bash/Installer%20Scripts/GNU%20Software/build-autoconf-2.69
+ac_ver=$(autoconf --version 2>/dev/null | head -n 1 | awk '{print $NF}')
+if [[ "$ac_ver" != '2.69' ]]; then
+    wget --show-progress -cqO build-autoconf-2.69 'https://raw.githubusercontent.com/slyfox1186/script-repo/main/Bash/Installer%20Scripts/GNU%20Software/build-autoconf-2.69'
     if bash build-autoconf-2.69; then
         rm build-autoconf-2.69
+    else
+        printf "%s\n\n" 'Failed to install autoconf-v2.69'
+        exit 1
     fi
 fi
 
-#
-# DOWNLOAD THE ARCHIVE FILE
-#
+# Download and extract archive
+wget --show-progress --tries=2 -cqO - "$archive_url" | tar --lzip -xf -
 
-if [ ! -f "$cwd/${archive_name}" ]; then
-    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
-fi
-
-#
-# CREATE OUTPUT DIRECTORY
-#
-
-if [ -d "$cwd/$archive_dir" ]; then
-    sudo rm -fr "$cwd/$archive_dir"
-fi
-mkdir -p "$cwd/$archive_dir/build"
-
-#
-# EXTRACT ARCHIVE FILES
-#
-
-if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
-    exit 1
-fi
-
-#
-# BUILD PROGRAM FROM SOURCE
-#
-
-printf "%s\n%s\n%s\n\n" \
-    "Binutils Build Script - v${script_ver}" \
-    '===============================================' \
-    'Downloading the install files...'
-sleep 1
-
-cd "$cwd/$archive_dir" || exit 1
+cd "$archive_dir"
 
 autoreconf -fi -I /usr/share/aclocal
-cd build || exit 1
-../configure --prefix="$install_dir"                                   \
-             --disable-werror                                          \
+mkdir -p build
+cd build
+../configure --prefix="$install_dir" \
+             --disable-werror \
              --enable-default-compressed-debug-sections-algorithm=zstd \
-             --enable-gold=default                                     \
-             --enable-host-shared                                      \
-             --enable-ld=yes                                           \
-             --enable-libssp                                           \
-             --enable-lto                                              \
-             --enable-pgo-build=lto                                    \
-             --enable-plugins                                          \
-             --enable-year2038                                         \
-             --with-boot-ldflags="${LDFLAGS}"                          \
-             --with-gcc-major-version-only                             \
-             --with-gmp=/usr                                           \
-             --with-isl=/usr                                           \
-             --with-mpc=/usr                                           \
-             --with-mpfr=/usr                                          \
-             --with-stage1-ldflags="${LDFLAGS}"                        \
-             --with-system-zlib                                        \
+             --enable-gold=default \
+             --enable-host-shared \
+             --enable-ld=yes \
+             --enable-libssp \
+             --enable-lto \
+             --enable-pgo-build=lto \
+             --enable-plugins \
+             --enable-year2038 \
+             --with-boot-ldflags="$LDFLAGS" \
+             --with-gcc-major-version-only \
+             --with-gmp=/usr \
+             --with-mpc=/usr \
+             --with-mpfr=/usr \
+             --with-stage1-ldflags="$LDFLAGS" \
+             --with-system-zlib \
              --with-zstd
-echo
-if ! make "-j$(nproc --all)"; then
-    fail_fn "Failed to execute: make -j$(nproc --all). Line: ${LINENO}"
-fi
-echo
-if ! sudo make all-gold install; then
-    fail_fn "Failed to execute: sudo make install. Line: ${LINENO}"
-fi
 
-# CREATE SOFT LINKS TO A COMMON PATH
-link_fn
+make "-j$(nproc --all)"
+sudo make all-gold install
 
-# PROMPT USER TO CLEAN UP FILES
-cleanup_fn
+# Link the installed binaries (optional)
+sudo ln -sf "$install_dir"/bin/* /usr/local/bin/
 
-# SHOW EXIT MESSAGE
-exit_fn
+printf "%s\n\n" "Binutils installation complete."
