Update build-systemd

diff --git a/Bash/Installer Scripts/GNU Software/build-systemd b/Bash/Installer Scripts/GNU Software/build-systemd
--- a/Bash/Installer Scripts/GNU Software/build-systemd
+++ b/Bash/Installer Scripts/GNU Software/build-systemd
@@ -1,17 +1,34 @@
 #!/usr/bin/env bash
-# shellcheck disable=SC2068,SC2086
+
+###########################################################################################################
+##
+##  GitHub Script: https://github.com/slyfox1186/script-repo/edit/main/Bash/Installer%20Scripts/GNU%20Software/build-systemd
+##
+##  Purpose: Build GNU systemd
+##
+##  Updated: 08.01.23
+##
+##  Script version: 1.1
+##
+###########################################################################################################
 
 clear
 
+if [ "$EUID" -eq '0' ]; then
+    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+    exit 1
+fi
+
 #
-# SET PROGRAM NAME + VERSION
+# SET VARIABLES
 #
 
-script_ver=1.0
+script_ver=1.1
 archive_dir=systemd-253
 archive_url=https://github.com/systemd/systemd/archive/refs/tags/v253.tar.gz
 archive_ext="${archive_url//*.}"
 cwd="$PWD"/systemd-build-script
+repo=https://github.com/slyfox1186/script-repo
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
 
 printf "\n%s\n%s\n\n" \
@@ -44,15 +61,25 @@ export {CFLAGS,CXXFLAGS}='-g -O3 -march=native'
 
 exit_fn()
 {
-    printf "\n%s\n\n" 'The script has completed.'
+    printf "\n%s\n\n%s\n\n" \
+        'Make sure to star this repository to show your support!' \
+        "$repo"
     exit 0
+}
+
+fail_fn()
+{
+    printf "\n%s\n\n%s\n\n" \
+        "$1" \
+        "To report a bug create an issue at: $repo/issues"
+    exit 1
 }
 
 cleanup_fn()
 {
-    local choice
+    local choice dpkg_list
 
-    printf "\n%s\n%s\n%s\n\n%s\n%s\n\n" \
+    printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
         '============================================' \
         '  Do you want to clean up the build files?  ' \
         '============================================' \
@@ -74,12 +101,6 @@ cleanup_fn()
     esac
 }
 
-fail_fn()
-{
-    printf "%s\n\n" "$1"
-    exit 1
-}
-
 #
 # INSTALL REQUIRED APT PACKAGES
 #
@@ -94,7 +115,7 @@ pkgs=(autoconf autogen automake binutils bpftool build-essential ccache clang cm
 
 for i in ${pkgs[@]}
 do
-    missing_pkg="$(dpkg -l | grep $i)"
+    missing_pkg="$(dpkg -l | grep "$i")"
 
     if [ -z "$missing_pkg" ]; then
         missing_pkgs+=" $i"
@@ -104,6 +125,7 @@ unset i
 
 if [ -n "$missing_pkgs" ]; then
     sudo apt -y install $missing_pkgs
+    sudo apt -y autoremove
     clear
 fi
 
@@ -147,20 +169,15 @@ fi
 # BUILD PROGRAM FROM SOURCE
 #
 
-clear
-
 cd "$cwd/$archive_dir" || exit 1
-meson setup build --buildtype=release    \
-                  --default-library=both \
-                  --strip                \
-                  -Dzstd=true
+meson setup build --buildtype=release --default-library=both --strip -Dzstd=true
 ninja "-j$(nproc --all)" -C build
 if ! sudo ninja "-j$(nproc --all)" -C build install; then
     printf "\n%s\n\n" 'Failed to install systemd.'
     exit 1
 fi
 
-# CLEANUP FILES
+# PROMPT USER TO CLEAN UP FILES
 cleanup_fn
 
 # SHOW EXIT MESSAGE
