Update build-isl

diff --git a/Bash/Installer Scripts/GNU Software/build-isl b/Bash/Installer Scripts/GNU Software/build-isl
--- a/Bash/Installer Scripts/GNU Software/build-isl
+++ b/Bash/Installer Scripts/GNU Software/build-isl
@@ -6,10 +6,11 @@ clear
 # SET PROGRAM NAME + VERSION
 #
 
-script_ver=1.0
+script_ver=1.1
 archive_dir=isl-git
 archive_url=https://repo.or.cz/isl.git
 cwd="$PWD"/isl-build-script
+repo=https://github.com/slyfox1186/script-repo
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
 
 printf "\n%s\n%s\n\n" \
@@ -28,10 +29,29 @@ fi
 # SET THE C+CPP COMPILERS
 #
 
-export CC=clang CXX=clang++
+export CC=gcc CXX=g++
 
 #
-# EXPORT COMPILER OPTIMIZATION FLAGS
+# SET PATH
+#
+
+PATH="\
+/usr/lib/ccache:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
+/usr/local/sbin:\
+/usr/local/bin:\
+/usr/sbin:\
+/usr/bin:\
+/sbin:\
+/bin:\
+/usr/local/cuda/bin:\
+/snap/bin\
+"
+export PATH
+
+#
+# SET COMPILER OPTIMIZATION FLAGS
 #
 
 export {CFLAGS,CXXFLAGS}='-g -O3 -march=native'
@@ -42,15 +62,25 @@ export {CFLAGS,CXXFLAGS}='-g -O3 -march=native'
 
 exit_fn()
 {
-    printf "\n%s\n\n" 'The script has completed.'
+    printf "\n%s\n\n%s\n\n" \
+        'Make sure to star this repository to show your support!' \
+        "$repo"
     exit 0
+}
+
+fail_fn()
+{
+    printf "\n%s\n\n%s\n\n" \
+        "$1" \
+        "To report a bug create an issue at: $repo/issues"
+    exit 1
 }
 
 cleanup_fn()
 {
-    local choice
+    local choice dpkg_list
 
-    printf "\n%s\n%s\n%s\n\n%s\n%s\n\n" \
+    printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
         '============================================' \
         '  Do you want to clean up the build files?  ' \
         '============================================' \
@@ -70,12 +100,6 @@ cleanup_fn()
                 cleanup_fn
                 ;;
     esac
-}
-
-fail_fn()
-{
-    printf "%s\n\n" "$1"
-    exit 1
 }
 
 #
@@ -157,5 +181,8 @@ if ! sudo make install; then
     exit 1
 fi
 
-sudo rm -fr "$cwd"
-unset archive_dir archive_ext archive_name archive_url CC CXX i missing_pkg missing_pkgs pc_type pem_target pkgs script_ver
+# PROMPT USER TO CLEAN UP FILES
+cleanup_fn
+
+# SHOW EXIT MESSAGE
+exit_fn
