changes to code formatting

diff --git a/Bash/Installer Scripts/FFmpeg/fast-build-ffmpeg b/Bash/Installer Scripts/FFmpeg/fast-build-ffmpeg
--- a/Bash/Installer Scripts/FFmpeg/fast-build-ffmpeg
+++ b/Bash/Installer Scripts/FFmpeg/fast-build-ffmpeg
@@ -1,10 +1,10 @@
-#!/usr/bin/env bash
+#!/Usr/bin/env bash
 
 ###########################################################################################################
 ##
-##  GitHub Script:
+##  Github script:
 ##
-##  Purpose: Build FFmpeg
+##  Purpose: build ffmpeg
 ##  Updated: 08.14.23
 ##
 ##  Script version: 1.0
@@ -13,21 +13,19 @@
 
 clear
 
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+if [ "$EUID" -eq '0' ]; then
+    echo "You must run this script without root or sudo."
     exit 1
 fi
 
-#
-# SET VARIABLES
-#
+# Set variables
 
 script_ver=1.0
 archive_dir=ffmpeg-5.1.3
 archive_url=https://www.ffmpeg.org/releases/ffmpeg-5.1.3.tar.xz
-archive_ext="${archive_url//*.}"
-cwd="${PWD}"/ffmpeg-build-script
-workspace="${cwd}"/workspace
+archive_ext="$archive_url//*."
+cwd="$PWD"/ffmpeg-build-script
+workspace="$cwd"/workspace
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
 repo=https://github.com/slyfox1186/script-repo
 export LIBS='-lpthread -lm -lz'
@@ -47,8 +45,8 @@ export LDFLAGS
 
 PATH="\
 /usr/lib/ccache:\
-${workspace}/bin:\
-${PATH}\
+$workspace/bin:\
+$PATH\
 "
 export PATH
 
@@ -57,11 +55,11 @@ CFLAGS="\
 -I/usr/local/cuda-12.2/targets/x86_64-linux/include \
 -I/usr/local/cuda-12.2/include \
 -I/usr/include \
--g -O3 -pipe -march=native\
+-g -O3 -pipe -fno-plt -march=native\
 "
 export CFLAGS
 
-export CXXFLAGS='-g -O3 -pipe -march=native'
+export CXXFLAGS='-g -O3 -pipe -fno-plt -march=native'
 
 PKG_CONFIG_PATH="\
 /usr/share/pkgconfig:\
@@ -75,52 +73,41 @@ PKG_CONFIG_PATH="\
 export PKG_CONFIG_PATH
 
 printf "\n%s\n%s\n\n" \
-    "FFmpeg build script - v${script_ver}" \
+    "FFmpeg build script - v$script_ver" \
     '==============================================='
 
-#
-# CREATE THE OUTPUT DIRECTORIES
-#
+# Create the output directories
 
-mkdir -p "${cwd}" "${workspace}"
+mkdir -p "$cwd" "$workspace"
 
-#
-# SET THE AVAILABLE CPU THREAD AND CORE COUNT FOR PARALLEL PROCESSING (SPEEDS UP THE BUILD PROCESS)
-#
+# Set the available cpu thread and core count for parallel processing (speeds up the build process)
 
 if [ -f /proc/cpuinfo ]; then
     cpu_threads="$(grep -c ^processor /proc/cpuinfo)"
 else
     cpu_threads="$(nproc --all)"
 fi
-#
-# SET THE C+CPP COMPILERS
-#
+# Set the c+cpp compilers
 
 export CC=gcc CXX=g++
 
-#
-# CREATE FUNCTIONS
-#
+# Create functions
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${repo}"
+        "$repo"
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $repo/issues"
     exit 1
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local choice
 
     printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
@@ -131,8 +118,8 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+    case "$choice" in
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -145,8 +132,7 @@ cleanup_fn()
     esac
 }
 
-ff_move_fn()
-{
+ff_move_fn() {
     local answer
 
     printf "\n%s\n\n%s\n%s\n\n" \
@@ -155,12 +141,12 @@ ff_move_fn()
         '[2] No'
         read -p 'Your choices are (1 or 2): ' answer
 
-    case "${answer}" in
+    case "$answer" in
         1)
                 clear
-                sudo cp -f "${workspace}"/bin/ffmpeg /usr/local/bin 2>/dev/null
-                sudo cp -f "${workspace}"/bin/ffprobe /usr/local/bin 2>/dev/null
-                sudo cp -f "${workspace}"/bin/ffplay /usr/local/bin 2>/dev/null
+                sudo cp -f "$workspace"/bin/ffmpeg /usr/local/bin 2>/dev/null
+                sudo cp -f "$workspace"/bin/ffprobe /usr/local/bin 2>/dev/null
+                sudo cp -f "$workspace"/bin/ffplay /usr/local/bin 2>/dev/null
                 ;;
         2)      clear;;
         *)
@@ -175,40 +161,34 @@ ff_move_fn()
 }
 
 
-ff_ver_fn()
-{
-    cd "${workspace}/bin" || exit 1
+ff_ver_fn() {
+    cd "$workspace/bin" || exit 1
 
     printf "%s\n%s\n%s\n\n" \
         '============================================' \
         '               FFmpeg Version               ' \
         '============================================'
-    "${workspace}/bin/ffmpeg" -version
+    "$workspace/bin/ffmpeg" -version
     sleep 3
 }
 
-#
-# CREATE FUNCTIONS
-#
+# Create functions
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "${repo}"
+        "$repo"
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${repo}/issues"
+        "$1" \
+        "To report a bug create an issue at: $repo/issues"
     exit 1
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local choice
 
     printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
@@ -219,8 +199,8 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "${choice}" in
-        1)      sudo rm -fr "${cwd}";;
+    case "$choice" in
+        1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
                 clear
@@ -233,24 +213,20 @@ cleanup_fn()
     esac
 }
 
-#
-# INSTALL REQUIRED APT PACKAGES
-#
+# Install required apt packages
 
 pkgs='ant apt asciidoc autoconf autoconf-archive automake autopoint binutils bison build-essential cargo ccache checkinstall clang cmake curl doxygen fcitx-libs-dev flex flite1-dev freeglut3-dev frei0r-plugins-dev gawk gettext git gnome-desktop-testing gnustep-gui-runtime google-perftools gperf gtk-doc-tools guile-3.0-dev help2man jq junit ladspa-sdk libasound2-dev libass-dev libaudio-dev libavfilter-dev libbluray-dev libbs2b-dev libbz2-dev libc6 libc6-dev libcaca-dev libcairo2-dev libcdio-dev libcdio-paranoia-dev libcdparanoia-dev libchromaprint-dev libcrypto++-dev libcurl4-openssl-dev libdbus-1-dev libde265-dev libdevil-dev libdmalloc-dev libdrm-dev libdvbpsi-dev libebml-dev libegl1-mesa-dev libfdk-aac-dev libffi-dev libgbm-dev libgdbm-dev libgl1-mesa-dev libgles2-mesa-dev libglib2.0-dev libgme-dev libgnutls28-dev libgnutls30 libgoogle-perftools4 libgoogle-perftools-dev libgvc6 libibus-1.0-dev libiconv-hook-dev libintl-perl libjack-dev libjemalloc-dev libladspa-ocaml-dev libleptonica-dev liblz-dev liblzma-dev liblzo2-dev libmathic-dev libmatroska-dev libmodplug-dev libmp3lame-dev libmusicbrainz5-dev libmysofa-dev libncurses5-dev libncursesw5-dev libnuma1 libnuma-dev libopencore-amrnb-dev libopencore-amrwb-dev libopencv-dev libopenjp2-7-dev libopenmpt-dev libopus-dev libperl-dev libpstoedit-dev libpulse-dev libraqm-dev libraw-dev librsvg2-dev librubberband-dev libshine-dev libsmbclient-dev libsnappy-dev libsndio-dev libsoxr-dev libspeex-dev libsqlite3-dev libssl-dev libsvtav1dec-dev libsvtav1-dev libsvtav1enc-dev libtalloc-dev libtheora-dev libtool libtool-bin libtwolame-dev libudev-dev libv4l-dev libvidstab-dev libvlccore-dev libvo-amrwbenc-dev libvpx-dev libx11-dev libx264-dev libx265-dev libxcursor-dev libxext-dev libxfixes-dev libxi-dev libxkbcommon-dev libxrandr-dev libxss-dev libxvidcore-dev libzstd-dev libzzip-dev lshw lzma-dev m4 meson nasm ninja-build openjdk-17-jdk-headless pandoc python3 python3-pip ragel re2c scons sudo texi2html texinfo tk-dev unzip wget xmlto zlib1g-dev'
 
-sudo apt -y install ${pkgs}
+sudo apt -y install $pkgs
 sudo apt -y autoremove
 clear
 
-#
-# INSTALL NV-CODEC-HEADERS TO ENABLE HARDWARE ACCELERATION
-#
+# Install nv-codec-headers to enable hardware acceleration
 
-curl -A "${user_agent}" -Lso "${cwd}"/nv-headers.tar.gz https://github.com/FFmpeg/nv-codec-headers/releases/download/n12.0.16.0/nv-codec-headers-12.0.16.0.tar.gz
-mkdir -p "${cwd}"/nv-headers
-tar -zxf "${cwd}"/nv-headers.tar.gz -C "${cwd}"/nv-headers --strip-components 1
-cd "${cwd}"/nv-headers || exit 1
+curl -A "$user_agent" -Lso "$cwd"/nv-headers.tar.gz https://github.com/FFmpeg/nv-codec-headers/releases/download/n12.0.16.0/nv-codec-headers-12.0.16.0.tar.gz
+mkdir -p "$cwd"/nv-headers
+tar -zxf "$cwd"/nv-headers.tar.gz -C "$cwd"/nv-headers --strip-components 1
+cd "$cwd"/nv-headers || exit 1
 make "-j$(nproc --all)"
 if sudo make PREFIX=/usr/local install; then
     clear
@@ -261,41 +237,33 @@ else
     fail_fn 'Failed to install the nv-codec-headers.'
 fi
 
-#
-# DOWNLOAD THE ARCHIVE FILE
-#
+# Download the archive file
 
-archive_name="${archive_dir}.tar.${archive_ext}"
+archive_name="$archive_dir.tar.$archive_ext"
 
-if [ ! -f "${cwd}/${archive_name}" ]; then
-    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/$archive_name" ]; then
+    curl -A "$user_agent" -Lso "$cwd/$archive_name" "$archive_url"
 fi
 
-#
-# CREATE OUTPUT DIRECTORY
-#
+# Create output directory
 
-if [ -d "${cwd}/${archive_dir}" ]; then
-    sudo rm -fr "${cwd}/${archive_dir}"
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
 fi
-mkdir -p "${cwd}/${archive_dir}/build"
+mkdir -p "$cwd/$archive_dir/build"
 
-#
-# EXTRACT ARCHIVE FILES
-#
+# Extract archive files
 
-if ! tar -xf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
+if ! tar -xf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/$archive_name"
     exit 1
 fi
 
-#
-# BUILD PROGRAM FROM SOURCE
-#
+# Build program from source
 
-cd "${cwd}/${archive_dir}/build" || exit 1
+cd "$cwd/$archive_dir/build" || exit 1
 ../configure                                                                       \
-    --prefix="${workspace}"                                                          \
+    --prefix="$workspace"                                                          \
     --arch="$(uname -m)"                                                           \
     --cpu="$((cpu_threads / 2))"                                                   \
     --cc="$CC"                                                                     \
@@ -310,10 +278,10 @@ cd "${cwd}/${archive_dir}/build" || exit 1
     --enable-{libvidstab,libvo-amrwbenc,libvorbis,libvpx,libwebp,libx264,libx265}  \
     --enable-{libxml2,libxvid,opengl,openssl,version3,lto,pthreads}                \
     --enable-{ffnvcodec,gpl,nonfree,small,static,version3}                         \
-    --extra-cflags="${CFLAGS}"                                                       \
-    --extra-cxxflags="${CXXFLAGS}"                                                   \
-    --extra-ldflags="${LDFLAGS}"                                                    \
-    --extra-libs="${LIBS}"                                                           \
+    --extra-cflags="$CFLAGS"                                                       \
+    --extra-cxxflags="$CXXFLAGS"                                                   \
+    --extra-ldflags="$LDFLAGS"                                                    \
+    --extra-libs="$LIBS"                                                           \
     --pkg-config="$(type -P pkg-config)"                                           \
     --pkg-config-flags='--static'                                                  \
     --strip="$(type -P strip)"
@@ -327,14 +295,14 @@ if [ -f /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-16.1.so ]; then
     fi
 fi
 
-# SHOW THE NEW FFMPEG VERSION
+# Show the new ffmpeg version
 ff_ver_fn
 
-# MOVE THE FILES TO /USR/LOCAL/BIN
+# Move the files to /usr/local/bin
 ff_move_fn
 
-# PROMPT USER TO CLEAN UP FILES
+# Prompt user to clean up files
 cleanup_fn
 
-# SHOW EXIT MESSAGE
+# Show exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GNU Software/build-eog b/Bash/Installer Scripts/GNU Software/build-eog
--- a/Bash/Installer Scripts/GNU Software/build-eog
+++ b/Bash/Installer Scripts/GNU Software/build-eog
@@ -1,33 +1,22 @@
-#!/usr/bin/env bash
+#!/Usr/bin/env bash
 
-##########################################################################################################################
-##
-##  GitHub Script: https://github.com/slyfox1186/script-repo/edit/main/Bash/Installer%20Scripts/GNU%20Software/build-eog
-##
+##  Github script: https://github.com/slyfox1186/script-repo/edit/main/bash/installer%20scripts/gnu%20software/build-eog
 ##  Purpose: build gnu eye of gnome (aka eog)
-##
 ##  Updated: 08.31.23
-##
 ##  Script version: 1.1
-##
-##########################################################################################################################
 
-clear
-
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+if [ "$EUID" -eq 0 ]; then
+    echo "You must run this script without root or sudo."
     exit 1
 fi
 
-#
-# SET THE VARIABLES
-#
+# Set the variables
 
 script_ver=1.1
 archive_dir=eog
 archive_url=https://download.gnome.org/sources/eog/44/eog-44.3.tar.xz
-archive_ext="${archive_url//*.}"
-archive_name="$archive_dir.tar.${archive_ext}"
+archive_ext="$archive_url//*."
+archive_name="$archive_dir.tar.$archive_ext"
 cwd="$PWD"/eog-build-script
 install_dir=/usr/local
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
@@ -35,39 +24,30 @@ web_repo=https://github.com/slyfox1186/script-repo
 debug=OFF
 
 printf "%s\n%s\n\n" \
-    "eog build script - v${script_ver}" \
+    "eog build script - v$script_ver" \
     '==============================================='
 
-#
-# CREATE OUTPUT DIRECTORY
-#
-
+# Create output directory
 if [ -d "$cwd" ]; then
     sudo rm -fr "$cwd"
 fi
 mkdir -p "$cwd"
 
-#
-# SET THE C + CPP COMPILERS
-#
+# Set the c + cpp compilers
+set_compiler_options() {
+    CC="ccache gcc"
+    CXX="ccache g++"
+    CFLAGS="-g -O3 -pipe -fno-plt -march=native"
+    CXXFLAGS="-g -O3 -pipe -fno-plt -march=native"
+    export CC CFLAGS CXX CXXFLAGS
+}
 
-export CC=gcc CXX=g++
-
-#
-# SET COMPILER OPTIMIZATION FLAGS
-#
-
-export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -march=native'
-
-#
-# SET THE PATH VARIABLE
-#
-
+# Set the path variable
 PATH="\
 /usr/lib/ccache:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
+$HOME/perl5/bin:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -82,9 +62,7 @@ ${HOME}/.local/bin:\
 "
 export PATH
 
-#
-# SET THE PKG_CONFIG_PATH VARIABLE
-#
+# Set the pkg_config_path variable
 
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
@@ -101,9 +79,7 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
-#
-# SET THE LIBRARY_PATH VARIABLE
-#
+# Set the library_path variable
 
 LIBRARY_PATH="\
 /usr/lib/x86_64-linux-gnu:\
@@ -111,28 +87,23 @@ $LIBRARY_PATH\
 "
 export LIBRARY_PATH
 
-#
-# CREATE FUNCTIONS
-#
+# Create functions
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
         "$web_repo"
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n%s\n\n%s\n\n" \
         "$1" \
         "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local choice
 
     printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
@@ -143,8 +114,8 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "${choice}" in
-        1)      sudo rm -fr "$cwd" "${0}";;
+    case "$choice" in
+        1)      sudo rm -fr "$cwd" "$0";;
         2)      echo;;
         *)
                 clear
@@ -157,9 +128,7 @@ cleanup_fn()
     esac
 }
 
-#
-# INSTALL REQUIRED APT PACKAGES
-#
+# Install required apt packages
 
 pkgs=(autoconf autoconf-archive autogen automake binutils build-essential ccache clang
       cmake curl git libgnome-desktop-3-dev libexempi-dev libportal-dev libportal-gtk3-dev
@@ -168,10 +137,10 @@ pkgs=(autoconf autoconf-archive autogen automake binutils build-essential ccache
 
 for i in ${pkgs[@]}
 do
-    missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
+    missing_pkg="$(sudo dpkg -l | grep -o "$i")"
 
-    if [ -z "${missing_pkg}" ]; then
-        missing_pkgs+=" ${i}"
+    if [ -z "$missing_pkg" ]; then
+        missing_pkgs+=" $i"
     fi
 done
 
@@ -181,27 +150,21 @@ if [ -n "$missing_pkgs" ]; then
     clear
 fi
 
-#
-# DOWNLOAD THE ARCHIVE FILE
-#
+# Download the archive file
 
-if [ ! -f "$cwd/${archive_name}" ]; then
-    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/$archive_name" ]; then
+    curl -Lso "$cwd/$archive_name" "$archive_url"
 fi
 mkdir -p "$cwd/$archive_dir/build"
 
-#
-# EXTRACT ARCHIVE FILES
-#
+# Extract archive files
 
-if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
-    fail_fn "Failed to extract: $cwd/${archive_name}"
+if ! tar -xf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
+    fail_fn "Failed to extract: $cwd/$archive_name"
     exit 1
 fi
 
-#
-# BUILD PROGRAM FROM SOURCE
-#
+# Build program from source
 
 clear
 cd "$cwd/$archive_dir" || exit 1
@@ -211,12 +174,12 @@ meson setup build --prefix="$install_dir" \
                   --strip
 ninja "-j$(nproc --all)" -C build
 if ! sudo ninja "-j$(nproc --all)" -C build install; then
-    fail_fn "Failed to execute: sudo ninja -j$(nproc --all) -C build install:Line ${LINENO}"
+    fail_fn "Failed to execute: sudo ninja -j$(nproc --all) -C build install:Line $LINENO"
     exit 1
 fi
 
-# PROMPT USER TO CLEAN UP FILES
+# Prompt user to clean up files
 cleanup_fn
 
-# SHOW EXIT MESSAGE
+# Show exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GNU Software/build-make b/Bash/Installer Scripts/GNU Software/build-make
--- a/Bash/Installer Scripts/GNU Software/build-make
+++ b/Bash/Installer Scripts/GNU Software/build-make
@@ -1,65 +1,55 @@
-#!/usr/bin/env bash
+#!/Usr/bin/env bash
 
-##  GitHub Script: https://github.com/slyfox1186/script-repo/edit/main/Bash/Installer%20Scripts/GNU%20Software/build-make
+##  Github script: https://github.com/slyfox1186/script-repo/edit/main/bash/installer%20scripts/gnu%20software/build-make
 ##  Purpose: build gnu make
 ##  Updated: 08.01.23
 ##  Script version: 1.1
 
 clear
 
-if [ "${EUID}" -ne '0' ]; then
-    printf "%s\n\n" 'You must run this script with root/sudo.'
+if [ "$EUID" -ne '0' ]; then
+    echo "You must run this script with root or sudo."
     exit 1
 fi
 
-#
-# SET THE VARIABLES
-#
+# Set the variables
 
 script_ver=1.1
 archive_dir=make-4.4.1
 archive_url=https://ftp.gnu.org/gnu/make/make-4.4.1.tar.lz
-archive_ext="${archive_url//*.}"
-archive_name="$archive_dir.tar.${archive_ext}"
+archive_ext="$archive_url//*."
+archive_name="$archive_dir.tar.$archive_ext"
 cwd="$PWD"/make-build-script
 install_dir=/usr/local
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
 
 printf "%s\n%s\n\n" \
-    "make build script - v${script_ver}" \
+    "make build script - v$script_ver" \
     '==============================================='
 
-#
-# CREATE OUTPUT DIRECTORY
-#
+# Create output directory
 
 if [ -d "$cwd" ]; then
     rm -fr "$cwd"
 fi
 mkdir -p "$cwd"
 
-#
-# SET THE C + CPP COMPILERS
-#
+# Set the c + cpp compilers
 
 export CC=gcc CXX=g++
 
-#
-# SET COMPILER OPTIMIZATION FLAGS
-#
+# Set compiler optimization flags
 
-export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -march=native'
+export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -fno-plt -march=native'
 
-#
-# SET THE PATH VARIABLE
-#
+# Set the path variable
 
 PATH="\
 /usr/lib/ccache:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
+$HOME/perl5/bin:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -74,9 +64,7 @@ ${HOME}/.local/bin:\
 "
 export PATH
 
-#
-# SET THE PKG_CONFIG_PATH VARIABLE
-#
+# Set the pkg_config_path variable
 
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
@@ -93,28 +81,23 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
-#
-# CREATE FUNCTIONS
-#
+# Create functions
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
         "$web_repo"
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n%s\n\n%s\n\n" \
         "$1" \
         "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local choice
 
     printf "\n%s\n%s\n%s\n\n%s\n%s\n\n" \
@@ -125,7 +108,7 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "${choice}" in
+    case "$choice" in
         1)      rm -fr "$cwd";;
         2)      echo;;
         *)
@@ -139,9 +122,7 @@ cleanup_fn()
     esac
 }
 
-#
-# INSTALL REQUIRED APT PACKAGES
-#
+# Install required apt packages
 
 pkgs=(autoconf autoconf-archive autogen automake binutils build-essential ccache cmake
       curl git guile-3.0-dev libdmalloc-dev libdmalloc5 libgmp-dev libintl-perl libmpfr-dev
@@ -150,10 +131,10 @@ pkgs=(autoconf autoconf-archive autogen automake binutils build-essential ccache
 
 for i in ${pkgs[@]}
 do
-    missing_pkg="$(dpkg -l | grep -o "${i}")"
+    missing_pkg="$(dpkg -l | grep -o "$i")"
 
-    if [ -z "${missing_pkg}" ]; then
-        missing_pkgs+=" ${i}"
+    if [ -z "$missing_pkg" ]; then
+        missing_pkgs+=" $i"
     fi
 done
 
@@ -163,35 +144,27 @@ if [ -n "$missing_pkgs" ]; then
     clear
 fi
 
-#
-# DOWNLOAD THE ARCHIVE FILE
-#
+# Download the archive file
 
-if [ ! -f "$cwd/${archive_name}" ]; then
-    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/$archive_name" ]; then
+    curl -A "$user_agent" -Lso "$cwd/$archive_name" "$archive_url"
 fi
 
-#
-# CREATE OUTPUT DIRECTORY
-#
+# Create output directory
 
 if [ -d "$cwd/$archive_dir" ]; then
     rm -fr "$cwd/$archive_dir"
 fi
 mkdir -p "$cwd/$archive_dir/build"
 
-#
-# EXTRACT ARCHIVE FILES
-#
+# Extract archive files
 
-if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
+if ! tar -xf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/$archive_name"
     exit 1
 fi
 
-#
-# BUILD PROGRAM FROM SOURCE
-#
+# Build program from source
 
 cd "$cwd/$archive_dir" || exit 1
 autoreconf -fi -I /usr/share/aclocal
@@ -206,12 +179,12 @@ cd build || exit 1
              PKG_CONFIG="$(type -P pkg-config)"
 make "-j$(nproc --all)"
 if ! make install; then
-    fail_fn "Failed to execute: make install:Line ${LINENO}"
+    fail_fn "Failed to execute: make install:Line $LINENO"
     exit 1
 fi
 
-# PROMPT USER TO CLEAN UP FILES
+# Prompt user to clean up files
 cleanup_fn
 
-# SHOW EXIT MESSAGE
+# Show exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GNU Software/build-nano b/Bash/Installer Scripts/GNU Software/build-nano
--- a/Bash/Installer Scripts/GNU Software/build-nano
+++ b/Bash/Installer Scripts/GNU Software/build-nano
@@ -1,8 +1,8 @@
-#!/usr/bin/env bash
+#!/Usr/bin/env bash
 
 ###########################################################################################################
 ##
-##  GitHub Script: https://github.com/slyfox1186/script-repo/edit/main/Bash/Installer%20Scripts/GNU%20Software/build-nano
+##  Github script: https://github.com/slyfox1186/script-repo/edit/main/bash/installer%20scripts/gnu%20software/build-nano
 ##
 ##  Purpose: build gnu nano
 ##
@@ -14,59 +14,49 @@
 
 clear
 
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+if [ "$EUID" -eq '0' ]; then
+    echo "You must run this script without root or sudo."
     exit 1
 fi
 
-#
-# SET THE VARIABLES
-#
+# Set the variables
 
 script_ver=1.0
 archive_dir=nano-7.2
 archive_url=https://ftp.gnu.org/gnu/nano/nano-7.2.tar.xz
-archive_ext="${archive_url//*.}"
-archive_name="$archive_dir.tar.${archive_ext}"
+archive_ext="$archive_url//*."
+archive_name="$archive_dir.tar.$archive_ext"
 cwd="$PWD"/nano-build-script
 install_dir=/usr/local
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
 
 printf "%s\n%s\n\n" \
-    "nano build script - v${script_ver}" \
+    "nano build script - v$script_ver" \
     '==============================================='
 
-#
-# CREATE OUTPUT DIRECTORY
-#
+# Create output directory
 
 if [ -d "$cwd" ]; then
     sudo rm -fr "$cwd"
 fi
 mkdir -p "$cwd"
 
-#
-# SET THE C + CPP COMPILERS
-#
+# Set the c + cpp compilers
 
 export CC=gcc CXX=g++
 
-#
-# SET COMPILER OPTIMIZATION FLAGS
-#
+# Set compiler optimization flags
 
-export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -march=native'
+export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -fno-plt -march=native'
 
-#
-# SET THE PATH VARIABLE
-#
+# Set the path variable
 
 PATH="\
 /usr/lib/ccache:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
+$HOME/perl5/bin:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -81,9 +71,7 @@ ${HOME}/.local/bin:\
 "
 export PATH
 
-#
-# SET THE PKG_CONFIG_PATH VARIABLE
-#
+# Set the pkg_config_path variable
 
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
@@ -100,28 +88,23 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
-#
-# CREATE FUNCTIONS
-#
+# Create functions
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
         "$web_repo"
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n%s\n\n%s\n\n" \
         "$1" \
         "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local choice
 
     printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
@@ -132,7 +115,7 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "${choice}" in
+    case "$choice" in
         1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
@@ -146,9 +129,7 @@ cleanup_fn()
     esac
 }
 
-#
-# INSTALL REQUIRED APT PACKAGES
-#
+# Install required apt packages
 
 pkgs=("$1" autoconf autoconf-archive autogen automake binutils bison build-essential bzip2 ccache curl
       libc6-dev libintl-perl libpth-dev libticonv-dev libtool libtool-bin lzip lzma-dev m4 nasm texinfo
@@ -156,10 +137,10 @@ pkgs=("$1" autoconf autoconf-archive autogen automake binutils bison build-essen
 
 for i in ${pkgs[@]}
 do
-    missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
+    missing_pkg="$(sudo dpkg -l | grep -o "$i")"
 
-    if [ -z "${missing_pkg}" ]; then
-        missing_pkgs+=" ${i}"
+    if [ -z "$missing_pkg" ]; then
+        missing_pkgs+=" $i"
     fi
 done
 
@@ -169,35 +150,27 @@ if [ -n "$missing_pkgs" ]; then
     clear
 fi
 
-#
-# DOWNLOAD THE ARCHIVE FILE
-#
+# Download the archive file
 
-if [ ! -f "$cwd/${archive_name}" ]; then
-    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/$archive_name" ]; then
+    curl -A "$user_agent" -Lso "$cwd/$archive_name" "$archive_url"
 fi
 
-#
-# CREATE OUTPUT DIRECTORY
-#
+# Create output directory
 
 if [ -d "$cwd/$archive_dir" ]; then
     sudo rm -fr "$cwd/$archive_dir"
 fi
 mkdir -p "$cwd/$archive_dir/build"
 
-#
-# EXTRACT ARCHIVE FILES
-#
+# Extract archive files
 
-if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
+if ! tar -xf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/$archive_name"
     exit 1
 fi
 
-#
-# BUILD PROGRAM FROM SOURCE
-#
+# Build program from source
 
 cd "$cwd/$archive_dir" || exit 1
 autoreconf -fi
@@ -211,15 +184,15 @@ cd build || exit 1
              --with-libiconv-prefix=/usr        \
              --with-libintl-prefix=/usr         \
              PKG_CONFIG="$(type -P pkg-config)" \
-             PKG_CONFIG_PATH="${PKG_CONFIG_PATH}"
+             PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
 make "-j$(nproc --all)"
 if ! sudo make install; then
-    fail_fn "Failed to execute: sudo make install:Line ${LINENO}"
+    fail_fn "Failed to execute: sudo make install:Line $LINENO"
     exit 1
 fi
 
-# PROMPT USER TO CLEAN UP FILES
+# Prompt user to clean up files
 cleanup_fn
 
-# SHOW EXIT MESSAGE
+# Show exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GNU Software/build-wget b/Bash/Installer Scripts/GNU Software/build-wget
--- a/Bash/Installer Scripts/GNU Software/build-wget
+++ b/Bash/Installer Scripts/GNU Software/build-wget
@@ -1,7 +1,7 @@
-#!/usr/bin/env bash
+#!/Usr/bin/env bash
 
-# GitHub Script: https://github.com/slyfox1186/script-repo/edit/main/util-linux/Installer%20Scripts/GNU%20Software/build-wget
-# Purpose: Build GNU Wget from source code
+# Github script: https://github.com/slyfox1186/script-repo/edit/main/util-linux/installer%20scripts/gnu%20software/build-wget
+# Purpose: build gnu wget from source code
 # Features: +cares +digest +gpgme +https -ipv6 +iri +large-file +metalink -nls +ntlm +opie +psl +ssl/openssl
 # Updated: 01.30.24
 # Script version: 1.4
@@ -11,11 +11,11 @@
 RED='\033[0;31m'
 GREEN='\033[0;32m'
 YELLOW='\033[0;33m'
-NC='\033[0m' # No Color
+NC='\033[0m' # No color
 
 # Ensure running as root
 if [ "$EUID" -ne 0 ]; then
-    echo -e "${RED}This script must be run as root. Exiting.${NC}" >&2
+    echo -e "$REDThis script must be run as root. Exiting.$NC" >&2
     exit 1
 fi
 
@@ -40,17 +40,17 @@ display_help() {
 
 log() {
     if [[ $verbose -eq 1 ]]; then
-        echo -e "${GREEN}[INFO]${NC} $1"
+        echo -e "$GREEN[INFO]$NC $1"
     fi
 }
 
 error() {
-    echo -e "${RED}[ERROR]${NC} $1" >&2
+    echo -e "$RED[ERROR]$NC $1" >&2
     exit 1
 }
 
 warn() {
-    echo -e "${YELLOW}[WARN]${NC} $1"
+    echo -e "$YELLOW[WARN]$NC $1"
 }
 
 check_dependencies() {
@@ -105,7 +105,7 @@ cleanup() {
 
 # Parse command line arguments
 parse_args() {
-    while (( "$#" )); do
+    while (( "$#" )); Do
         case "$1" in
             -v|--verbose)
                 verbose=1
diff --git a/Bash/Installer Scripts/GitHub Projects/build-adobe-fonts b/Bash/Installer Scripts/GitHub Projects/build-adobe-fonts
--- a/Bash/Installer Scripts/GitHub Projects/build-adobe-fonts
+++ b/Bash/Installer Scripts/GitHub Projects/build-adobe-fonts
@@ -1,8 +1,8 @@
-#!/usr/bin/env bash
+#!/Usr/bin/env bash
 
 ####################################################################################################################################################
 ##
-##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/SlyFox1186%20Scripts/install-adobe-sans+pro+serif-fonts.sh
+##  Github script: https://github.com/slyfox1186/script-repo/blob/main/bash/installer%20scripts/slyfox1186%20scripts/install-adobe-sans+pro+serif-fonts.sh
 ##
 ##  Purpose: install adobe-sans + adobe-pro fonts system wide
 ##
@@ -14,14 +14,12 @@
 
 clear
 
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+if [ "$EUID" -eq '0' ]; then
+    echo "You must run this script without root or sudo."
     exit 1
 fi
 
-#
-# SET THE VARIABLES
-#
+# Set the variables
 
 script_ver=1.1
 pro_url=https://github.com/adobe-fonts/source-code-pro/archive/refs/tags/2.042R-u/1.062R-i/1.026R-vf.tar.gz
@@ -37,136 +35,117 @@ install_dir_serif=/usr/local/share/fonts/adobe-serif
 user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
 
-# sudo rm -fr /usr/local/share/fonts/adobe-pro /usr/local/share/fonts/adobe-sans /usr/local/share/fonts/adobe-serif
+# Sudo rm -fr /usr/local/share/fonts/adobe-pro /usr/local/share/fonts/adobe-sans /usr/local/share/fonts/adobe-serif
 
-#
-# PRINT SCRIPT BANNER
-#
+# Print script banner
 
-box_out_banner_header()
-{
+box_out_banner_header() {
     input_char=$(echo "$@" | wc -c)
-    line=$(for i in $(seq 0 ${input_char}); do printf "-"; done)
+    line=$(for i in $(seq 0 $input_char); do printf "-"; done)
     tput bold
     line="$(tput setaf 3)$line"
-    space=${line//-/ }
+    space=$line//-/ 
     echo " $line"
-    printf '|' ; echo -n "${space}" ; printf "%s\n" '|';
+    printf '|' ; echo -n "$space" ; printf "%s\n" '|';
     printf '| ' ;tput setaf 4; echo -n "$@"; tput setaf 3 ; printf "%s\n" ' |';
-    printf '|' ; echo -n "${space}" ; printf "%s\n" '|';
+    printf '|' ; echo -n "$space" ; printf "%s\n" '|';
     echo " $line"
     tput sgr 0
 }
-box_out_banner_header "Installer Script - Adobe-Sans & Adobe-Pro Fonts - version ${script_ver}"
+box_out_banner_header "Installer Script - Adobe-Sans & Adobe-Pro Fonts - version $script_ver"
 
-printf "\n%s\n\n" "The script will utilize (${cpu_threads}) CPU threads for parallel processing to accelerate the build speed."
+printf "\n%s\n\n" "The script will utilize ($cpu_threads) CPU threads for parallel processing to accelerate the build speed."
 
-#
-# CREATE FUNCTIONS
-#
+# Create functions
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
         "$web_repo"
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n%s\n\n%s\n\n" \
         "$1" \
         "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
-#
-# CREATE OR DELETE OLD OUTPUT DIRECTORIES FROM PREVIOUS RUNS
-#
+# Create or delete old output directories from previous runs
 
-if [ -d "${pro_dir}" ] && [ -d "${sans_dir}" ] && [ -d "${serif_dir}" ]; then
-    sudo rm -fr "${pro_dir}" "${sans_dir}" "${serif_dir}"
+if [ -d "$pro_dir" ] && [ -d "$sans_dir" ] && [ -d "$serif_dir" ]; then
+    sudo rm -fr "$pro_dir" "$sans_dir" "$serif_dir"
 fi
-mkdir -p "${pro_dir}" "${sans_dir}" "${serif_dir}"
+mkdir -p "$pro_dir" "$sans_dir" "$serif_dir"
 
-#
-# CREATE THE FONT OUTPUT DIRECTORIES
-#
+# Create the font output directories
 
-sudo mkdir -p "${install_dir_pro}" "${install_dir_sans}" "${install_dir_serif}" 2>/dev/null
+sudo mkdir -p "$install_dir_pro" "$install_dir_sans" "$install_dir_serif" 2>/dev/null
 
-#
-# DOWNLOAD THE ARCHIVE FILES
-#
+# Download the archive files
 
-if [ ! -f "${pro_dir}".tar.gz ]; then
-    if ! wget --show-progress -t 2 -cqO "${pro_dir}".tar.gz "${pro_url}"; then
-        fail_fn "Failed to download the archive file \"${pro_dir}.tar.gz\". Line: ${LINENO}"
+if [ ! -f "$pro_dir".tar.gz ]; then
+    if ! wget --show-progress -t 2 -cqO "$pro_dir".tar.gz "$pro_url"; then
+        fail_fn "Failed to download the archive file \"$pro_dir.tar.gz\". Line: $LINENO"
     fi
 fi
 
-if [ ! -f "${sans_dir}".tar.gz ]; then
-    if ! wget --show-progress -t 2 -cqO "${sans_dir}".tar.gz "${sans_url}"; then
-        fail_fn "Failed to download the archive file \"${sans_dir}.tar.gz\". Line: ${LINENO}"
+if [ ! -f "$sans_dir".tar.gz ]; then
+    if ! wget --show-progress -t 2 -cqO "$sans_dir".tar.gz "$sans_url"; then
+        fail_fn "Failed to download the archive file \"$sans_dir.tar.gz\". Line: $LINENO"
     fi
 fi
-if [ ! -f "${serif_dir}".tar.gz ]; then
-    if ! wget --show-progress -t 2 -cqO "${serif_dir}".tar.gz "${sans_url}"; then
-        fail_fn "Failed to download the archive file \"${serif_dir}.tar.gz\". Line: ${LINENO}"
+if [ ! -f "$serif_dir".tar.gz ]; then
+    if ! wget --show-progress -t 2 -cqO "$serif_dir".tar.gz "$sans_url"; then
+        fail_fn "Failed to download the archive file \"$serif_dir.tar.gz\". Line: $LINENO"
     fi
 fi
 echo
 
-#
-# EXTRACT THE ARCHIVE FILES
-#
+# Extract the archive files
 
-if ! tar -zxf "${pro_dir}".tar.gz -C "${pro_dir}" --strip-components 1; then
-    fail_fn "Failed to extract the archive \"${pro_dir}.tar.gz\". Line: ${LINENO}"
+if ! tar -zxf "$pro_dir".tar.gz -C "$pro_dir" --strip-components 1; then
+    fail_fn "Failed to extract the archive \"$pro_dir.tar.gz\". Line: $LINENO"
 fi
-if ! tar -zxf "${sans_dir}".tar.gz -C "${sans_dir}" --strip-components 1; then
-    fail_fn "Failed to extract the archive \"${sans_dir}.tar.gz\". Line: ${LINENO}"
+if ! tar -zxf "$sans_dir".tar.gz -C "$sans_dir" --strip-components 1; then
+    fail_fn "Failed to extract the archive \"$sans_dir.tar.gz\". Line: $LINENO"
 fi
-if ! tar -zxf "${serif_dir}".tar.gz -C "${serif_dir}" --strip-components 1; then
-    fail_fn "Failed to extract the archive \"${serif_dir}.tar.gz\". Line: ${LINENO}"
+if ! tar -zxf "$serif_dir".tar.gz -C "$serif_dir" --strip-components 1; then
+    fail_fn "Failed to extract the archive \"$serif_dir.tar.gz\". Line: $LINENO"
 fi
 echo
 
-#
-# FIND AND MOVE THE FONT FILES TO THE OUTPUT FOLDER
-#
+# Find and move the font files to the output folder
 
-cd "${pro_dir}" || exit 1
-sudo find . -type f -name '*.ttf' -exec sudo mv -f '{}' "${install_dir_pro}" \;
-sudo find . -type f -name '*.otf' -exec sudo mv -f '{}' "${install_dir_pro}" \;
-sudo find . -type f -name '*.woff' -exec sudo mv -f '{}' "${install_dir_pro}" \;
-cd "${sans_dir}" || exit 1
-sudo find . -type f -name '*.ttf' -exec sudo mv -f '{}' "${install_dir_sans}" \;
-sudo find . -type f -name '*.otf' -exec sudo mv -f '{}' "${install_dir_sans}" \;
-sudo find . -type f -name '*.woff' -exec sudo mv -f '{}' "${install_dir_sans}" \;
-cd "${serif_dir}" || exit 1
-sudo find . -type f -name '*.ttf' -exec sudo mv -f '{}' "${install_dir_serif}" \;
-sudo find . -type f -name '*.otf' -exec sudo mv -f '{}' "${install_dir_serif}" \;
-sudo find . -type f -name '*.woff' -exec sudo mv -f '{}' "${install_dir_serif}" \;
+cd "$pro_dir" || exit 1
+sudo find . -type f -name '*.ttf' -exec sudo mv -f '{}' "$install_dir_pro" \;
+sudo find . -type f -name '*.otf' -exec sudo mv -f '{}' "$install_dir_pro" \;
+sudo find . -type f -name '*.woff' -exec sudo mv -f '{}' "$install_dir_pro" \;
+cd "$sans_dir" || exit 1
+sudo find . -type f -name '*.ttf' -exec sudo mv -f '{}' "$install_dir_sans" \;
+sudo find . -type f -name '*.otf' -exec sudo mv -f '{}' "$install_dir_sans" \;
+sudo find . -type f -name '*.woff' -exec sudo mv -f '{}' "$install_dir_sans" \;
+cd "$serif_dir" || exit 1
+sudo find . -type f -name '*.ttf' -exec sudo mv -f '{}' "$install_dir_serif" \;
+sudo find . -type f -name '*.otf' -exec sudo mv -f '{}' "$install_dir_serif" \;
+sudo find . -type f -name '*.woff' -exec sudo mv -f '{}' "$install_dir_serif" \;
 echo
 
-#
-# MAKE SURE THERE THE FILES WERE MOVED SUCCESSFULLY AND THEN UPDATE THE FONT CACHE
-#
+# Make sure there the files were moved successfully and then update the font cache
 
-if [ "$(sudo find "${install_dir_pro}" -type f -name '*.*' | wc -l)" -lt '64' ]; then
-    fail_fn "The script failed to extract 64 total fonts to the adobe-pro directory. Line: ${LINENO}"
-elif [ "$(sudo find "${install_dir_sans}" -type f -name '*.*' | wc -l)" -lt '64' ]; then
-    fail_fn "The script failed to extract 64 total fonts to the adobe-pro directory. Line: ${LINENO}"
-elif [ "$(sudo find "${install_dir_serif}" -type f -name '*.*' | wc -l)" -lt '64' ]; then
-    fail_fn "The script failed to extract 64 total fonts to the adobe-pro directory. Line: ${LINENO}"
+if [ "$(sudo find "$install_dir_pro" -type f -name '*.*' | wc -l)" -lt 64 ]; then
+    fail_fn "The script failed to extract 64 total fonts to the adobe-pro directory. Line: $LINENO"
+elif [ "$(sudo find "$install_dir_sans" -type f -name '*.*' | wc -l)" -lt 64 ]; then
+    fail_fn "The script failed to extract 64 total fonts to the adobe-pro directory. Line: $LINENO"
+elif [ "$(sudo find "$install_dir_serif" -type f -name '*.*' | wc -l)" -lt 64 ]; then
+    fail_fn "The script failed to extract 64 total fonts to the adobe-pro directory. Line: $LINENO"
 else
     sudo fc-cache -fv
 fi
 
-# CLEANUP THE LEFTOVER BUILD FILES
+# Cleanup the leftover build files
 sudo rm -fr "$cwd"
 
-# SHOW THE EXIT MESSAGE
+# Show the exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GitHub Projects/build-libhwy b/Bash/Installer Scripts/GitHub Projects/build-libhwy
--- a/Bash/Installer Scripts/GitHub Projects/build-libhwy
+++ b/Bash/Installer Scripts/GitHub Projects/build-libhwy
@@ -1,11 +1,11 @@
-#!/usr/bin/env bash
-# shellcheck source=/dev/null disable=SC2016,SC2034,SC2046,SC2066,SC2068,SC2086,SC2162,SC2317
+#!/Usr/bin/env bash
+# Shellcheck source=/dev/null disable=sc2016,sc2034,sc2046,sc2066,sc2068,sc2086,sc2162,sc2317
 
 ########################################################################
 ##
 ##  Install libhwy
 ##
-##  Supported OS:
+##  Supported os:
 ##               - Debian
 ##               - Ubuntu
 ##
@@ -17,14 +17,12 @@
 
 clear
 
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+if [ "$EUID" -eq '0' ]; then
+    echo "You must run this script without root or sudo."
     exit 1
 fi
 
-#
-# SET THE VARIABLES
-#
+# Set the variables
 
 script_ver=1.0
 install_prefix=/usr/local
@@ -36,15 +34,11 @@ user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Geck
 web_repo=https://github.com/slyfox1186/script-repo
 debug=OFF
 
-#
-# CREATE OUTPUT DIRECTORIES
-#
+# Create output directories
 
 mkdir -p "$packages" "$workspace"
 
-#
-# GET CPU CORE COUNT FOR PARALLEL PROCESSING
-#
+# Get cpu core count for parallel processing
 
 if [ -f /proc/cpuinfo ]; then
     cpu_threads="$(grep --count ^processor /proc/cpuinfo)"
@@ -52,42 +46,34 @@ else
     cpu_threads="$(nproc --all)"
 fi
 
-#
-# SET THE C & C++ COMPILERS
-#
+# Set the c & c++ compilers
 
 export CC=gcc CXX=g++
 
-#
-# SET COMPILER OPTIMIZATION FLAGS
-#
+# Set compiler optimization flags
 
-CFLAGS='-g -O3 -pipe -march=native'
-CXXFLAGS="${CFLAGS}"
+CFLAGS='-g -O3 -pipe -fno-plt -march=native'
+CXXFLAGS="$CFLAGS"
 CPPFLAGS="-I$workspace/include -I/usr/local/include -I/usr/include"
 LDFLAGS="-L$workspace/lib64 -L$workspace/lib -L$workspace/lib/x86_64-linux-gnu -L/usr/local/lib64"
 LDFLAGS+=' -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib64 -L/usr/lib -L/lib64 -L/lib'
 MAKEFLAGS="-j$(nproc --all)"
 export CFLAGS CPPFLAGS CXXFLAGS LDFLAGS MAKEFLAGS
 
-#
-# PRINT BANNER
-#
+# Print banner
 
 printf "%s\n%s\n%s\n" \
-    "libhwy build script - v${script_ver}" \
+    "libhwy build script - v$script_ver" \
     '=========================================' \
-    "This script will utilize (${cpu_threads}) CPU threads for parallel processing to accelerate the build process."
+    "This script will utilize ($cpu_threads) CPU threads for parallel processing to accelerate the build process."
 
-#
-# CREATE GLOBAL VARIABLES
-#
+# Create global variables
 
 PATH="\
 /usr/lib/ccache:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
+$HOME/perl5/bin:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -124,12 +110,9 @@ $workspace/share/pkgconfig:\
 "
 export PKG_CONFIG_PATH
 
-#
-# DEFINE FUNCTIONS
-#
+# Define functions
 
-fail_fn()
-{
+fail_fn() {
     printf "\n%s\n%s\n%s\n\n" \
         "$1" \
         'You can enable the script'\''s debugging feature by changing the variable "debug" to "ON"' \
@@ -137,16 +120,14 @@ fail_fn()
     exit 1
 }
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
         "$web_repo"
     exit 0
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local choice
  
     printf "\n%s\n\n%s\n%s\n\n" \
@@ -156,7 +137,7 @@ cleanup_fn()
     read -p 'Your choices are (1 or 2): ' choice
     clear
 
-    case "${choice}" in
+    case "$choice" in
         1)      sudo rm -fr "$cwd";;
         2)      clear;;
         *)
@@ -166,70 +147,64 @@ cleanup_fn()
     esac
 }
 
-#
-# SCRAPE GITHUB WEBSITE FOR THE LATEST REPO VERSION
-#
+# Scrape github website for the latest repo version
 
-git_1_fn()
-{
+git_1_fn() {
     local curl_cmd github_repo github_url
 
     github_repo="$1"
     github_url="$2"
 
-    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/$github_repo/$github_url")"; then
         g_ver="$(echo "$curl_cmd" | jq -r '.[0].name' 2>/dev/null)"
     fi
 
 }
 
-git_ver_fn()
-{
+git_ver_fn() {
     git_1_fn "$1" 'releases' 2>/dev/null
 }
 
-execute()
-{
-    echo "$ ${*}"
+execute() {
+    echo "$ $*"
 
-    if [ "${debug}" = 'ON' ]; then
+    if [ "$debug" = 'ON' ]; then
         if ! output=$("$@"); then
-            notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
-            fail_fn "Failed to execute: ${*}"
+            notify-send -t 5000 "Failed to execute: $*" 2>/dev/null
+            fail_fn "Failed to execute: $*"
         fi
     else
         if ! output=$("$@" 2>&1); then
-            notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
-            fail_fn "Failed to execute: ${*}"
+            notify-send -t 5000 "Failed to execute: $*" 2>/dev/null
+            fail_fn "Failed to execute: $*"
         fi
     fi
 }
 
-download()
-{
+download() {
     dl_path="$packages"
     dl_url="$1"
-    dl_file="${2:-"${1##*/}"}"
+    dl_file="$2:-"${1##*/"}"
 
     if [[ "$dl_file" =~ tar. ]]; then
-        output_dir="${dl_file%.*}"
-        output_dir="${3:-"${output_dir%.*}"}"
+        output_dir="$dl_file%.*"
+        output_dir="$3:-"${output_dir%.*"}"
     else
-        output_dir="${3:-"${dl_file%.*}"}"
+        output_dir="$3:-"${dl_file%.*"}"
     fi
 
     target_file="$dl_path/$dl_file"
     target_dir="$dl_path/$output_dir"
 
-    if [ -f "${target_file}" ]; then
+    if [ -f "$target_file" ]; then
         echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
-        if ! wget -U "$user_agent" -cqO "${target_file}" "${dl_url}"; then
+        echo "Downloading \"$dl_url\" saving as \"$dl_file\""
+        if ! wget -U "$user_agent" -cqO "$target_file" "$dl_url"; then
             printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! wget -U "$user_agent" -cqO "${target_file}" "${dl_url}"; then
-                fail_fn "The script failed to download \"$dl_file\" twice and will now exit. Line: ${LINENO}"
+            if ! wget -U "$user_agent" -cqO "$target_file" "$dl_url"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit. Line: $LINENO"
             fi
         fi
         echo 'Download Completed'
@@ -241,30 +216,29 @@ download()
     mkdir -p "$target_dir"
 
     if [ -n "$3" ]; then
-        if ! tar -zxf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
-            sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
+        if ! tar -zxf "$target_file" -C "$target_dir" 2>/dev/null >/dev/null; then
+            sudo rm "$target_file"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: $LINENO"
         fi
     else
-        if ! tar -zxf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
-            sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
+        if ! tar -zxf "$target_file" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
+            sudo rm "$target_file"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: $LINENO"
         fi
     fi
 
     printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: $LINENO"
 }
 
-download_git()
-{
+download_git() {
     local dl_path dl_url dl_file target_dir
 
     dl_path="$packages"
     dl_url="$1"
-    dl_file="${2:-"${1##*/}"}"
-    dl_file="${dl_file//\./-}"
+    dl_file="$2:-"${1##*/"}"
+    dl_file="$dl_file//\./-"
     target_dir="$dl_path/$dl_file"
 
     if [ -n "$3" ]; then
@@ -276,23 +250,22 @@ download_git()
         sudo rm -fr "$target_dir"
     fi
 
-    echo "Downloading ${dl_url} as $dl_file"
+    echo "Downloading $dl_url as $dl_file"
 
-    if ! git clone -q "${dl_url}" "$target_dir"; then
+    if ! git clone -q "$dl_url" "$target_dir"; then
         printf "\n%s\n\n" "The script failed to clone the directory \"$target_dir\" and will try again in 10 seconds..."
         sleep 10
-        if ! git clone -q "${dl_url}" "$target_dir"; then
-            fail_fn "The script failed to clone the directory \"$target_dir\" twice and will now exit the buildLine: ${LINENO}"
+        if ! git clone -q "$dl_url" "$target_dir"; then
+            fail_fn "The script failed to clone the directory \"$target_dir\" twice and will now exit the buildLine: $LINENO"
         fi
     else
         printf "%s\n\n" "Successfully cloned: $target_dir"
     fi
 
-    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: $LINENO"
 }
 
-build()
-{
+build() {
     printf "\n%s\n%s\n" \
         "building $1 - version $2" \
         '===================================='
@@ -310,14 +283,12 @@ build()
     return 0
 }
 
-build_done()
-{
+build_done() {
     echo "$2" > "$packages/$1.done"
 }
 
-installed()
-{
-    return $(dpkg-query -W -f '${Status}\n' "$1" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}')
+installed() {
+    return $(dpkg-query -W -f '$Status\n' "$1" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}')
 }
 
 find_lsb_release="$(sudo find /usr -type f -name 'lsb_release')"
@@ -327,21 +298,18 @@ if [ -f /etc/os-release ]; then
     OS_TMP="$NAME"
     VER_TMP="$VERSION_ID"
     CODENAME="$VERSION_CODENAME"
-    OS="$(echo "${OS_TMP}" | awk '{print $1}')"
-    VER="$(echo "${VER_TMP}" | awk '{print $1}')"
-elif [ -n "${find_lsb_release}" ]; then
+    OS="$(echo "$OS_TMP" | awk '{print $1}')"
+    VER="$(echo "$VER_TMP" | awk '{print $1}')"
+elif [ -n "$find_lsb_release" ]; then
     OS="$(lsb_release -d | awk '{print $2}')"
     VER="$(lsb_release -r | awk '{print $2}')"
 else
-    fail_fn "Failed to define the \$OS and/or \$VER variables. Line: ${LINENO}"
+    fail_fn "Failed to define the \$OS and/or \$VER variables. Line: $LINENO"
 fi
 
-#
-# INSTALL REQUIRED APT/PACMAN PACKAGES
-#
+# Install required apt/pacman packages
 
-pkgs_arch_fn()
-{
+pkgs_arch_fn() {
     pkgs=(autoconf autoconf-archive autogen automake xorg-util-macros autogen
           base-devel ccache cmake curl git gtest jq libtool m4 ninja openssl
           pkg-config python python-pip python-setuptools qt6-base)
@@ -352,10 +320,10 @@ pkgs_arch_fn()
 
     for i in ${pkgs[@]}
     do
-        missing_pkg="$(sudo pacman -Qi | grep -o "${i}")"
+        missing_pkg="$(sudo pacman -Qi | grep -o "$i")"
 
-        if [ -z "${missing_pkg}" ]; then
-            missing_pkgs+=" ${i}"
+        if [ -z "$missing_pkg" ]; then
+            missing_pkgs+=" $i"
         fi
     done
 
@@ -364,25 +332,24 @@ pkgs_arch_fn()
     fi
 
     rm_pip_lock="$(sudo find /usr/lib/python3* -type f -name 'EXTERNALLY-MANAGED')"
-    if [ -n "${rm_pip_lock}" ]; then
-        sudo rm "${rm_pip_lock}"
+    if [ -n "$rm_pip_lock" ]; then
+        sudo rm "$rm_pip_lock"
     fi
 
-    # INSTALL PYTHON PIP PACKAGES
+# Install python pip packages
     pip uninstall -q -y setuptools 2>/dev/null
     sudo pip install -q --no-input setuptools 2>/dev/null
 }
 
-pkgs_fn()
-{
+pkgs_fn() {
     pkgs=(autoconf autoconf-archive autogen automake autotools-dev
           build-essential ccache cmake curl libgtest-dev libtool
           libtool-bin m4 ninja-build pkg-config)
 
     for pkg in ${pkgs[@]}
     do
-        if ! installed "${pkg}"; then
-            missing_pkgs+=" ${pkg}"
+        if ! installed "$pkg"; then
+            missing_pkgs+=" $pkg"
         fi
     done
 
@@ -393,7 +360,7 @@ pkgs_fn()
     fi
 }
 
-case "${OS}" in
+case "$OS" in
     Arch)   pkgs_arch_fn;;
     *)      pkgs_fn;;
 esac
@@ -410,9 +377,7 @@ else
     printf "%s\n" 'The required APT packages are already installed.'
 fi
 
-#
-# BUILD LIBRARIES FROM SOURCE
-#
+# Build libraries from source
 
 git_ver_fn 'google/highway' 'R'
 if build 'libhwy' "$g_ver"; then
@@ -428,16 +393,16 @@ if build 'libhwy' "$g_ver"; then
                   -DHWY_ENABLE_EXAMPLES=OFF \
                   -DHWY_FORCE_STATIC_LIBS=ON \
                   -G Ninja -Wno-dev
-    execute ninja "-j${cpu_threads}"
+    execute ninja "-j$cpu_threads"
     execute sudo ninja install
     build_done 'libhwy' "$g_ver"
 fi
 
-# LDCONFIG MUST BE RUN NEXT IN ORDER TO UPDATE FILE CHANGES OR THE VERSION COMMANDS MIGHT NOT WORK
+# Ldconfig must be run next in order to update file changes or the version commands might not work
 sudo ldconfig 2>/dev/null
 
-# CLEANUP LEFTOVER FILES
+# Cleanup leftover files
 cleanup_fn
 
-# DISPLAY EXIT MESSAGE
+# Display exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GitHub Projects/build-libpng b/Bash/Installer Scripts/GitHub Projects/build-libpng
--- a/Bash/Installer Scripts/GitHub Projects/build-libpng
+++ b/Bash/Installer Scripts/GitHub Projects/build-libpng
@@ -1,11 +1,11 @@
-#!/usr/bin/env bash
-# shellcheck disable=SC2162,SC2317
+#!/Usr/bin/env bash
+# Shellcheck disable=sc2162,sc2317
 
 ###########################################################################################################
 ##
-##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-libpng
+##  Github script: https://github.com/slyfox1186/script-repo/blob/main/bash/installer%20scripts/github%20projects/build-libpng
 ##
-##  Purpose: Build GNU libpng
+##  Purpose: build gnu libpng
 ##
 ##  Updated: 08.31.23
 ##
@@ -15,14 +15,12 @@
 
 clear
 
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+if [ "$EUID" -eq '0' ]; then
+    echo "You must run this script without root or sudo."
     exit 1
 fi
 
-#
-# SET VARIABLES
-#
+# Set variables
 
 script_ver=1.1
 cwd="$PWD"/libpng-build-script
@@ -32,39 +30,31 @@ web_repo=https://github.com/slyfox1186/script-repo
 debug=OFF
 
 printf "\n%s\n%s\n\n" \
-    "libpng build script - v${script_ver}" \
+    "libpng build script - v$script_ver" \
     '==============================================='
 
-#
-# CREATE OUTPUT DIRECTORY
-#
+# Create output directory
 
 if [ -d "$cwd" ]; then
     sudo rm -fr "$cwd"
 fi
 mkdir -p "$cwd"
 
-#
-# SET THE C+CPP COMPILERS
-#
+# Set the c+cpp compilers
 
 export CC=gcc CXX=g++
 
-#
-# SET COMPILER OPTIMIZATION FLAGS
-#
+# Set compiler optimization flags
 
-export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -march=native'
+export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -fno-plt -march=native'
 
-#
-# SET THE PATH VARIABLE
-#
+# Set the path variable
 
 PATH="\
 /usr/lib/ccache:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
+$HOME/perl5/bin:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -79,9 +69,7 @@ ${HOME}/.local/bin:\
 "
 export PATH
 
-#
-# SET THE PKG_CONFIG_PATH VARIABLE
-#
+# Set the pkg_config_path variable
 
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
@@ -98,28 +86,23 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
-#
-# CREATE FUNCTIONS
-#
+# Create functions
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
         "$web_repo"
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n%s\n\n%s\n\n" \
         "$1" \
         "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local choice
 
     printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
@@ -130,7 +113,7 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "${choice}" in
+    case "$choice" in
         1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
@@ -144,8 +127,7 @@ cleanup_fn()
     esac
 }
 
-build()
-{
+build() {
     printf "\n%s\n%s\n" \
         "building $1 - version $2" \
         '===================================='
@@ -154,7 +136,7 @@ build()
         if grep -Fx "$2" "$cwd/$1.done" >/dev/null; then
             echo "$1 version $2 already built. Remove $cwd/$1.done lockfile to rebuild it."
             return 1
-        elif ${latest}; then
+        elif $latest; then
             echo "$1 is oudebugtdated and will be rebuilt using version $2"
             return 0
         else
@@ -165,48 +147,46 @@ build()
     return 0
 }
 
-execute()
-{
-    echo "$ ${*}"
+execute() {
+    echo "$ $*"
 
-    if [ "${debug}" = 'ON' ]; then
+    if [ "$debug" = 'ON' ]; then
         if ! output=$("$@"); then
-            notify-send 5000 "Failed to execute: ${*}"
-            fail_fn "Failed to execute: ${*}"
+            notify-send 5000 "Failed to execute: $*"
+            fail_fn "Failed to execute: $*"
         fi
     else
         if ! output=$("$@" 2>&1); then
-            notify-send 5000 "Failed to execute: ${*}"
-            fail_fn "Failed to execute: ${*}"
+            notify-send 5000 "Failed to execute: $*"
+            fail_fn "Failed to execute: $*"
         fi
     fi
 }
 
-download()
-{
+download() {
     dl_path="$cwd"
     dl_url="$1"
-    dl_file="${2:-"${1##*/}"}"
+    dl_file="$2:-"${1##*/"}"
 
     if [[ "$dl_file" =~ tar. ]]; then
-        output_dir="${dl_file%.*}"
-        output_dir="${3:-"${output_dir%.*}"}"
+        output_dir="$dl_file%.*"
+        output_dir="$3:-"${output_dir%.*"}"
     else
-        output_dir="${3:-"${dl_file%.*}"}"
+        output_dir="$3:-"${dl_file%.*"}"
     fi
 
     target_file="$dl_path/$dl_file"
     target_dir="$dl_path/$output_dir"
 
-    if [ -f "${target_file}" ]; then
+    if [ -f "$target_file" ]; then
         echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
-        if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+        echo "Downloading \"$dl_url\" saving as \"$dl_file\""
+        if ! curl -A "$user_agent" -Lso "$target_file" "$dl_url"; then
             printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
-                fail_fn "The script failed to download \"$dl_file\" twice and will now exit:Line ${LINENO}"
+            if ! curl -A "$user_agent" -Lso "$target_file" "$dl_url"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit:Line $LINENO"
             fi
         fi
         echo 'Download Completed'
@@ -219,38 +199,35 @@ download()
     mkdir -p "$target_dir"
 
     if [ -n "$3" ]; then
-        if ! tar -xf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
-            sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line ${LINENO}"
+        if ! tar -xf "$target_file" -C "$target_dir" 2>/dev/null >/dev/null; then
+            sudo rm "$target_file"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line $LINENO"
         fi
     else
-        if ! tar -xf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
-            sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line ${LINENO}"
+        if ! tar -xf "$target_file" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
+            sudo rm "$target_file"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line $LINENO"
         fi
     fi
 
     printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir:Line ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir:Line $LINENO"
 }
 
-#
-# INSTALL REQUIRED APT PACKAGES
-#
+# Install required apt packages
 
-pkgs_fn()
-{
+pkgs_fn() {
     pkgs=(asciidoc autogen automake binutils bison build-essential bzip2 ccache cmake
           curl libc6-dev libintl-perl libpth-dev libtool libtool-bin lzip lzma-dev
           nasm ninja-build texinfo xmlto yasm zlib1g-dev)
 
     for i in ${pkgs[@]}
     do
-        missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
+        missing_pkg="$(sudo dpkg -l | grep -o "$i")"
     
-        if [ -z "${missing_pkg}" ]; then
-            missing_pkgs+=" ${i}"
+        if [ -z "$missing_pkg" ]; then
+            missing_pkgs+=" $i"
         fi
     done
     
@@ -263,15 +240,11 @@ pkgs_fn()
 
 build_done() { echo "$2" > "$cwd/$1.done"; }
 
-#
-# INSTALL APT PACKAGES
-#
+# Install apt packages
 
 pkgs_fn
 
-#
-# BUILD PROGRAM FROM SOURCE
-#
+# Build program from source
 
 if build 'libpng' '1.6.40'; then
     download 'https://github.com/glennrp/libpng/archive/refs/tags/v1.6.40.tar.gz' 'libpng-1.6.40.tar.gz'
@@ -284,7 +257,7 @@ if build 'libpng' '1.6.40'; then
                          --enable-unversioned-links               \
                          --with-binconfigs                        \
                          --with-pic                               \
-                         --with-pkgconfigdir="${PKG_CONFIG_PATH}" \
+                         --with-pkgconfigdir="$PKG_CONFIG_PATH" \
                          --with-zlib-prefix
     execute make "-j$(nproc --all)"
     execute sudo make install-header-links
@@ -294,8 +267,8 @@ if build 'libpng' '1.6.40'; then
     build_done 'libpng' '1.6.40'
 fi
 
-# PROMPT USER TO CLEAN UP FILES
+# Prompt user to clean up files
 cleanup_fn
 
-# SHOW EXIT MESSAGE
+# Show exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GitHub Projects/build-libxml2 b/Bash/Installer Scripts/GitHub Projects/build-libxml2
--- a/Bash/Installer Scripts/GitHub Projects/build-libxml2
+++ b/Bash/Installer Scripts/GitHub Projects/build-libxml2
@@ -1,11 +1,11 @@
-#!/usr/bin/env bash
-# shellcheck disable=SC2162,SC2317
+#!/Usr/bin/env bash
+# Shellcheck disable=sc2162,sc2317
 
 ###########################################################################################################
 ##
-##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-libxml2
+##  Github script: https://github.com/slyfox1186/script-repo/blob/main/bash/installer%20scripts/github%20projects/build-libxml2
 ##
-##  Purpose: Build libxml2
+##  Purpose: build libxml2
 ##
 ##  Updated: 08.31.23
 ##
@@ -15,57 +15,47 @@
 
 clear
 
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+if [ "$EUID" -eq '0' ]; then
+    echo "You must run this script without root or sudo."
     exit 1
 fi
 
-#
-# SET VARIABLES
-#
+# Set variables
 
 script_ver=1.1
 cwd="$PWD"/libxml2-build-script
 install_dir=/usr/local
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
 web_repo='https://github.com/slyfox1186/script-repo'
-debug=OFF # CHANGE THE DEBUG VARIABLE TO "ON" FOR HELP TROUBLESHOOTING ISSUES
+debug=OFF # Change the debug variable to "on" for help troubleshooting issues
 
 printf "%s\n%s\n\n" \
-    "libxml2 build script - v${script_ver}" \
+    "libxml2 build script - v$script_ver" \
     '==============================================='
 sleep 2
 
-#
-# CREATE OUTPUT DIRECTORY
-#
+# Create output directory
 
 if [ -d "$cwd" ]; then
     sudo rm -fr "$cwd"
 fi
 mkdir -p "$cwd"
 
-#
-# SET THE C+CPP COMPILERS
-#
+# Set the c+cpp compilers
 
 export CC=gcc CXX=g++
 
-#
-# SET COMPILER OPTIMIZATION FLAGS
-#
+# Set compiler optimization flags
 
-export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -march=native'
+export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -fno-plt -march=native'
 
-#
-# SET THE PATH VARIABLE
-#
+# Set the path variable
 
 PATH="\
 /usr/lib/ccache:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
+$HOME/perl5/bin:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -80,9 +70,7 @@ ${HOME}/.local/bin:\
 "
 export PATH
 
-#
-# SET THE PKG_CONFIG_PATH VARIABLE
-#
+# Set the pkg_config_path variable
 
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
@@ -99,28 +87,23 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
-#
-# CREATE FUNCTIONS
-#
+# Create functions
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n\n"                                       \
         'Make sure to star this repository to show your support!' \
         "$web_repo"
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n%s\n\n%s\n\n" \
         "$1"              \
         "To report a bug create an issue at $web_repo/issues"
     exit 1
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local choice
 
     printf "%s\n%s\n%s\n\n%s\n%s\n\n"                  \
@@ -131,7 +114,7 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "${choice}" in
+    case "$choice" in
         1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
@@ -142,8 +125,7 @@ cleanup_fn()
     esac
 }
 
-build()
-{
+build() {
     printf "\n%s\n%s\n"                \
         "Building $1 - version $2" \
         '===================================='
@@ -160,48 +142,46 @@ build()
     return 0
 }
 
-execute()
-{
-    echo "$ ${*}"
+execute() {
+    echo "$ $*"
 
-    if [ "${debug}" = 'ON' ]; then
+    if [ "$debug" = 'ON' ]; then
         if ! output=$("$@"); then
-            notify-send 5000 "Failed to execute: ${*}" 2>/dev/null
-            fail_fn "Failed to execute: ${*}"
+            notify-send 5000 "Failed to execute: $*" 2>/dev/null
+            fail_fn "Failed to execute: $*"
         fi
     else
         if ! output=$("$@" 2>&1); then
-            notify-send 5000 "Failed to execute: ${*}" 2>/dev/null
-            fail_fn "Failed to execute: ${*}"
+            notify-send 5000 "Failed to execute: $*" 2>/dev/null
+            fail_fn "Failed to execute: $*"
         fi
     fi
 }
 
-download()
-{
+download() {
     dl_path="$cwd"
     dl_url="$1"
-    dl_file="${2:-"${1##*/}"}"
+    dl_file="$2:-"${1##*/"}"
 
     if [[ "$dl_file" =~ tar. ]]; then
-        output_dir="${dl_file%.*}"
-        output_dir="${3:-"${output_dir%.*}"}"
+        output_dir="$dl_file%.*"
+        output_dir="$3:-"${output_dir%.*"}"
     else
-        output_dir="${3:-"${dl_file%.*}"}"
+        output_dir="$3:-"${dl_file%.*"}"
     fi
 
     target_file="$dl_path/$dl_file"
     target_dir="$dl_path/$output_dir"
 
-    if [ -f "${target_file}" ]; then
+    if [ -f "$target_file" ]; then
         echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
-        if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
+        echo "Downloading \"$dl_url\" saving as \"$dl_file\""
+        if ! curl -A "$user_agent" -Lso "$target_file" "$dl_url"; then
             printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
-                fail_fn "The script failed to download \"$dl_file\" twice and will now exit:Line ${LINENO}"
+            if ! curl -A "$user_agent" -Lso "$target_file" "$dl_url"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit:Line $LINENO"
             fi
         fi
         echo 'Download Completed'
@@ -214,36 +194,33 @@ download()
     mkdir -p "$target_dir"
 
     if [ -n "$3" ]; then
-        if ! tar -xf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
-            sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line ${LINENO}"
+        if ! tar -xf "$target_file" -C "$target_dir" 2>/dev/null >/dev/null; then
+            sudo rm "$target_file"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line $LINENO"
         fi
     else
-        if ! tar -xf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
-            sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line ${LINENO}"
+        if ! tar -xf "$target_file" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
+            sudo rm "$target_file"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line $LINENO"
         fi
     fi
 
     printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir:Line ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir:Line $LINENO"
 }
 
-git_1_fn()
-{
+git_1_fn() {
     web_repo="$1"
     url="$2"
-    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://gitlab.gnome.org/api/v4/projects/$web_repo/repository/${url}" | jq -r '.[0].name')"; then
-        g_ver="${curl_cmd#v}"
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://gitlab.gnome.org/api/v4/projects/$web_repo/repository/$url" | jq -r '.[0].name')"; then
+        g_ver="$curl_cmd#V"
     fi
 }
 
 build_done() { echo "$2" > "$cwd/$1.done"; }
 
-#
-# INSTALL REQUIRED APT PACKAGES
-#
+# Install required apt packages
 
 pkgs=(asciidoc autogen automake binutils bison build-essential bzip2 ccache cmake
       curl libc6-dev libintl-perl libpth-dev libtool libtool-bin lzip lzma-dev
@@ -251,10 +228,10 @@ pkgs=(asciidoc autogen automake binutils bison build-essential bzip2 ccache cmak
 
 for i in ${pkgs[@]}
 do
-    missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
+    missing_pkg="$(sudo dpkg -l | grep -o "$i")"
 
-    if [ -z "${missing_pkg}" ]; then
-        missing_pkgs+=" ${i}"
+    if [ -z "$missing_pkg" ]; then
+        missing_pkgs+=" $i"
     fi
 done
 
@@ -264,9 +241,7 @@ if [ -n "$missing_pkgs" ]; then
     clear
 fi
 
-#
-# BUILD PROGRAM FROM SOURCE
-#
+# Build program from source
 
 git_1_fn '1665' 'tags'
 if build 'libxml2' "$g_ver"; then
@@ -292,8 +267,8 @@ if build 'libxml2' "$g_ver"; then
     build_done 'libxml2' "$g_ver"
 fi
 
-# PROMPT USER TO CLEAN UP FILES
+# Prompt user to clean up files
 cleanup_fn
 
-# SHOW EXIT MESSAGE
+# Show exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GitHub Projects/build-openssl-lts b/Bash/Installer Scripts/GitHub Projects/build-openssl-lts
--- a/Bash/Installer Scripts/GitHub Projects/build-openssl-lts
+++ b/Bash/Installer Scripts/GitHub Projects/build-openssl-lts
@@ -1,13 +1,13 @@
-#!/usr/bin/env bash
-# shellcheck disable=SC2068,SC2086,SC2162,SC2317
+#!/Usr/bin/env bash
+# Shellcheck disable=sc2068,sc2086,sc2162,sc2317
 
-# Purpose: Build the latest stable release of OpenSSL from the official website's source code
+# Purpose: build the latest stable release of openssl from the official website's source code
 # Enabled features: fips, rc5, shared, tfo, threads, zlib
 # Version: 2.1
 
 # Check for root/and exit if detected
 if [ "$EUID" -ne 0 ]; then
-    printf "%s\n\n" "You must run this script with root/sudo."
+    echo "You must run this script with root or sudo."
     exit 1
 fi
 
@@ -51,14 +51,14 @@ cleanup_fn() {
     esac
 }
 
-# Function to display the OpenSSL version
+# Function to display the openssl version
 show_ver_fn() {
     clear
     show_ver="$(/usr/local/ssl/bin/openssl version -a | grep -Eo "[0-9\.]?+" | head -n1)"
     printf "%s\n" "The updated OpenSSL version is: $show_ver"
 }
 
-# Function to install required packages on Arch Linux
+# Function to install required packages on arch linux
 pkgs_arch_fn() {
     local missing_pkgs
 
@@ -81,7 +81,7 @@ pkgs_arch_fn() {
     fi
 }
 
-# Function to install required packages on Debian/Ubuntu
+# Function to install required packages on debian/ubuntu
 pkgs_fn() {
     local missing_packages available_packages unavailable_packages
 
@@ -94,20 +94,20 @@ pkgs_fn() {
         zlib1g-dev
     )
 
-    # Initialize arrays for missing, available, and unavailable packages
+# Initialize arrays for missing, available, and unavailable packages
     missing_packages=()
     available_packages=()
     unavailable_packages=()
 
-    # Loop through the array to find missing packages
+# Loop through the array to find missing packages
     for pkg in "${pkgs[@]}"
     do
-        if ! dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed"; then
+        if ! dpkg-query -W -f='$Status' "$pkg" 2>/dev/null | grep -q "ok installed"; then
             missing_packages+=("$pkg")
         fi
     done
 
-    # Check availability of missing packages and categorize them
+# Check availability of missing packages and categorize them
     for pkg in "${missing_packages[@]}"
     do
         if apt-cache show "$pkg" > /dev/null 2>&1; then
@@ -117,14 +117,14 @@ pkgs_fn() {
         fi
     done
 
-    # Print unavailable packages
-    if [[ "${#unavailable_packages[@]}" -gt 0 ]]; then
-        echo "Unavailable packages: ${unavailable_packages[*]}"
+# Print unavailable packages
+    if [[ "${#Unavailable_packages[@]}" -gt 0 ]]; then
+        echo "Unavailable packages: $unavailable_packages[*]"
     fi
 
-    # Install available missing packages
-    if [[ "${#available_packages[@]}" -gt 0 ]]; then
-        echo "Installing available missing packages: ${available_packages[*]}"
+# Install available missing packages
+    if [[ "${#Available_packages[@]}" -gt 0 ]]; then
+        echo "Installing available missing packages: $available_packages[*]"
         apt install "${available_packages[@]}"
     else
         printf "%s\n\n" "No missing packages to install or all missing packages are unavailable."
@@ -163,7 +163,7 @@ add_to_path() {
     ln -sf "/usr/local/ssl/bin/openssl" "/usr/local/bin"
 }
 
-# Function to configure and build OpenSSL
+# Function to configure and build openssl
 build_openssl() {
     cd "$1" || exit 1
     ../Configure linux-x86_64-clang \
@@ -198,7 +198,7 @@ build_openssl() {
     fi
 }
 
-# Function to install CA certificates from cURL's website
+# Function to install ca certificates from curl's website
 install_ca_certs() {
     printf "\n%s\n%s\n\n" \
         "Install the latest security certificate from cURL's website" \
@@ -232,7 +232,7 @@ update_ldconfig() {
 script_ver="2.1"
 openssl_ver="$(curl -s https://www.openssl.org/source/ | grep -o "openssl-3.1\.[4-9]\{1,2\}" | head -n 1)"
 archive_url="https://www.openssl.org/source/$openssl_ver.tar.gz"
-archive_ext="${archive_url//*./}"
+archive_ext="$archive_url//*./"
 archive_name="$openssl_ver.tar.$archive_ext"
 cwd="$PWD/openssl-build-script"
 install_dir="/usr/local/ssl"
@@ -248,7 +248,7 @@ sleep 2
 # Create output directory
 create_dir "$cwd"
 
-# Detect OS and version
+# Detect os and version
 find_lsb_release="$(find /usr/bin/ -type f -name "lsb_release")"
 
 if [ -f "/etc/os-release" ]; then
@@ -261,7 +261,7 @@ else
     fail_fn "Failed to define the \$OS and/or \$VER variables. Line: $LINENO"
 fi
 
-# If Ubuntu is the current OS, softlink for OpenSSL to function
+# If ubuntu is the current os, softlink for openssl to function
 ubuntu_os_ver() {
     ln -sf "/usr/lib64/libcrypto.so.3" "/usr/lib64/libcrypto.so"
 }
@@ -270,7 +270,7 @@ case "$OS" in
     Ubuntu) ubuntu_os_ver ;;
 esac
 
-# Install required packages based on OS
+# Install required packages based on os
 if [[ "$OS" == "Arch" ]]; then
     pkgs_arch_fn
 else
@@ -286,22 +286,22 @@ create_dir "$cwd/$openssl_ver/build"
 # Extract archive files
 extract_archive "$cwd/$archive_name" "$cwd/$openssl_ver"
 
-# Build OpenSSL from source
+# Build openssl from source
 build_openssl "$cwd/$openssl_ver/build"
 
-# Install CA certificates from cURL's website
+# Install ca certificates from curl's website
 install_ca_certs
 
 # Update linker library search path
 update_ldconfig
 
-# Add OpenSSL bin to user's ~/.bashrc file
+# Add openssl bin to user's ~/.bashrc file
 add_to_path
 
 # Prompt user to clean up files
 cleanup_fn
 
-# Display updated OpenSSL version
+# Display updated openssl version
 show_ver_fn
 
 # Exit with message
diff --git a/Bash/Installer Scripts/GitHub Projects/build-python2 b/Bash/Installer Scripts/GitHub Projects/build-python2
--- a/Bash/Installer Scripts/GitHub Projects/build-python2
+++ b/Bash/Installer Scripts/GitHub Projects/build-python2
@@ -1,11 +1,11 @@
-#!/usr/bin/env bash
-# shellcheck disable=SC2162,SC2317
+#!/Usr/bin/env bash
+# Shellcheck disable=sc2162,sc2317
 
 #################################################################################################################################
 ##
-##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-python2
+##  Github script: https://github.com/slyfox1186/script-repo/blob/main/bash/installer%20scripts/github%20projects/build-python2
 ##
-##  Purpose: Install Python2 - version 2.7.18
+##  Purpose: install python2 - version 2.7.18
 ##
 ##  Updated: 10.26.23
 ##
@@ -15,69 +15,57 @@
 
 clear
 
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+if [ "$EUID" -eq '0' ]; then
+    echo "You must run this script without root or sudo."
     exit 1
 fi
 
-#
-# SET THE SCRIPT VARIABLES
-#
+# Set the script variables
 
 script_ver=1.0
 py_ver=2.7.18
-archive_dir="python2-${py_ver}"
-archive_url="https://www.python.org/ftp/python/2.7.18/Python-${py_ver}.tar.xz"
-archive_ext="${archive_url//*.}"
-archive_name="$archive_dir.tar.${archive_ext}"
+archive_dir="python2-$py_ver"
+archive_url="https://www.python.org/ftp/python/2.7.18/Python-$py_ver.tar.xz"
+archive_ext="$archive_url//*."
+archive_name="$archive_dir.tar.$archive_ext"
 install_dir=/usr/local
 cwd="$PWD"/python2-build-script
 pc_type=$(gcc -dumpmachine)
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
 
-#
-# START THE PYTHON2 BUILD
-#
+# Start the python2 build
 
 printf "%s\n%s\n\n" \
-    "Python2 Build Script -- version ${script_ver}" \
+    "Python2 Build Script -- version $script_ver" \
     '==============================================='
 
-#
-# CREATE THE OUTPUT DIRECTORY
-#
+# Create the output directory
 
 if [ -d "$cwd" ]; then
     sudo rm -fr "$cwd"
 fi
 mkdir -p "$cwd"
 
-#
-# SET THE C & CPP COMPILERS
-#
+# Set the c & cpp compilers
 
 export CC=gcc CXX=g++
 
-#
-# SET THE COMPILER OPTIMIZATION FLAGS
-#
+# Set the compiler optimization flags
 
 LDFLAGS='-L/usr/local/lib64 -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu'
 LDFLAGS+=' -L/usr/lib64 -L/usr/lib -L/lib64 -L/lib'
 CPPFLAGS='-I/usr/local/include -I/usr/include'
-CFLAGS='-g -O3 -march=native'
-CXXFLAGS='-g -O3 -march=native'
+CFLAGS='-g -O3 -pipe -fno-plt -march=native'
+CXXFLAGS='-g -O3 -pipe -fno-plt -march=native'
 
-#
-# SET THE PATH VARIABLE
-#
+# Set the path variable
 
 PATH="\
 /usr/lib/ccache:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
+$HOME/perl5/bin:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -92,9 +80,7 @@ ${HOME}/.local/bin:\
 "
 export PATH
 
-#
-# SET THE PKG_CONFIG_PATH VARIABLE
-#
+# Set the pkg_config_path variable
 
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
@@ -111,12 +97,9 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
-#
-# CREATE FUNCTIONS
-#
+# Create functions
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n%s\n\n"                                   \
         'The script has completed!'                               \
         'Make sure to star this repository to show your support!' \
@@ -124,8 +107,7 @@ exit_fn()
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n\n%s\n\n%s\n\n%s\n\n"                              \
         "$1"                                                   \
         'Please create a support ticket so I can work on a fix.' \
@@ -133,15 +115,13 @@ fail_fn()
     exit 1
 }
 
-show_ver_fn()
-{
+show_ver_fn() {
     clear
     python_ver="$(python2 -c 'import sys; print(sys.version)' | grep -Eo '^[0-9\.]+')"
-    printf "%s\n\n" "The installed python2 version is: ${python_ver}"
+    printf "%s\n\n" "The installed python2 version is: $python_ver"
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local answer
 
     printf "%s\n\n%s\n%s\n\n"                    \
@@ -150,7 +130,7 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' answer
 
-    case "${answer}" in
+    case "$answer" in
         1)      sudo rm -fr "$cwd";;
         2)      return 0;;
         *)
@@ -161,10 +141,9 @@ cleanup_fn()
     esac
 }
 
-installed() { return $(dpkg-query -W -f '${Status}\n' "$1" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}'); }
+installed() { return $(dpkg-query -W -f '$Status\n' "$1" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}'); }
 
-pkgs_fn()
-{
+pkgs_fn() {
     clear
 
     pkgs=("$1" autoconf autoconf-archive autogen automake binutils build-essential ccache
@@ -174,8 +153,8 @@ pkgs_fn()
 
     for pkg in ${pkgs[@]}
     do
-        if ! installed "${pkg}"; then
-            missing_pkgs+=" ${pkg}"
+        if ! installed "$pkg"; then
+            missing_pkgs+=" $pkg"
         fi
     done
 
@@ -185,8 +164,8 @@ pkgs_fn()
             '======================================'
         for i in "$missing_pkgs"
             do
-                if ! sudo apt install ${i}; then
-                    fail_fn "Failed to install the following APT packages: ${i}. Line: ${LINENO}"
+                if ! sudo apt install $i; then
+                    fail_fn "Failed to install the following APT packages: $i. Line: $LINENO"
                 fi
             done
     else
@@ -194,15 +173,12 @@ pkgs_fn()
     fi
 }
 
-#
-# INSTALL REQUIRED APT PACKAGES
-#
+# Install required apt packages
 
-install_libportal_fn()
-{
+install_libportal_fn() {
     if ! wget --show-progress -t 2 -cqO 'https://github.com/flatpak/libportal/releases/download/0.7.1/libportal-0.7.1.tar.xz'; then
         clear
-        printf "%s\n\n" "Failed to download the libportal archive file. Line: ${LINENO}"
+        printf "%s\n\n" "Failed to download the libportal archive file. Line: $LINENO"
         exit 1
     fi
     mkdir libportal-0.7.1
@@ -212,27 +188,24 @@ install_libportal_fn()
                       --buildtype=release      \
                       --default-library=static \
                       --strip                  \
-                      -Dc_args="${CFLAGS}"     \
-                      -Dcpp_args="${CXXFLAGS}"
+                      -Dc_args="$CFLAGS"     \
+                      -Dcpp_args="$CXXFLAGS"
     ninja "-j$(nproc --all)" -C build
     sudo ninja "-j$(nproc --all)" -C build install
 }
 
-debian_os_version()
-{
-    case "${VER}" in
+debian_os_version() {
+    case "$VER" in
         12|trixie)      pkgs_fn 'libgnome-desktop-4-dev libportal-dev libportal-gtk3-dev libportal-gtk4-dev';;
         10|11)
                         pkgs_fn 'libgnome-desktop-3-dev'
                         install_libportal_fn
                         ;;
-        *)              fail_fn "Could not detect the Debian version. Line: ${LINENO}";;
+        *)              fail_fn "Could not detect the Debian version. Line: $LINENO";;
     esac
 }
 
-#
-# TEST THE OS AND ITS VERSION
-#
+# Test the os and its version
 
 find_lsb_release="$(sudo find /usr -type f -name 'lsb_release')"
 
@@ -241,106 +214,93 @@ if [ -f '/etc/os-release' ]; then
     OS_TMP="$NAME"
     VER_TMP="$VERSION_ID"
     CODENAME="$VERSION_CODENAME"
-    OS="$(echo "${OS_TMP}" | awk '{print $1}')"
-    VER="$(echo "${VER_TMP}" | awk '{print $1}')"
-elif [ -n "${find_lsb_release}" ]; then
+    OS="$(echo "$OS_TMP" | awk '{print $1}')"
+    VER="$(echo "$VER_TMP" | awk '{print $1}')"
+elif [ -n "$find_lsb_release" ]; then
     OS="$(lsb_release -d | awk '{print $2}')"
     VER="$(lsb_release -r | awk '{print $2}')"
 else
-    fail_fn "Failed to define the \$OS and/or \$VER variables. Line: ${LINENO}"
+    fail_fn "Failed to define the \$OS and/or \$VER variables. Line: $LINENO"
 fi
 
-if [ -z "${VER}" ]; then
-    VER="${CODENAME}"
+if [ -z "$VER" ]; then
+    VER="$CODENAME"
 fi
 
-case "${OS}" in
+case "$OS" in
     'Debian'|'n/a')     debian_os_version;;
     'Ubuntu')           pkgs_fn;;
-    *)                  fail_fn "Could not detect the OS architecture. Line: ${LINENO}";
+    *)                  fail_fn "Could not detect the OS architecture. Line: $LINENO";
 esac
 
-#
-# DOWNLOAD THE ARCHIVE FILE
-#
+# Download the archive file
 
-if [ ! -f "$cwd/${archive_name}" ]; then
-    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
+if [ ! -f "$cwd/$archive_name" ]; then
+    curl -A "$user_agent" -Lso "$cwd/$archive_name" "$archive_url"
 fi
 
-#
-# CREATE THE OUTPUT DIRECTORY
-#
+# Create the output directory
 
 if [ -d "$cwd/$archive_dir" ]; then
     sudo rm -fr "$cwd/$archive_dir"
 fi
 mkdir -p "$cwd/$archive_dir/build"
 
-#
-# EXTRACT THE ARCHIVE FILES
-#
+# Extract the archive files
 
-if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
-    fail_fn "Failed to extract: $cwd/${archive_name}. Line: ${LINENO}"
+if ! tar -xf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
+    fail_fn "Failed to extract: $cwd/$archive_name. Line: $LINENO"
     exit 1
 fi
 
-#
-# STORE FILE PATHS IN VARIABLES FOR USE WITH THE CONFIGURE SCRIPT
-#
+# Store file paths in variables for use with the configure script
 
 libm_lib="$(sudo find /usr/lib/ -type f -name libm.so | head -n1)"
 libc_lib="$(sudo find /usr/lib/ -type f -name libc.so | head -n1)"
 
-#
-# BUILD THE PROGRAM FROM SOURCE CODE
-#
+# Build the program from source code
 
 cd "$cwd/$archive_dir/build" || exit 1
 ../configure --prefix="$install_dir"          \
-             --{build,host,target}="${pc_type}" \
+             --{build,host,target}="$pc_type" \
              --disable-ipv6                     \
              --disable-profiling                \
              --enable-optimizations             \
              --with-ensurepip=install           \
-             --with-libc="${libc_lib}"          \
-             --with-libm="${libm_lib}"          \
+             --with-libc="$libc_lib"          \
+             --with-libm="$libm_lib"          \
              --with-lto                         \
              --with-pth                         \
              --with-pymalloc                    \
              --with-valgrind                    \
-             CFLAGS="${CFLAGS}"                 \
-             CXXFLAGS="${CXXFLAGS}"             \
-             CPPFLAGS="${CPPFLAGS}"             \
-             LDFLAGS="${LDFLAGS}"
+             CFLAGS="$CFLAGS"                 \
+             CXXFLAGS="$CXXFLAGS"             \
+             CPPFLAGS="$CPPFLAGS"             \
+             LDFLAGS="$LDFLAGS"
 
-no_optimize_fn()
-{
+no_optimize_fn() {
     if ! make "-j$(nproc --all)" build_all; then
-        printf "\n%s\n\n" "Failed to execute: make -j$(nproc --all) build_all. Line: ${LINENO}"
+        printf "\n%s\n\n" "Failed to execute: make -j$(nproc --all) build_all. Line: $LINENO"
         exit 1
     fi
     if ! sudo make "-j$(nproc --all)" install; then
-        printf "\n%s\n\n" "Failed to execute: make -j$(nproc --all) install. Line: ${LINENO}"
+        printf "\n%s\n\n" "Failed to execute: make -j$(nproc --all) install. Line: $LINENO"
         exit 1
     fi
 }
 
-optimize_fn()
-{
+optimize_fn() {
     if ! make "-j$(nproc --all)"; then
-        printf "\n%s\n\n" "Failed to execute: make -j$(nproc --all). Line: ${LINENO}"
+        printf "\n%s\n\n" "Failed to execute: make -j$(nproc --all). Line: $LINENO"
         exit 1
     fi
     if ! sudo make "-j$(nproc --all)" install; then
-        printf "\n%s\n\n" "Failed to execute: make -j$(nproc --all) install. Line: ${LINENO}"
+        printf "\n%s\n\n" "Failed to execute: make -j$(nproc --all) install. Line: $LINENO"
         exit 1
     fi
 }
 
-optimize_prompt_fn()
-{
+optimize_prompt_fn() {
     local choice
     clear
 
@@ -350,7 +310,7 @@ optimize_prompt_fn()
     read -p '[Y]es or [N]o: ' choice
     clear
 
-    case "${choice}" in
+    case "$choice" in
         Y|y)     optimize_fn;;
         N|n)     no_optimize_fn;;
         *)
@@ -361,11 +321,11 @@ optimize_prompt_fn()
 }
 optimize_prompt_fn
 
-# SHOW THE NEW VERSION
+# Show the new version
 show_ver_fn
 
-# PROMPT THE USER TO CLEAN UP THE BUILD FILES
+# Prompt the user to clean up the build files
 cleanup_fn
 
-# SHOW THE EXIT MESSAGE
+# Show the exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GitHub Projects/build-terminator-terminal b/Bash/Installer Scripts/GitHub Projects/build-terminator-terminal
--- a/Bash/Installer Scripts/GitHub Projects/build-terminator-terminal
+++ b/Bash/Installer Scripts/GitHub Projects/build-terminator-terminal
@@ -1,11 +1,11 @@
-#!/usr/bin/env bash
-# shellcheck disable=SC2162,SC2317
+#!/Usr/bin/env bash
+# Shellcheck disable=sc2162,sc2317
 
 #############################################################################################################
 ##
-##  Install: Terminator Terminal
+##  Install: terminator terminal
 ##
-##  GitHub: https://github.com/slyfox1186/script-repo/edit/main/shell/installers/build-terminator-terminal
+##  Github: https://github.com/slyfox1186/script-repo/edit/main/shell/installers/build-terminator-terminal
 ##
 ##  Updated: 08.09.23
 ##
@@ -15,56 +15,44 @@
 
 clear
 
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo'
+if [ "$EUID" -eq 0 ]; then
+    echo "You must run this script without root or sudo."
     exit 1
 fi
 
-#
-# CREATE SCRIPT VARIABLES
-#
+# Create script variables
 
 script_ver=1.0
-cwd="$PWD"/terminator-build-script
+cwd="$PWD/terminator-build-script"
 install_dir=/usr/local
 archive_dir=terminator-2.1.3
 archive_url=https://salsa.debian.org/python-team/packages/terminator/-/archive/debian/2.1.3-1/terminator-debian-2.1.3-1.tar.bz2
-archive_ext="${archive_url//*.}"
-archive_name="$archive_dir.tar.${archive_ext}"
-user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
-web_repo=https://github.com/slyfox1186/script-repo
+archive_ext="$archive_url//*."
+archive_name="$archive_dir.tar.$archive_ext"
 
 printf "\n%s\n%s\n\n" \
-    "Terminator Build Script - v${script_ver}" \
+    "Terminator Build Script - v$script_ver" \
     '==============================================='
 
-#
-# CREATE OUTPUT DIRECTORY
-#
+# Create output directory
 
 mkdir -p "$cwd"
 
-#
-# SET THE C+CPP COMPILERS
-#
+# Set the c+cpp compilers
 
 export CC=gcc CXX=g++
 
-#
-# EXPORT COMPILER OPTIMIZATION FLAGS
-#
+# Export compiler optimization flags
 
-export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -march=native'
+export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -fno-plt -march=native'
 
-#
-# SET THE PATH VARIABLE
-#
+# Set the path variable
 
 PATH="\
 /usr/lib/ccache:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
+$HOME/perl5/bin:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -79,9 +67,7 @@ ${HOME}/.local/bin:\
 "
 export PATH
 
-#
-# SET THE PKG_CONFIG_PATH VARIABLE
-#
+# Set the pkg_config_path variable
 
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
@@ -98,30 +84,25 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
-#
-# CREATE FUNCTIONS
-#
+# Create functions
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n%s\n\n" \
         'The script has completed' \
         'Make sure to star this repository to show your support!' \
-        "$web_repo"
+        "https://github.com/slyfox1186/script-repo"
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n\n%s\n\n%s\n\n%s\n\n" \
         "$1" \
         'To report a bug please create an issue at:' \
-        "$web_repo/issues"
+        "https://github.com/slyfox1186/script-repo/issues"
     exit 1
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local choice
 
     printf "\n%s\n%s\n%s\n\n%s\n%s\n\n" \
@@ -132,7 +113,7 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "${choice}" in
+    case "$choice" in
         1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
@@ -146,9 +127,7 @@ cleanup_fn()
     esac
 }
 
-#
-# INSTALL REQUIRED APT PACKAGES
-#
+# Install required apt packages
 
 pkgs=(autoconf autogen automake build-essential ca-certificates ccache clang curl libaria2-0 libaria2-0-dev
       libc-ares-dev libdmalloc-dev libgcrypt20-dev libgmp-dev libgnutls28-dev libgpg-error-dev libjemalloc-dev
@@ -158,10 +137,10 @@ pkgs=(autoconf autogen automake build-essential ca-certificates ccache clang cur
 
 for i in ${pkgs[@]}
 do
-    missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
+    missing_pkg="$(sudo dpkg -l | grep -o "$i")"
 
-    if [ -z "${missing_pkg}" ]; then
-        missing_pkgs+=" ${i}"
+    if [ -z "$missing_pkg" ]; then
+        missing_pkgs+=" $i"
     fi
 done
 unset i
@@ -172,57 +151,50 @@ if [ -n "$missing_pkgs" ]; then
     clear
 fi
 
-#
-# DOWNLOAD THE ARCHIVE FILE
-#
-
-if [ ! -f "$cwd/${archive_name}" ]; then
-    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
+# Download the archive file
+if [ ! -f "$cwd/$archive_name" ]; then
+    curl -Lso "$cwd/$archive_name" "$archive_url"
 fi
 
-#
-# CREATE OUTPUT DIRECTORY
-#
+# Create output directory
 
 if [ -d "$cwd/$archive_dir" ]; then
     sudo rm -fr "$cwd/$archive_dir"
 fi
 mkdir -p "$cwd/$archive_dir"
 
-#
-# EXTRACT ARCHIVE FILES
-#
+# Extract archive files
 
-if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
+if ! tar -xf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/$archive_name"
     exit 1
 fi
 
-#
-# BUILD PROGRAM FROM SOURCE
-#
+# Build program from source
 
 cd "$cwd/$archive_dir" || exit 1
 python3 setup.py build
-if ! sudo python3 setup.py install --prefix="$install_dir"                        \
-                                   --install-lib=/usr/local/lib                     \
-                                   --home="${HOME}"                                 \
-                                   --single-version-externally-managed              \
-                                   --record=install-files.txt                       \
-                                   --install-headers                                \
-                                   --install-scripts                                \
-                                   --install-data                                   \
-                                   --compile -optimize -O2                          \
-                                   --force                                          \
+if ! sudo python3 setup.py install --prefix="$install_dir" \
+                                   --install-lib=/usr/local/lib \
+                                   --home="$HOME" \
+                                   --single-version-externally-managed \
+                                   --record=install-files.txt \
+                                   --install-headers \
+                                   --install-scripts \
+                                   --install-data \
+                                   --compile -optimize -O2 \
+                                   --force \
                                    --record "$cwd"/terminator-installed-files.txt \
-                                   --user                                           \
+                                   --user \
                                    --install-layout=unix; then
-    fail_fn "Failed to execute: sudo python3 setup.py install:Line ${LINENO}"
+    fail_fn "Failed to execute: sudo python3 setup.py install:Line $LINENO"
     exit 1
 fi
 
-# CLEANUP FILES
+# Cleanup files
+
 cleanup_fn
 
-# SHOW EXIT MESSAGE
+# Show exit message
+
 exit_fn
diff --git a/Bash/Installer Scripts/GitHub Projects/build-zlib b/Bash/Installer Scripts/GitHub Projects/build-zlib
--- a/Bash/Installer Scripts/GitHub Projects/build-zlib
+++ b/Bash/Installer Scripts/GitHub Projects/build-zlib
@@ -1,14 +1,14 @@
-#!/usr/bin/env bash
+#!/Usr/bin/env bash
 
 ########################################################################################################################################
 ##
-##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-zlib
+##  Github script: https://github.com/slyfox1186/script-repo/blob/main/bash/installer%20scripts/github%20projects/build-zlib
 ##
-##  Purpose: Build zlib
+##  Purpose: build zlib
 ##
 ##  Updated: 09.13.23
 ##
-##  Added: -fPIC to CFLAGS & CXXFLAGS to avoid other programs not compiling when attempting to use the libz.a file while linking
+##  Added: -fpic to cflags & cxxflags to avoid other programs not compiling when attempting to use the libz.a file while linking
 ##
 ##  Script version: 1.2
 ##
@@ -16,14 +16,12 @@
 
 clear
 
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+if [ "$EUID" -eq '0' ]; then
+    echo "You must run this script without root or sudo."
     exit 1
 fi
 
-#
-# SET VARIABLES
-#
+# Set variables
 
 script_ver=1.2
 install_dir=/usr/local
@@ -34,39 +32,31 @@ web_repo=https://github.com/slyfox1186/script-repo
 debug=OFF
 
 printf "\n%s\n%s\n\n" \
-    "zlib build script - v${script_ver}" \
+    "zlib build script - v$script_ver" \
     '==============================================='
 
-#
-# CREATE OUTPUT DIRECTORY
-#
+# Create output directory
 
 if [ -d "$cwd" ]; then
     sudo rm -fr "$cwd"
 fi
 mkdir -p "$cwd"
 
-#
-# SET THE C+CPP COMPILERS
-#
+# Set the c+cpp compilers
 
 export CC=gcc CXX=g++
 
-#
-# SET COMPILER OPTIMIZATION FLAGS
-#
+# Set compiler optimization flags
 
-export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -march=native'
+export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -fno-plt -march=native'
 
-#
-# SET THE PATH VARIABLE
-#
+# Set the path variable
 
 PATH="\
 /usr/lib/ccache:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
+$HOME/perl5/bin:\
+$HOME/.cargo/bin:\
+$HOME/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -81,9 +71,7 @@ ${HOME}/.local/bin:\
 "
 export PATH
 
-#
-# SET THE PKG_CONFIG_PATH VARIABLE
-#
+# Set the pkg_config_path variable
 
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
@@ -100,28 +88,23 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
-#
-# CREATE FUNCTIONS
-#
+# Create functions
 
-exit_fn()
-{
+exit_fn() {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
         "$web_repo"
     exit 0
 }
 
-fail_fn()
-{
+fail_fn() {
     printf "\n%s\n\n%s\n\n" \
         "$1" \
         "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
-cleanup_fn()
-{
+cleanup_fn() {
     local choice
 
     printf "\n%s\n%s\n%s\n\n%s\n%s\n\n" \
@@ -132,7 +115,7 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "${choice}" in
+    case "$choice" in
         1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
@@ -146,8 +129,7 @@ cleanup_fn()
     esac
 }
 
-build()
-{
+build() {
     printf "\n%s\n%s\n" \
         "building $1 - version $2" \
         '===================================='
@@ -164,34 +146,32 @@ build()
     return 0
 }
 
-execute()
-{
-    echo "$ ${*}"
+execute() {
+    echo "$ $*"
 
-    if [ "${debug}" = 'ON' ]; then
+    if [ "$debug" = 'ON' ]; then
         if ! output=$("$@"); then
-            notify-send 5000 "Failed to execute: ${*}"
-            fail_fn "Failed to execute: ${*}"
+            notify-send 5000 "Failed to execute: $*"
+            fail_fn "Failed to execute: $*"
         fi
     else
         if ! output=$("$@" 2>&1); then
-            notify-send 5000 "Failed to execute: ${*}"
-            fail_fn "Failed to execute: ${*}"
+            notify-send 5000 "Failed to execute: $*"
+            fail_fn "Failed to execute: $*"
         fi
     fi
 }
 
-download()
-{
+download() {
     dl_path="$packages"
     dl_url="$1"
-    dl_file="${2:-"${1##*/}"}"
+    dl_file="$2:-"${1##*/"}"
 
     if [[ "$dl_file" =~ tar. ]]; then
-        output_dir="${dl_file%.*}"
-        output_dir="${3:-"${output_dir%.*}"}"
+        output_dir="$dl_file%.*"
+        output_dir="$3:-"${output_dir%.*"}"
     else
-        output_dir="${3:-"${dl_file%.*}"}"
+        output_dir="$3:-"${dl_file%.*"}"
     fi
 
     target_file="$dl_path/$dl_file"
@@ -202,15 +182,15 @@ download()
     fi
     cd "$dl_path" || exit 1
 
-    if [ -f "${target_file}" ]; then
+    if [ -f "$target_file" ]; then
         echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
-        if ! curl -A "$user_agent" -Lso "$dl_file" "${dl_url}"; then
+        echo "Downloading \"$dl_url\" saving as \"$dl_file\""
+        if ! curl -A "$user_agent" -Lso "$dl_file" "$dl_url"; then
             printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! curl -A "$user_agent" -Lso "$dl_file" "${dl_url}"; then
-                fail_fn "The script failed to download \"$dl_file\" twice and will now exit:Line ${LINENO}"
+            if ! curl -A "$user_agent" -Lso "$dl_file" "$dl_url"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit:Line $LINENO"
             fi
         fi
         echo 'Download Completed'
@@ -224,55 +204,51 @@ download()
     if [ -n "$3" ]; then
         if ! tar -xf "$dl_file" -C "$target_dir" 2>/dev/null >/dev/null; then
             sudo rm "$dl_file"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line $LINENO"
         fi
     else
         if ! tar -xf "$dl_file" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
             sudo rm "$dl_file"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line ${LINENO}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script:Line $LINENO"
         fi
     fi
 
     printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir:Line ${LINENO}"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir:Line $LINENO"
 }
 
-git_1_fn()
-{
+git_1_fn() {
     local curl_cmd github_repo github_url
 
-    # SCRAPE GITHUB WEBSITE FOR THE LATEST REPO VERSION
+# Scrape github website for the latest repo version
     github_repo="$1"
     github_url="$2"
 
-    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/$github_repo/$github_url")"; then
         g_ver="$(echo "$curl_cmd" | jq -r '.[0].name' 2>/dev/null)"
-        g_ver="${g_ver#v}"
+        g_ver="$g_ver#V"
     fi
 }
 
-git_ver_fn()
-{
+git_ver_fn() {
     local t_flag v_tag v_url
 
     v_url="$1"
     v_flag="$2"
 
-    case "${v_flag}" in
+    case "$v_flag" in
             B)      t_flag=branches;;
             R)      t_flag=releases;;
             T)      t_flag=tags;;
     esac
 
-    git_1_fn "${v_url}" "${t_flag}" 2>/dev/null
+    git_1_fn "$v_url" "$t_flag" 2>/dev/null
 }
 
 build_done() { echo "$2" > "$packages/$1.done"; }
 
-#
-# INSTALL REQUIRED APT PACKAGES
-#
+# Install required apt packages
 
 pkgs=(libtool autogen automake binutils bison build-essential bzip2 ccache curl
       libc6-dev libintl-perl libpth-dev libtool libtool-bin lzip lzma-dev libtool
@@ -280,10 +256,10 @@ pkgs=(libtool autogen automake binutils bison build-essential bzip2 ccache curl
 
 for i in ${pkgs[@]}
 do
-    missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
+    missing_pkg="$(sudo dpkg -l | grep -o "$i")"
 
-    if [ -z "${missing_pkg}" ]; then
-        missing_pkgs+=" ${i}"
+    if [ -z "$missing_pkg" ]; then
+        missing_pkgs+=" $i"
     fi
 done
 
@@ -293,9 +269,7 @@ if [ -n "$missing_pkgs" ]; then
     clear
 fi
 
-#
-# BUILD PROGRAM FROM SOURCE
-#
+# Build program from source
 
 git_ver_fn 'madler/zlib' 'T'
 if build 'zlib' "$g_ver"; then
@@ -312,8 +286,8 @@ if build 'zlib' "$g_ver"; then
     build_done 'zlib' "$g_ver"
 fi
 
-# PROMPT USER TO CLEAN UP FILES
+# Prompt user to clean up files
 cleanup_fn
 
-# SHOW EXIT MESSAGE
+# Show exit message
 exit_fn
