Update build-7zip

diff --git a/Bash/Installer Scripts/SlyFox1186 Scripts/build-7zip b/Bash/Installer Scripts/SlyFox1186 Scripts/build-7zip
--- a/Bash/Installer Scripts/SlyFox1186 Scripts/build-7zip
+++ b/Bash/Installer Scripts/SlyFox1186 Scripts/build-7zip
@@ -1,74 +1,31 @@
 #!/usr/bin/env bash
+clear
 
-################################################################################
-##
-##  GitHub: https://github.com/slyfox1186/script-repo
-##
-##  Purpose: Install the latest 7-zip package across multiple OS types.
-##          The user will be prompted to select their OS architecture before
-##          installing.
-##
-##  Updated: 09.04.23
-##
-##  Script version: 1.3
-##
-################################################################################
+# Purpose: Install the latest 7-zip package across multiple OS types.
+# Updated: 01.16.24
+# Script version: 1.3
 
-#
-# SET VARIABLES
-#
+# GitHub Repository
+web_repo='https://github.com/slyfox1186/script-repo'
 
-script_ver=1.3
-version=7z2301
-tar_file="${version}.tar.xz"
-cwd="$PWD"/7zip-build-script
-output_dir="$cwd/${version}"
-install_dir=/usr/local/bin
-user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
-web_repo=https://github.com/slyfox1186/script-repo
+# Set variables
+script_ver='1.3'
+version='7z2301'
+tar_file="$version.tar.xz"
+cwd="/home/jman/tmp/7zip-build-script"
+output_dir="$cwd/$version"
+install_dir='/usr/local/bin'
+user_agents=("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3" "User-Agent: curl/7.68.0")
 
-#
-# CREATE OUTPUT FOLDERS
-#
-
-if [ ! -d "$cwd" ]; then
-    mkdir -p "$cwd"
-fi
-
-#
-# CREATE FUNCTIONS
-#
-
-exit_fn()
-{
-    printf "%s\n%s\n\n"                                           \
-        'Make sure to star this repository to show your support!' \
-        "$web_repo"
-    exit 0
+# Function to print 7-Zip version
+version_fn() {
+    local version_info
+    version_info="$("$install_dir/7z" | awk -F ' |\\(' '/7-Zip/{print $4; exit}')"
+    printf "\n7-Zip has been updated to version %s\n\n" "$version_info"
 }
 
-fail_fn()
-{
-    printf "\n\n%s\n\n%s\n\n%s\n\n"          \
-        "$1"                               \
-        'Please create a support ticket at:' \
-        "$web_repo/issues"
-    exit 1
-}
-
-# PRINT 7-ZIP VERSION
-version_fn()
-{
-    show_ver="$("$install_dir/7z" | head -n 2 | cut -d ' ' -f3 | awk 'NF' | xargs -I{} echo "7-Zip has been updated to version {}")"
-    printf "\n%s\n\n" "${show_ver}"
-}
-
-#
-# PRINT SCRIPT BANNER
-#
-
-box_out_banner()
-{
+# Function to print script banner
+box_out_banner() {
     input_char=$(echo "$@" | wc -c)
     line=$(for i in $(seq 0 ${input_char}); do printf '-'; done)
     tput bold
@@ -83,49 +40,77 @@ box_out_banner()
 }
 box_out_banner "7-Zip Install Script"
 
-# DETECT PC ARCHITECTURE
-case "$(uname -m)" in
-      x86_64)          url=linux-x64.tar.xz;;
-      i386|i686)       url=linux-x86.tar.xz;;
-      aarch64*|armv8*) url=linux-arm64.tar.xz;;
-      arm|armv7*)      url=linux-arm.tar.xz;;
-      *)               fail_fn "Unrecognized architecture '$(uname -m)'";;
-esac
+# Function to handle errors
+fail_fn() {
+    echo -e "\n\n$1\n\nPlease create a support ticket at:\n$web_repo/issues"
+    exit 1
+}
 
-# Install curl (needed to download the files)
-if ! sudo dpkg -l | grep -o curl &>/dev/null; then
-    sudo apt -y install curl
+# Function to download the file with retries
+download_with_retry() {
+    local url="$1"
+    local dest="$2"
+    local max_attempts=3
+    local attempt=1
+
+    while [ $attempt -le $max_attempts ]; do
+        wget -U "${user_agents[$((attempt-1))]}" -cqO "$dest" "$url" && return 0
+        ((attempt++))
+        sleep 2 # Wait for a few seconds before retrying
+    done
+
+    return 1
+}
+
+# Check if wget is not installed and install it
+if ! command -v wget &>/dev/null; then
+    sudo apt -y install wget
     sudo apt -y autoremove
     clear
 fi
 
-# Download the tar file if missing
-if [ ! -f "${tar_file}" ]; then
-   curl -A "$user_agent" -Lso "$cwd/${tar_file}" "https://www.7-zip.org/a/${version}-${url}"
+# Check if the '7zip-build-script' directory exists and delete it
+if [ -d "$cwd" ]; then
+    echo -e "\nDeleting existing '7zip-build-script' directory..."
+    sudo rm -fr "$cwd"
+fi
+
+# Create '7zip-build-script' directory
+mkdir -p "$cwd"
+
+# Detect PC architecture and set download URL
+case "$(uname -m)" in
+    x86_64)          url='linux-x64.tar.xz';;
+    i386|i686)       url='linux-x86.tar.xz';;
+    aarch64*|armv8*) url='linux-arm64.tar.xz';;
+    arm|armv7*)      url='linux-arm.tar.xz';;
+    *)               fail_fn "Unrecognized architecture '$(uname -m)'";;
+esac
+
+# Download the tar file with retries if missing
+if [ ! -f "$cwd/$tar_file" ]; then
+    download_with_retry "https://www.7-zip.org/a/${version}-${url}" "$cwd/$tar_file" || fail_fn "Failed to download the file"
 fi
 
 # Extract files into directory '7z'
 mkdir -p "$output_dir"
-if [ -f "$cwd/${tar_file}" ]; then
-    if ! tar -xf "$cwd/${tar_file}" -C "$output_dir"; then
-        fail_fn "The script was unable to extract the archive: '$cwd/${tar_file}'"
-    fi
-else
-    fail_fn "The script was unable to find the download file '$cwd/${tar_file}'"
+if [ ! -f "$cwd/$tar_file" ]; then
+    fail_fn "The script was unable to find the download file '$cwd/$tar_file'"
+fi
+
+if ! tar -xf "$cwd/$tar_file" -C "$output_dir"; then
+    fail_fn "The script was unable to extract the archive: '$cwd/$tar_file'"
 fi
 
 # Copy the file to its destination or throw an error if the copying of the file fails
-if ! sudo cp -f "$cwd/${version}/7zzs" "$install_dir/7z"; then
+if ! sudo cp -f "$cwd/$version/7zzs" "$install_dir/7z"; then
     fail_fn "The script was unable to copy the static file '7zzs' to '$install_dir/7z'"
 else
     sudo chmod 755 "$install_dir/7z"
 fi
 
-# SHOW THE NEWLY INSTALLED 7-ZIP VERSION
+# Show the newly installed 7-Zip version
 version_fn
 
-# CLEAN UP THE INSTALL FILES
+# Clean up the install files
 sudo rm -fr "$cwd"
-
-# SHOW THE EXIT MESSAGE
-exit_fn
