Update build-openssl

diff --git a/shell/installers/build-openssl b/shell/installers/build-openssl
--- a/shell/installers/build-openssl
+++ b/shell/installers/build-openssl
@@ -10,29 +10,28 @@
 ##  
 ##  Enabled features: egd, fips, md2, rc5, trace, sctp, threads
 ##
-##  Updated: 07.12.23
+##  Updated: 07.17.23
 ##
-##  Script version: 1.0
+##  Script version: 1.1
 ##
 ###################################################################
 
 clear
 
-if [ "$EUID" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
-    exit 1
-fi
-
 #
 # SET PROGRAM NAME + VERSION
 #
 
-script_ver=1.0
-archive_name=openssl-3.1.1
+script_ver=1.1
+archive_dir=openssl-3.1.1
 archive_url=https://github.com/openssl/openssl/releases/download/openssl-3.1.1/openssl-3.1.1.tar.gz
 archive_ext="${archive_url//*.}"
 cwd="$PWD"/openssl-build-script
-packages="$cwd"/packages
+install_dir=/usr/local
+ssl_dir="$install_dir"/lib/ssl
+cert_dir="$ssl_dir"/certs
+pem_filename=cacert.pem
+pem_output="$cert_dir/$pem_filename"
 repo=https://github.com/slyfox1186/script-repo
 
 printf "\n%s\n%s\n\n" \
@@ -40,203 +39,162 @@ printf "\n%s\n%s\n\n" \
     '==============================================='
 
 #
-# CREATE FUNCTIONS
+# CREATE OUTPUT DIRECTORY
 #
 
-exit_fn()
-{
-    printf "\n%s\n\n%s\n%s\n\n" \
-        'The script has completed' \
-        'Make sure to star this repository to show your support!' \
-        "$repo"
-    exit 0
-}
-
-fail_fn()
-{
-    printf "\n\n%s\n\n%s\n\n%s\n\n" \
-        "$1" \
-        'To get help with bugs visit:' \
-        "$repo/issues"
-    exit 1
-}
-
-cleanup_fn() { sudo rm -fr "$cwd"; }
-
-installed() { return $(dpkg-query -W -f '${Status}\n' "$1" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}'); }
+mkdir -p "$cwd"
 
 #
-# CREATE OUTPUT DIRECTORIES
-#
-
-mkdir -p "$packages"/sctp
-
-#
-# SET THE C AND C++ COMPILERS
+# SET THE C+CPP COMPILERS
 #
 
 export CC=gcc CXX=g++
 
 #
-# SET LDFLAGS
-#
-
-LDFLAGS="\
--L/usr/local/lib64 \
--L/usr/local/lib \
--L/usr/local/cuda/nvvm/lib64 \
--L/usr/local/cuda/targets/x86_64-linux/lib \
--L/usr/lib \
--L/usr/lib/x86_64-linux-gnu \
--L/usr/lib/gcc/x86_64-linux-gnu \
--L/lib64 \
--L/lib \
--L/lib/x86_64-linux-gnu\
-"
-export LDFLAGS
-
-#
 # EXPORT COMPILER OPTIMIZATION FLAGS
 #
 
-CPPFLAGS='-I/usr/local/include -I/usr/include -I/usr/include/x86_64-linux-gnu -I/usr/lib/gcc/x86_64-linux-gnu/12/include'
-CPPFLAGS+=' -I/usr/share/cmake-3.25/include -I/usr/lib/llvm-14/include -I/usr/local/cuda-12.2/compute-sanitizer/include'
-CPPFLAGS+=' -I/usr/local/cuda-12.2/targets/x86_64-linux/include -I/usr/local/cuda-12.2/nvvm/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include'
-CPPFLAGS+=' -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/lib/jvm/java-17-openjdk-amd64/include'
+export {CFLAGS,CXXFLAGS}='-g -O3 -march=native -D_REENTRANT'
 
-export CPPFLAGS
-export {CFLAGS,CXXFLAGS}='-g -O3 -march=native'
+#
+# CREATE FUNCTIONS
+#
+
+exit_fn()
+{
+    printf "\n%s\n\n" 'The script has completed.'
+    exit 0
+}
+
+cleanup_fn()
+{
+    local choice
+
+    printf "\n%s\n%s\n%s\n\n%s\n%s\n\n" \
+        '============================================' \
+        '  Do you want to clean up the build files?  ' \
+        '============================================' \
+        '[1] Yes' \
+        '[2] No'
+    read -p 'Your choices are (1 or 2): ' choice
+
+    case "$choice" in
+        1)      sudo rm -fr "$cwd";;
+        2)      echo;;
+        *)
+                clear
+                printf "%s\n\n" 'Bad user input. Reverting script...'
+                sleep 3
+                unset choice
+                clear
+                cleanup_fn
+                ;;
+    esac
+}
+
+fail_fn()
+{
+    printf "%s\n\n" "$1"
+    exit 1
+}
 
 #
 # INSTALL REQUIRED APT PACKAGES
 #
 
 pkgs=(autoconf autogen automake build-essential ca-certificates ccache curl libc-ares-dev libcurl4-openssl-dev
-      libdmalloc-dev libgcrypt20-dev libgmp-dev libgpg-error-dev libjemalloc-dev libmbedtls-dev libssh2-1-dev
-      libssh-dev libssl-dev libxml2-dev)
+      libdmalloc-dev libgcrypt20-dev libgmp-dev libgpg-error-dev libjemalloc-dev libmbedtls-dev libsctp-dev
+      libssh2-1-dev libssh-dev libssl-dev libxml2-dev zlib1g-dev)
 
-for pkg in ${pkgs[@]}
+for i in ${pkgs[@]}
 do
-    if ! installed "$pkg"; then
-        missing_pkgs+=" $pkg"
+    missing_pkg="$(dpkg -l | grep $i)"
+
+    if [ -z "$missing_pkg" ]; then
+        missing_pkgs+=" $i"
     fi
 done
+unset i
 
 if [ -n "$missing_pkgs" ]; then
-    if sudo apt -y install $missing_pkgs; then
-        echo 'The required APT packages were installed.'
-    else
-        fail_fn "These required APT packages failed to install: $missing_pkgs"
-    fi
-else
-    echo 'The required APT packages are already installed.'
+    sudo apt -y install $missing_pkgs
+    clear
 fi
 
 #
-# INSTALL SCTP MODULE TO ENABLE SCTP SUPPORT IN OPENSSL
+# INSTALL CA CERTS FROM CURL'S OFFICIAL WEBSITE
 #
 
-cd "$packages" || exit 1
-
-# DOWNLOAD SCTP SOURCE ARCHIVE
-if [ ! -f "$packages/sctp-1.0.17.tar.gz" ]; then
-    if ! curl -Lso "$packages/sctp-1.0.17.tar.gz" 'https://versaweb.dl.sourceforge.net/project/lksctp/lksctp-tools/lksctp-tools-1.0.17.tar.gz'; then
-        printf "%s\n\n" 'Failed to download sctp source code.'
-    fi
-fi
-
-# EXTRACT SCTP ARCHIVE
-if ! tar -zxf "$packages/sctp-1.0.17.tar.gz" -C "$packages"/sctp --strip-components 1; then
-    printf "%s\n\n" "Failed to extract the SCTP archive file: $packages/sctp-1.0.17.tar.gz"
-fi
-
-printf "\n%s\n%s\n\n" \
-    'Building SCTP Module Support version 1.0.17' \
-    '==============================================='
-
-# INSTALL SCTP MODULE SUPPORT
-cd "$packages/sctp" || exit 1
-autoreconf -fi
-./bootstrap
-./configure
-make -j32
-
-# ENSURE THAT AUTH CHUNKS ARE ENABLED
-sudo sysctl -w net.sctp.auth_enable=1
-
-#
-# DOWNLOAD OPENSSL ARCHIVE FILE
-#
-
-cd $packages || exit 1
-
-archive_file="$archive_name.tar.$archive_ext"
-
-if [ ! -f "$archive_file" ]; then
-    if ! curl -Lso "$archive_file" "$archive_url"; then
-        fail_fn "Failed to download: $archive_url as $archive_file"
-    fi
+if [ ! -f "$cert_dir/$pem_filename" ]; then
+    printf "%s\n%s\n\n" \
+        'Download the latest security certificate' \
+        '================================================'
+    curl -Lso "$cwd/$pem_filename" "https://curl.se/ca/$pem_filename"
+    sudo mv -f "$cwd/$pem_filename" "$cert_dir/$pem_filename"
 fi
 
 #
-# CREATE THE OPENSSL OUTPUT DIRECTORY
+# DOWNLOAD ARCHIVE FILE
 #
 
-if [ -d "$packages/$archive_name" ]; then
-    sudo rm -fr "$packages/$archive_name"
-fi
+archive_name="$archive_dir.tar.$archive_ext"
 
-mkdir -p "$packages/$archive_name/build"
-
-#
-# EXTRACT OPENSSL ARCHIVE FILE
-#
-
-if ! tar -zxf "$archive_file" -C "$packages/$archive_name" --strip-components 1; then
-    fail_fn "Failed to extract: $archive_file"
+if [ ! -f "$cwd/$archive_name" ]; then
+    curl -Lso "$cwd/$archive_name" "$archive_url"
 fi
 
 #
-# BUILD OPENSSL FROM SOURCE
+# CREATE OUTPUT DIRECTORY
 #
 
-printf "\n%s\n%s\n\n" \
-    'Building OpenSSL version 3.1.1' \
-    '==============================================='
+if [ -d "$cwd/$archive_dir" ]; then
+    sudo rm -fr "$cwd/$archive_dir"
+fi
+mkdir -p "$cwd/$archive_dir/build"
 
-cd "$packages/$archive_name/build" || exit 1
-clear
+#
+# EXTRACT ARCHIVE FILES
+#
 
-../Configure linux-x86_64                \
-             --prefix=/usr/local         \
-             --with-rand-seed=os         \
-             enable-egd                  \
-             enable-fips                 \
-             enable-md2                  \
-             enable-rc5                  \
-             enable-trace                \
-             sctp                        \
-             threads
+if ! tar -xf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/$archive_name"
+    exit 1
+fi
 
+#
+# BUILD PROGRAM FROM SOURCE
+#
+
+cd "$cwd/$archive_dir/build" || exit 1
+../Configure --prefix="$install_dir"          \
+             --openssldir="$ssl_dir"          \
+             --with-rand-seed=os              \
+             --with-zlib-include=/usr/include \
+             --with-zlib-lib=/usr/lib         \
+             enable-egd                       \
+             enable-fips                      \
+             enable-md2                       \
+             enable-rc5                       \
+             enable-trace                     \
+             sctp                             \
+             threads                          \
+             zlib
 make "-j$(nproc --all)"
-
-if ! sudo make all; then
-    make distclean
-    fail_fn 'Failed to execute: sudo make all'
-fi
-
 if ! sudo make install; then
-    make distclean
     fail_fn 'Failed to execute: sudo make install'
 fi
 
 if ! sudo make install_fips; then
-    make distclean
     fail_fn 'Failed to execute: sudo make install_fips'
 fi
 
 # REQUIRED FOR FIPS FUNCTIONALITY TO WORK
 sudo openssl fipsinstall
+
+# ENSURE THE CORRECT PERMISSIONS ARE ATTACHED TO THE CUSTOM PEM FILE THAT WAS ADDED
+if [ -f "$pem_output" ]; then
+    sudo chmod 644 "$pem_output"
+fi
 
 # CLEANUP FILES
 cleanup_fn
