Update build-tools

diff --git a/Bash/Installer Scripts/GitHub Projects/build-tools b/Bash/Installer Scripts/GitHub Projects/build-tools
--- a/Bash/Installer Scripts/GitHub Projects/build-tools
+++ b/Bash/Installer Scripts/GitHub Projects/build-tools
@@ -6,42 +6,37 @@
 ##  Updated: 02.16.24
 ##  Added: Automatic version check for Golang.
 
-clear
-
 if [ "$EUID" -eq 0 ]; then
     printf "%s\n\n" "You must run this script WITHOUT root/sudo"
     exit 1
 fi
 
-# CREATE SCRIPT VARIABLES
-script_ver="2.8"
+# Create script variables
+script_ver=2.8
 cwd="$PWD/build-tools-script"
 install_dir="/usr/local"
-user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
 web_repo="https://github.com/slyfox1186/script-repo"
 latest=false
-debug=OFF # CHANGE THE DEBUG VARIABLE TO "ON" FOR HELP TROUBLESHOOTING ISSUES
+debug=OFF # Change the debug variable to "ON" for help troubleshooting issues
 
-# PRINT SCRIPT BANNER
+# Print script banner
 printf "%s\n%s\n" "Build-tools script: v$script_ver" "===================================="
 sleep 2
 
-# GET CPU CORE COUNT FOR PARALLEL PROCESSING
-cpu_threads=$(grep --count ^processor '/proc/cpuinfo' 2>/dev/null || nproc --all)
+# Get CPU core count for parallel processing
+cpu_threads=$(grep -c ^processor '/proc/cpuinfo' 2>/dev/null || nproc --all)
 
 # CREATE OUTPUT DIRECTORIES
 mkdir -p "$cwd"
 
-# SET THE CC/CXX COMPILERS & THE COMPILER OPTIMIZATION FLAGS
+# Set the CC/CXX compilers & the compiler optimization flags
 CC=gcc
 CXX=g++
 CFLAGS="-g -O3 -pipe -march=native"
 CXXFLAGS="$CFLAGS"
-CPPFLAGS="-I/usr/local/include -I/usr/include"
-LDFLAGS+="-L/usr/local/lib64 -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib64 -L/usr/lib -L/lib64 -L/lib"
-export CC CXX CFLAGS CPPFLAGS CXXFLAGS LDFLAGS
+export CC CXX CFLAGS CXXFLAGS
 
-# SET THE PATH VARIABLE
+# Set the PATH variable
 PATH="\
 /usr/lib/ccache:\
 $HOME/perl5/bin:\
@@ -58,7 +53,7 @@ $HOME/.local/bin:\
 "
 export PATH
 
-# SET THE PKG_CONFIG_PATH VARIABLE
+# Set the PKG_CONFIG_PATH variable
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
 /usr/local/lib/pkgconfig:\
@@ -74,27 +69,35 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
-# CREATE FUNCTIONS
+# Create functions
 exit_fn() {
     printf "\n%s\n\n%s\n%s\n\n" "The script has completed" "Make sure to star this repository to show your support!" "$web_repo"
     exit 0
 }
 
 fail_fn() {
-    printf "\n\n%s\n\n%s\n\n%s\n\n" "$1" "To report a bug please create an issue at:" "$web_repo/issues"
+    echo "Error: $1"
+    echo
+    echo "To report a bug please create an issue at:"
+    echo "$web_repo/issues"
+    echo
     exit 1
 }
 
 cleanup_fn() {
     local choice
-    printf "\n%s\n\n%s\n%s\n\n" "Do you want to remove the build files?" "[1] Yes" "[2] No"
+    echo
+    echo "Do you want to remove the build files?"
+    echo
+    echo "[1] Yes"
+    echo "[2] No"
+    echo
     read -p "Your choices are (1 or 2): " choice
 
     case "$choice" in
         1) sudo rm -fr "$cwd" ;;
         2) return 0 ;;
-        *)
-           unset choice
+        *) unset choice
            clear
            cleanup_fn
            ;;
@@ -103,14 +106,17 @@ cleanup_fn() {
 
 show_versions_fn() {
     local show_cmake_ver show_ninja_ver show_meson_ver show_go_ver
-    clear
 
     show_cmake_ver=$(cmake --version | sed -e 's/cmake version //g' -e 's/CMake suite maintained and supported by Kitware (kitware.com\/cmake).//g' | xargs -n1)
     show_ninja_ver=$(ninja --version)
     show_meson_ver=$(meson --version)
     show_go_ver=$(go version | grep -Eo '[0-9\.]+ | xargs -n1')
 
-    printf "%s\n\n%s\n%s\n%s\n%s\n" "The updated versions are:" "CMake:  $show_cmake_ver" "Ninja:  $show_ninja_ver" "Meson:  $show_meson_ver" "GoLang: $show_go_ver"
+    printf "\n%s\n\n" "The updated versions are:"
+    echo "CMake:  $show_cmake_ver"
+    echo "Ninja:  $show_ninja_ver"
+    echo "Meson:  $show_meson_ver"
+    echo "GoLang: $show_go_ver"
 }
 
 execute() {
@@ -148,10 +154,10 @@ download() {
         echo "The file \"$dl_file\" is already downloaded."
     else
         echo "Downloading \"$dl_url\" saving as \"$dl_file\""
-        if ! curl -A "$user_agent" -Lso "$target_file" "$dl_url"; then
+        if ! curl -Lso "$target_file" "$dl_url"; then
             printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! curl -A "$user_agent" -Lso "$target_file" "$dl_url"; then
+            if ! curl -Lso "$target_file" "$dl_url"; then
                 fail_fn "The script failed to download \"$dl_file\" twice and will now exit:Line $LINENO"
             fi
         fi
@@ -180,39 +186,6 @@ download() {
     cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: $LINENO"
 }
 
-download_git() {
-    local dl_path dl_url dl_file target_dir
-
-    dl_path="$cwd"
-    dl_url="$1"
-    dl_file="${2:-"${1##*/}"}"
-    dl_file="${dl_file//\./-}"
-    target_dir="$dl_path/$dl_file"
-
-    if [ -n "$3" ]; then
-        output_dir="$dl_path/$3"
-        target_dir="$output_dir"
-    fi
-
-    if [ -d "$target_dir" ]; then
-        sudo rm -fr "$target_dir"
-    fi
-
-    echo "Downloading $dl_url as $dl_file"
-
-    if ! git clone -q "$dl_url" "$target_dir"; then
-        printf "\n%s\n\n" "The script failed to clone the directory \"$target_dir\" and will try again in 10 seconds..."
-        sleep 10
-        if ! git clone -q "$dl_url" "$target_dir"; then
-            fail_fn "The script failed to clone the directory \"$target_dir\" twice and will now exit the build. Line: $LINENO"
-        fi
-    else
-        printf "%s\n\n" "Successfully cloned: $target_dir"
-    fi
-
-    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: $LINENO"
-}
-
 build() {
     printf "\n%s\n%s\n" "Building $1 - version $2" "===================================="
 
@@ -220,7 +193,7 @@ build() {
         if grep -Fx "$2" "$cwd/$1.done" >/dev/null; then
             echo "$1 version $2 already built. Remove $cwd/$1.done lockfile to rebuild it."
             return 1
-        elif "${latest}"; then
+        elif "$latest"; then
             echo "$1 is outdated and will be rebuilt using version $2"
             return 0
         else
@@ -259,7 +232,7 @@ pkgs_arch_fn() {
 
     [ -n "$(sudo find /usr/lib/python3* -type f -name 'EXTERNALLY-MANAGED')" ] && sudo rm "$rm_pip_lock"
 
-    # INSTALL PYTHON PIP PACKAGES
+    # Install python pip packages
     pip install -q --user --no-input requests setuptools wheel
 }
 
@@ -303,7 +276,7 @@ pkgs_fn() {
         echo "Installing available missing packages: ${available_packages[*]}"
         sudo apt install "${available_packages[@]}"
     else
-        printf "%s\n\n" "No missing packages to install or all missing packages are unavailable."
+        echo "No missing packages to install or all missing packages are unavailable."
     fi
 }
 
@@ -348,7 +321,21 @@ git_1_fn() {
 
     # Check if a version was found
     if [ $cnt -gt 10 ]; then
-        echo "No matching version found without RC/rc suffix."
+        fail_fn "No matching version found without RC/rc suffix."
+    fi
+}
+
+add_go_path_command_to_bashrc() {
+    local command='PATH="$PATH:$GOROOT/bin"'
+    local bashrc="$HOME/.bashrc"
+
+    echo "Checking if command is already in .bashrc file..."
+    if grep -Fq "$command" "$bashrc"; then
+        echo "Command already exists in .bashrc. No action taken."
+    else
+        echo "Adding command to .bashrc file..."
+        echo "$command" >> "$bashrc"
+        echo "Command added to .bashrc successfully."
     fi
 }
 
@@ -356,10 +343,10 @@ git_1_fn() {
 get_first_word() { echo "$1" | awk '{print $1}'; }
 
 # Try to detect the OS using /etc/os-release, fall back to lsb_release if available
-if [ -f "/etc/os-release" ]; then
-    . "/etc/os-release"
+if [ -f /etc/os-release ]; then
+    . /etc/os-release
     OS=$(get_first_word "$NAME")
-elif lsb_release -d &> /dev/null; then
+elif lsb_release -d &>/dev/null; then
     OS=$(lsb_release -d | awk '{print $2}')
 else
     fail_fn "Failed to define the \$OS and/or \$VER variables. Line: $LINENO"
@@ -370,14 +357,11 @@ case "$OS" in
     *)      pkgs_fn ;;
 esac
 
-# CHECK IF THE LATEST RELEASE IS A "RC" AKA RELEASE CANDIDATE AND IF SO GO BACK TO THE PREVIOUS STABLE RELEASE
+# Check if the latest release is a "rc" aka release candidate and if so go back to the previous stable release
 git_1_fn "Kitware/CMake"
 if build "cmake" "$g_ver"; then
     download "https://github.com/Kitware/CMake/archive/refs/tags/v$g_ver.tar.gz" "cmake-$g_ver.tar.gz"
-    execute ./bootstrap --prefix="$install_dir" \
-                        --enable-ccache \
-                        --parallel="$(nproc --all)" \
-                        --qt-gui
+    execute ./bootstrap --prefix="$install_dir" --enable-ccache --parallel="$(nproc --all)" --qt-gui
     execute make "-j$cpu_threads"
     execute sudo make install
     build_done "cmake" "$g_ver"
@@ -387,18 +371,13 @@ git_1_fn "ninja-build/ninja"
 if build "ninja" "$g_ver"; then
     download "https://github.com/ninja-build/ninja/archive/refs/tags/v$g_ver.tar.gz" "ninja-$g_ver.tar.gz"
     re2c_path="$(type -P re2c)"
-    execute cmake -B build \
-                  -DCMAKE_INSTALL_PREFIX="$install_dir" \
-                  -DCMAKE_BUILD_TYPE=Release \
-                  -DRE2C="$re2c_path" \
-                  -DBUILD_TESTING=OFF \
-                  -Wno-dev
+    execute cmake -B build -DCMAKE_INSTALL_PREFIX="$install_dir" -DCMAKE_BUILD_TYPE=Release -DRE2C="$re2c_path" -DBUILD_TESTING=OFF -Wno-dev
     execute make "-j$cpu_threads" -C build
     execute sudo make -C build install
     build_done "ninja" "$g_ver"
 fi
 
-if [[ "${OS}" == "Arch" ]]; then
+if [[ "$OS" == "Arch" ]]; then
     sudo pacman -Sq --needed --noconfirm meson 2>&1
 else
     git_1_fn "mesonbuild/meson"
@@ -410,35 +389,36 @@ else
     fi
 fi
 
-if [[ "$OS" == "Arch" ]]; then
-    sudo pacman -Sq --needed --noconfirm go
-    mkdir -p  "$HOME/go"
-    GOPATH="$HOME/go"
-    export GOPATH
-    source "$HOME/.bash_profile"
-else
-    if build "golang" "1.21.6"; then
-        download "https://go.dev/dl/go${latest_version}.linux-amd64.tar.gz" "golang-${latest_version}.tar.gz"
-        execute sudo cp -f "bin/go" "bin/gofmt" "$install_dir/bin"
-        if [ -d  "$install_dir/go" ]; then
-            sudo rm -fr "$install_dir/go"
-        fi
-        sudo mkdir -p "$install_dir/go"
-        GOROOT="$install_dir/go"
-        PATH="$PATH:$GOROOT/bin"
-        export GOROOT PATH
-        build_done "golang" "1.21.6"
-    fi
+# Remove leftover files from previous runs
+if [ -d  "$install_dir/go" ]; then
+    sudo rm -fr "$install_dir/go"
 fi
 
-# LDCONFIG MUST BE RUN NEXT IN ORDER TO UPDATE FILE CHANGES
+# Install Golang
+if [[ "$OS" == "Arch" ]]; then
+    sudo pacman -Sq --needed --noconfirm go
+else
+    if build "golang" "$latest_version"; then
+        download "https://go.dev/dl/go${latest_version}.linux-amd64.tar.gz" "golang-${latest_version}.tar.gz"
+        execute sudo cp -f "bin/go" "bin/gofmt" "$install_dir/bin"
+        build_done "golang" "$latest_version"
+    fi
+    sudo mkdir -p "$install_dir/go"
+    GOROOT="$install_dir/go"
+    PATH="$PATH:$GOROOT/bin"
+    export GOROOT PATH
+    add_go_path_command_to_bashrc
+    source "$HOME/.bashrc"
+fi
+
+# ldconfig must be run next in order to update file changes
 sudo ldconfig 2>/dev/null
 
-# SHOW THE NEWLY INSTALLED VERSION OF EACH PACKAGE
+# Show the newly installed version of each package
 show_versions_fn
 
-# PROMPT THE USER TO CLEAN UP THE BUILD FILES
+# Prompt the user to clean up the build files
 cleanup_fn
 
-# SHOW THE EXIT MESSAGE
+# Show the exit message
 exit_fn
