Update build-nasm

diff --git a/Bash/Installer Scripts/GitHub Projects/build-nasm b/Bash/Installer Scripts/GitHub Projects/build-nasm
--- a/Bash/Installer Scripts/GitHub Projects/build-nasm
+++ b/Bash/Installer Scripts/GitHub Projects/build-nasm
@@ -5,8 +5,9 @@
 ##
 ##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-nasm
 ##
-##  Purpose: Build nasm
-##  Updated: 08.04.23
+##  Purpose: Build NASM
+##
+##  Updated: 10.13.23
 ##
 ##  Script version: 1.0
 ##
@@ -20,24 +21,20 @@ if [ "${EUID}" -eq '0' ]; then
 fi
 
 #
-# SET VARIABLES
+# SET GLOBAL VARIABLES
 #
 
 script_ver=1.0
-archive_dir=nasm-2.16.01
-archive_url=https://www.nasm.us/pub/nasm/stable/nasm-2.16.01.tar.xz
-archive_ext="${archive_url//*.}"
+progname="${0}"
 cwd="${PWD}"/nasm-build-script
+install_prefix=/usr/local
+pc_type=x86_64-linux-gnu
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
-debug=OFF
-
-printf "\n%s\n%s\n\n" \
-    "nasm build script - v${script_ver}" \
-    '==============================================='
+debug=OFF # CHANGE THIS VARIABLE TO "ON" FOR HELP WITH TROUBLESHOOTING UNEXPECTED ISSUES DURING THE BUILD
 
 #
-# CREATE OUTPUT DIRECTORY
+# CREATE OUTPUT DIRECTORIES
 #
 
 if [ ! -d "${cwd}" ]; then
@@ -45,7 +42,7 @@ if [ ! -d "${cwd}" ]; then
 fi
 
 #
-# SET THE C+CPP COMPILERS
+# FIGURE OUT WHICH COMPILERS TO USE
 #
 
 export CC=gcc CXX=g++
@@ -57,8 +54,14 @@ export CC=gcc CXX=g++
 export {CFLAGS,CXXFLAGS}='-g -O2 -march=native'
 
 #
-# SET THE PATH VARIABLE
+# SET THE AVAILABLE CPU COUNT FOR PARALLEL PROCESSING (SPEEDS UP THE BUILD PROCESS)
 #
+
+if [ -f /proc/cpuinfo ]; then
+    cpu_threads="$(grep --count ^processor /proc/cpuinfo)"
+else
+    cpu_threads="$(nproc --all)"
+fi
 
 PATH="\
 /usr/lib/ccache:\
@@ -75,22 +78,17 @@ ${HOME}/.local/bin:\
 "
 export PATH
 
-#
-# SET THE PKG_CONFIG_PATH VARIABLE
-#
-
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
 /usr/local/lib/pkgconfig:\
-/usr/local/lib/usr/local/pkgconfig:\
+/usr/local/lib/x86_64-linux-gnu/pkgconfig:\
 /usr/local/share/pkgconfig:\
 /usr/lib64/pkgconfig:\
 /usr/lib/pkgconfig:\
-/usr/lib/usr/local/pkgconfig:\
+/usr/lib/x86_64-linux-gnu/pkgconfig:\
 /usr/share/pkgconfig:\
 /lib64/pkgconfig:\
-/lib/pkgconfig:\
-/lib/usr/local/pkgconfig\
+/lib/pkgconfig\
 "
 export PKG_CONFIG_PATH
 
@@ -100,7 +98,8 @@ export PKG_CONFIG_PATH
 
 exit_fn()
 {
-    printf "\n%s\n\n%s\n\n" \
+    printf "\n%s\n\n%s\n%s\n\n"                                    \
+        'The script has completed'                                \
         'Make sure to star this repository to show your support!' \
         "${web_repo}"
     exit 0
@@ -108,9 +107,10 @@ exit_fn()
 
 fail_fn()
 {
-    printf "\n%s\n\n%s\n\n" \
-        "${1}" \
-        "To report a bug create an issue at: ${web_repo}/issues"
+    printf "\n\n%s\n\n%s\n\n%s\n\n"      \
+        "${1}"                           \
+        'To report a bug please visit: ' \
+        "${web_repo}/issues"
     exit 1
 }
 
@@ -118,20 +118,18 @@ cleanup_fn()
 {
     local choice
 
-    printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
-        '============================================' \
-        '  Do you want to clean up the build files?  ' \
-        '============================================' \
-        '[1] Yes' \
+    printf "%s\n\n%s\n%s\n\n"                    \
+        'Do you want to remove the build files?' \
+        '[1] Yes'                                \
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
     case "${choice}" in
         1)      sudo rm -fr "${cwd}";;
-        2)      echo;;
+        2)      clear;;
         *)
                 clear
-                printf "%s\n\n" 'Bad user input. Reverting script...'
+                printf "%s\n\n" 'Error: bad user input. Reverting script...'
                 sleep 3
                 unset choice
                 clear
@@ -140,43 +138,39 @@ cleanup_fn()
     esac
 }
 
+execute()
+{
+    echo "$ ${*}"
+
+    if [ "${debug}" = 'ON' ]; then
+        if ! output="$("${@}")"; then
+            notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
+            fail_fn "Failed to execute: ${*}"
+        fi
+    else
+        if ! output="$("${@}" 2>&1)"; then
+            notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
+            fail_fn "Failed to execute: ${*}"
+        fi
+    fi
+}
+
 build()
 {
     printf "\n%s\n%s\n" \
-        "building ${1} - version ${2}" \
-        '===================================='
+        "Building ${1} - version ${2}" \
+        '=========================================='
 
     if [ -f "${cwd}/${1}.done" ]; then
         if grep -Fx "${2}" "${cwd}/${1}.done" >/dev/null; then
             echo "${1} version ${2} already built. Remove ${cwd}/${1}.done lockfile to rebuild it."
-            return 1
-        elif ${latest}; then
-            echo "${1} is outdated and will be rebuilt using version ${2}"
-            return 0
-        else
-            echo "${1} is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove ${cwd}/${1}.done lockfile."
             return 1
         fi
     fi
     return 0
 }
 
-execute()
-{
-    echo "$ ${*}"
-
-    if [ "${debug}" = 'ON' ]; then
-        if ! output=$("${@}"); then
-            notify-send 5000 "Failed to execute: ${*}"
-            fail_fn "Failed to execute: ${*}"
-        fi
-    else
-        if ! output=$("${@}" 2>&1); then
-            notify-send 5000 "Failed to execute: ${*}"
-            fail_fn "Failed to execute: ${*}"
-        fi
-    fi
-}
+build_done() { echo "${2}" > "${cwd}/${1}.done"; }
 
 download()
 {
@@ -198,14 +192,14 @@ download()
         echo "The file \"${dl_file}\" is already downloaded."
     else
         echo "Downloading \"${dl_url}\" saving as \"${dl_file}\""
-        if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
+        if ! wget --show-progress -U "${user_agent}" -cqO "${target_file}" "${dl_url}"; then
             printf "\n%s\n\n" "The script failed to download \"${dl_file}\" and will try again in 10 seconds..."
             sleep 10
-            if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
-                fail_fn "The script failed to download \"${dl_file}\" twice and will now exit:Line ${LINENO}"
+            if ! wget --show-progress -U "${user_agent}" -cqO "${target_file}" "${dl_url}"; then
+                fail_fn "The script failed to download \"${dl_file}\" twice and will now exit. Line: ${LINENO}"
             fi
         fi
-        echo 'Download Completed'
+        printf "\n%s\n\n" 'Download completed'
     fi
 
     if [ -d "${target_dir}" ]; then
@@ -217,29 +211,56 @@ download()
     if [ -n "${3}" ]; then
         if ! tar -xf "${target_file}" -C "${target_dir}" 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script:Line ${LINENO}"
+            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script. Line: ${LINENO}"
         fi
     else
         if ! tar -xf "${target_file}" -C "${target_dir}" --strip-components 1 2>/dev/null >/dev/null; then
             sudo rm "${target_file}"
-            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script:Line ${LINENO}"
+            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script. Line: ${LINENO}"
         fi
     fi
 
     printf "%s\n\n" "File extracted: ${dl_file}"
 
-    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}:Line ${LINENO}"
+    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}. Line: ${LINENO}"
 }
 
-build_done() { echo "${2}" > "${cwd}/${1}.done"; }
+git_1_fn()
+{
+    local curl_cmd github_repo github_url
+
+    github_repo="${1}"
+    github_url="${2}"
+
+    if curl_cmd="$(curl -A "${user_agent}" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
+        g_ver="$(echo "${curl_cmd}" | jq -r '.[1].name' 2>/dev/null)"
+        g_url="$(echo "${curl_cmd}" | jq -r '.[1].tarball_url' 2>/dev/null)"
+        g_ver="${g_ver#llvmorg-}"
+    fi
+}
+
+git_ver_fn()
+{
+    local t_flag v_flag v_url
+
+    v_url="${1}"
+    v_flag="${2}"
+
+    case "${v_flag}" in
+            R)      t_flag=releases;;
+            T)      t_flag=tags;;
+    esac
+
+    git_1_fn "${v_url}" "${t_flag}" 2>/dev/null
+}
 
 #
-# INSTALL REQUIRED APT PACKAGES
+# PRINT THE OPTIONS AVAILABLE WHEN MANUALLY RUNNING THE SCRIPT
 #
 
-pkgs=(asciidoc autogen automake binutils bison build-essential bzip2 ccache cmake
-      curl libc6-dev libintl-perl libpth-dev libtool libtool-bin lzip lzma-dev
-      nasm ninja-build texinfo xmlto yasm zlib1g-dev)
+pkgs=(autoconf autoconf-archive automake autopoint binutils binutils-dev bison
+      build-essential ccache clang cmake curl jq libc6 libc6-dev libedit-dev
+      libtool libtool-bin libxml2-dev m4 nasm ninja-build yasm zlib1g-dev)
 
 for i in ${pkgs[@]}
 do
@@ -252,27 +273,43 @@ done
 
 if [ -n "${missing_pkgs}" ]; then
     sudo apt -y install ${missing_pkgs}
-    sudo apt -y autoremove
     clear
+else
+    printf "%s\n" 'The APT packages are already installed'
 fi
 
 #
-# BUILD PROGRAM FROM SOURCE
+# BEGIN BUILDING CLANG
 #
+
+clear
+box_out_banner()
+{
+    input_char=$(echo "${@}" | wc -c)
+    line=$(for i in $(seq 0 ${input_char}); do printf '-'; done)
+    tput bold
+    line="$(tput setaf 3)${line}"
+    space=${line//-/ }
+    echo " ${line}"
+    printf '|' ; echo -n "${space}" ; printf "%s\n" '|';
+    printf '| ' ;tput setaf 4; echo -n "${@}"; tput setaf 3 ; printf "%s\n" ' |';
+    printf '|' ; echo -n "${space}" ; printf "%s\n" '|';
+    echo " ${line}"
+    tput sgr 0
+}
+box_out_banner "Nasm Build Script - version ${script_ver}"
 
 if build 'nasm' '2.16.01'; then
-    download "${archive_url}"
-    ./autogen.sh
-    ./configure --prefix=/usr/local                    \
-                --{build,host,target}=x86_64-linux-gnu \
-                --disable-pedantic                     \
-                --enable-ccache
-    execute make "-j$(nproc --all)"
+    download 'https://www.nasm.us/pub/nasm/stable/nasm-2.16.01.tar.xz'
+    execute ./autogen.sh
+    execute ./configure --prefix=/usr/local                \
+                        --{build,host,target}="${pc_type}" \
+                        --enable-ccache
+    execute make "-j${cpu_threads}"
     execute sudo make install
-    build_done 'nasm' '2.16.01'
 fi
 
-# PROMPT USER TO CLEAN UP FILES
+# PROMPT THE USER TO CLEAN UP THE BUILD FILES
 cleanup_fn
 
 # SHOW EXIT MESSAGE
