revert scripts to earlier versions

diff --git a/Bash/Installer Scripts/GitHub Projects/build-clang-17 b/Bash/Installer Scripts/GitHub Projects/build-clang-17
--- a/Bash/Installer Scripts/GitHub Projects/build-clang-17
+++ b/Bash/Installer Scripts/GitHub Projects/build-clang-17
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
+# Shellcheck disable=sc2162,sc2317
 
+##  Github Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-clang-17-gold
+##  Purpose: Build LLVM Clang-17 with GOLD enabled
+##  Updated: 03.06.24
+##  Script version: 1.7
 
 log() {
     echo "[LOG] $1"
@@ -14,6 +19,7 @@ fail_fn() {
     exit 1
 }
 
+# Function to check if running as root/sudo
 check_root() {
     if [ "$EUID" -ne 0 ]; then
         echo "You must run this script with root or sudo.privileges."
@@ -22,6 +28,7 @@ check_root() {
     fi
 }
 
+# Function to install required apt packages
 install_required_packages() {
     local pkgs=(
         autoconf autoconf-archive automake autopoint binutils binutils-dev
@@ -33,11 +40,12 @@ install_required_packages() {
     local missing_packages=()
 
     for pkg in "${pkgs[@]}"; do
-        if ! dpkg-query -W -f='$Status' "$pkg" | grep -q "ok installed"; then
+        if ! dpkg-query -W -f='${Status}' "$pkg" | grep -q "ok installed"; then
             missing_packages+=("$pkg")
         fi
     done
 
+    if [ "${#Missing_packages[@]}" -gt 0 ]; then
         apt update
         apt install "${missing_packages[@]}"
     else
@@ -45,6 +53,7 @@ install_required_packages() {
     fi
 }
 
+# Function to fix missing x265 library symlink
 fix_missing_x265_lib() {
     local link_in=$(find /usr/lib/x86_64-linux-gnu/ -type f -name 'libstdc++.so.6.0.*')
     local link_out="/usr/lib/x86_64-linux-gnu/libstdc++.so"
@@ -57,6 +66,7 @@ fix_missing_x265_lib() {
 find_highest_clang_version() {
     local clang_version
 
+# Check if a specific version is installed, in descending order of preference
     for clang_version in 16 15 14 13; do
         if command -v "clang-$clang_version" &>/dev/null; then
             CC="clang-$clang_version"
@@ -65,6 +75,7 @@ find_highest_clang_version() {
         fi
     done
 
+# If none of the specific versions are found, fall back to "clang" if it's installed
     if command -v clang &>/dev/null; then
         CC="clang"
         CXX="clang++"
@@ -73,9 +84,11 @@ find_highest_clang_version() {
     fi
 }
 
+# Function to download and extract a file
 download_and_extract() {
     local url="$1"
     local target_dir="$2"
+    local filename="${url##*/}"
     clear
     set -x
     echo $filename
@@ -96,12 +109,15 @@ download_and_extract() {
     fi
 }
 
+# Function to build and install llvm clang-17
 build_and_install_llvm_clang() {
     local llvm_url="https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-17.0.6.tar.gz"
 
+# Specify the directory where you want to extract the llvm source code
     local llvm_code_dir="$workspace"
     local llvm_source_file_dir="$source_files_dir"
 
+# Check if the source file already exists or download it
     local llvm_tar_url="https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-17.0.6.tar.gz"
     local llvm_tar_filename="$llvm_source_file_dir/llvmorg-17.0.6.tar.gz"
 
@@ -113,10 +129,12 @@ build_and_install_llvm_clang() {
         log "Download completed"
     fi
 
+# Extract the source file
     echo "Extracting LLVM source to $llvm_code_dir..."
     tar -zxf "$llvm_tar_filename" -C "$llvm_code_dir" --strip-components 1
     echo "LLVM source code extracted to $llvm_code_dir"
 
+# Check if the source directory exists or clone llvm if not
     if [ ! -d "$llvm_code_dir" ]; then
         log "LLVM source directory not found. Cloning LLVM source..."
         download_and_extract "$llvm_url" "/tmp"
@@ -271,6 +289,7 @@ build_and_install_llvm_clang() {
     fi
 }
 
+# Function to show installed clang version
 show_installed_clang_version() {
     local clang_versions=("clang-17" "clang++-17" "clang++")
 
@@ -287,6 +306,7 @@ show_installed_clang_version() {
     done
 }
 
+# Function to prompt the user to clean up the build files
 cleanup_build_files() {
     local choice
     echo
@@ -307,6 +327,7 @@ cleanup_build_files() {
     esac
 }
 
+# Display exit message
 display_exit_message() {
     echo
     log "The script has completed."
@@ -315,6 +336,7 @@ display_exit_message() {
     exit 0
 }
 
+# Function to check if a package needs to be built
 build() {
     local pkg_name="$1"
     local pkg_version="$2"
@@ -328,31 +350,38 @@ build() {
     return 0
 }
 
+# Function to mark a package as built
 build_done() {
     local pkg_name="$1"
     local pkg_version="$2"
     echo "$pkg_version" > "$workspace/$pkg_name.done"
 }
 
+# Check if running as root/sudo
 check_root
 
+# Set global variables
 source_files_dir="$PWD/clang-17-build-script"
 workspace="$PWD/clang-17-build-script/workspace"
 install_dir="/usr/local"
 web_repo="https://github.com/slyfox1186/script-repo"
 
+# Remove files from previous attempts to keep things clean
 if [ -d "$workspace" ]; then
     log "Removing files from previous attempts."
     rm -fr "$workspace"
 fi
 
+# Create output directories
 mkdir -p "$workspace" "$source_files_dir"
 
+# Set the cc/cxx compilers & the compiler optimization flags
 CFLAGS="-g -O3 -pipe -fno-plt -march=native"
 CXXFLAGS="-g -O3 -pipe -fno-plt -march=native"
 LDFLAGS="-Wl,-rpath -Wl,/usr/local/lib -Wl,--as-needed"
 export CC CFLAGS CXX CXXFLAGS LDFLAGS
 
+# Set the path variable
 PATH="\
 /usr/lib/ccache:\
 $HOME/perl5/bin:\
@@ -369,6 +398,7 @@ $HOME/.local/bin:\
 "
 export PATH
 
+# Set the pkg_config_path variable
 PKG_CONFIG_PATH="\
 /usr/share/pkgconfig:\
 /usr/local/lib/x86_64-linux-gnu/pkgconfig:\
@@ -381,18 +411,26 @@ export PKG_CONFIG_PATH
 
 export -f log
 
+# Install required apt packages
 install_required_packages
 
+# Fix missing 'x265' library symlink
 fix_missing_x265_lib
 
+# Refresh the ld linker library shared library files
 ldconfig
 
+# Get the highest installed clang version to use as our compiler
 find_highest_clang_version
 
+# Build and install llvm clang-17
 build_and_install_llvm_clang
 
+# Show the newly installed clang version
 show_installed_clang_version
 
+# Prompt the user to clean up the build files
 cleanup_build_files
 
+# Display exit message
 display_exit_message
diff --git a/Bash/Installer Scripts/GitHub Projects/build-curl b/Bash/Installer Scripts/GitHub Projects/build-curl
--- a/Bash/Installer Scripts/GitHub Projects/build-curl
+++ b/Bash/Installer Scripts/GitHub Projects/build-curl
@@ -1,50 +1,62 @@
-#!/Usr/bin/env bash
+#!/usr/bin/env bash
 
+##  Github Script: https://github.com/slyfox1186/script-repo/edit/main/util-linux/Installer%20Scripts/GNU%20Software/build-curl
+##  Purpose: Build cURL with OpenSSL backend
+##  Updated: 02.02.24
+##  Script version: 1.7
 
 clear
 
-if [ "$EUID" -eq "0" ]; then
+if [ "${EUID}" -eq "0" ]; then
     echo "You must run this script without root or sudo."
     exit 1
 fi
 
+# Set strict mode for bash
 set -euo pipefail
 
+# Define the program name
 program="curl"
 pem_file="cacert.pem"
 install_dir=/usr/local
 certs_dir="/etc/ssl/certs"
 pem_out="$certs_dir/$pem_file"
 
+# Environment variable settings
 CC=gcc
 CXX=g++
 CFLAGS="-g -O3 -pipe -fno-plt -march=native"
-CXXFLAGS="$CFLAGS -Wno-variadic-macros"
+CXXFLAGS="${CFLAGS} -Wno-variadic-macros"
 CPPFLAGS="-I/usr/include/openssl -I/usr/local/include -I/usr/include/libxml2 -I/usr/include"
 export CC CXX CFLAGS CPPFLAGS CXXFLAGS
 
 PKG_CONFIG_PATH="/usr/local/lib64/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/lib/pkgconfig"
 export PKG_CONFIG_PATH
 
+# Fail function to handle errors
 fail_fn() {
     echo "Error: $1"
     exit 1
 }
 
+# Fetch the latest release tag from github tags page
 version="$(curl -s "https://github.com/curl/curl/tags" | grep -oP 'curl-[0-9]+_[0-9]+_[0-9]+' | head -n 1)"
 if [ -z "$version" ]; then
     printf "Error: Unable to fetch the latest release version of %s.\n" "$program"
     exit 1
 fi
 
+# Extract and format the version number
 formatted_version="$(echo "$version" | sed "s/curl-//" | sed "s/_/\./g")"
 
 printf "Latest release version of %s is %s.\n" "$program" "$formatted_version"
 
-download_url="https://github.com/curl/curl/archive/refs/tags/$version.tar.gz"
-tar_file="$program-$formatted_version.tar.gz"
-extract_dir="$program-build-script-$formatted_version"
+# Construct the download url and tar file name
+download_url="https://github.com/curl/curl/archive/refs/tags/${version}.tar.gz"
+tar_file="${program}-${formatted_version}.tar.gz"
+extract_dir="${program}-build-script-${formatted_version}"
 
+# Check if the tar file already exists
 if [ ! -f "$tar_file" ]; then
     printf "Downloading %s version %s...\n" "$program" "$formatted_version"
     wget "$download_url" -O "$tar_file"
@@ -52,15 +64,18 @@ else
     printf "The tar file %s already exists, skipping download.\n" "$tar_file"
 fi
 
+# Remove the output directory if it exists
 if [ -d "$extract_dir" ]; then
     printf "Removing existing directory %s...\n" "$extract_dir"
     rm -rf "$extract_dir"
 fi
 
+# Extract the tar file
 printf "Extracting %s...\n" "$tar_file"
 mkdir "$extract_dir"
 tar -zxf "$tar_file" -C "$extract_dir" --strip-components 1
 
+# Change to the directory
 cd "$extract_dir"
 
 libgcc_ver="$(sudo apt list libgcc-* 2>/dev/null | grep -Eo 'libgcc-[0-9]*-dev' | uniq | head -n1)"
@@ -69,12 +84,13 @@ libgtk_ver="$(sudo apt list libgtk-* 2>/dev/null | grep -Eo 'libgtk-[0-9]+-doc' 
 pkgs_fn() {
     local missing_pkg missing_packages pkg pkgs available_packages unavailable_packages
 
+# Check and install missing packages
     pkgs=(
         apt-transport-https apt-utils autoconf autoconf-archive autogen automake autopoint autotools-dev
         build-essential bzip2 ca-certificates ccache clang cmake curl gfortran git google-perftools graphviz
         jq lcov libaria2-0 libaria2-0-dev libc-ares-dev libcppunit-dev libcunit1-dev libcurl4 libcurl4-openssl-dev
-        libdmalloc-dev libec-dev libedit-dev libev-dev libevent-dev libexiv2-27 libexpat1-dev "$libgcc_ver"
-        libgcrypt20-dev libgexiv2-2 libgimp2.0 libgmp3-dev libgpg-error-dev "$libgtk_ver" libgpgme-dev libicu-dev
+        libdmalloc-dev libec-dev libedit-dev libev-dev libevent-dev libexiv2-27 libexpat1-dev "${libgcc_ver}"
+        libgcrypt20-dev libgexiv2-2 libgimp2.0 libgmp3-dev libgpg-error-dev "${libgtk_ver}" libgpgme-dev libicu-dev
         libjemalloc-dev libkrb5-3 libldap2-dev libldap-dev liblttng-ust-dev liblzma-dev libmbedtls-dev libnghttp2-dev
         libnghttp3-dev libntlm0-dev libparted-dev libpng-dev libpsl-dev librtmp-dev librust-bzip2-dev librust-openssl-dev
         libsqlite3-dev libssh2-1-dev libssh-dev libssl-dev libtinfo5 libticonv-dev libtinfo-dev libtool libtool-bin
@@ -83,17 +99,20 @@ pkgs_fn() {
         re2c rsync unzip valgrind zip zlib1g-dev
     )
 
+# Initialize arrays for missing, available, and unavailable packages
     missing_packages=()
     available_packages=()
     unavailable_packages=()
 
+# Loop through the array to find missing packages
     for pkg in "${pkgs[@]}"
     do
-        if ! dpkg-query -W -f='$Status' "$pkg" 2>/dev/null | grep -q "ok installed"; then
+        if ! dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed"; then
             missing_packages+=("$pkg")
         fi
     done
 
+# Check availability of missing packages and categorize them
     for pkg in "${missing_packages[@]}"
     do
         if apt-cache show "$pkg" > /dev/null 2>&1; then
@@ -103,21 +122,27 @@ pkgs_fn() {
         fi
     done
 
-        echo "Unavailable packages: $unavailable_packages[*]"
+# Print unavailable packages
+    if [[ "${#Unavailable_packages[@]}" -gt 0 ]]; then
+        echo "Unavailable packages: ${unavailable_packages[*]}"
     fi
 
-        echo "Installing available missing packages: $available_packages[*]"
+# Install available missing packages
+    if [[ "${#Available_packages[@]}" -gt 0 ]]; then
+        echo "Installing available missing packages: ${available_packages[*]}"
         sudo apt install "${available_packages[@]}"
     else
         printf "%s\n\n" "No missing packages to install or all missing packages are unavailable."
     fi
 }
 
+# Install required apt packages
 pkgs_fn
 
-if [ ! -f "$pem_out" ]; then
+# Install ca certs from curl's official website
+if [ ! -f "${pem_out}" ]; then
     curl -Lso "$pem_file" "https://curl.se/ca/$pem_file"
-    sudo cp -f "$pem_file" "$pem_out"
+    sudo cp -f "$pem_file" "${pem_out}"
 fi
 
 if type -P update-ca-certificates &>/dev/null; then
@@ -134,26 +159,31 @@ eopts+=('--enable-'{openssl-auto-load-config,optimize,pop3,progress-meter})
 eopts+=('--enable-'{proxy,pthreads,rtsp,smb,smtp,socketpair,sspi,static,telnet})
 eopts+=('--enable-'{tftp,threaded-resolver,tls-srp,unix-sockets,websockets})
 wopts=('--with-'{libssh2,nghttp2='/usr/include',nghttp3='/usr/include',openssl='/usr',ssl,zlib})
-wopts+=('--with-'{ca-bundle="$pem_out",ca-fallback,ca-path="$certs_dir",secure-transport})
+wopts+=('--with-'{ca-bundle="${pem_out}",ca-fallback,ca-path="$certs_dir",secure-transport})
 
+# Generate configuration scripts
 autoreconf -fi
 
+# Create a build directory if it doesn't exist
 mkdir -p build
 cd build || fail_fn "Failed to enter the build directory."
 
+# Run the configure script
 ../configure --prefix="$install_dir" \
             "${dopts[@]}"        \
             "${eopts[@]}"        \
             "${wopts[@]}"        \
-            CPPFLAGS="$CPPFLAGS" || fail_fn "Configuration failed."
+            CPPFLAGS="${CPPFLAGS}" || fail_fn "Configuration failed."
+# Compile using all available cores
 echo "Compiling..."
 if ! make "-j$(nproc --all)"; then
-    fail_fn "Failed to execute: make -j$(nproc --all). Line: $LINENO"
+    fail_fn "Failed to execute: make -j$(nproc --all). Line: ${LINENO}"
 fi
 
+# Install
 echo "Installing..."
 if ! sudo make install; then
-    fail_fn "Failed to execute: sudo make install. Line: $LINENO"
+    fail_fn "Failed to execute: sudo make install. Line: ${LINENO}"
 fi
 
 curl_version="$($install_dir/bin/curl --version | head -n 1 | awk '{print $2}')"
diff --git a/Bash/Installer Scripts/GitHub Projects/build-curl-git b/Bash/Installer Scripts/GitHub Projects/build-curl-git
--- a/Bash/Installer Scripts/GitHub Projects/build-curl-git
+++ b/Bash/Installer Scripts/GitHub Projects/build-curl-git
@@ -1,11 +1,16 @@
-#!/Usr/bin/env bash
+#!/usr/bin/env bash
 
+##  Github Script: https://github.com/slyfox1186/script-repo/edit/main/util-linux/Installer%20Scripts/GNU%20Software/build-curl-git
+##  Purpose: Build cURL with OpenSSL backend
+##  Updated: 03.09.24
+##  Script version: 1.1
 
 if [ "$EUID" -ne 0 ]; then
     echo "You must run this script with root or sudo."
     exit 1
 fi
 
+# Set the variables
 script_ver=1.1
 archive_dir=curl-git
 git_url=https://github.com/curl/curl.git
@@ -116,11 +121,12 @@ install_required_packages() {
     local missing_packages=()
 
     for pkg in "${pkgs[@]}"; do
-        if ! dpkg-query -W -f='$Status' "$pkg" | grep -q "ok installed"; then
+        if ! dpkg-query -W -f='${Status}' "$pkg" | grep -q "ok installed"; then
             missing_packages+=("$pkg")
         fi
     done
 
+    if [ "${#Missing_packages[@]}" -gt 0 ]; then
         apt update
         apt install "${missing_packages[@]}"
     else
@@ -129,6 +135,7 @@ install_required_packages() {
 }
 install_required_packages
 
+# Install certs from curl's official website
 if [ ! -f "$pem_out" ]; then
     printf "%s\n%s\n\n" \
         'Download the latest security certificate' \
@@ -137,12 +144,15 @@ if [ ! -f "$pem_out" ]; then
     cp -f "$cwd/$pem_file" "$pem_out"
 fi
 
+# Create output directory curl
 if [ -d "$cwd/$archive_dir" ]; then
     rm -fr "$cwd/$archive_dir"
 fi
 
+# Download the archive file curl
 git clone "$git_url" "$cwd/$archive_dir"
 
+# Update the system security certificates before installing curl
 if type -P 'update-ca-certificates' &>/dev/null; then
     update-ca-certificates
 fi
@@ -177,10 +187,13 @@ if ! make install; then
     fail_fn "Failed to execute: make install. Line: $LINENO"
 fi
 
+# Prompt user to clean up files
 cleanup_fn
 
+# Show new version
 curl_ver="$(/usr/local/bin/curl --version | grep -Eo '^curl [0-9\.]+' | grep -Eo '[0-9\.]+')"
 
 printf "\n%s\n" "The updated cURL version is: $curl_ver"
 
+# Show exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GitHub Projects/build-garbage-collector b/Bash/Installer Scripts/GitHub Projects/build-garbage-collector
--- a/Bash/Installer Scripts/GitHub Projects/build-garbage-collector
+++ b/Bash/Installer Scripts/GitHub Projects/build-garbage-collector
@@ -1,44 +1,60 @@
 #!/usr/bin/env bash
 
+###########################################################################################################
+##
+##  Github Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-garbage-collector
+##
+##  Purpose: Build Boehm-Demers-Weiser Conservative Garbage Collector
+##
+##  Updated: 08.16.23
+##
+##  Script version: 1.0
+##
+###########################################################################################################
 
 clear
 
-if [ "$EUID" -eq '0' ]; then
+if [ "${EUID}" -eq '0' ]; then
     echo "You must run this script without root or sudo."
     exit 1
 fi
 
+# Set variables
 
 script_ver=1.0
 archive_dir=gc-8.2.4
 archive_url=https://github.com/ivmai/bdwgc/releases/download/v8.2.4/gc-8.2.4.tar.gz
 archive_ext="${archive_url//*.}"
-archive_name="$archive_dir.tar.$archive_ext"
+archive_name="$archive_dir.tar.${archive_ext}"
 cwd="$PWD"/garbage-collector-build-script
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
 
 printf "\n%s\n%s\n\n" \
-    "garbage collector build script - v$script_ver" \
+    "garbage collector build script - v${script_ver}" \
     '==============================================='
 
+# Create output directory
 
 if [ ! -d "$cwd" ]; then
     mkdir -p "$cwd"
 fi
 
+# Set the c+cpp compilers
 
 export CC=gcc CXX=g++
 
+# Set compiler optimization flags
 
 export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -fno-plt -march=native'
 
+# Set the path variable
 
 PATH="\
 /usr/lib/ccache:\
-$HOME/perl5/bin:\
-$HOME/.cargo/bin:\
-$HOME/.local/bin:\
+${HOME}/perl5/bin:\
+${HOME}/.cargo/bin:\
+${HOME}/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -53,6 +69,7 @@ $HOME/.local/bin:\
 "
 export PATH
 
+# Set the pkg_config_path variable
 
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
@@ -69,22 +86,26 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
+# Create functions
 
-exit_fn() {
+exit_fn()
+{
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
         "$web_repo"
     exit 0
 }
 
-fail_fn() {
+fail_fn()
+{
     printf "\n%s\n\n%s\n\n" \
         "$1" \
         "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
-cleanup_fn() {
+cleanup_fn()
+{
     local choice
 
     printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
@@ -95,7 +116,7 @@ cleanup_fn() {
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "$choice" in
+    case "${choice}" in
         1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
@@ -109,18 +130,20 @@ cleanup_fn() {
     esac
 }
 
+# Install required apt packages
 
-pkgs_fn() {
+pkgs_fn()
+{
     pkgs=(autoconf autoconf-archive autogen automake binutils bison build-essential bzip2 ccache curl
           libc6-dev libintl-perl libpth-dev libticonv-dev libtool libtool-bin lzip lzma-dev m4 nasm texinfo
           zlib1g-dev yasm)
 
     for i in ${pkgs[@]}
     do
-        missing_pkg="$(sudo dpkg -l | grep -o "$i")"
+        missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
 
-        if [ -z "$missing_pkg" ]; then
-            missing_pkgs+=" $i"
+        if [ -z "${missing_pkg}" ]; then
+            missing_pkgs+=" ${i}"
         fi
     done
 
@@ -131,23 +154,27 @@ pkgs_fn() {
     fi
 }
 
+# Download the archive file
 
-if [ ! -f "$cwd/$archive_name" ]; then
-    curl -A "$user_agent" -Lso "$cwd/$archive_name" "$archive_url"
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
+# Create output directory
 
 if [ -d "$cwd/$archive_dir" ]; then
     sudo rm -fr "$cwd/$archive_dir"
 fi
 mkdir -p "$cwd/$archive_dir/build"
 
+# Extract archive files
 
-if ! tar -zxf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: $cwd/$archive_name"
+if ! tar -zxf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
+# Build program from source
 
 cd "$cwd/$archive_dir" || exit 1
 autoreconf -fi
@@ -168,10 +195,12 @@ cd build || exit 1
              --with-pic
 make "-j$(nproc --all)"
 if ! sudo make install; then
-    fail_fn "Failed to execute: sudo make install:Line $LINENO"
+    fail_fn "Failed to execute: sudo make install:Line ${LINENO}"
     exit 1
 fi
 
+# Prompt user to clean up files
 cleanup_fn
 
+# Show exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GitHub Projects/build-libgcrypt b/Bash/Installer Scripts/GitHub Projects/build-libgcrypt
--- a/Bash/Installer Scripts/GitHub Projects/build-libgcrypt
+++ b/Bash/Installer Scripts/GitHub Projects/build-libgcrypt
@@ -1,13 +1,28 @@
-#!/Usr/bin/env bash
+#!/usr/bin/env bash
+# Shellcheck disable=sc2016,sc2034,sc2046,sc2066,sc2068,sc2086,sc2162,sc2317
 
+########################################################################
+##
+##  Install libgcrypt LTS + libgcrypt-error
+##
+##  Supported OS:
+##  - debian
+##  - ubuntu
+##
+##  Updated: 10.14.23
+##
+##  Script version: 1.0
+##
+########################################################################
 
 clear
 
-if [ "$EUID" -eq '0' ]; then
+if [ "${EUID}" -eq '0' ]; then
     echo "You must run this script without root or sudo."
     exit 1
 fi
 
+# Set the variables
 
 script_ver=1.0
 install_prefix=/usr/local
@@ -19,9 +34,11 @@ user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Geck
 web_repo=https://github.com/slyfox1186/script-repo
 debug=OFF
 
+# Create output directories
 
 mkdir -p "$packages" "$workspace"
 
+# Get cpu core count for parallel processing
 
 if [ -f /proc/cpuinfo ]; then
     cpu_threads="$(grep --count ^processor /proc/cpuinfo)"
@@ -29,9 +46,11 @@ else
     cpu_threads="$(nproc --all)"
 fi
 
+# Set the c & c++ compilers
 
 export CC=gcc CXX=g++
 
+# Set compiler optimization flags
 
 export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -fno-plt -march=native'
 CPPFLAGS="-I$workspace/include -I/usr/local/include -I/usr/include"
@@ -39,18 +58,20 @@ LDFLAGS="-L$workspace/lib64 -L$workspace/lib -L$workspace/lib/x86_64-linux-gnu -
 LDFLAGS+=' -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib64 -L/usr/lib -L/lib64 -L/lib'
 export CPPFLAGS LDFLAGS
 
+# Print banner
 
 printf "%s\n%s\n%s\n" \
-    "libgcrypt build script - v$script_ver" \
+    "libgcrypt build script - v${script_ver}" \
     '=========================================' \
-    "This script will utilize ($cpu_threads) CPU threads for parallel processing to accelerate the build process."
+    "This script will utilize (${cpu_threads}) CPU threads for parallel processing to accelerate the build process."
 
+# Create global variables
 
 PATH="\
 /usr/lib/ccache:\
-$HOME/perl5/bin:\
-$HOME/.cargo/bin:\
-$HOME/.local/bin:\
+${HOME}/perl5/bin:\
+${HOME}/.cargo/bin:\
+${HOME}/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -87,8 +108,10 @@ $workspace/share/pkgconfig:\
 "
 export PKG_CONFIG_PATH
 
+# Define functions
 
-fail_fn() {
+fail_fn()
+{
     printf "\n%s\n%s\n%s\n\n" \
         "$1" \
         'You can enable the script'\''s debugging feature by changing the variable "debug" to "ON"' \
@@ -96,14 +119,16 @@ fail_fn() {
     exit 1
 }
 
-exit_fn() {
+exit_fn()
+{
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
         "$web_repo"
     exit 0
 }
 
-cleanup_fn() {
+cleanup_fn()
+{
     local choice
  
     printf "\n%s\n\n%s\n%s\n\n" \
@@ -113,7 +138,7 @@ cleanup_fn() {
     read -p 'Your choices are (1 or 2): ' choice
     clear
 
-    case "$choice" in
+    case "${choice}" in
         1)      sudo rm -fr "$cwd";;
         2)      clear;;
         *)
@@ -123,21 +148,31 @@ cleanup_fn() {
     esac
 }
 
+# Scrape github website for the latest repo version
 
-git_1_fn() {
+git_1_fn()
+{
     local curl_cmd github_repo github_url
 
     github_repo="$1"
     github_url="$2"
 
-    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/$github_repo/$github_url")"; then
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
         g_ver="$(echo "$curl_cmd" | jq -r '.[0].name' 2>/dev/null)"
         g_url="$(echo "$curl_cmd" | jq -r '.[0].tarball_url' 2>/dev/null)"
+        g_ver="${g_ver#Cares-}"
+        g_ver="${g_ver#Aria2 }"
+        g_ver="${g_ver#Nghttp2 v}"
+        g_ver="${g_ver#Nghttp3 v}"
+        g_ver="${g_ver#OpenSSL }"
+        g_ver="${g_ver#Release-}"
+        g_ver="${g_ver#V}"
     fi
 
 }
 
-git_ver_fn() {
+git_ver_fn()
+{
     local v_flag v_url v_tag url_tag t_url
 
     v_url="$1"
@@ -145,55 +180,58 @@ git_ver_fn() {
 
     if [ -n "$3" ]; then
         v_flag="$3"
-        case "$v_flag" in
+        case "${v_flag}" in
             T)      t_url=tags;;
             R)      t_url=releases;;
             *)      fail_fn 'Failed to pass "tags" and "releases" to the command: curl_cmd.';;
         esac
     fi
 
-    git_1_fn "$v_url" "$t_url" 2>/dev/null
+    git_1_fn "${v_url}" "${t_url}" 2>/dev/null
 }
 
-execute() {
-    echo "$ $*"
+execute()
+{
+    echo "$ ${*}"
 
-    if [ "$debug" = 'ON' ]; then
+    if [ "${debug}" = 'ON' ]; then
         if ! output=$("$@"); then
-            notify-send -t 5000 "Failed to execute: $*" 2>/dev/null
-            fail_fn "Failed to execute: $*"
+            notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
+            fail_fn "Failed to execute: ${*}"
         fi
     else
         if ! output=$("$@" 2>&1); then
-            notify-send -t 5000 "Failed to execute: $*" 2>/dev/null
-            fail_fn "Failed to execute: $*"
+            notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
+            fail_fn "Failed to execute: ${*}"
         fi
     fi
 }
 
-download() {
+download()
+{
     dl_path="$packages"
     dl_url="$1"
+    dl_file="${2:-"${1##*/}"}"
 
     if [[ "$dl_file" =~ tar. ]]; then
-        output_dir="$dl_file%.*"
-        output_dir="$3:-"${output_dir%.*"}"
+        output_dir="${dl_file%.*}"
+        output_dir="${3:-"${output_dir%.*}"}"
     else
-        output_dir="$3:-"${dl_file%.*"}"
+        output_dir="${3:-"${dl_file%.*}"}"
     fi
 
     target_file="$dl_path/$dl_file"
     target_dir="$dl_path/$output_dir"
 
-    if [ -f "$target_file" ]; then
+    if [ -f "${target_file}" ]; then
         echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"$dl_url\" saving as \"$dl_file\""
-        if ! wget -U "$user_agent" -cqO "$target_file" "$dl_url"; then
+        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
+        if ! wget -U "$user_agent" -cqO "${target_file}" "${dl_url}"; then
             printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! wget -U "$user_agent" -cqO "$target_file" "$dl_url"; then
-                fail_fn "The script failed to download \"$dl_file\" twice and will now exit. Line: $LINENO"
+            if ! wget -U "$user_agent" -cqO "${target_file}" "${dl_url}"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit. Line: ${LINENO}"
             fi
         fi
         echo 'Download Completed'
@@ -205,23 +243,24 @@ download() {
     mkdir -p "$target_dir"
 
     if [ -n "$3" ]; then
-        if ! tar -xf "$target_file" -C "$target_dir" 2>/dev/null >/dev/null; then
-            sudo rm "$target_file"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: $LINENO"
+        if ! tar -xf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
+            sudo rm "${target_file}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
         fi
     else
-        if ! tar -xf "$target_file" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
-            sudo rm "$target_file"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: $LINENO"
+        if ! tar -xf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
+            sudo rm "${target_file}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
         fi
     fi
 
     printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: $LINENO"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: ${LINENO}"
 }
 
-build() {
+build()
+{
     printf "\n%s\n%s\n" \
         "building $1 - version $2" \
         '===================================='
@@ -239,22 +278,25 @@ build() {
     return 0
 }
 
-build_done() {
+build_done()
+{
     echo "$2" > "$packages/$1.done"
 }
 
-installed() {
-    return $(dpkg-query -W -f '$Status\n' "$1" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}')
+installed()
+{
+    return $(dpkg-query -W -f '${Status}\n' "$1" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}')
 }
 
+# Install required apt packages
 
 pkgs=(autoconf autoconf-archive autogen automake autotools-dev
       build-essential ccache curl libtool libtool-bin m4 pkg-config)
 
 for pkg in ${pkgs[@]}
 do
-    if ! installed "$pkg"; then
-        missing_pkgs+=" $pkg"
+    if ! installed "${pkg}"; then
+        missing_pkgs+=" ${pkg}"
     fi
 done
 
@@ -270,12 +312,13 @@ else
     printf "%s\n" 'The required APT packages are already installed.'
 fi
 
+# Build libraries from source
 
 if build 'libgpg-error' '1.47'; then
     download 'https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.47.tar.bz2' 'libgpg-error-1.47.tar.bz2'
     execute ./autogen.sh
     execute ./configure --prefix="$install_prefix" \
-                        --{build,host}="$pc_type"  \
+                        --{build,host}="${pc_type}"  \
                         --disable-doc                \
                         --disable-nls                \
                         --disable-tests              \
@@ -286,7 +329,7 @@ if build 'libgpg-error' '1.47'; then
                         --with-libiconv-prefix=/usr  \
                         --with-libintl-prefix=/usr   \
                         --with-pic
-    execute make "-j$cpu_threads"
+    execute make "-j${cpu_threads}"
     execute sudo make install
     execute sudo cp -f 'src/gpg-error-config' "$install_prefix"/bin
     build_done 'libgpg-error' '1.47'
@@ -296,17 +339,20 @@ if build 'libgcrypt' '1.8.10-LTS'; then
     download 'https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.10.tar.bz2' 'libgcrypt-1.8.10-LTS.tar.bz2'
     execute ./autogen.sh
     ./configure --prefix="$install_prefix"                   \
-                --{build,host}="$pc_type"                    \
+                --{build,host}="${pc_type}"                    \
                 --enable-static                                \
                 --with-libgpg-error-prefix="$install_prefix" \
                 --with-pic
-    execute make "-j$cpu_threads"
+    execute make "-j${cpu_threads}"
     execute sudo make install
     build_done 'libgcrypt' '1.8.10-LTS'
 fi
 
+# Ldconfig must be run next in order to update file changes or the version commands might not work
 sudo ldconfig 2>/dev/null
 
+# Cleanup leftover files
 cleanup_fn
 
+# Display exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GitHub Projects/build-terminator-terminal b/Bash/Installer Scripts/GitHub Projects/build-terminator-terminal
--- a/Bash/Installer Scripts/GitHub Projects/build-terminator-terminal
+++ b/Bash/Installer Scripts/GitHub Projects/build-terminator-terminal
@@ -1,11 +1,17 @@
 #!/usr/bin/env bash
+# Shellcheck disable=sc2162,sc2317
 
+##  Install: Terminator Terminal
+##  Github: https://github.com/slyfox1186/script-repo/edit/main/shell/installers/build-terminator-terminal
+##  Updated: 08.09.23
+##  Script version: 1.0
 
 if [ "$EUID" -eq 0 ]; then
     echo "You must run this script without root or sudo."
     exit 1
 fi
 
+# Create script variables
 script_ver=1.0
 cwd="$PWD/terminator-build-script"
 install_dir=/usr/local
@@ -15,20 +21,24 @@ archive_ext="${archive_url//*.}"
 archive_name="$archive_dir.tar.$archive_ext"
 
 printf "\n%s\n%s\n\n" \
-    "Terminator Build Script - v$script_ver" \
+    "Terminator Build Script - v${script_ver}" \
     '==============================================='
 
+# Create output directory
 mkdir -p "$cwd"
 
+# Set the c+cpp compilers
 export CC=gcc CXX=g++
 
+# Export compiler optimization flags
 export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -fno-plt -march=native'
 
+# Set the path variable
 PATH="\
 /usr/lib/ccache:\
-$HOME/perl5/bin:\
-$HOME/.cargo/bin:\
-$HOME/.local/bin:\
+${HOME}/perl5/bin:\
+${HOME}/.cargo/bin:\
+${HOME}/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -43,6 +53,7 @@ $HOME/.local/bin:\
 "
 export PATH
 
+# Set the pkg_config_path variable
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
 /usr/local/lib/pkgconfig:\
@@ -58,6 +69,7 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
+# Create functions
 exit_fn() {
     printf "\n%s\n\n%s\n%s\n\n" \
         'The script has completed' \
@@ -85,7 +97,7 @@ cleanup_fn() {
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "$choice" in
+    case "${choice}" in
         1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
@@ -99,6 +111,7 @@ cleanup_fn() {
     esac
 }
 
+# Install required apt packages
 pkgs=(autoconf autogen automake build-essential ca-certificates ccache clang curl libaria2-0 libaria2-0-dev
       libc-ares-dev libdmalloc-dev libgcrypt20-dev libgmp-dev libgnutls28-dev libgpg-error-dev libjemalloc-dev
       libmbedtls-dev libnghttp2-dev librust-openssl-dev libsqlite3-dev libssh2-1-dev libssh-dev libssl-dev
@@ -107,10 +120,10 @@ pkgs=(autoconf autogen automake build-essential ca-certificates ccache clang cur
 
 for i in ${pkgs[@]}
 do
-    missing_pkg="$(sudo dpkg -l | grep -o "$i")"
+    missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
 
-    if [ -z "$missing_pkg" ]; then
-        missing_pkgs+=" $i"
+    if [ -z "${missing_pkg}" ]; then
+        missing_pkgs+=" ${i}"
     fi
 done
 unset i
@@ -121,39 +134,45 @@ if [ -n "$missing_pkgs" ]; then
     clear
 fi
 
-if [ ! -f "$cwd/$archive_name" ]; then
-    curl -Lso "$cwd/$archive_name" "$archive_url"
+# Download the archive file
+if [ ! -f "$cwd/${archive_name}" ]; then
+    curl -Lso "$cwd/${archive_name}" "${archive_url}"
 fi
 
+# Create output directory
 if [ -d "$cwd/$archive_dir" ]; then
     sudo rm -fr "$cwd/$archive_dir"
 fi
 mkdir -p "$cwd/$archive_dir"
 
-if ! tar -xf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: $cwd/$archive_name"
+# Extract archive files
+if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: $cwd/${archive_name}"
     exit 1
 fi
 
+# Build program from source
 cd "$cwd/$archive_dir" || exit 1
 python3 setup.py build
-if ! sudo python3 setup.py install --prefix="$install_dir" \
-                                   --install-lib=/usr/local/lib \
-                                   --home="$HOME" \
-                                   --single-version-externally-managed \
-                                   --record=install-files.txt \
-                                   --install-headers \
-                                   --install-scripts \
-                                   --install-data \
-                                   --compile -optimize -O2 \
-                                   --force \
+if ! sudo python3 setup.py install --prefix="$install_dir"                        \
+                                   --install-lib=/usr/local/lib                     \
+                                   --home="${HOME}"                                 \
+                                   --single-version-externally-managed              \
+                                   --record=install-files.txt                       \
+                                   --install-headers                                \
+                                   --install-scripts                                \
+                                   --install-data                                   \
+                                   --compile -optimize -O2                          \
+                                   --force                                          \
                                    --record "$cwd"/terminator-installed-files.txt \
-                                   --user \
+                                   --user                                           \
                                    --install-layout=unix; then
-    fail_fn "Failed to execute: sudo python3 setup.py install:Line $LINENO"
+    fail_fn "Failed to execute: sudo python3 setup.py install:Line ${LINENO}"
     exit 1
 fi
 
+# Cleanup files
 cleanup_fn
 
+# Show exit message
 exit_fn
diff --git a/Bash/Installer Scripts/GitHub Projects/build-yasm b/Bash/Installer Scripts/GitHub Projects/build-yasm
--- a/Bash/Installer Scripts/GitHub Projects/build-yasm
+++ b/Bash/Installer Scripts/GitHub Projects/build-yasm
@@ -1,8 +1,8 @@
 PATH="\
 /usr/lib/ccache:\
-$HOME/perl5/bin:\
-$HOME/.cargo/bin:\
-$HOME/.local/bin:\
+${HOME}/perl5/bin:\
+${HOME}/.cargo/bin:\
+${HOME}/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -15,15 +15,29 @@ $HOME/.local/bin:\
 /usr/games:\
 /snap/bin\
 "
+export PATH#!/usr/bin/env bash
+# Shellcheck disable=sc2162,sc2317
 
+###############################################################################################################################
+##
+##  Github Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-yasm
+##
+##  Purpose: Build yasm
+##
+##  Updated: 08.31.23
+##
+##  Script version: 1.1
+##
+###############################################################################################################################
 
 clear
 
-if [ "$EUID" -eq '0' ]; then
+if [ "${EUID}" -eq '0' ]; then
     echo "You must run this script without root or sudo."
     exit 1
 fi
 
+# Set variables
 
 script_ver=1.1
 install_dir=/usr/local
@@ -31,28 +45,33 @@ cwd="$PWD"/yasm-build-script
 packages="$cwd"/packages
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
 web_repo=https://github.com/slyfox1186/script-repo
+debug=OFF # Change THE DEBUG VARIABLE TO "ON" FOR HELP TROUBLESHOOTING ISSUES
 
 printf "\n%s\n%s\n\n" \
-    "yasm build script - v$script_ver" \
+    "yasm build script - v${script_ver}" \
     '==============================================='
 
+# Create output directory
 
 if [ ! -d "$cwd" ]; then
     mkdir -p "$packages"
 fi
 
+# Set the c+cpp compilers
 
 export CC=gcc CXX=g++
 
+# Set compiler optimization flags
 
 export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -fno-plt -march=native'
 
+# Set the path variable
 
 PATH="\
 /usr/lib/ccache:\
-$HOME/perl5/bin:\
-$HOME/.cargo/bin:\
-$HOME/.local/bin:\
+${HOME}/perl5/bin:\
+${HOME}/.cargo/bin:\
+${HOME}/.local/bin:\
 /usr/local/sbin:\
 /usr/local/cuda/bin:\
 /usr/local/x86_64-linux-gnu/bin:\
@@ -67,6 +86,7 @@ $HOME/.local/bin:\
 "
 export PATH
 
+# Set the pkg_config_path variable
 
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
@@ -83,22 +103,26 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
+# Create functions
 
-exit_fn() {
+exit_fn()
+{
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
         "$web_repo"
     exit 0
 }
 
-fail_fn() {
+fail_fn()
+{
     printf "\n%s\n\n%s\n\n" \
         "$1" \
         "To report a bug create an issue at: $web_repo/issues"
     exit 1
 }
 
-cleanup_fn() {
+cleanup_fn()
+{
     local choice
 
     printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
@@ -109,7 +133,7 @@ cleanup_fn() {
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "$choice" in
+    case "${choice}" in
         1)      sudo rm -fr "$cwd";;
         2)      echo;;
         *)
@@ -123,7 +147,8 @@ cleanup_fn() {
     esac
 }
 
-build() {
+build()
+{
     printf "\n%s\n%s\n" \
         "building $1 - version $2" \
         '===================================='
@@ -140,44 +165,47 @@ build() {
     return 0
 }
 
-execute() {
-    echo "$ $*"
+execute()
+{
+    echo "$ ${*}"
 
-    if [ "$debug" = 'ON' ]; then
+    if [ "${debug}" = 'ON' ]; then
         if ! output=$("$@"); then
-            notify-send 5000 "Failed to execute: $*"
-            fail_fn "Failed to execute: $*"
+            notify-send 5000 "Failed to execute: ${*}"
+            fail_fn "Failed to execute: ${*}"
         fi
     else
         if ! output=$("$@" 2>&1); then
-            notify-send 5000 "Failed to execute: $*"
-            fail_fn "Failed to execute: $*"
+            notify-send 5000 "Failed to execute: ${*}"
+            fail_fn "Failed to execute: ${*}"
         fi
     fi
 }
 
-download() {
+download()
+{
     dl_path="$packages"
     dl_url="$1"
+    dl_file="${2:-"${1##*/}"}"
 
     if [[ "$dl_file" =~ tar. ]]; then
-        output_dir="$dl_file%.*"
-        output_dir="$3:-"${output_dir%.*"}"
+        output_dir="${dl_file%.*}"
+        output_dir="${3:-"${output_dir%.*}"}"
     else
-        output_dir="$3:-"${dl_file%.*"}"
+        output_dir="${3:-"${dl_file%.*}"}"
     fi
 
     target_file="$dl_path/$dl_file"
     target_dir="$dl_path/$output_dir"
 
-    if [ -f "$target_file" ]; then
+    if [ -f "${target_file}" ]; then
         echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"$dl_url\" saving as \"$dl_file\""
-        if ! curl -A "$user_agent" -Lso "$target_file" "$dl_url"; then
+        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
+        if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
             printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! curl -A "$user_agent" -Lso "$target_file" "$dl_url"; then
+            if ! curl -A "$user_agent" -Lso "${target_file}" "${dl_url}"; then
                 fail_fn "The script failed to download \"$dl_file\" twice and will now exit."
             fi
         fi
@@ -191,13 +219,13 @@ download() {
     mkdir -p "$target_dir"
 
     if [ -n "$3" ]; then
-        if ! tar -xf "$target_file" -C "$target_dir" 2>/dev/null >/dev/null; then
-            sudo rm "$target_file"
+        if ! tar -xf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
+            sudo rm "${target_file}"
             fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script."
         fi
     else
-        if ! tar -xf "$target_file" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
-            sudo rm "$target_file"
+        if ! tar -xf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
+            sudo rm "${target_file}"
             fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script."
         fi
     fi
@@ -207,44 +235,50 @@ download() {
     cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir"
 }
 
-git_1_fn() {
+git_1_fn()
+{
     local curl_cmd github_repo github_url
 
+# Scrape github website for the latest repo version
     github_repo="$1"
     github_url="$2"
 
-    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/$github_repo/$github_url")"; then
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
         g_ver="$(echo "$curl_cmd" | jq -r '.[0].name' 2>/dev/null)"
+        g_ver="${g_ver#V}"
     fi
 }
 
-git_ver_fn() {
+git_ver_fn()
+{
     local t_flag v_flag v_url
 
     v_url="$1"
     v_flag="$2"
 
-    case "$v_flag" in
+    case "${v_flag}" in
             B)      t_flag=branches;;
             R)      t_flag=releases;;
             T)      t_flag=tags;;
     esac
 
-    git_1_fn "$v_url" "$t_flag" 2>/dev/null
+    git_1_fn "${v_url}" "${t_flag}" 2>/dev/null
 }
 
+# Install required apt packages
 
-pkgs_fn() {
+pkgs_fn()
+{
     pkgs=(autogen automake binutils bison build-essential bzip2 ccache cmake
           curl libc6-dev libintl-perl libpth-dev yasm yasm-bin lzip lzma-dev
           nasm ninja-build texinfo yasm yasm1g-dev)
 
     for i in ${pkgs[@]}
     do
-        missing_pkg="$(sudo dpkg -l | grep -o "$i")"
+        missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
     
-        if [ -z "$missing_pkg" ]; then
-            missing_pkgs+=" $i"
+        if [ -z "${missing_pkg}" ]; then
+            missing_pkgs+=" ${i}"
         fi
     done
     
@@ -257,6 +291,7 @@ pkgs_fn() {
 
 build_done() { echo "$2" > "$packages/$1.done"; }
 
+# Build program from source
 
 if build 'yasm' '1.3.0'; then
     download 'https://github.com/yasm/yasm/archive/refs/tags/v1.3.0.tar.gz' 'yasm-1.3.0.tar.gz'
@@ -270,6 +305,8 @@ if build 'yasm' '1.3.0'; then
     build_done 'yasm' '1.3.0'
 fi
 
+# Prompt user to clean up files
 cleanup_fn
 
+# Show exit message
 exit_fn
