Update build-tools

diff --git a/Bash/Installer Scripts/GitHub Projects/build-tools b/Bash/Installer Scripts/GitHub Projects/build-tools
--- a/Bash/Installer Scripts/GitHub Projects/build-tools
+++ b/Bash/Installer Scripts/GitHub Projects/build-tools
@@ -1,30 +1,42 @@
-#!/Usr/bin/env bash
+#!/usr/bin/env bash
+# shellcheck disable=SC2162,SC2317
 
+##  GitHub: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-tools
+##  Purpose: Install the latest versions of: CMake, Ninja, Meson, & Golang
+##  Updated: 02.16.24
+##  Added: Automatic version check for Golang.
 
 if [ "$EUID" -eq 0 ]; then
-    printf "%s\n\n" "You must run this script without root or sudo.
+    printf "%s\n\n" "You must run this script WITHOUT root/sudo"
     exit 1
 fi
 
+# Create script variables
 script_ver=2.8
 cwd="$PWD/build-tools-script"
 install_dir="/usr/local"
 web_repo="https://github.com/slyfox1186/script-repo"
 latest=false
+debug=OFF # Change the debug variable to "ON" for help troubleshooting issues
 
+# Print script banner
 printf "%s\n%s\n" "Build-tools script: v$script_ver" "===================================="
 sleep 2
 
+# Get CPU core count for parallel processing
 cpu_threads=$(grep -c ^processor '/proc/cpuinfo' 2>/dev/null || nproc --all)
 
+# CREATE OUTPUT DIRECTORIES
 mkdir -p "$cwd"
 
+# Set the CC/CXX compilers & the compiler optimization flags
 CC=gcc
 CXX=g++
-CFLAGS="-g -O3 -pipe -fno-plt -march=native"
+CFLAGS="-g -O3 -pipe -march=native"
 CXXFLAGS="$CFLAGS"
 export CC CXX CFLAGS CXXFLAGS
 
+# Set the PATH variable
 PATH="\
 /usr/lib/ccache:\
 $HOME/perl5/bin:\
@@ -41,6 +53,7 @@ $HOME/.local/bin:\
 "
 export PATH
 
+# Set the PKG_CONFIG_PATH variable
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
 /usr/local/lib/pkgconfig:\
@@ -51,6 +64,7 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
+# Create functions
 exit_fn() {
     printf "\n%s\n\n%s\n%s\n\n" "The script has completed" "Make sure to star this repository to show your support!" "$web_repo"
     exit 0
@@ -119,12 +133,13 @@ execute() {
 download() {
     dl_path="$cwd"
     dl_url="$1"
+    dl_file="${2:-"${1##*/}"}"
 
     if [[ "$dl_file" =~ tar. ]]; then
-        output_dir="$dl_file%.*"
-        output_dir="$3:-"${output_dir%.*"}"
+        output_dir="${dl_file%.*}"
+        output_dir="${3:-"${output_dir%.*}"}"
     else
-        output_dir="$3:-"${dl_file%.*"}"
+        output_dir="${3:-"${dl_file%.*}"}"
     fi
 
     target_file="$dl_path/$dl_file"
@@ -186,6 +201,7 @@ build() {
 
 build_done() { echo "$2" > "$cwd/$1.done"; }
 
+# INSTALL REQUIRED APT/PACMAN PACKAGES
 pkgs_arch_fn() {
     pkgs_arch=(
         autoconf automake autogen bluez-qt5 base-devel ccache cmake curl
@@ -193,6 +209,7 @@ pkgs_arch_fn() {
         qt6-base
     )
 
+    # Remove any locks on pacman
     [ -f "/var/lib/pacman/db.lck" ] && sudo rm "/var/lib/pacman/db.lck"
 
     for i in ${pkgs_arch[@]}
@@ -210,6 +227,7 @@ pkgs_arch_fn() {
 
     [ -n "$(sudo find /usr/lib/python3* -type f -name 'EXTERNALLY-MANAGED')" ] && sudo rm "$rm_pip_lock"
 
+    # Install python pip packages
     pip install -q --user --no-input requests setuptools wheel
 }
 
@@ -220,17 +238,20 @@ pkgs_fn() {
         qtbase5-dev
     )
 
+    # Initialize arrays for missing, available, and unavailable packages
     missing_packages=()
     available_packages=()
     unavailable_packages=()
 
+    # Loop through the array to find missing packages
     for pkg in "${pkgs[@]}"
     do
-        if ! dpkg-query -W -f='$Status' "$pkg" 2>/dev/null | grep -q "ok installed"; then
+        if ! dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed"; then
             missing_packages+=("$pkg")
         fi
     done
 
+    # Check availability of missing packages and categorize them
     for pkg in "${missing_packages[@]}"
     do
         if apt-cache show "$pkg" > /dev/null 2>&1; then
@@ -240,45 +261,60 @@ pkgs_fn() {
         fi
     done
 
-        echo "Unavailable packages: $unavailable_packages[*]"
+    # Print unavailable packages
+    if [ "${#unavailable_packages[@]}" -gt 0 ]; then
+        echo "Unavailable packages: ${unavailable_packages[*]}"
     fi
 
-        echo "Installing available missing packages: $available_packages[*]"
+    # Install available missing packages
+    if [ "${#available_packages[@]}" -gt 0 ]; then
+        echo "Installing available missing packages: ${available_packages[*]}"
         sudo apt install "${available_packages[@]}"
     else
         echo "No missing packages to install or all missing packages are unavailable."
     fi
 }
 
+# Function to find the latest release version of GoLang
 find_latest_golang_version() {
+    # Use curl to fetch the HTML content and grep to find lines with download links
     local versions=$(curl -s https://go.dev/dl/ | grep -oP 'go[0-9]+\.[0-9]+\.[0-9]+\.linux-amd64.tar.gz' | sort -Vr | uniq | head -n 1)
 
+    # Extract and print the version number
     local latest_version=$(echo $versions | awk -F. '{print $1"."$2"."$3}' | sed 's/go//g' | sed 's/.linux-amd64.tar.gz//g')
     
     echo "$latest_version"
 }
 
+# Call the function and store its output in a variable
 latest_version=$(find_latest_golang_version)
 
 git_1_fn() {
+    # Initial cnt
     local cnt curl_cmd git_repo
     git_repo="$1"
     cnt=1
 
+    # Loop until the condition is met or a maximum limit is reached
     while [ $cnt -le 10 ]
     do
         curl_cmd="$(curl -sSL "https://github.com/$git_repo/tags")"
 
-        line=$(echo "$curl_cmd" | grep -o 'href="[^"]*\.tar\.gz"' | sed -n "$cntp")
+        # Extract the specific line
+        line=$(echo "$curl_cmd" | grep -o 'href="[^"]*\.tar\.gz"' | sed -n "${cnt}p")
 
+        # Check if the line matches the pattern (version without 'RC'/'rc')
         if echo "$line" | grep -qP '[v]*(\d+\.\d+(?:\.\d*){0,2})\.tar\.gz'; then
+            # Extract and print the version number
             g_ver=$(echo "$line" | grep -oP '(\d+\.\d+(?:\.\d+){0,2})')
             break
         else
+            # Increment the cnt if no match is found
             ((cnt++))
         fi
     done
 
+    # Check if a version was found
     if [ $cnt -gt 10 ]; then
         fail_fn "No matching version found without RC/rc suffix."
     fi
@@ -301,8 +337,10 @@ add_go_path_command_to_bashrc() {
     fi
 }
 
+# Function to extract the first word from a string
 get_first_word() { echo "$1" | awk '{print $1}'; }
 
+# Try to detect the OS using /etc/os-release, fall back to lsb_release if available
 if [ -f /etc/os-release ]; then
     . /etc/os-release
     OS=$(get_first_word "$NAME")
@@ -317,6 +355,7 @@ case "$OS" in
     *)      pkgs_fn ;;
 esac
 
+# Check if the latest release is a "rc" aka release candidate and if so go back to the previous stable release
 git_1_fn "Kitware/CMake"
 if build "cmake" "$g_ver"; then
     download "https://github.com/Kitware/CMake/archive/refs/tags/v$g_ver.tar.gz" "cmake-$g_ver.tar.gz"
@@ -348,15 +387,17 @@ else
     fi
 fi
 
+# Remove leftover files from previous runs
 if [ -d  "$install_dir/go" ]; then
     sudo rm -fr "$install_dir/go"
 fi
 
+# Install Golang
 if [[ "$OS" == "Arch" ]]; then
     sudo pacman -Sq --needed --noconfirm go
 else
     if build "golang" "$latest_version"; then
-        download "https://go.dev/dl/go$latest_version.linux-amd64.tar.gz" "golang-$latest_version.tar.gz"
+        download "https://go.dev/dl/go${latest_version}.linux-amd64.tar.gz" "golang-${latest_version}.tar.gz"
         execute sudo cp -f "bin/go" "bin/gofmt" "$install_dir/bin"
         build_done "golang" "$latest_version"
     fi
@@ -368,10 +409,14 @@ else
     source "$HOME/.bashrc"
 fi
 
+# ldconfig must be run next in order to update file changes
 sudo ldconfig 2>/dev/null
 
+# Show the newly installed version of each package
 show_versions_fn
 
+# Prompt the user to clean up the build files
 cleanup_fn
 
+# Show the exit message
 exit_fn
