Update build-aria2

diff --git a/Bash/Installer Scripts/GitHub Projects/build-aria2 b/Bash/Installer Scripts/GitHub Projects/build-aria2
--- a/Bash/Installer Scripts/GitHub Projects/build-aria2
+++ b/Bash/Installer Scripts/GitHub Projects/build-aria2
@@ -29,31 +29,51 @@ if [ "$EUID" -eq 0 ]; then
     exit 1
 fi
 
-# Install Required APT packages
-pkgs=(autoconf autoconf-archive autogen automake build-essential ca-certificates ccache
-      curl gettext libaria2-0 libaria2-0-dev libc-ares-dev libdmalloc-dev libexpat1-dev libgmp-dev
-      libintl-perl liblzma-dev libmbedtls-dev libnghttp2-dev librust-openssl-dev libsqlite3-dev
-      libssh2-1-dev libssh-dev libssl-dev libticonv-dev libtool libtool-bin libuv1-dev libxml2-dev
-      m4 pkg-config zlib1g-dev)
+pkgs_fn() {
+    local missing_pkg missing_packages pkg pkgs available_packages unavailable_packages
 
-for pkg in ${pkgs[@]}
-do
-    missing_pkg="$(sudo dpkg -l | grep -o "${pkg}")"
+    # Install Required APT packages
+    pkgs=(autoconf autoconf-archive autogen automake build-essential ca-certificates ccache
+          curl gettext libaria2-0 libaria2-0-dev libc-ares-dev libdmalloc-dev libexpat1-dev libgmp-dev
+          libintl-perl liblzma-dev libmbedtls-dev libnghttp2-dev librust-openssl-dev libsqlite3-dev
+          libssh2-1-dev libssh-dev libssl-dev libticonv-dev libtool libtool-bin libuv1-dev libxml2-dev
+          m4 pkg-config zlib1g-dev)
 
-    if [ -z "${missing_pkg}" ]; then
-        missing_pkgs+=" ${pkg}"
+    # Initialize arrays for missing, available, and unavailable packages
+    missing_packages=()
+    available_packages=()
+    unavailable_packages=()
+
+    # Loop through the array to find missing packages
+    for pkg in "${pkgs[@]}"
+    do
+        if ! dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed"; then
+            missing_packages+=("$pkg")
+        fi
+    done
+
+    # Check availability of missing packages and categorize them
+    for pkg in "${missing_packages[@]}"
+    do
+        if apt-cache show "$pkg" > /dev/null 2>&1; then
+            available_packages+=("$pkg")
+        else
+            unavailable_packages+=("$pkg")
+        fi
+    done
+
+    # Print unavailable packages
+    if [ "${#unavailable_packages[@]}" -gt 0 ]; then
+        echo "Unavailable packages: ${unavailable_packages[*]}"
     fi
-done
 
-if [ -n "${missing_pkgs}" ]; then
-    sudo apt install ${missing_pkgs}
-fi
-
-
-# Function to handle errors
-handle_error() {
-    echo "Error occurred: $1"
-    exit 1
+    # Install available missing packages
+    if [ "${#available_packages[@]}" -gt 0 ]; then
+        echo "Installing available missing packages: ${available_packages[*]}"
+        sudo apt -y install "${available_packages[@]}"
+    else
+        printf "%s\n\n" "No missing packages to install or all missing packages are unavailable."
+    fi
 }
 
 # Determine OS
