Improved variable reliability

diff --git a/Bash/Installer Scripts/GitHub Projects/build-tools b/Bash/Installer Scripts/GitHub Projects/build-tools
--- a/Bash/Installer Scripts/GitHub Projects/build-tools
+++ b/Bash/Installer Scripts/GitHub Projects/build-tools
@@ -22,8 +22,8 @@
 
 clear
 
-if [ "$EUID" -eq '0' ]; then
-    printf "\n%s\n\n" 'You must run this script WITHOUT root/sudo'
+if [ "${EUID}" -eq '0' ]; then
+    printf "%s\n\n" 'You must run this script WITHOUT root/sudo'
     exit 1
 fi
 
@@ -32,9 +32,9 @@ fi
 #
 
 script_ver=2.3
-cwd="$PWD"/build-tools-script
-packages="$cwd"/packages
-workspace="$cwd"/workspace
+cwd="${PWD}"/build-tools-script
+packages="${cwd}"/packages
+workspace="${cwd}"/workspace
 install_prefix=/usr/local
 repo=https://github.com/slyfox1186/script-repo
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
@@ -54,8 +54,8 @@ fi
 # CREATE OUTPUT DIRECTORIES
 #
 
-if [ ! -d "$packages" ] || [ ! -d "$workspace" ]; then
-    mkdir -p "$packages" "$workspace" 2>/dev/null
+if [ ! -d "${packages}" ] || [ ! -d "${workspace}" ]; then
+    mkdir -p "${packages}" "${workspace}" 2>/dev/null
 fi
 
 #
@@ -76,8 +76,8 @@ export {CFLAGS,CXXFLAGS}='-g -O2 -ffunction-sections -fdata-sections -pipe -marc
 
 PATH="\
 /usr/lib/ccache:\
-$HOME/.cargo/bin:\
-$HOME/.local/bin:\
+${HOME}/.cargo/bin:\
+${HOME}/.local/bin:\
 /usr/local/sbin:\
 /usr/local/bin:\
 /usr/sbin:\
@@ -117,16 +117,16 @@ exit_fn()
     printf "\n%s\n\n%s\n%s\n\n" \
         'The script has completed' \
         'Make sure to star this repository to show your support!' \
-        "$repo"
+        "${repo}"
     exit 0
 }
 
 fail_fn()
 {
     printf "\n\n%s\n\n%s\n\n%s\n\n" \
-        "$1" \
+        "${1}" \
         'To report a bug please create an issue at:' \
-        "$repo/issues"
+        "${repo}/issues"
     exit 1
 }
 
@@ -140,8 +140,8 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' answer
 
-    case "$answer" in
-        1)      sudo rm -fr "$cwd" "$0";;
+    case "${answer}" in
+        1)      sudo rm -fr "${cwd}" "${0}";;
         2)      return 0;;
         *)
                 printf "%s\n\n" 'Bad user input. Reverting script...'
@@ -165,93 +165,93 @@ show_versions_fn()
 
         printf "%s\n\n%s\n%s\n%s\n%s\n" \
             'The updated versions are:' \
-            "CMake:  $show_cmake_ver" \
-            "Ninja:  $show_ninja_ver" \
-            "Meson:  $show_meson_ver" \
-            "GoLang: $show_go_ver"
+            "CMake:  ${show_cmake_ver}" \
+            "Ninja:  ${show_ninja_ver}" \
+            "Meson:  ${show_meson_ver}" \
+            "GoLang: ${show_go_ver}"
 }
 
 execute()
 {
-    echo "$ $*"
+    echo "$ ${*}"
 
-    if [ "$debug" = 'ON' ]; then
-        if ! output="$("$@")"; then
-            notify-send -u critical -t 10000 "Failed to execute: $*"
-            fail_fn "Failed to execute: $*"
+    if [ "${debug}" = 'ON' ]; then
+        if ! output="$("${@}")"; then
+            notify-send -t 5000 "Failed to execute: ${*}"
+            fail_fn "Failed to execute: ${*}"
         fi
     else
-        if ! output="$("$@" 2>&1)"; then
-            notify-send -u critical -t 10000 "Failed to execute: $*"
-            fail_fn "Failed to execute: $*"
+        if ! output="$("${@}" 2>&1)"; then
+            notify-send -t 5000 "Failed to execute: ${*}"
+            fail_fn "Failed to execute: ${*}"
         fi
     fi
 }
 
 download()
 {
-    dl_path="$packages"
-    dl_url="$1"
+    dl_path="${packages}"
+    dl_url="${1}"
     dl_file="${2:-"${1##*/}"}"
 
-    if [[ "$dl_file" =~ tar. ]]; then
+    if [[ "${dl_file}" =~ tar. ]]; then
         output_dir="${dl_file%.*}"
         output_dir="${3:-"${output_dir%.*}"}"
     else
         output_dir="${3:-"${dl_file%.*}"}"
     fi
 
-    target_file="$dl_path/$dl_file"
-    target_dir="$dl_path/$output_dir"
+    target_file="${dl_path}/${dl_file}"
+    target_dir="${dl_path}/${output_dir}"
 
-    if [ -f "$target_file" ]; then
-        echo "The file \"$dl_file\" is already downloaded."
+    if [ -f "${target_file}" ]; then
+        echo "The file \"${dl_file}\" is already downloaded."
     else
-        echo "Downloading \"$dl_url\" saving as \"$dl_file\""
-        if ! curl -A "$user_agent" -Lso "$target_file" "$dl_url"; then
-            printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
+        echo "Downloading \"${dl_url}\" saving as \"${dl_file}\""
+        if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
+            printf "\n%s\n\n" "The script failed to download \"${dl_file}\" and will try again in 10 seconds..."
             sleep 10
-            if ! curl -A "$user_agent" -Lso "$target_file" "$dl_url"; then
-                fail_fn "The script failed to download \"$dl_file\" twice and will now exit."
+            if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
+                fail_fn "The script failed to download \"${dl_file}\" twice and will now exit."
             fi
         fi
         echo 'Download Completed'
     fi
 
-    if [ -d "$target_dir" ]; then
-        sudo rm -fr "$target_dir"
+    if [ -d "${target_dir}" ]; then
+        sudo rm -fr "${target_dir}"
     fi
-    mkdir -p "$target_dir"
+    mkdir -p "${target_dir}"
 
-    if [ -n "$3" ]; then
-        if ! tar -xf "$target_file" -C "$target_dir" 2>/dev/null >/dev/null; then
-            sudo rm "$target_file"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script."
+    if [ -n "${3}" ]; then
+        if ! tar -xf "${target_file}" -C "${target_dir}" 2>/dev/null >/dev/null; then
+            sudo rm "${target_file}"
+            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script."
         fi
     else
-        if ! tar -xf "$target_file" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
-            sudo rm "$target_file"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script."
+        if ! tar -xf "${target_file}" -C "${target_dir}" --strip-components 1 2>/dev/null >/dev/null; then
+            sudo rm "${target_file}"
+            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script."
         fi
     fi
 
-    printf "%s\n\n" "File extracted: $dl_file"
+    printf "%s\n\n" "File extracted: ${dl_file}"
 
-    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir"
+    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}"
 }
 
 build()
 {
     echo
-    echo "building $1 - version $2"
+    echo "building ${1} - version ${2}"
     echo '===================================='
 
-    if [ -f "$packages/$1.done" ]; then
-        if grep -Fx "$2" "$packages/$1.done" >/dev/null; then
-            echo "$1 version $2 is already built. Remove $packages/$1.done lockfile to rebuild it."
+    if [ -f "${packages}/${1}.done" ]; then
+        if grep -Fx "${2}" "${packages}/${1}.done" >/dev/null; then
+            echo "${1} version ${2} is already built. Remove ${packages}/${1}.done lockfile to rebuild it."
             return 1
         else
-            echo "$1 is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove $packages/$1.done lockfile."
+            echo "${1} is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove ${packages}/${1}.done lockfile."
             return 1
         fi
     fi
@@ -266,12 +266,12 @@ git_1_fn()
     local curl_cmd github_repo github_url g_sver g_sver1
 
     # SCRAPE GITHUB'S API FOR THE LATEST REPO VERSION
-    github_repo="$1"
-    github_url="$2"
+    github_repo="${1}"
+    github_url="${2}"
 
-    if curl_cmd="$(curl -m "$curl_timeout" -sSL "https://api.github.com/repos/$github_repo/$github_url")"; then
-        g_sver="$(echo "$curl_cmd" | jq -r '.[0].tag_name' 2>/dev/null)"
-        g_sver1="$(echo "$curl_cmd" | jq -r '.[0].name' 2>/dev/null)"
+    if curl_cmd="$(curl -m "${curl_timeout}" -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
+        g_sver="$(echo "${curl_cmd}" | jq -r '.[0].tag_name' 2>/dev/null)"
+        g_sver1="$(echo "${curl_cmd}" | jq -r '.[0].name' 2>/dev/null)"
         g_ver="${g_sver#v}"
         g_ver1="${g_sver1#v}"
     fi
@@ -279,11 +279,11 @@ git_1_fn()
 
 git_2_fn()
 {
-    gitlab_repo="$1"
-    github_url="$2"
+    gitlab_repo="${1}"
+    github_url="${2}"
 
-    if curl_cmd="$(curl -A "$user_agent" -m "$curl_timeout" -sSL "https://gitlab.kitware.com/api/v4/projects/$gitlab_repo/repository/$github_url")"; then
-        g_ver="$(echo "$curl_cmd" | jq -r '.[0].name')"
+    if curl_cmd="$(curl -A "${user_agent}" -m "${curl_timeout}" -sSL "https://gitlab.kitware.com/api/v4/projects/${gitlab_repo}/repository/${github_url}")"; then
+        g_ver="$(echo "${curl_cmd}" | jq -r '.[0].name')"
         g_ver="${g_ver#v}"
     fi
 }
@@ -292,31 +292,31 @@ git_ver_fn()
 {
     local t_flag u_flag v_flag v_tag v_url
 
-    v_url="$1"
-    v_tag="$2"
+    v_url="${1}"
+    v_tag="${2}"
 
-    if [ -n "$3" ]; then
-        v_flag="$3"
+    if [ -n "${3}" ]; then
+        v_flag="${3}"
     fi
 
-    case "$v_flag" in
+    case "${v_flag}" in
             R)      t_flag=releases;;
             T)      t_flag=tags;;
-            *)      fail_fn 'Could not detect the variable $v_flag.'
+            *)      fail_fn 'Could not detect the variable ${v_flag}.'
     esac
 
-    case "$v_tag" in
+    case "${v_tag}" in
             1)      u_flag=git_1_fn;;
             2)      u_flag=git_2_fn;;
-            *)      fail_fn 'Could not detect the variable $v_tag.'
+            *)      fail_fn 'Could not detect the variable ${v_tag}.'
     esac
 
-    "$u_flag" "$v_url" "$t_flag" 2>/dev/null
+    "${u_flag}" "${v_url}" "${t_flag}" 2>/dev/null
 }
 
 build_done()
 {
-    echo "$2" > "$packages/$1.done"
+    echo "${2}" > "${packages}/${1}.done"
 }
 
 #
@@ -324,7 +324,7 @@ build_done()
 #
 
 printf "%s\n%s\n%s" \
-    "Build-tools script: v$script_ver" \
+    "Build-tools script: v${script_ver}" \
     '===================================='
 
 #
@@ -337,13 +337,13 @@ for i in ${pkgs[@]}
 do
     missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
 
-    if [ -z "$missing_pkg" ]; then
-        missing_pkgs+=" $i"
+    if [ -z "${missing_pkg}" ]; then
+        missing_pkgs+=" ${i}"
     fi
 done
 
-if [ -n "$missing_pkgs" ]; then
-    sudo apt -y install $missing_pkgs
+if [ -n "${missing_pkgs}" ]; then
+    sudo apt -y install ${missing_pkgs}
     clear
 fi
 unset i missing_pkgs
@@ -359,42 +359,42 @@ export ACLOCAL_PATH=/usr/share/aclocal
 #
 
 git_ver_fn '541' '2' 'T'
-if build 'cmake' "$g_ver"; then
-    download "https://gitlab.kitware.com/cmake/cmake/-/archive/v$g_ver/cmake-v$g_ver.tar.bz2" "cmake-$g_ver.tar.bz2"
-    execute ./configure --prefix="$install_prefix" --parallel="$cpu_threads" --enable-ccache -- -DCMAKE_USE_OPENSSL=OFF
-    execute make "-j$cpu_threads"
+if build 'cmake' "${g_ver}"; then
+    download "https://gitlab.kitware.com/cmake/cmake/-/archive/v${g_ver}/cmake-v${g_ver}.tar.bz2" "cmake-${g_ver}.tar.bz2"
+    execute ./configure --prefix="${install_prefix}" --parallel="${cpu_threads}" --enable-ccache -- -DCMAKE_USE_OPENSSL=OFF
+    execute make "-j${cpu_threads}"
     execute sudo make install
     execute make clean
-    build_done 'cmake' "$g_ver"
+    build_done 'cmake' "${g_ver}"
 fi
 
 git_ver_fn 'ninja-build/ninja' '1' 'T'
-if build 'ninja' "$g_ver1"; then
-    download "https://codeload.github.com/ninja-build/ninja/tar.gz/refs/tags/v$g_ver1" "ninja-$g_ver1.tar.gz"
+if build 'ninja' "${g_ver1}"; then
+    download "https://codeload.github.com/ninja-build/ninja/tar.gz/refs/tags/v${g_ver1}" "ninja-${g_ver1}.tar.gz"
     re2c_path="$(type -P re2c)"
-    execute cmake -B build -DCMAKE_{INSTALL_PREFIX="$install_prefix",BUILD_TYPE=Release} \
-        -DRE2C="$re2c_path" -DBUILD_TESTING=OFF -G 'Unix Makefiles' -Wno-dev
-    execute make "-j$cpu_threads" -C build
+    execute cmake -B build -DCMAKE_{INSTALL_PREFIX="${install_prefix}",BUILD_TYPE=Release} \
+        -DRE2C="${re2c_path}" -DBUILD_TESTING=OFF -G 'Unix Makefiles' -Wno-dev
+    execute make "-j${cpu_threads}" -C build
     execute sudo make -C build install
     execute make -C build clean
-    build_done 'ninja' "$g_ver1"
+    build_done 'ninja' "${g_ver1}"
 fi
 
 git_ver_fn 'mesonbuild/meson' '1' 'T'
-if build 'meson' "$g_ver1"; then
-    download "https://codeload.github.com/mesonbuild/meson/tar.gz/refs/tags/$g_ver1" "meson-$g_ver1.tar.gz"
+if build 'meson' "${g_ver1}"; then
+    download "https://codeload.github.com/mesonbuild/meson/tar.gz/refs/tags/${g_ver1}" "meson-${g_ver1}.tar.gz"
     execute python3 setup.py build
-    execute sudo python3 setup.py install --prefix="$install_prefix"
-    build_done 'meson' "$g_ver1"
+    execute sudo python3 setup.py install --prefix="${install_prefix}"
+    build_done 'meson' "${g_ver1}"
 fi
 
 if build 'golang' '21.0'; then
     download 'https://go.dev/dl/go1.21.0.linux-amd64.tar.gz' 'golang-21.0.tar.gz'
-    execute sudo cp -f bin/go bin/gofmt "$install_prefix"/bin
+    execute sudo cp -f bin/go bin/gofmt "${install_prefix}"/bin
     sudo rm -fr /usr/local/go 2>/dev/null
     sudo mkdir -p /usr/local/go
     export GOROOT=/usr/local/go
-    export PATH=$PATH:$GOROOT/bin
+    export PATH="${PATH}:${GOROOT}/bin"
     build_done 'golang' '21.0'
 fi
 
diff --git a/Bash/Installer Scripts/Tilix Terminal/build-tilix b/Bash/Installer Scripts/Tilix Terminal/build-tilix
--- a/Bash/Installer Scripts/Tilix Terminal/build-tilix
+++ b/Bash/Installer Scripts/Tilix Terminal/build-tilix
@@ -10,19 +10,19 @@ script_ver=1.0
 archive_dir=tilix-1.9.5
 archive_url=https://github.com/gnunn1/tilix/archive/refs/tags/1.9.5.tar.gz
 archive_ext="${archive_url//*.}"
-cwd="$PWD"/tilix-build-script
-packages="$cwd"/packages
-schemes_folder="$HOME"/.config/tilix/schemes
+cwd="${PWD}"/tilix-build-script
+packages="${cwd}"/packages
+schemes_folder="${HOME}"/.config/tilix/schemes
 
 printf "\n%s\n%s\n\n" \
-    "tilix build script - v$script_ver" \
+    "tilix build script - v${script_ver}" \
     '==============================================='
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-mkdir -p "$packages"
+mkdir -p "${packages}"
 
 #
 # SET THE C+CPP COMPILERS
@@ -41,11 +41,11 @@ export {CFLAGS,CXXFLAGS}='-g -O3 -march=native'
 #
 
 PKG_CONFIG_PATH="\
-$workspace/lib/pkgconfig:\
-$workspace/lib64/pkgconfig:\
-$workspace/share/pkgconfig:\
-$workspace/lib/x86_64-linux-gnu/pkgconfig:\
-$workspace/usr/lib/pkgconfig:\
+${workspace}/lib/pkgconfig:\
+${workspace}/lib64/pkgconfig:\
+${workspace}/share/pkgconfig:\
+${workspace}/lib/x86_64-linux-gnu/pkgconfig:\
+${workspace}/usr/lib/pkgconfig:\
 /lib/pkgconfig:\
 /usr/local/lib/x86_64-linux-gnu/pkgconfig:\
 /usr/local/lib64/pkgconfig:\
@@ -70,7 +70,7 @@ exit_fn()
 
 fail_fn()
 {
-    printf "%s\n\n" "$1"
+    printf "%s\n\n" "${1}"
     exit 1
 }
 
@@ -86,8 +86,8 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "$choice" in
-        1)      sudo rm -fr "$cwd";;
+    case "${choice}" in
+        1)      sudo rm -fr "${cwd}";;
         2)      echo;;
         *)
                 clearinstall-tilix.sh
@@ -109,16 +109,16 @@ pkgs=(autoconf autogen automake build-essential ccache curl gettext git gtk-doc-
 
 for i in ${pkgs[@]}
 do
-    missing_pkg="$(dpkg -l | grep $i)"
+    missing_pkg="$(sudo dpkg -l | grep ${i})"
 
-    if [ -z "$missing_pkg" ]; then
-        missing_pkgs+=" $i"
+    if [ -z "${missing_pkg}" ]; then
+        missing_pkgs+=" ${i}"
     fi
 done
 unset i
 
-if [ -n "$missing_pkgs" ]; then
-    sudo apt -y install $missing_pkgs
+if [ -n "${missing_pkgs}" ]; then
+    sudo apt -y install ${missing_pkgs}
     sudo apt -y autoremove
     clear
 fi
@@ -127,19 +127,19 @@ fi
 # DOWNLOAD AND INSTALL DUB 
 #
 
-if [ -d "$packages"/dub ]; then
-    sudo rm -fr "$packages"/dub
+if [ -d "${packages}"/dub ]; then
+    sudo rm -fr "${packages}"/dub
 fi
-mkdir -p "$packages"/dub
+mkdir -p "${packages}"/dub
 
 if [ -f '/usr/bin/dub' ]; then
     sudo apt remove -y dub
 else
-    if ! git clone -q 'https://github.com/dlang/dub.git' "$packages"/dub; then
+    if ! git clone -q 'https://github.com/dlang/dub.git' "${packages}"/dub; then
         fail_fn 'Could not git clone dub.'
     else
         clear
-        cd "$packages"/dub || exschemes_folderit 1
+        cd "${packages}"/dub || exschemes_folderit 1
         ./build.d
         if ! sudo mv bin/dub /usr/bin; then
             fail_fn 'Failed to move dub binary to /usr/bin'
@@ -155,15 +155,15 @@ fi
 # DOWNLOAD AND INSTALL TILIX
 #
 
-if [ -d "$packages"/tilix ]; then
-    sudo rm -fr "$packages"/tilix
+if [ -d "${packages}"/tilix ]; then
+    sudo rm -fr "${packages}"/tilix
 fi
 
-if ! git clone 'https://github.com/gnunn1/tilix.git' "$packages"/tilix; then
+if ! git clone 'https://github.com/gnunn1/tilix.git' "${packages}"/tilix; then
     fail_fn 'Could not git clone tilix.'
 else
     clear
-    cd "$packages"/tilix || exit 1
+    cd "${packages}"/tilix || exit 1
     dub build --build=release
     if ! sudo bash install.sh; then
         fail_fn 'Tilix failed to install. Press enter to continue.'
@@ -174,17 +174,17 @@ fi
 # DOWNLOAD, EXTRACT, AND INSTALL THE TILIX THEMES
 #
 
-if [ -d "$packages"/tilix-themes ]; then
-    sudo rm -fr "$packages"/tilix-themes
+if [ -d "${packages}"/tilix-themes ]; then
+    sudo rm -fr "${packages}"/tilix-themes
 fi
-mkdir -p "$packages"/tilix-themes
+mkdir -p "${packages}"/tilix-themes
 
-if ! curl -Lso "$packages"/tilix-themes.tar.gz 'https://raw.githubusercontent.com/slyfox1186/script-repo/main/shell/installers/tilix/tilix-themes.tar.gz'; then
+if ! curl -Lso "${packages}"/tilix-themes.tar.gz 'https://raw.githubusercontent.com/slyfox1186/script-repo/main/shell/installers/tilix/tilix-themes.tar.gz'; then
     fail_fn 'Failed to down download the tilix-schemes archive file.'
 fi
 
-if ! tar -zxf "$packages"/tilix-themes.tar.gz -C "$packages"/tilix-themes --strip-components 1; then
-    printf "%s\n\n" "Failed to extract the themes archive: $packages/tilix-themes.tar.gz"
+if ! tar -zxf "${packages}"/tilix-themes.tar.gz -C "${packages}"/tilix-themes --strip-components 1; then
+    printf "%s\n\n" "Failed to extract the themes archive: ${packages}/tilix-themes.tar.gz"
     exit 1
 fi
 
@@ -192,7 +192,7 @@ if [ ! -d "$schemes_folder" ]; then
     mkdir -p "$schemes_folder"
 fi
 
-cd "$packages"/tilix-themes || exit 1
+cd "${packages}"/tilix-themes || exit 1
 if [ -f argonaut.json ] ;then
     cp -fr argonaut.json dracula.json neopolitan.json vibrant-ink.json "$schemes_folder"
 else
