Update build-curl

diff --git a/Bash/Installer Scripts/GitHub Projects/build-curl b/Bash/Installer Scripts/GitHub Projects/build-curl
--- a/Bash/Installer Scripts/GitHub Projects/build-curl
+++ b/Bash/Installer Scripts/GitHub Projects/build-curl
@@ -1,21 +1,14 @@
 #!/usr/bin/env bash
 
-###################################################################################################################################
-##
 ##  GitHub Script: https://github.com/slyfox1186/script-repo/edit/main/util-linux/Installer%20Scripts/GNU%20Software/build-curl
-##
 ##  Purpose: Build cURL with OpenSSL backend
-##
-##  Updated: 01.07.24
-##
-##  Script version: 1.5
-##
-###################################################################################################################################
+##  Updated: 01.26.24
+##  Script version: 1.6
 
 clear
 
-if [ "${EUID}" -eq '0' ]; then
-    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
+if [ "${EUID}" -eq "0" ]; then
+    printf "%s\n\n" "You must run this script WITHOUT root/sudo."
     exit 1
 fi
 
@@ -23,48 +16,39 @@ fi
 set -euo pipefail
 
 # Define the program name
-program='curl'
-pem_file='cacert.pem'
-certs_dir='/etc/ssl/certs'
+program="curl"
+pem_file="cacert.pem"
+certs_dir="/etc/ssl/certs"
 pem_out="$certs_dir/$pem_file"
 
 # Environment variable settings
 CC=gcc
 CXX=g++
-CFLAGS='-g -O3 -pipe -march=native'
+CFLAGS="-g -O3 -pipe -march=native"
 CXXFLAGS="${CFLAGS} -Wno-variadic-macros"
-CPPFLAGS='-I/usr/include/openssl -I/usr/local/include -I/usr/include/libxml2 -I/usr/include'
+CPPFLAGS="-I/usr/include/openssl -I/usr/local/include -I/usr/include/libxml2 -I/usr/include"
 export CC CXX CFLAGS CPPFLAGS CXXFLAGS
 
-PKG_CONFIG_PATH="\
-/usr/local/lib64/pkgconfig:\
-/usr/local/lib/x86_64-linux-gnu/pkgconfig:\
-/usr/local/lib/pkgconfig:\
-/usr/share/pkgconfig:\
-/usr/lib/x86_64-linux-gnu/pkgconfig:\
-/usr/lib/pkgconfig:\
-/lib/pkgconfig\
-"
+PKG_CONFIG_PATH="/usr/local/lib64/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/lib/pkgconfig"
 export PKG_CONFIG_PATH
 
 # Fail function to handle errors
-fail_fn()
-{
+fail_fn() {
     echo "Error: $1"
     exit 1
 }
 
 # Fetch the latest release tag from GitHub tags page
-version=$(curl -s "https://github.com/curl/curl/tags" | grep -oP 'curl-[0-9]+_[0-9]+_[0-9]+' | head -n 1)
+version="$(curl -s "https://github.com/curl/curl/tags" | grep -oP 'curl-[0-9]+_[0-9]+_[0-9]+' | head -n 1)"
 if [ -z "$version" ]; then
-    printf 'Error: Unable to fetch the latest release version of %s.\n' "$program"
+    printf "Error: Unable to fetch the latest release version of %s.\n" "$program"
     exit 1
 fi
 
 # Extract and format the version number
-formatted_version=$(echo "$version" | sed 's/curl-//' | sed 's/_/\./g')
+formatted_version="$(echo "$version" | sed "s/curl-//" | sed "s/_/\./g")"
 
-printf 'Latest release version of %s is %s.\n' "$program" "$formatted_version"
+printf "Latest release version of %s is %s.\n" "$program" "$formatted_version"
 
 # Construct the download URL and tar file name
 download_url="https://github.com/curl/curl/archive/refs/tags/${version}.tar.gz"
@@ -73,20 +57,20 @@ extract_dir="${program}-build-script-${formatted_version}"
 
 # Check if the tar file already exists
 if [ ! -f "$tar_file" ]; then
-    printf 'Downloading %s version %s...\n' "$program" "$formatted_version"
+    printf "Downloading %s version %s...\n" "$program" "$formatted_version"
     wget "$download_url" -O "$tar_file"
 else
-    printf 'The tar file %s already exists, skipping download.\n' "$tar_file"
+    printf "The tar file %s already exists, skipping download.\n" "$tar_file"
 fi
 
 # Remove the output directory if it exists
 if [ -d "$extract_dir" ]; then
-    printf 'Removing existing directory %s...\n' "$extract_dir"
+    printf "Removing existing directory %s...\n" "$extract_dir"
     rm -rf "$extract_dir"
 fi
 
 # Extract the tar file
-printf 'Extracting %s...\n' "$tar_file"
+printf "Extracting %s...\n" "$tar_file"
 mkdir "$extract_dir"
 tar -zxf "$tar_file" -C "$extract_dir" --strip-components 1
 
@@ -96,39 +80,68 @@ cd "$extract_dir"
 libgcc_ver="$(sudo apt list libgcc-* 2>/dev/null | grep -Eo 'libgcc-[0-9]*-dev' | uniq | head -n1)"
 libgtk_ver="$(sudo apt list libgtk-* 2>/dev/null | grep -Eo 'libgtk-[0-9]+-doc' | head -n1)"
 
-# Check and install missing packages
-pkgs=(apt-transport-https apt-utils autoconf autoconf-archive autogen automake autopoint autotools-dev
-      build-essential bzip2 ca-certificates ccache clang cmake curl gfortran git google-perftools graphviz
-      jq lcov libaria2-0 libaria2-0-dev libc-ares-dev libcppunit-dev libcunit1-dev libcurl4 libcurl4-openssl-dev
-      libdmalloc-dev libec-dev libedit-dev libev-dev libevent-dev libexiv2-27 libexpat1-dev "${libgcc_ver}"
-      libgcrypt20-dev libgexiv2-2 libgimp2.0 libgmp3-dev libgpg-error-dev "${libgtk_ver}" libgpgme-dev libicu-dev
-      libjemalloc-dev libkrb5-3 libldap2-dev libldap-dev liblttng-ust-dev liblzma-dev libmbedtls-dev libnghttp2-dev
-      libnghttp3-dev libntlm0-dev libparted-dev libpng-dev libpsl-dev librtmp-dev librust-bzip2-dev librust-openssl-dev
-      libsqlite3-dev libssh2-1-dev libssh-dev libssl-dev libtinfo5 libticonv-dev libtinfo-dev libtool libtool-bin
-      libunistring-dev libunwind8 libuv1-dev libxml2-dev libzstd-dev lzip m4 nettle-dev default-jdk-headless openssh-server
-      pkg-config python3-dev python3-numpy python3-packaging python3-pip python3-pytest python3-setuptools python3-wheel
-      re2c rsync unzip valgrind zip zlib1g-dev)
+pkgs_fn() {
+    local missing_pkg missing_packages pkg pkgs available_packages unavailable_packages
 
-missing_pkgs=''
-for pkg in "${pkgs[@]}"
-do
-    if ! dpkg -l "$pkg" &> /dev/null; then
-        missing_pkgs+="$pkg "
+    # Check and install missing packages
+    pkgs=(
+        apt-transport-https apt-utils autoconf autoconf-archive autogen automake autopoint autotools-dev
+        build-essential bzip2 ca-certificates ccache clang cmake curl gfortran git google-perftools graphviz
+        jq lcov libaria2-0 libaria2-0-dev libc-ares-dev libcppunit-dev libcunit1-dev libcurl4 libcurl4-openssl-dev
+        libdmalloc-dev libec-dev libedit-dev libev-dev libevent-dev libexiv2-27 libexpat1-dev "${libgcc_ver}"
+        libgcrypt20-dev libgexiv2-2 libgimp2.0 libgmp3-dev libgpg-error-dev "${libgtk_ver}" libgpgme-dev libicu-dev
+        libjemalloc-dev libkrb5-3 libldap2-dev libldap-dev liblttng-ust-dev liblzma-dev libmbedtls-dev libnghttp2-dev
+        libnghttp3-dev libntlm0-dev libparted-dev libpng-dev libpsl-dev librtmp-dev librust-bzip2-dev librust-openssl-dev
+        libsqlite3-dev libssh2-1-dev libssh-dev libssl-dev libtinfo5 libticonv-dev libtinfo-dev libtool libtool-bin
+        libunistring-dev libunwind8 libuv1-dev libxml2-dev libzstd-dev lzip m4 nettle-dev default-jdk-headless openssh-server
+        pkg-config python3-dev python3-numpy python3-packaging python3-pip python3-pytest python3-setuptools python3-wheel
+        re2c rsync unzip valgrind zip zlib1g-dev
+    )
+
+    # Initialize arrays for missing, available, and unavailable packages
+    missing_packages=()
+    available_packages=()
+    unavailable_packages=()
+
+    # Loop through the array to find missing packages
+    for pkg in "${pkgs[@]}"
+    do
+        if ! dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed"; then
+            missing_packages+=("$pkg")
+        fi
+    done
+
+    # Check availability of missing packages and categorize them
+    for pkg in "${missing_packages[@]}"
+    do
+        if apt-cache show "$pkg" > /dev/null 2>&1; then
+            available_packages+=("$pkg")
+        else
+            unavailable_packages+=("$pkg")
+        fi
+    done
+
+    # Print unavailable packages
+    if [[ "${#unavailable_packages[@]}" -gt 0 ]]; then
+        echo "Unavailable packages: ${unavailable_packages[*]}"
     fi
-done
 
-if [ -n "$missing_pkgs" ]; then
-    printf 'Installing missing packages: %s\n' "$missing_pkgs"
-    sudo apt install $missing_pkgs
-fi
+    # Install available missing packages
+    if [[ "${#available_packages[@]}" -gt 0 ]]; then
+        echo "Installing available missing packages: ${available_packages[*]}"
+        sudo apt install "${available_packages[@]}"
+    else
+        printf "%s\n\n" "No missing packages to install or all missing packages are unavailable."
+    fi
+}
+
+# INSTALL REQUIRED APT PACKAGES
+pkgs_fn
 
 # INSTALL CA CERTS FROM CURL'S OFFICIAL WEBSITE
 if [ ! -f "${pem_out}" ]; then
-    printf "%s\n%s\n\n"                            \
-        'Download the latest security certificate' \
-        '================================================'
-    curl -Lso "$cwd/$pem_file" "https://curl.se/ca/$pem_file"
-    sudo cp -f "$cwd/$pem_file" "${pem_out}"
+    curl -Lso "$pem_file" "https://curl.se/ca/$pem_file"
+    sudo cp -f "$pem_file" "${pem_out}"
 fi
 
 if type -P update-ca-certificates &>/dev/null; then
@@ -172,7 +185,7 @@ if ! sudo make install; then
     fail_fn "Failed to execute: sudo make install. Line: ${LINENO}"
 fi
 
-curl_version=$(curl --version | head -n 1 | awk '{print $2}')
+curl_version="$($install_dir/bin/curl --version | head -n 1 | awk '{print $2}')"
 
 printf "\n%s\n\n" "The installed version of cURL is: $curl_version"
 sleep 2
