Update build-curl

diff --git a/Bash/Installer Scripts/GitHub Projects/build-curl b/Bash/Installer Scripts/GitHub Projects/build-curl
--- a/Bash/Installer Scripts/GitHub Projects/build-curl
+++ b/Bash/Installer Scripts/GitHub Projects/build-curl
@@ -6,9 +6,9 @@
 ##
 ##  Purpose: Build cURL with OpenSSL backend
 ##
-##  Updated: 12.30.23
+##  Updated: 01.07.24
 ##
-##  Script version: 1.4
+##  Script version: 1.5
 ##
 ###################################################################################################################################
 
@@ -19,77 +19,22 @@ if [ "${EUID}" -eq '0' ]; then
     exit 1
 fi
 
-#
-# SET THE VARIABLES
-#
+# Set strict mode for bash
+set -euo pipefail
 
-script_ver=1.4
-curl_ver=8.5.0
-archive_dir=${curl_ver}
-archive_dir1=${curl_ver//./_}
-archive_url="https://github.com/curl/curl/releases/download/curl-${archive_dir1}/curl-$archive_dir.tar.xz"
-archive_ext="${archive_url//*.}"
-archive_name="$archive_dir.tar.${archive_ext}"
-cwd="$PWD"/curl-build-script
-install_prefix=/usr/local
-pem_file=cacert.pem
+# Define the program name
+program='curl'
+pem_file='cacert.pem'
 certs_dir='/etc/ssl/certs'
 pem_out="$certs_dir/$pem_file"
-pc_type=x86_64-linux-gnu
-user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
-web_repo=https://github.com/slyfox1186/script-repo
 
-printf "%s\n%s\n\n"                      \
-    "cURL Build Script - v${script_ver}" \
-    '==============================================='
-sleep 2
-
-#
-# CREATE OUTPUT DIRECTORY
-#
-
-if [ -d "$cwd" ]; then
-    sudo rm -fr "$cwd"
-fi
-mkdir -p "$cwd"
-
-#
-# SET THE C/CXX COMPILERS & SET THE COMPILER OPTIMIZATION FLAGS
-#
-
+# Environment variable settings
 CC=gcc
 CXX=g++
 CFLAGS='-g -O3 -pipe -march=native'
 CXXFLAGS="${CFLAGS} -Wno-variadic-macros"
 CPPFLAGS='-I/usr/include/openssl -I/usr/local/include -I/usr/include/libxml2 -I/usr/include'
 export CC CXX CFLAGS CPPFLAGS CXXFLAGS
-
-#
-# SET THE PATH VARIABLE
-#
-
-PATH="\
-/usr/lib/ccache:\
-${HOME}/perl5/bin:\
-${HOME}/.cargo/bin:\
-${HOME}/.local/bin:\
-/usr/local/sbin:\
-/usr/local/cuda/bin:\
-/usr/local/x86_64-linux-gnu/bin:\
-/usr/local/bin:\
-/usr/sbin:\
-/usr/bin:\
-/sbin:\
-/bin:\
-/usr/local/games:\
-/usr/games:\
-/snap/bin\
-"
-export PATH
-
-#
-# SET THE PKG_CONFIG_PATH VARIABLE
-#
 
 PKG_CONFIG_PATH="\
 /usr/local/lib64/pkgconfig:\
@@ -102,57 +47,56 @@ PKG_CONFIG_PATH="\
 "
 export PKG_CONFIG_PATH
 
-#
-# CREATE FUNCTIONS
-#
-
-exit_fn()
-{
-    printf "\n%s\n\n%s\n\n"                                       \
-        'Make sure to star this repository to show your support!' \
-        "$web_repo"
-    exit 0
-}
-
+# Fail function to handle errors
 fail_fn()
 {
-    printf "\n%s\n\n%s\n\n" \
-        "$1"              \
-        "To report a bug create an issue at: $web_repo/issues"
+    echo "Error: $1"
     exit 1
 }
 
-cleanup_fn()
-{
-    local choice
+# Fetch the latest release tag from GitHub tags page
+version=$(curl -s "https://github.com/curl/curl/tags" | grep -oP 'curl-[0-9]+_[0-9]+_[0-9]+' | head -n 1)
+if [ -z "$version" ]; then
+    printf 'Error: Unable to fetch the latest release version of %s.\n' "$program"
+    exit 1
+fi
 
-    printf "\n%s\n%s\n%s\n\n%s\n%s\n\n"                \
-        '============================================' \
-        '  Do you want to clean up the build files?  ' \
-        '============================================' \
-        '[1] Yes'                                      \
-        '[2] No'
-    read -p 'Your choices are (1 or 2): ' choice
-    clear
+# Extract and format the version number
+formatted_version=$(echo "$version" | sed 's/curl-//' | sed 's/_/\./g')
 
-    case "${choice}" in
-        1)      sudo rm -fr "$cwd";;
-        2)      return 0;;
-        *)
-                unset choice
-                clear
-                cleanup_fn
-                ;;
-    esac
-}
+printf 'Latest release version of %s is %s.\n' "$program" "$formatted_version"
 
-#
-# INSTALL REQUIRED APT PACKAGES
-#
+# Construct the download URL and tar file name
+download_url="https://github.com/curl/curl/archive/refs/tags/${version}.tar.gz"
+tar_file="${program}-${formatted_version}.tar.gz"
+extract_dir="${program}-build-script-${formatted_version}"
+
+# Check if the tar file already exists
+if [ ! -f "$tar_file" ]; then
+    printf 'Downloading %s version %s...\n' "$program" "$formatted_version"
+    wget "$download_url" -O "$tar_file"
+else
+    printf 'The tar file %s already exists, skipping download.\n' "$tar_file"
+fi
+
+# Remove the output directory if it exists
+if [ -d "$extract_dir" ]; then
+    printf 'Removing existing directory %s...\n' "$extract_dir"
+    rm -rf "$extract_dir"
+fi
+
+# Extract the tar file
+printf 'Extracting %s...\n' "$tar_file"
+mkdir "$extract_dir"
+tar -zxf "$tar_file" -C "$extract_dir" --strip-components 1
+
+# Change to the directory
+cd "$extract_dir"
 
 libgcc_ver="$(sudo apt list libgcc-* 2>/dev/null | grep -Eo 'libgcc-[0-9]*-dev' | uniq | head -n1)"
 libgtk_ver="$(sudo apt list libgtk-* 2>/dev/null | grep -Eo 'libgtk-[0-9]+-doc' | head -n1)"
 
+# Check and install missing packages
 pkgs=(apt-transport-https apt-utils autoconf autoconf-archive autogen automake autopoint autotools-dev
       build-essential bzip2 ca-certificates ccache clang cmake curl gfortran git google-perftools graphviz
       jq lcov libaria2-0 libaria2-0-dev libc-ares-dev libcppunit-dev libcunit1-dev libcurl4 libcurl4-openssl-dev
@@ -165,69 +109,32 @@ pkgs=(apt-transport-https apt-utils autoconf autoconf-archive autogen automake a
       pkg-config python3-dev python3-numpy python3-packaging python3-pip python3-pytest python3-setuptools python3-wheel
       re2c rsync unzip valgrind zip zlib1g-dev)
 
-for pkg in ${pkgs[@]}
+missing_pkgs=''
+for pkg in "${pkgs[@]}"
 do
-    missing_pkg="$(sudo dpkg -l | grep -o "${pkg}")"
-
-    if [ -z "${missing_pkg}" ]; then
-        missing_pkgs+=" ${pkg}"
+    if ! dpkg -l "$pkg" &> /dev/null; then
+        missing_pkgs+="$pkg "
     fi
 done
 
-if [ -n "${missing_pkgs}" ]; then
-    sudo apt -y install ${missing_pkgs}
-    sudo apt -y autoremove
-    clear
+if [ -n "$missing_pkgs" ]; then
+    printf 'Installing missing packages: %s\n' "$missing_pkgs"
+    sudo apt -y install $missing_pkgs
 fi
 
-#
 # INSTALL CA CERTS FROM CURL'S OFFICIAL WEBSITE
-#
-
 if [ ! -f "${pem_out}" ]; then
-    printf "%s\n%s\n\n" \
+    printf "%s\n%s\n\n"                            \
         'Download the latest security certificate' \
         '================================================'
-    curl -A "$user_agent" -Lso "$cwd/$pem_file" "https://curl.se/ca/$pem_file"
+    curl -Lso "$cwd/$pem_file" "https://curl.se/ca/$pem_file"
     sudo cp -f "$cwd/$pem_file" "${pem_out}"
 fi
 
-#
-# CREATE OUTPUT DIRECTORY CURL
-#
-
-if [ -d "$cwd/$archive_dir" ]; then
-    sudo rm -fr "$cwd/$archive_dir"
-fi
-mkdir -p "$cwd/$archive_dir/build"
-
-#
-# DOWNLOAD THE ARCHIVE FILE CURL
-#
-
-if [ ! -f "$cwd/${archive_name}" ]; then
-    curl -A "$user_agent" -Lso "$cwd/${archive_name}" "${archive_url}"
-fi
-
-#
-# EXTRACT THE ARCHIVE FILE CURL
-#
-
-if ! tar -xf "$cwd/${archive_name}" -C "$cwd/$archive_dir" --strip-components 1; then
-    fail_fn "Failed to extract: $cwd/${archive_name}"
-fi
-
-# UPDATE THE SYSTEM SECURITY CERTIFICATES BEFORE INSTALLING CURL
-if type -P 'update-ca-certificates' &>/dev/null; then
+if type -P update-ca-certificates &>/dev/null; then
     sudo update-ca-certificates
 fi
 
-#
-# DETERMINE IF HTTP3 SUPPORT IS ENABLED
-#
-
-
-cd "$cwd/$archive_dir" || exit 1
 dopts=('--disable-'{get-easy-options,shared,verbose,versioned-symbols})
 eopts=('--enable-'{alt-svc,ares=/usr,cookies})
 eopts+=('--enable-'{dict,dnsshuffle,doh,file,ftp,gopher})
@@ -239,31 +146,34 @@ eopts+=('--enable-'{proxy,pthreads,rtsp,smb,smtp,socketpair,sspi,static,telnet})
 eopts+=('--enable-'{tftp,threaded-resolver,tls-srp,unix-sockets,websockets})
 wopts=('--with-'{libssh2,nghttp2='/usr/include',nghttp3='/usr/include',openssl='/usr',ssl,zlib})
 wopts+=('--with-'{ca-bundle="${pem_out}",ca-fallback,ca-path="$certs_dir",secure-transport})
+
+# Generate configuration scripts
 autoreconf -fi
-cd build || exit 1
-../configure --prefix="$install_prefix" \
-            "${dopts[@]}"                 \
-            "${eopts[@]}"                 \
-            "${wopts[@]}"                 \
-            "${csuffix}"                  \
-             CPPFLAGS="${CPPFLAGS}"
-echo
+
+# Create a build directory if it doesn't exist
+mkdir -p build
+cd build || fail_fn "Failed to enter the build directory."
+
+# Run the configure script
+../configure --prefix=/usr/local \
+            "${dopts[@]}"        \
+            "${eopts[@]}"        \
+            "${wopts[@]}"        \
+            CPPFLAGS="${CPPFLAGS}" || fail_fn "Configuration failed."
+# Compile using all available cores
+echo "Compiling..."
 if ! make "-j$(nproc --all)"; then
     fail_fn "Failed to execute: make -j$(nproc --all). Line: ${LINENO}"
 fi
-echo
+
+# Install
+echo "Installing..."
 if ! sudo make install; then
     fail_fn "Failed to execute: sudo make install. Line: ${LINENO}"
 fi
 
-# PROMPT USER TO CLEAN UP FILES
-cleanup_fn
+curl_version=$(curl --version | head -n 1 | awk '{print $2}')
 
-# SHOW NEW VERSION
-curl_ver="$(/usr/local/bin/curl --version | grep -Eo '^curl [0-9\.]+' | grep -Eo '[0-9\.]+')"
-clear
-printf "%s\n" "The updated cURL version is: ${curl_ver}"
-sleep 3
-
-# SHOW EXIT MESSAGE
-exit_fn
+printf "\n%s\n\n" "The installed version of cURL is: $curl_version"
+sleep 2
+echo "CURL installation completed successfully."
