Update build-aria2

diff --git a/Bash/Installer Scripts/GitHub Projects/build-aria2 b/Bash/Installer Scripts/GitHub Projects/build-aria2
--- a/Bash/Installer Scripts/GitHub Projects/build-aria2
+++ b/Bash/Installer Scripts/GitHub Projects/build-aria2
@@ -17,138 +17,176 @@ set -euo pipefail
 ##         - RUNPATH to LDFLAGS
 ##  Fixed: Soft linking error
 
-# Ensure the script is run with superuser privileges
-if [[ $EUID -ne 0 ]]; then
-    echo "This script must be run as root or with sudo."
-    exit 1
-fi
+[[ $EUID -ne 0 ]] && { echo "This script must be run as root or with sudo."; exit 1; }
 
-# Script information
 script_ver="1.9"
 echo "GitHub Script for building aria2 from source. Version: $script_ver"
 
-# Define color codes
 GREEN='\033[0;32m'
 RED='\033[0;31m'
-NC='\033[0m' # No Color
+NC='\033[0m'
 
-# Logging function for standardized messages
-log() {
-    echo -e "${GREEN}[LOG]${NC} $(date +'%Y-%m-%d %H:%M:%S') - $*"
+log() { echo -e "${GREEN}[LOG]${NC} $(date +'%Y-%m-%d %H:%M:%S') - $*"; }
+handle_error() { echo -e "${RED}[ERROR]${NC} $(date +'%Y-%m-%d %H:%M:%S') - $*"; exit 1; }
+
+display_help() {
+    echo "Usage: $0 [OPTION]..."
+    echo "Build aria2 from source code."
+    echo
+    echo "Options:"
+    echo "  -s, --service     Create aria2 service"
+    echo "  -w, --webui       Install webui-aria2"
+    echo "  -h, --help        Display this help message and exit"
+    echo
+    exit 0
 }
 
-# Error handling function
-handle_error() {
-    echo -e "${RED}[ERROR]${NC} $(date +'%Y-%m-%d %H:%M:%S') - $*"
-    exit 1
-}
+# Check if help argument is passed
+if [[ "$1" == "-h" || "$1" == "--help" ]]; then
+    display_help
+fi
 
-# Install required packages
 install_packages() {
-    local pkgs=(
-        autoconf autoconf-archive autogen automake build-essential ca-certificates
-        ccache curl libssl-dev libtool libtool-bin m4 pkg-config zlib1g-dev
-    )
+    local pkgs=(autoconf autoconf-archive autogen automake build-essential ca-certificates
+                ccache curl libssl-dev libtool libtool-bin m4 pkg-config zlib1g-dev)
     log "Attempting to install required packages..."
     sudo apt install -y "${pkgs[@]}"
-    
     for pkg in "${pkgs[@]}"; do
-        if ! dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed"; then
-            handle_error "Failed to install: $pkg"
-        fi
+        dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed" || handle_error "Failed to install: $pkg"
     done
-    
+    echo
     log "Installation of required packages completed."
 }
 
-# Retrieve the latest release version of a GitHub repository
-github_latest_release_version() {
-    github_version=$(
-                      curl -sLH "Content-Type: text/plain" "https://gitver.optimizethis.net" |
-                      bash -s "$1"
-                  )
-    echo "$github_version"
-}
+github_latest_release_version() { curl -sLH "Content-Type: text/plain" "https://gitver.optimizethis.net" | bash -s "$1"; }
 
 libgpg_latest_release_version() {
     local url="$1"
-    local latest_version=$(
-                            curl -s "$url" |
-                            grep -Eo 'href="libgpg-error-[0-9]+\.[0-9]+\.tar\.bz2"' |
-                            head -n1 |
-                            grep -Eo '[0-9]+\.[0-9]+'
-                        )
-
-    if [[ -z "$latest_version" ]]; then
-        echo "Failed to find the latest version of libgpg-error."
-        exit 1
-    else
-        echo "$latest_version"
-    fi
+    local latest_version=$(curl -s "$url" | grep -Eo 'href="libgpg-error-[0-9]+\.[0-9]+\.tar\.bz2"' | head -n1 | grep -Eo '[0-9]+\.[0-9]+')
+    [[ -z "$latest_version" ]] && { echo "Failed to find the latest version of libgpg-error."; exit 1; } || echo "$latest_version"
 }
 
-# Prepare the build environment
 prepare_build_environment() {
     build_dir="$PWD/aria2-build"
+    temp_dir="/tmp/aria2-temp-$(date +%s)"
     log "Creating build directory: $build_dir"
     mkdir -p "$build_dir"
     cd "$build_dir" || handle_error "Failed to create or navigate to build directory."
+    log "Creating temporary directory: $temp_dir"
+    mkdir -p "$temp_dir"
 }
 
-# Build and install jemalloc
 build_jemalloc() {
     log "Compiling jemalloc..."
+    echo
     local jemalloc_version=$(github_latest_release_version "https://github.com/jemalloc/jemalloc.git")
     local jemalloc_url="https://github.com/jemalloc/jemalloc/releases/download/$jemalloc_version/jemalloc-$jemalloc_version.tar.bz2"
     curl -Ls "$jemalloc_url" | tar -xj
     cd "jemalloc-$jemalloc_version"
-    ./configure --prefix=/usr/local
-    make "-j$(nproc)" && sudo make install
+    ./configure --prefix="$temp_dir/jemalloc"
+    make "-j$(nproc)" && make install
     cd ../
 }
 
-# Build and install libgpg-error
 build_libgpg_error() {
+    echo
     log "Compiling libgpg-error..."
+    echo
     local libgpg_error_version=$(libgpg_latest_release_version "https://gnupg.org/ftp/gcrypt/libgpg-error/")
     local libgpg_error_url="https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-$libgpg_error_version.tar.bz2"
     curl -Ls "$libgpg_error_url" | tar -xj
     cd "libgpg-error-${libgpg_error_version}"
-    ./configure --prefix=/usr/local
-    make "-j$(nproc)" && sudo make install
+    ./configure --prefix="$temp_dir/libgpg-error"
+    make "-j$(nproc)" && make install
     cd ../
 }
 
-# Compile and install Aria2
 compile_aria2() {
+    echo
     log "Compiling Aria2..."
+    echo
     local aria2_version=$(github_latest_release_version "https://github.com/aria2/aria2.git")
     local aria2_url="https://github.com/aria2/aria2/releases/download/release-$aria2_version/aria2-$aria2_version.tar.xz"
     curl -Ls "$aria2_url" | tar -xJ
     cd "aria2-$aria2_version"
     sed -i "s/1, 16/1, 128/g" "src/OptionHandlerFactory.cc"
-    ./configure --prefix=/usr/local --without-gnutls --with-openssl --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt
-    make "-j$(nproc)"
-    sudo make install
+    PATH="$temp_dir/jemalloc/bin:$temp_dir/libgpg-error/bin:$PATH" \
+    ./configure --prefix=/usr/local --without-gnutls --with-openssl --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt \
+                --with-jemalloc="$temp_dir/jemalloc" \
+                LDFLAGS="-L$temp_dir/jemalloc/lib -L$temp_dir/libgpg-error/lib" \
+                CPPFLAGS="-I$temp_dir/jemalloc/include -I$temp_dir/libgpg-error/include"
+    make "-j$(nproc)" && sudo make install
     cd ../
 }
 
-# Cleanup the build environment
-cleanup() {
+create_aria2_service() {
     echo
+    log "Creating aria2 service..."
+    echo
+    sudo tee /etc/systemd/system/aria2.service > /dev/null <<EOT
+[Unit]
+Description=Aria2 Service
+After=network.target
+
+[Service]
+Type=simple
+ExecStart=/usr/local/bin/aria2c --enable-rpc --rpc-listen-all
+Restart=on-abort
+
+[Install]
+WantedBy=multi-user.target
+EOT
+
+    sudo systemctl daemon-reload
+    sudo systemctl enable aria2
+    sudo systemctl start aria2
+    log "Aria2 service created and started."
+    echo
+}
+
+install_webui_aria2() {
+    local webui_aria2_dir="/var/www/html/webui-aria2"
+    if [ -d "$webui_aria2_dir" ]; then
+        log "webui-aria2 is already installed. Skipping installation."
+    else
+        log "Installing webui-aria2..."
+        sudo git clone https://github.com/ziahamza/webui-aria2.git "$webui_aria2_dir"
+        sudo chown -R www-data:www-data "$webui_aria2_dir"
+        log "webui-aria2 installed."
+    fi
+    echo
+}
+
+cleanup() {
     log "Cleaning up..."
-    rm -fr "$build_dir"
+    rm -fr "$build_dir" "$temp_dir"
     log "Cleanup completed."
 }
 
 main() {
     log "Starting aria2 build process..."
+    echo
     install_packages
     prepare_build_environment
     build_jemalloc
     build_libgpg_error
     compile_aria2
+    
+    for arg in "$@"; do
+        case $arg in
+            -s|--service)
+                create_aria2_service
+                ;;
+            -w|--webui)
+                install_webui_aria2
+                ;;
+            *)
+                ;;
+        esac
+    done
+    
     cleanup
+    echo
     log "Aria2 build process completed successfully."
 }
 
