Update build-openssl

diff --git a/Bash/Installer Scripts/GitHub Projects/build-openssl b/Bash/Installer Scripts/GitHub Projects/build-openssl
--- a/Bash/Installer Scripts/GitHub Projects/build-openssl
+++ b/Bash/Installer Scripts/GitHub Projects/build-openssl
@@ -10,15 +10,15 @@
 ##  
 ##  Enabled features: egd, fips, md2, rc5, trace, sctp, threads, and zlib
 ##
-##  Updated: 08.03.23
+##  Updated: 08.30.23
 ##
-##  Script version: 1.2
+##  Script version: 1.3
 ##
 #############################################################################
 
 clear
 
-if [ "$EUID" -eq '0' ]; then
+if [ "${EUID}" -eq '0' ]; then
     printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
     exit 1
 fi
@@ -27,29 +27,29 @@ fi
 # SET VARIABLES
 #
 
-script_ver=1.2
+script_ver=1.3
 archive_dir=openssl-3.1.2
-archive_url=https://github.com/openssl/openssl/releases/download/openssl-3.1.2/openssl-3.1.2.tar.gz
+archive_url=https://github.com/openssl/openssl/releases/download/openssl-3.1.2/${archive_dir}.tar.gz
 archive_ext="${archive_url//*.}"
-cwd="$PWD"/openssl-build-script
+cwd="${PWD}"/openssl-build-script
 install_dir=/usr
 ssl_dir=/usr/lib/ssl
-cert_dir=$ssl_dir/certs
+cert_dir=${ssl_dir}/certs
 pem_filename=cacert.pem
-pem_output=$cert_dir/cacert.pem
+pem_output=${cert_dir}/cacert.pem
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
 repo=https://github.com/slyfox1186/script-repo
 
 printf "\n%s\n%s\n\n" \
-    "OpenSSL Build Script - v$script_ver" \
+    "OpenSSL Build Script - v${script_ver}" \
     '==============================================='
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ ! -d "$cwd" ]; then
-    mkdir -p "$cwd"
+if [ ! -d "${cwd}" ]; then
+    mkdir -p "${cwd}"
 fi
 
 #
@@ -70,8 +70,8 @@ export {CFLAGS,CXXFLAGS}='-g -O2 -flto -ffunction-sections -fdata-sections -pipe
 
 PATH="\
 /usr/lib/ccache:\
-$HOME/.cargo/bin:\
-$HOME/.local/bin:\
+${HOME}/.cargo/bin:\
+${HOME}/.local/bin:\
 /usr/local/sbin:\
 /usr/local/bin:\
 /usr/sbin:\
@@ -110,13 +110,13 @@ exit_fn()
 {
     printf "\n%s\n\n%s\n\n" \
         'Make sure to star this repository to show your support!' \
-        "$repo"
+        "${repo}"
     exit 0
 }
 
 fail_fn()
 {
-    printf "%s\n\n" "$1"
+    printf "%s\n\n" "${1}"
     exit 1
 }
 
@@ -132,8 +132,8 @@ cleanup_fn()
         '[2] No'
     read -p 'Your choices are (1 or 2): ' choice
 
-    case "$choice" in
-        1)      sudo rm -fr "$cwd";;
+    case "${choice}" in
+        1)      sudo rm -fr "${cwd}";;
         2)      clear;;
         *)
                 clear
@@ -158,13 +158,13 @@ for i in ${pkgs[@]}
 do
     missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
 
-    if [ -z "$missing_pkg" ]; then
-        missing_pkgs+=" $i"
+    if [ -z "${missing_pkg}" ]; then
+        missing_pkgs+=" ${i}"
     fi
 done
 
-if [ -n "$missing_pkgs" ]; then
-    sudo apt -y install $missing_pkgs
+if [ -n "${missing_pkgs}" ]; then
+    sudo apt -y install ${missing_pkgs}
     clear
 fi
 unset i missing_pkgs
@@ -173,39 +173,39 @@ unset i missing_pkgs
 # INSTALL CA CERTS FROM CURL'S OFFICIAL WEBSITE
 #
 
-if [ ! -f "$cert_dir/$pem_filename" ]; then
+if [ ! -f "${cert_dir}/${pem_filename}" ]; then
     printf "%s\n%s\n\n" \
         'Download the latest security certificate' \
         '================================================'
-    curl -A "$user_agent" -Lso "$cwd/$pem_filename" "https://curl.se/ca/$pem_filename"
-    sudo mv -f "$cwd/$pem_filename" "$cert_dir/$pem_filename"
+    curl -A "${user_agent}" -Lso "${cwd}/${pem_filename}" "https://curl.se/ca/${pem_filename}"
+    sudo mv -f "${cwd}/${pem_filename}" "${cert_dir}/${pem_filename}"
 fi
 
 #
 # DOWNLOAD THE ARCHIVE FILE
 #
 
-archive_name="$archive_dir.tar.$archive_ext"
+archive_name="${archive_dir}.tar.${archive_ext}"
 
-if [ ! -f "$cwd/$archive_name" ]; then
-    curl -A "$user_agent" -Lso "$cwd/$archive_name" "$archive_url"
+if [ ! -f "${cwd}/${archive_name}" ]; then
+    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
 fi
 
 #
 # CREATE OUTPUT DIRECTORY
 #
 
-if [ -d "$cwd/$archive_dir" ]; then
-    sudo rm -fr "$cwd/$archive_dir"
+if [ -d "${cwd}/${archive_dir}" ]; then
+    sudo rm -fr "${cwd}/${archive_dir}"
 fi
-mkdir -p "$cwd/$archive_dir/build"
+mkdir -p "${cwd}/${archive_dir}/build"
 
 #
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -zxf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
-    printf "%s\n\n" "Failed to extract: $cwd/$archive_name"
+if ! tar -zxf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
+    printf "%s\n\n" "Failed to extract: ${cwd}/${archive_name}"
     exit 1
 fi
 
@@ -213,9 +213,16 @@ fi
 # BUILD PROGRAM FROM SOURCE
 #
 
-cd "$cwd/$archive_dir/build" || exit 1
-../Configure --prefix=/usr                    \
-             --openssldir="$ssl_dir"          \
+clear
+printf "%s\n%s\n\n" \
+    'Running: Configure' \
+    '===================================='
+sleep 2
+
+cd "${cwd}/${archive_dir}/build" || exit 1
+
+../Configure --prefix="${install_dir}"        \
+             --openssldir="${ssl_dir}"        \
              --with-rand-seed=os              \
              --with-zlib-include=/usr/include \
              --with-zlib-lib=/usr/lib         \
@@ -226,21 +233,48 @@ cd "$cwd/$archive_dir/build" || exit 1
              enable-trace                     \
              threads                          \
              zlib
+
+printf "\n%s\n%s\n\n" \
+    "Running: make -j$(nproc --all)" \
+    '===================================='
+sleep 2
+
 make "-j$(nproc --all)"
+
+printf "\n%s\n%s\n\n" \
+    'Running: sudo make install_sw' \
+    '===================================='
+sleep 2
+
 if ! sudo make install_sw; then
-    fail_fn 'Failed to execute: sudo make install'
+    fail_fn 'Failed to execute: sudo make install_sw'
 fi
+
+printf "\n%s\n%s\n\n" \
+    'Running: sudo make install_fips' \
+    '===================================='
+sleep 2
 
 if ! sudo make install_fips; then
     fail_fn 'Failed to execute: sudo make install_fips'
 fi
 
+printf "\n%s\n%s\n\n" \
+    'Running: sudo openssl fipsinstall' \
+    '===================================='
+sleep 2
+
 # REQUIRED FOR FIPS FUNCTIONALITY TO WORK
 sudo openssl fipsinstall
 
+printf "\n%s\n%s\n\n" \
+    "Running: sudo chmod 644 ${pem_output}" \
+    '===================================='
+sleep 2
+
 # ENSURE THE CORRECT PERMISSIONS ARE ATTACHED TO THE CUSTOM PEM FILE THAT WAS ADDED
-if [ -f "$pem_output" ]; then
-    sudo chmod 644 "$pem_output"
+if [ -f "${pem_output}" ]; then
+    sudo chmod 644 "${pem_output}"
 fi
 
 # PROMPT USER TO CLEAN UP FILES
