revert scripts to earlier versions

diff --git a/Bash/Installer Scripts/GitHub Projects/build-aria2 b/Bash/Installer Scripts/GitHub Projects/build-aria2
--- a/Bash/Installer Scripts/GitHub Projects/build-aria2
+++ b/Bash/Installer Scripts/GitHub Projects/build-aria2
@@ -1,5 +1,22 @@
-#!/Usr/bin/env bash
+#!/usr/bin/env bash
 
+##  Github Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-aria2
+##  Purpose: Build aria2 from source code
+##  Updated: 03.07.24
+##  Script version: 2.0
+##  Features:
+##            - static build
+##            - openssl backend
+##            - increased the max connections from 16 to 128
+##  Added:
+##         - display a menu by passing -h or --help as arguments to the script
+##         - build a service by passing an argument to the script
+##         - builds everything in temporary directories in the /tmp folder and removes them when done
+##         - updated Aria2 to the latest version - 1.37.0
+##         - if OpenSSL is manually installed using the build-openssl script then use its certs directory instead of the default.
+##         - build jemalloc from the latest source code
+##         - runpath to LDFLAGS
+##  Fixed: Soft linking error
 
 script_ver="2.0"
 echo "GitHub Script for building aria2 from source. Version: $script_ver"
@@ -8,8 +25,8 @@ GREEN='\033[0;32m'
 RED='\033[0;31m'
 NC='\033[0m'
 
-log() { echo -e "$GREEN[LOG]$NC $(date +'%Y-%m-%d %H:%M:%S') - $*"; }
-handle_error() { echo -e "$RED[ERROR]$NC $(date +'%Y-%m-%d %H:%M:%S') - $*"; exit 1; }
+log() { echo -e "${GREEN}[LOG]${NC} $(date +'%Y-%m-%d %H:%M:%S') - $*"; }
+handle_error() { echo -e "${RED}[ERROR]${NC} $(date +'%Y-%m-%d %H:%M:%S') - $*"; exit 1; }
 
 display_help() {
     echo "Usage: $0 [OPTION]..."
@@ -30,6 +47,7 @@ set_compiler_options() {
     export CC CFLAGS CXX CXXFLAGS
 }
 
+# Check if help argument is passed
 if [[ "$1" == "-h" || "$1" == "--help" ]]; then
     display_help
 fi
@@ -40,7 +58,7 @@ install_packages() {
     log "Attempting to install required packages..."
     apt install -y "${pkgs[@]}"
     for pkg in "${pkgs[@]}"; do
-        dpkg-query -W -f='$Status' "$pkg" 2>/dev/null | grep -q "ok installed" || handle_error "Failed to install: $pkg"
+        dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed" || handle_error "Failed to install: $pkg"
     done
     echo
     log "Installation of required packages completed."
@@ -83,7 +101,7 @@ build_libgpg_error() {
     local libgpg_error_version=$(libgpg_latest_release_version "https://gnupg.org/ftp/gcrypt/libgpg-error/")
     local libgpg_error_url="https://gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-$libgpg_error_version.tar.bz2"
     curl -Ls "$libgpg_error_url" | tar -xj
-    cd "libgpg-error-$libgpg_error_version"
+    cd "libgpg-error-${libgpg_error_version}"
     ./configure --prefix="$temp_dir/libgpg-error"
     make "-j$(nproc)" && make install
     cd ../
diff --git a/Bash/Installer Scripts/GitHub Projects/build-clang-16 b/Bash/Installer Scripts/GitHub Projects/build-clang-16
--- a/Bash/Installer Scripts/GitHub Projects/build-clang-16
+++ b/Bash/Installer Scripts/GitHub Projects/build-clang-16
@@ -1,5 +1,10 @@
-#!/Usr/bin/env bash
+#!/usr/bin/env bash
+# Shellcheck disable=sc2162,sc2317
 
+##  Github Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-clang-16
+##  Purpose: Build LLVM-16
+##  Updated: 01.30.24
+##  Script version: 1.3
 
 clear
 
@@ -8,6 +13,7 @@ if [ "$EUID" -ne 0 ]; then
     exit 1
 fi
 
+# Set global variables
 
 script_ver="1.3"
 progname="$0"
@@ -15,20 +21,27 @@ cwd="$PWD/clang-16-build-script"
 install_prefix="/usr/local"
 pc_type="x86_64-linux-gnu"
 web_repo="https://github.com/slyfox1186/script-repo"
+debug="OFF" # CHANGE THIS VARIABLE TO "ON" FOR HELP WITH TROUBLESHOOTING UNEXPECTED ISSUES DURING THE BUILD
 
+# Create output directories
 mkdir -p "$cwd"
 
+# Figure out which compilers to use
 export CC="clang" CXX="clang++"
 
+# Set compiler optimization flags
 export CXXFLAGS="$CFLAGS"
 
+# Set the available cpu count for parallel processing (speeds up the build process)
 cpu_threads="$(grep --count ^processor /proc/cpuinfo 2>/dev/null || nproc --all)"
 
 export PATH="/usr/lib/ccache:$HOME/perl5/bin:$HOME/.cargo/bin:$HOME/.local/bin:/usr/local/sbin:/usr/local/cuda/bin:/usr/local/x86_64-linux-gnu/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/snap/bin"
 
 export PKG_CONFIG_PATH="/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/share/pkgconfig:/usr/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:/lib64/pkgconfig:/lib/pkgconfig"
 
-exit_fn() {
+# Create functions
+exit_fn()
+{
     printf "\n%s\n\n%s\n%s\n\n" \
         "The script has completed" \
         "Make sure to star this repository to show your support!" \
@@ -36,7 +49,8 @@ exit_fn() {
     exit 0
 }
 
-fail_fn() {
+fail_fn()
+{
     printf "\n\n%s\n\n%s\n\n%s\n\n" \
         "$1" \
         "To report a bug please visit: " \
@@ -44,7 +58,8 @@ fail_fn() {
     exit 1
 }
 
-cleanup_fn() {
+cleanup_fn()
+{
     local choice
 
     printf "%s\n\n%s\n%s\n\n" \
@@ -53,7 +68,7 @@ cleanup_fn() {
         "[2] No"
     read -p "Your choices are (1 or 2): " choice
 
-    case "$choice" in
+    case "${choice}" in
         1)      sudo rm -fr "$cwd";;
         2)      clear;;
         *)
@@ -67,16 +82,18 @@ cleanup_fn() {
     esac
 }
 
-create_soft_link_fn() {
+create_soft_link_fn()
+{
     clear
     if [ -f "$install_prefix"/bin/clang++ ] && [ ! -f "$install_prefix"/bin/clang++-16 ]; then
         if ! sudo ln -s "$install_prefix"/bin/clang++ "$install_prefix"/bin/clang++-16; then
-            printf "\n%s\n\n" "Failed to create the clang++ soft link. Line: $LINENO"
+            printf "\n%s\n\n" "Failed to create the clang++ soft link. Line: ${LINENO}"
         fi
     fi
 }
 
-show_ver_fn() {
+show_ver_fn()
+{
     printf "%s\n\n" "The installed clang version is:"
 
     if [ -f "$install_prefix"/bin/clang-16 ]; then
@@ -96,23 +113,25 @@ show_ver_fn() {
     fi
 }
 
-execute() {
-    echo "$ $*"
+execute()
+{
+    echo "$ ${*}"
 
-    if [ "$debug" = "ON" ]; then
+    if [ "${debug}" = "ON" ]; then
         if ! output="$("$@")"; then
-            notify-send -t 5000 "Failed to execute: $*" 2>/dev/null
-            fail_fn "Failed to execute: $*"
+            notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
+            fail_fn "Failed to execute: ${*}"
         fi
     else
         if ! output="$("$@" 2>&1)"; then
-            notify-send -t 5000 "Failed to execute: $*" 2>/dev/null
-            fail_fn "Failed to execute: $*"
+            notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
+            fail_fn "Failed to execute: ${*}"
         fi
     fi
 }
 
-build() {
+build()
+{
     printf "\n%s\n%s\n" \
         "Building $1 - version $2" \
         "=========================================="
@@ -128,29 +147,31 @@ build() {
 
 build_done() { echo "$2" > "$cwd/$1.done"; }
 
-download() {
+download()
+{
     dl_path="$cwd"
     dl_url="$1"
+    dl_file="${2:-"${1##*/}"}"
 
     if [[ "$dl_file" =~ tar. ]]; then
-        output_dir="$dl_file%.*"
-        output_dir="$3:-"${output_dir%.*"}"
+        output_dir="${dl_file%.*}"
+        output_dir="${3:-"${output_dir%.*}"}"
     else
-        output_dir="$3:-"${dl_file%.*"}"
+        output_dir="${3:-"${dl_file%.*}"}"
     fi
 
     target_file="$dl_path/$dl_file"
     target_dir="$dl_path/$output_dir"
 
-    if [ -f "$target_file" ]; then
+    if [ -f "${target_file}" ]; then
         echo "The file \"$dl_file\" is already downloaded."
     else
-        echo "Downloading \"$dl_url\" saving as \"$dl_file\""
-        if ! wget --show-progress -t 2 -cqO "$target_file" "$dl_url"; then
+        echo "Downloading \"${dl_url}\" saving as \"$dl_file\""
+        if ! wget --show-progress -t 2 -cqO "${target_file}" "${dl_url}"; then
             printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 10 seconds..."
             sleep 10
-            if ! wget --show-progress -t 2 -cqO "$target_file" "$dl_url"; then
-                fail_fn "The script failed to download \"$dl_file\" twice and will now exit. Line: $LINENO"
+            if ! wget --show-progress -t 2 -cqO "${target_file}" "${dl_url}"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit. Line: ${LINENO}"
             fi
         fi
         printf "\n%s\n\n" "Download completed"
@@ -163,48 +184,52 @@ download() {
     mkdir -p "$target_dir"
 
     if [ -n "$3" ]; then
-        if ! tar -zxf "$target_file" -C "$target_dir" 2>/dev/null >/dev/null; then
-            sudo rm "$target_file"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: $LINENO"
+        if ! tar -zxf "${target_file}" -C "$target_dir" 2>/dev/null >/dev/null; then
+            sudo rm "${target_file}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
         fi
     else
-        if ! tar -zxf "$target_file" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
-            sudo rm "$target_file"
-            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: $LINENO"
+        if ! tar -zxf "${target_file}" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
+            sudo rm "${target_file}"
+            fail_fn "The script failed to extract \"$dl_file\" so it was deleted. Please re-run the script. Line: ${LINENO}"
         fi
     fi
 
     printf "%s\n\n" "File extracted: $dl_file"
 
-    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: $LINENO"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir. Line: ${LINENO}"
 }
 
-git_1_fn() {
+git_1_fn()
+{
     local curl_cmd github_repo github_url
 
     github_repo="$1"
     github_url="$2"
 
-    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/$github_repo/$github_url")"; then
+    if curl_cmd="$(curl -A "$user_agent" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
         g_ver="$(echo "$curl_cmd" | jq -r ".[1].name" 2>/dev/null)"
         g_url="$(echo "$curl_cmd" | jq -r ".[1].tarball_url" 2>/dev/null)"
+        g_ver="${g_ver#Llvmorg-}"
     fi
 }
 
-git_ver_fn() {
+git_ver_fn()
+{
     local t_flag v_flag v_url
 
     v_url="$1"
     v_flag="$2"
 
-    case "$v_flag" in
+    case "${v_flag}" in
             R)      t_flag=releases;;
             T)      t_flag=tags;;
     esac
 
-    git_1_fn "$v_url" "$t_flag" 2>/dev/null
+    git_1_fn "${v_url}" "${t_flag}" 2>/dev/null
 }
 
+# Print the options available when manually running the script
 
 pkgs=(
     autoconf autoconf-archive automake autopoint binutils binutils-dev bison
@@ -214,10 +239,10 @@ pkgs=(
 
 for i in ${pkgs[@]}
 do
-    missing_pkg="$(sudo dpkg -l | grep -o "$i")"
+    missing_pkg="$(sudo dpkg -l | grep -o "${i}")"
 
-    if [ -z "$missing_pkg" ]; then
-        missing_pkgs+=" $i"
+    if [ -z "${missing_pkg}" ]; then
+        missing_pkgs+=" ${i}"
     fi
 done
 
@@ -228,25 +253,28 @@ else
     printf "%s\n" "The APT packages are already installed"
 fi
 
+# Refresh librarys
 
 sudo ldconfig 2>/dev/null
 
+# Begin building clang
 
 clear
-box_out_banner() {
+box_out_banner()
+{
     input_char=$(echo "$@" | wc -c)
-    line=$(for i in $(seq 0 $input_char); do printf "-"; done)
+    line=$(for i in $(seq 0 ${input_char}); do printf "-"; done)
     tput bold
     line="$(tput setaf 3)$line"
-    space=$line//-/ 
+    space=${line//-/ }
     echo " $line"
-    printf "|" ; echo -n "$space" ; printf "%s\n" "|";
+    printf "|" ; echo -n "${space}" ; printf "%s\n" "|";
     printf "| " ;tput setaf 4; echo -n "$@"; tput setaf 3 ; printf "%s\n" " |";
-    printf "|" ; echo -n "$space" ; printf "%s\n" "|";
+    printf "|" ; echo -n "${space}" ; printf "%s\n" "|";
     echo " $line"
     tput sgr 0
 }
-box_out_banner "Clang Build Script - version $script_ver"
+box_out_banner "Clang Build Script - version ${script_ver}"
 
 if build "llvm" "16.0.6"; then
     download "https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/llvm-project-16.0.6.src.tar.xz" "llvm-16.0.6.tar.gz"
@@ -285,12 +313,17 @@ if build "llvm" "16.0.6"; then
     execute sudo ninja -C build install
 fi
 
+# Ldconfig must be run next in order to update file changes or the magick command will not work
 sudo ldconfig 2>/dev/null
 
+# Create a soft link from clang++ to clang++-16
 create_soft_link_fn
 
+# Show the newly installed magick version
 show_ver_fn
 
+# Prompt the user to clean up the build files
 cleanup_fn
 
+# Show exit message
 exit_fn
