Update build-openssl-lts

diff --git a/Bash/Installer Scripts/GitHub Projects/build-openssl-lts b/Bash/Installer Scripts/GitHub Projects/build-openssl-lts
--- a/Bash/Installer Scripts/GitHub Projects/build-openssl-lts
+++ b/Bash/Installer Scripts/GitHub Projects/build-openssl-lts
@@ -1,11 +1,17 @@
-#!/Usr/bin/env bash
+#!/usr/bin/env bash
+# Shellcheck disable=sc2068,sc2086,sc2162,sc2317
 
+# Purpose: build the latest stable release of openssl from the official website's source code
+# Enabled features: fips, rc5, shared, tfo, threads, zlib
+# Version: 2.1
 
+# Check for root/and exit if detected
 if [ "$EUID" -ne 0 ]; then
     echo "You must run this script with root or sudo."
     exit 1
 fi
 
+# Function to print a message and exit
 exit_fn() {
     printf "\n%s\n\n%s\n\n" \
         "Make sure to star this repository to show your support!" \
@@ -13,6 +19,7 @@ exit_fn() {
     exit 0
 }
 
+# Function to print an error message and exit
 fail_fn() {
     printf "\n\n%s\n\n%s\n\n%s\n\n" \
         "$1" \
@@ -21,6 +28,7 @@ fail_fn() {
     exit 1
 }
 
+# Function to prompt user for cleanup
 cleanup_fn() {
     local choice
 
@@ -43,12 +51,14 @@ cleanup_fn() {
     esac
 }
 
+# Function to display the openssl version
 show_ver_fn() {
     clear
     show_ver="$(/usr/local/ssl/bin/openssl version -a | grep -Eo "[0-9\.]?+" | head -n1)"
     printf "%s\n" "The updated OpenSSL version is: $show_ver"
 }
 
+# Function to install required packages on arch linux
 pkgs_arch_fn() {
     local missing_pkgs
 
@@ -71,6 +81,7 @@ pkgs_arch_fn() {
     fi
 }
 
+# Function to install required packages on debian/ubuntu
 pkgs_fn() {
     local missing_packages available_packages unavailable_packages
 
@@ -83,17 +94,20 @@ pkgs_fn() {
         zlib1g-dev
     )
 
+# Initialize arrays for missing, available, and unavailable packages
     missing_packages=()
     available_packages=()
     unavailable_packages=()
 
+# Loop through the array to find missing packages
     for pkg in "${pkgs[@]}"
     do
-        if ! dpkg-query -W -f='$Status' "$pkg" 2>/dev/null | grep -q "ok installed"; then
+        if ! dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed"; then
             missing_packages+=("$pkg")
         fi
     done
 
+# Check availability of missing packages and categorize them
     for pkg in "${missing_packages[@]}"
     do
         if apt-cache show "$pkg" > /dev/null 2>&1; then
@@ -103,16 +117,21 @@ pkgs_fn() {
         fi
     done
 
-        echo "Unavailable packages: $unavailable_packages[*]"
+# Print unavailable packages
+    if [[ "${#Unavailable_packages[@]}" -gt 0 ]]; then
+        echo "Unavailable packages: ${unavailable_packages[*]}"
     fi
 
-        echo "Installing available missing packages: $available_packages[*]"
+# Install available missing packages
+    if [[ "${#Available_packages[@]}" -gt 0 ]]; then
+        echo "Installing available missing packages: ${available_packages[*]}"
         apt install "${available_packages[@]}"
     else
         printf "%s\n\n" "No missing packages to install or all missing packages are unavailable."
     fi
 }
 
+# Function to check and create directories
 create_dir() {
     local dir="$1"
     if [ ! -d "$dir" ]; then
@@ -120,6 +139,7 @@ create_dir() {
     fi
 }
 
+# Function to download a file
 download_file() {
     local url="$1"
     local output_file="$2"
@@ -128,6 +148,7 @@ download_file() {
     fi
 }
 
+# Function to extract an archive
 extract_archive() {
     local archive_file="$1"
     local target_dir="$2"
@@ -142,6 +163,7 @@ add_to_path() {
     ln -sf "/usr/local/ssl/bin/openssl" "/usr/local/bin"
 }
 
+# Function to configure and build openssl
 build_openssl() {
     cd "$1" || exit 1
     ../Configure linux-x86_64-clang \
@@ -176,6 +198,7 @@ build_openssl() {
     fi
 }
 
+# Function to install ca certificates from curl's website
 install_ca_certs() {
     printf "\n%s\n%s\n\n" \
         "Install the latest security certificate from cURL's website" \
@@ -199,28 +222,33 @@ install_ca_certs() {
     update-ca-certificates
 }
 
+# Function to update the linker library search path
 update_ldconfig() {
     echo "$install_dir/lib64" | tee "/etc/ld.so.conf.d/openssl-compiled.conf" >/dev/null
     ldconfig "/usr/local/ssl/lib64"
 }
 
+# Set script variables
 script_ver="2.1"
 openssl_ver="$(curl -s https://www.openssl.org/source/ | grep -o "openssl-3.1\.[4-9]\{1,2\}" | head -n 1)"
 archive_url="https://www.openssl.org/source/$openssl_ver.tar.gz"
-archive_ext="$archive_url//*./"
+archive_ext="${archive_url//*./}"
 archive_name="$openssl_ver.tar.$archive_ext"
 cwd="$PWD/openssl-build-script"
 install_dir="/usr/local/ssl"
 ssl_dir="$install_dir"
 cert_dir="$install_dir/certs"
 
+# Print header
 printf "%s\n%s\n\n" \
     "OpenSSL LTS Build Script - v$script_ver" \
     "==============================================="
 sleep 2
 
+# Create output directory
 create_dir "$cwd"
 
+# Detect os and version
 find_lsb_release="$(find /usr/bin/ -type f -name "lsb_release")"
 
 if [ -f "/etc/os-release" ]; then
@@ -233,6 +261,7 @@ else
     fail_fn "Failed to define the \$OS and/or \$VER variables. Line: $LINENO"
 fi
 
+# If ubuntu is the current os, softlink for openssl to function
 ubuntu_os_ver() {
     ln -sf "/usr/lib64/libcrypto.so.3" "/usr/lib64/libcrypto.so"
 }
@@ -241,28 +270,39 @@ case "$OS" in
     Ubuntu) ubuntu_os_ver ;;
 esac
 
+# Install required packages based on os
 if [[ "$OS" == "Arch" ]]; then
     pkgs_arch_fn
 else
     pkgs_fn
 fi
 
+# Download the archive file
 download_file "$archive_url" "$cwd/$archive_name"
 
+# Create output directory for extraction
 create_dir "$cwd/$openssl_ver/build"
 
+# Extract archive files
 extract_archive "$cwd/$archive_name" "$cwd/$openssl_ver"
 
+# Build openssl from source
 build_openssl "$cwd/$openssl_ver/build"
 
+# Install ca certificates from curl's website
 install_ca_certs
 
+# Update linker library search path
 update_ldconfig
 
+# Add openssl bin to user's ~/.bashrc file
 add_to_path
 
+# Prompt user to clean up files
 cleanup_fn
 
+# Display updated openssl version
 show_ver_fn
 
+# Exit with message
 exit_fn
