Update build-libhwy

diff --git a/Bash/Installer Scripts/GitHub Projects/build-libhwy b/Bash/Installer Scripts/GitHub Projects/build-libhwy
--- a/Bash/Installer Scripts/GitHub Projects/build-libhwy
+++ b/Bash/Installer Scripts/GitHub Projects/build-libhwy
@@ -66,6 +66,7 @@ export {CFLAGS,CXXFLAGS}='-g -O2 -march=native'
 CPPFLAGS="-I${workspace}/include -I/usr/local/include -I/usr/include"
 LDFLAGS="-L${workspace}/lib64 -L${workspace}/lib -L${workspace}/lib/x86_64-linux-gnu -L/usr/local/lib64"
 LDFLAGS+=' -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib64 -L/usr/lib -L/lib64 -L/lib'
+export MAKEFLAGS="-j $(grep --count ^processor /proc/cpuinfo)"
 export CPPFLAGS LDFLAGS
 
 #
@@ -252,6 +253,40 @@ download()
     cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}. Line: ${LINENO}"
 }
 
+download_git()
+{
+    local dl_path dl_url dl_file target_dir
+
+    dl_path="${packages}"
+    dl_url="${1}"
+    dl_file="${2:-"${1##*/}"}"
+    dl_file="${dl_file//\./-}"
+    target_dir="${dl_path}/${dl_file}"
+
+    if [ -n "${3}" ]; then
+        output_dir="${dl_path}/${3}"
+        target_dir="${output_dir}"
+    fi
+
+    if [ -d "${target_dir}" ]; then
+        sudo rm -fr "${target_dir}"
+    fi
+
+    echo "Downloading ${dl_url} as ${dl_file}"
+
+    if ! git clone -q "${dl_url}" "${target_dir}"; then
+        printf "\n%s\n\n" "The script failed to clone the directory \"${target_dir}\" and will try again in 10 seconds..."
+        sleep 10
+        if ! git clone -q "${dl_url}" "${target_dir}"; then
+            fail_fn "The script failed to clone the directory \"${target_dir}\" twice and will now exit the buildLine: ${LINENO}"
+        fi
+    else
+        printf "%s\n\n" "Successfully cloned: ${target_dir}"
+    fi
+
+    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}. Line: ${LINENO}"
+}
+
 build()
 {
     printf "\n%s\n%s\n" \
@@ -281,20 +316,115 @@ installed()
     return $(dpkg-query -W -f '${Status}\n' "${1}" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}')
 }
 
+find_lsb_release="$(sudo find /usr -type f -name 'lsb_release')"
+
+if [ -f /etc/os-release ]; then
+    source /etc/os-release
+    OS_TMP="$NAME"
+    VER_TMP="$VERSION_ID"
+    CODENAME="$VERSION_CODENAME"
+    OS="$(echo "${OS_TMP}" | awk '{print $1}')"
+    VER="$(echo "${VER_TMP}" | awk '{print $1}')"
+elif [ -n "${find_lsb_release}" ]; then
+    OS="$(lsb_release -d | awk '{print $2}')"
+    VER="$(lsb_release -r | awk '{print $2}')"
+else
+    fail_fn "Failed to define the \$OS and/or \$VER variables. Line: ${LINENO}"
+fi
+
 #
-# INSTALL REQUIRED APT PACKAGES
+# INSTALL REQUIRED APT/PACMAN PACKAGES
 #
 
-pkgs=(autoconf autoconf-archive autogen automake autotools-dev
-      build-essential ccache cmake curl libgtest-dev libtool
-      libtool-bin m4 ninja-build pkg-config)
-
-for pkg in ${pkgs[@]}
-do
-    if ! installed "${pkg}"; then
-        missing_pkgs+=" ${pkg}"
+python2_arch_fn()
+{
+    if build 'python2' 'git'; then
+        download_git 'https://aur.archlinux.org/python2.git' 'python2-AUR'
+            makepkg -si --noconfirm
+        build_done 'python2' 'git'
     fi
-done
+}
+
+python2_setuptools_arch_fn()
+{
+    if build 'python2-setuptools' 'git'; then
+        download_git 'https://aur.archlinux.org/python2-setuptools.git' 'python2-setuptools-AUR'
+            makepkg -si --noconfirm
+        build_done 'python2-setuptools' 'git'
+    fi
+}
+
+jq_arch_fn()
+{
+    if build 'jq' 'git'; then
+        download_git 'https://aur.archlinux.org/jq-git.git' 'jq-AUR'
+            makepkg -si --noconfirm
+        build_done 'jq' 'git'
+    fi
+}
+
+pkgs_arch_fn()
+{
+    pkgs=(autoconf autoconf-archive autogen automake xorg-util-macros autogen
+          base-devel ccache cmake curl git gtest libtool m4 ninja openssl
+          pkg-config python python-pip python-setuptools qt6-base)
+
+    if [ -f /var/lib/pacman/db.lck ]; then
+        sudo rm /var/lib/pacman/db.lck
+    fi
+
+    for i in ${pkgs[@]}
+    do
+        missing_pkg="$(sudo pacman -Qi | grep -o "${i}")"
+
+        if [ -z "${missing_pkg}" ]; then
+            missing_pkgs+=" ${i}"
+        fi
+    done
+
+    if [ -n "${missing_pkgs}" ]; then
+         sudo pacman -S --noconfirm ${missing_pkgs}
+    fi
+
+    # INSTALL JQ FROM AUR
+    python2_arch_fn
+    python2_setuptools_arch_fn
+    jq_arch_fn
+
+    rm_pip_lock="$(sudo find /usr/lib/python3* -type f -name 'EXTERNALLY-MANAGED')"
+    if [ -n "${rm_pip_lock}" ]; then
+        sudo rm "${rm_pip_lock}"
+    fi
+
+    # INSTALL PYTHON PIP PACKAGES
+    pip uninstall -q -y setuptools 2>/dev/null
+    sudo pip install -q --no-input setuptools 2>/dev/null
+}
+
+pkgs_fn()
+{
+    pkgs=(autoconf autoconf-archive autogen automake autotools-dev
+          build-essential ccache cmake curl libgtest-dev libtool
+          libtool-bin m4 ninja-build pkg-config)
+
+    for pkg in ${pkgs[@]}
+    do
+        if ! installed "${pkg}"; then
+            missing_pkgs+=" ${pkg}"
+        fi
+    done
+
+    if [ -n "${missing_pkgs}" ]; then
+        sudo apt -y install ${missing_pkgs}
+        sudo apt -y autoremove
+        clear
+    fi
+}
+
+case "${OS}" in
+    Arch)   pkgs_arch_fn;;
+    *)      pkgs_fn;;
+esac
 
 printf "\n%s\n%s\n" \
     'Installing required apt packages' \
