Update build-aria2-raspi

diff --git a/Bash/Pi-Hole/build-aria2-raspi b/Bash/Pi-Hole/build-aria2-raspi
--- a/Bash/Pi-Hole/build-aria2-raspi
+++ b/Bash/Pi-Hole/build-aria2-raspi
@@ -3,19 +3,20 @@
 clear
 
 #
-# SET PROGRAM NAME + VERSION
+# SET VARIABLES
 #
 
-script_ver=1.0
+script_ver=1.1
 archive_dir=aria2-1.36.0
 archive_url=https://github.com/aria2/aria2/releases/download/release-1.36.0/aria2-1.36.0.tar.gz
 archive_ext="${archive_url//*.}"
 cwd="$PWD"/aria2-build-script
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
+repo=https://github.com/slyfox1186/script-repo
 
 printf "\n%s\n%s\n\n" \
-    "Aria2 Build Script - v$script_ver" \
-    '==============================================='
+    "Aria2 Build Script (Raspberry Pi Edition) v$script_ver" \
+    '======================================================'
 
 #
 # CREATE OUTPUT DIRECTORY
@@ -43,20 +44,25 @@ export {CFLAGS,CXXFLAGS}='-g -O3 -march=native'
 
 exit_fn()
 {
-    printf "\n%s\n\n" 'The script has completed.'
+    printf "\n%s\n\n%s\n\n" \
+        'Make sure to star this repository to show your support!' \
+        "$repo"
     exit 0
 }
 
-
 fail_fn()
 {
-    printf "%s\n\n" "$1"
+    printf "\n%s\n\n%s\n\n" \
+        "$1" \
+        "To report a bug create an issue here: $repo/issues"
     exit 1
 }
 
 cleanup_fn()
 {
     local choice
+    
+    unset archive_dir archive_ext archive_name archive_url CC CXX i missing_pkg missing_pkgs pc_type pem_target pkgs script_ver
 
     if sudo dpkg -l | grep aria2 &>/dev/null; then
         sudo apt -y remove aria2
@@ -97,7 +103,7 @@ pkgs=(autoconf autogen automake build-essential ca-certificates ccache clang cur
 
 for i in ${pkgs[@]}
 do
-    missing_pkg="$(dpkg -l | grep $i)"
+    missing_pkg="$(dpkg -l | grep "$i")"
 
     if [ -z "$missing_pkg" ]; then
         missing_pkgs+=" $i"
@@ -141,7 +147,7 @@ mkdir -p "$cwd/$archive_dir/build"
 # EXTRACT ARCHIVE FILES
 #
 
-if ! tar -xf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
+if ! tar -zxf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
     printf "%s\n\n" "Failed to extract: $cwd/$archive_name"
     exit 1
 fi
@@ -178,12 +184,15 @@ if ! sudo make install; then
 fi
 
 #
-# CREATE SOFT LINK
+# CREATE SOFT LINKS
 #
 
 if [ -f "/usr/local/bin/$pc_type-aria2c" ]; then
     sudo ln -sf /usr/local/bin/"$pc_type"-aria2c /usr/local/bin/aria2c
 fi
 
-sudo rm -fr "$cwd"
-unset archive_dir archive_ext archive_name archive_url CC CXX i missing_pkg missing_pkgs pc_type pem_target pkgs script_ver
+# PROMPT USER TO CLEAN UP FILES
+cleanup_fn
+
+# SHOW EXIT MESSAGE
+exit_fn
