revert files mistakenly update with bad code

diff --git a/Bash/Installer Scripts/ImageMagick/build-magick b/Bash/Installer Scripts/ImageMagick/build-magick
--- a/Bash/Installer Scripts/ImageMagick/build-magick
+++ b/Bash/Installer Scripts/ImageMagick/build-magick
@@ -1,21 +1,50 @@
 #!/usr/bin/env bash
+# shellcheck disable=SC1091,SC2000,SC2046,SC2066,SC2068,SC2086,SC2119,SC2162,SC2181,SC2206
 
+##  Script Version: 1.1
+##  Updated: 02.20.24
+##  GitHub: https://github.com/slyfox1186/imagemagick-build-script
+##  Purpose: Build ImageMagick 7 from the source code obtained from ImageMagick's official GitHub repository
+##  Function: ImageMagick is the leading open-source command line image processor. It can blur, sharpen, warp,
+##            reduce total file size, ect... The possibilities are vast
+##  Method: The script will search GitHub for the latest released version and upon execution will import the
+##            information into the script.
+##  Added:
+##          - Ubuntu OS support for versions, 22.04 23.04, 23.10, 24.04
+##          - Debian OS support for versions, 11 & 12
+##          - A browser user-agent string to the curl command
+##          - A CPPFLAGS variable to ImageMagick's configure script
+##          - A case command to determine the required libtool version based on the active OS
+##          - Autotrace for Ubuntu (18/20/22).04 and Debian 10/11
+##          - LCMS Support
+##          - Deja-Vu Fonts
+##          - APT package
+##  Fixed:
+##          - error with the pkg-config location when building ImageMagick
+##          - error in the variable PKG_CONFIG_PATH
+##  Removed:
+##          - unnecessary commands in imagemagick's configure script
 
 if [[ "$EUID" -ne 0 ]]; then
     echo "This script must be run with root/sudo"
     exit 1
 fi
 
+# SET GLOBAL VARIABLES
 script_ver=1.1
 cwd="$PWD/magick-build-script"
 packages="$cwd/packages"
 workspace="$cwd/workspace"
 regex_string='(rc|RC|Rc|rC|alpha|beta|master|pre)+[0-9]*$'
+debug=OFF # CHANGE THIS VARIABLE TO "ON" FOR HELP WITH TROUBLESHOOTING UNEXPECTED ISSUES DURING THE BUILD
 
+# Pre-defined color variables
 RED='\033[0;31m'
 GREEN='\033[0;32m'
 YELLOW='\033[0;33m'
+NC='\033[0m' # No Color
 
+# ANNOUNCE THE BUILD HAS BEGUN
 box_out_banner_header() {
     input_char=$(echo "$@" | wc -c)
     line=$(for i in $(seq 0 $input_char); do printf "-"; done)
@@ -31,26 +60,31 @@ box_out_banner_header() {
 }
 box_out_banner_header "ImageMagick Build Script v$script_ver"
 
+# CREATE OUTPUT DIRECTORIES
 mkdir -p "$packages" "$workspace"
 
+# SET THE COMPILERS TO USE AND THE COMPILER OPTIMIZATION FLAGS
 CC=gcc
 CXX=g++
 CFLAGS="-g -O3 -pipe -march=native"
 CXXFLAGS="-g -O3 -pipe -march=native"
 export CC CFLAGS CXX CXXFLAGS
 
+# SET THE AVAILABLE CPU COUNT FOR PARALLEL PROCESSING (SPEEDS UP THE BUILD PROCESS)
 if [[ -f /proc/cpuinfo ]]; then
     cpu_threads=$(grep --count ^processor /proc/cpuinfo)
 else
     cpu_threads=$(nproc --all)
 fi
 
+# SET THE PATH
 if [[ -d /usr/lib/ccache/bin ]]; then
     ccache_dir=/usr/lib/ccache/bin
 else
     ccache_dir=/usr/lib/ccache
 fi
 
+# Set the path variable
 PATH="\
 $ccache_dir:\
 $workspace/bin:\
@@ -64,6 +98,7 @@ $HOME/.local/bin:\
 "
 export PATH
 
+# Set the pkg_config_path variable
 PKG_CONFIG_PATH="\
 $workspace/lib64/pkgconfig:\
 $workspace/lib/x86_64-linux-gnu/pkgconfig:\
@@ -85,26 +120,26 @@ export PKG_CONFIG_PATH
 
 exit_fn() {
     echo
-    echo -e "$GREEN[INFO]$NC Make sure to $YELLOWstar$NC this repository to show your support!"
-    echo -e "$GREEN[INFO]$NC https://github.com/slyfox1186/script-repo"
+    echo -e "${GREEN}[INFO]${NC} Make sure to ${YELLOW}star${NC} this repository to show your support!"
+    echo -e "${GREEN}[INFO]${NC} https://github.com/slyfox1186/script-repo"
     echo
     exit 0
 }
 
 fail() {
     echo
-    echo -e "$RED[ERROR]$NC $1\\n"
-    echo -e "$GREEN[INFO]$NC For help or to report a bug create an issue at: https://github.com/slyfox1186/script-repo/issues"
+    echo -e "${RED}[ERROR]${NC} $1\\n"
+    echo -e "${GREEN}[INFO]${NC} For help or to report a bug create an issue at: https://github.com/slyfox1186/script-repo/issues"
     echo
     exit 1
 }
 
 log() {
-    echo -e "$GREEN[INFO]$NC $1"
+    echo -e "${GREEN}[INFO]${NC} $1"
 }
 
 warn() {
-    echo -e "$YELLOW[WARNING]$NC $1"
+    echo -e "${YELLOW}[WARNING]${NC} $1"
 }
 
 cleanup() {
@@ -148,7 +183,7 @@ execute() {
 
 build() {
     echo
-    echo -e "$GREENBuilding $YELLOW$1$NC - $GREENversion $YELLOW$2$NC"
+    echo -e "${GREEN}Building ${YELLOW}$1${NC} - ${GREEN}version ${YELLOW}$2${NC}"
     echo "=========================================="
 
     if [[ -f "$packages/$1.done" ]]; then
@@ -167,6 +202,7 @@ build_done() {
 download() {
     path="$packages"
     url="$1"
+    archive="${2:-"${1##*/}"}"
 
     if [[ "$archive" =~ tar. ]]; then
         output_dir="${archive%.*}"
@@ -230,10 +266,12 @@ git_caller() {
 
 git_clone() {
     local repo_url="$1"
+    local repo_name="${2:-"${1##*/}"}"
     local repo_name="${repo_name//\./-}"
     local target_directory="$packages/$repo_name"
     local version
 
+    # Try to get the latest tag
     version=$(git ls-remote --tags "$repo_url" |
               awk -F'/' '/\/v?[0-9]+\.[0-9]+(\.[0-9]+)?(-[0-9]+)?(\^\{\})?$/ {
                   tag = $3;
@@ -245,6 +283,7 @@ git_clone() {
               head -n1
          )
 
+    # If no tags found, use the latest commit hash as the version
     if [[ -z "$version" ]]; then
         version=$(git ls-remote "$repo_url" |
                   grep "HEAD" |
@@ -258,9 +297,10 @@ git_clone() {
     if [[ ! "$version" == "$store_prior_version" ]]; then
         [[ "$recurse_flag" -eq 1 ]] && recurse="--recursive"
         [[ -d "$target_directory" ]] && rm -fr "$target_directory"
+        # Clone the repository
         if ! git clone --depth 1 $recurse -q "$repo_url" "$target_directory"; then
             echo
-            echo -e "$RED[ERROR]$NC Failed to clone \"$target_directory\". Second attempt in 10 seconds..."
+            echo -e "${RED}[ERROR]${NC} Failed to clone \"$target_directory\". Second attempt in 10 seconds..."
             echo
             sleep 10
             if ! git clone --depth 1 $recurse -q "$repo_url" "$target_directory"; then
@@ -281,6 +321,7 @@ show_version() {
     magick -version 2>/dev/null || fail "Failure to execute the command: magick -version. Line: $LINENO"
 }
 
+# Parse each git repoitory to find the latest release version number for each program
 gnu_repo() {
     local url="$1"
     version=$(curl -sS "$url" | grep -oP '[a-z]+-\K(([0-9\.]*[0-9]+)){2,}' | sort -rV | head -n1)
@@ -292,7 +333,9 @@ github_repo() {
     local git_url="$2"
     version=""
 
+    # Fetch GitHub tags page
     while [ $count -le 10 ]; do
+        # Apply case-insensitive matching for RC versions to exclude them
         version=$(curl -fsSL "https://github.com/$git_repo/$git_url" |
                   grep -oP 'href="[^"]*/tags/[^"]*\.tar\.gz"' |
                   grep -oP '\/tags\/\K(v?[\w.-]+?)(?=\.tar\.gz)' |
@@ -301,13 +344,16 @@ github_repo() {
                   sed 's/^v//'
              )
 
+        # Check if a non-RC version was found
         if [[ -n "$version" ]]; then
             break
         else
+            # Increment the count if no non-RC match is found
             ((count++))
         fi
     done
 
+    # Handle case where no non-RC version is found after max attempts
     [[ -z "$version" ]] && fail "No matching version found without RC/rc suffix."
 }
 
@@ -321,10 +367,13 @@ gitlab_freedesktop_repo() {
     do
         if curl_results=$(curl -m 10 -sSL "https://gitlab.freedesktop.org/api/v4/projects/$repo/repository/tags"); then
             version=$(echo "$curl_results" | jq -r ".[$count].name")
+            version="${version#v}"
 
+            # Check if version contains "RC" and skip it
             if [[ $version =~ $regex_string ]]; then
                 ((count++))
             else
+                break # Exit the loop when a non-RC version is found
             fi
         else
             fail "Failed to fetch data from GitLab API."
@@ -344,8 +393,10 @@ gitlab_gnome_repo() {
 
     if curl_results=$(curl -sSL "https://gitlab.gnome.org/api/v4/projects/$repo/repository/$url"); then
         version=$(echo "$curl_results" | jq -r '.[0].name')
+        version="${version#v}"
     fi
 
+    # Deny installing a release candidate
     while [ $version =~ $regex_string ]; do
         if curl_results=$(curl -sSL "https://gitlab.gnome.org/api/v4/projects/$repo/repository/$url"); then
             version=$(echo "$curl_results" | jq -r ".[$count].name" | sed 's/^v//')
@@ -389,17 +440,20 @@ apt_pkgs() {
         nasm ninja-build pkg-config python3-dev yasm zlib1g-dev php-dev
 )
 
+    # Initialize arrays for missing, available, and unavailable packages
     missing_packages=()
     available_packages=()
     unavailable_packages=()
 
+    # Loop through the array to find missing packages
     for pkg in "${pkgs[@]}"
     do
-        if ! dpkg-query -W -f='$Status' "$pkg" 2>/dev/null | grep -q "ok installed"; then
+        if ! dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed"; then
             missing_packages+=("$pkg")
         fi
     done
 
+    # Check availability of missing packages and categorize them
     for pkg in "${missing_packages[@]}"
     do
         if apt-cache show "$pkg" >/dev/null 2>&1; then
@@ -409,7 +463,11 @@ apt_pkgs() {
         fi
     done
 
+    # Print unavailable packages
+    [[ "${#unavailable_packages[@]}" -gt 0 ]] && log "Unavailable packages: ${unavailable_packages[@]}"
 
+    # Install available missing packages
+    if [[ "${#available_packages[@]}" -gt 0 ]]; then
         log "Installing available missing packages: ${available_packages[@]}"
         apt install "${available_packages[@]}"
     else
@@ -427,6 +485,7 @@ download_autotrace() {
 }
 
 set_autotrace() {
+    # enable/disable autotrace
     case "$OS" in
         Ubuntu) download_autotrace
                 local flag=true
@@ -440,6 +499,7 @@ set_autotrace() {
     fi
 }
 
+# Install APT packages
     echo
     echo "Installing required APT packages"
     echo "=========================================="
@@ -465,8 +525,10 @@ get_os_version() {
     fi
 }
 
+# GET THE OS NAME
 get_os_version
 
+# DISCOVER WHAT VERSION OF LINUX WE ARE RUNNING (DEBIAN OR UBUNTU)
 case "$OS" in
     Arch)   return ;;
     Debian) debian_version ;;
@@ -474,6 +536,7 @@ case "$OS" in
     *)      fail "Could not detect the OS architecture. Line: $LINENO" ;;
 esac
 
+# INSTALL OFFICIAL IMAGEMAGICK LIBS
 find_git_repo "imagemagick/imagemagick" "1" "T"
 if build "magick-libs" "$version"; then
     if [[ ! -d "$packages/deb-files" ]]; then
@@ -488,6 +551,7 @@ if build "magick-libs" "$version"; then
     build_done "magick-libs" "$version"
 fi
 
+# INSTALL COMPOSER TO COMPILE GRAPHVIZ
 if [[ ! -f "/usr/bin/composer" ]]; then
     EXPECTED_CHECKSUM=$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')
     php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
@@ -504,6 +568,7 @@ if [[ ! -f "/usr/bin/composer" ]]; then
     rm "composer-setup.php"
 fi
 
+# BEGIN BUILDING FROM SOURCE CODE
 if build "m4" "latest"; then
     download "https://ftp.gnu.org/gnu/m4/m4-latest.tar.xz"
     execute ./configure --prefix="$workspace" \
@@ -590,6 +655,7 @@ if build "$repo_name" "$version"; then
 fi
 
 find_git_repo "ArtifexSoftware/ghostpdl-downloads" "1" "T"
+modify_version="${version#gs}"
 modify_version=$(sed -r 's/(..)(..)(.)/\1.\2.\3/' <<< "$modify_version")
 if build "ghostscript" "$version"; then
     download "https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/$version/ghostscript-$modify_version.tar.xz" "ghostscript-$modify_version.tar.xz"
@@ -600,6 +666,7 @@ if build "ghostscript" "$version"; then
     build_done "ghostscript" "$version"
 fi
 
+get_os_version # Ubuntu throws an error if you don't install png12, however Debian works without issue.
 
 find_git_repo "pnggroup/libpng" "1" "T"
 [[ "$OS" == "Ubuntu" ]] && version="1.2.59"
@@ -635,6 +702,7 @@ if build "$repo_name" "${version//\$ /}"; then
 fi
 
 find_git_repo "7950" "2"
+version="${version#VER-}"
 version1="${version//-/.}"
 if build "freetype" "$version1"; then
     download "https://gitlab.freedesktop.org/freetype/freetype/-/archive/VER-$version/freetype-VER-$version.tar.bz2" "freetype-$version1.tar.bz2"
@@ -840,6 +908,7 @@ if build "$repo_name" "${version//\$ /}"; then
     build_done "$repo_name" "$version"
 fi
 
+# Determine whether of not to install autotrace
 set_autotrace
 
 echo
@@ -894,10 +963,14 @@ if build "$repo_name" "${version//\$ /}"; then
     execute make install
 fi
 
+# LDCONFIG MUST BE RUN NEXT IN ORDER TO UPDATE FILE CHANGES OR THE MAGICK COMMAND WILL NOT WORK
 ldconfig /usr/local/lib
 
+# SHOW THE NEWLY INSTALLED MAGICK VERSION
 show_version
 
+# PROMPT THE USER TO CLEAN UP THE BUILD FILES
 cleanup
 
+# SHOW EXIT MESSAGE
 exit_fn
