code changes

diff --git a/Bash/Installer Scripts/ImageMagick/build-magick b/Bash/Installer Scripts/ImageMagick/build-magick
--- a/Bash/Installer Scripts/ImageMagick/build-magick
+++ b/Bash/Installer Scripts/ImageMagick/build-magick
@@ -120,26 +120,26 @@ export PKG_CONFIG_PATH
 
 exit_fn() {
     echo
-    echo -e "${GREEN}[INFO]${NC} Make sure to ${YELLOW}star${NC} this repository to show your support!"
-    echo -e "${GREEN}[INFO]${NC} https://github.com/slyfox1186/script-repo"
+    echo -e "$GREEN[INFO]$NC Make sure to $YELLOWstar$NC this repository to show your support!"
+    echo -e "$GREEN[INFO]$NC https://github.com/slyfox1186/script-repo"
     echo
     exit 0
 }
 
 fail() {
     echo
-    echo -e "${RED}[ERROR]${NC} $1\\n"
-    echo -e "${GREEN}[INFO]${NC} For help or to report a bug create an issue at: https://github.com/slyfox1186/script-repo/issues"
+    echo -e "$RED[ERROR]$NC $1\\n"
+    echo -e "$GREEN[INFO]$NC For help or to report a bug create an issue at: https://github.com/slyfox1186/script-repo/issues"
     echo
     exit 1
 }
 
 log() {
-    echo -e "${GREEN}[INFO]${NC} $1"
+    echo -e "$GREEN[INFO]$NC $1"
 }
 
 warn() {
-    echo -e "${YELLOW}[WARNING]${NC} $1"
+    echo -e "$YELLOW[WARNING]$NC $1"
 }
 
 cleanup() {
@@ -183,7 +183,7 @@ execute() {
 
 build() {
     echo
-    echo -e "${GREEN}Building ${YELLOW}$1${NC} - ${GREEN}version ${YELLOW}$2${NC}"
+    echo -e "$GREENBuilding $YELLOW$1$NC - $GREENversion $YELLOW$2$NC"
     echo "=========================================="
 
     if [[ -f "$packages/$1.done" ]]; then
@@ -300,7 +300,7 @@ git_clone() {
         # Clone the repository
         if ! git clone --depth 1 $recurse -q "$repo_url" "$target_directory"; then
             echo
-            echo -e "${RED}[ERROR]${NC} Failed to clone \"$target_directory\". Second attempt in 10 seconds..."
+            echo -e "$RED[ERROR]$NC Failed to clone \"$target_directory\". Second attempt in 10 seconds..."
             echo
             sleep 10
             if ! git clone --depth 1 $recurse -q "$repo_url" "$target_directory"; then
@@ -448,7 +448,7 @@ apt_pkgs() {
     # Loop through the array to find missing packages
     for pkg in "${pkgs[@]}"
     do
-        if ! dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed"; then
+        if ! dpkg-query -W -f='$Status' "$pkg" 2>/dev/null | grep -q "ok installed"; then
             missing_packages+=("$pkg")
         fi
     done
