Update build-magick

diff --git a/Bash/Installer Scripts/ImageMagick/build-magick b/Bash/Installer Scripts/ImageMagick/build-magick
--- a/Bash/Installer Scripts/ImageMagick/build-magick
+++ b/Bash/Installer Scripts/ImageMagick/build-magick
@@ -3,33 +3,34 @@
 
 #############################################################################################################
 ##
+##  Script Version: 4.1
+##  Updated: 12.29.23
+##
 ##  GitHub: https://github.com/slyfox1186/script-repo/blob/main/shell/installers/imagemagick/build-magick
 ##
 ##  Purpose: Build ImageMagick 7 from the source code obtained from the official GitHub repository
 ##
-##  Function: ImageMagick is the leading open-source command line image processor
-##            It can blur, sharpen, warp, reduce total file size, ect... The possibilities are vast and wide
+##  Function: ImageMagick is the leading open-source command line image processor. It can blur, sharpen, warp,
+##            reduce total file size, ect... The possibilities are vast
 ##
 ##  Method: The script will search GitHub for the latest released version and upon execution will import the
-##          information into the script.
+##            information into the script.
 ##
-##  Added: Debian OS support for versions, 11 & 12
-##  Added: A browser user-agent string to the curl command
-##  Added: A CPPFLAGS variable to ImageMagick's configure script
-##  Added: A case command to determine the required libtool version based on the active OS
-##  Added: Autotrace for Ubuntu (18/20/22).04 and Debian 10/11
-##  Added: LCMS Support
-##  Added: Deja-Vu Fonts
-##  Added: APT packages
+##  Added:
 ##
-##  Fixed: Incorrect pkg-config location when building ImageMagick
-##  Fixed: libjxl dependency
+##          - Debian OS support for versions, 11 & 12
+##          - A browser user-agent string to the curl command
+##          - A CPPFLAGS variable to ImageMagick's configure script
+##          - A case command to determine the required libtool version based on the active OS
+##          - Autotrace for Ubuntu (18/20/22).04 and Debian 10/11
+##          - LCMS Support
+##          - Deja-Vu Fonts
+##          - APT packages
 ##
-##  Changed: Some support libraries prefix paths to avoid installing into the system
-##
-##  Updated: 12.29.23
-##
-##  Script Version: 4.0
+##  Fixed:
+##          - removed autoreconf command from imagemagick
+##          - Incorrect pkg-config location when building ImageMagick
+##          - libjxl dependency
 ##
 #############################################################################################################
 
@@ -44,7 +45,7 @@ fi
 # SET GLOBAL VARIABLES
 #
 
-script_ver=4.0
+script_ver=4.1
 progname="${0}"
 cwd="${PWD}"/magick-build-script
 packages="${cwd}"/packages
@@ -106,7 +107,6 @@ ${HOME}/.local/bin:\
 /usr/games:\
 /snap/bin\
 "
-export PATH
 export PATH
 
 PKG_CONFIG_PATH="\
@@ -280,19 +280,27 @@ download_git()
     dl_file="${dl_file//\./-}"
     target_dir="${dl_path}/${dl_file}"
 
+    if [[ "${3}" == 'R' ]]; then
+        set_recurse='--recursive'
+    elif [ -n "${3}" ]; then
+        output_dir="${dl_path}/${3}"
+        target_dir="${output_dir}"
+    fi
+
     if [ -d "${target_dir}" ]; then
         sudo rm -fr "${target_dir}"
     fi
 
-    echo "Git cloning ${dl_url} as ${dl_file}"
-    if ! git clone -q "${dl_url}" "${target_dir}"; then
-        printf "\n%s\n\n" "The script failed to clone the git repository \"${target_dir}\" and will try again in 10 seconds..."
+    echo "Downloading ${dl_url} as ${dl_file}"
+
+    if ! git clone ${set_recurse} -q "${dl_url}" "${target_dir}"; then
+        printf "\n%s\n\n" "The script failed to clone the directory \"${target_dir}\" and will try again in 10 seconds..."
         sleep 10
-        if ! git clone -q "${dl_url}" "${target_dir}"; then
-            fail_fn "The script failed to clone \"${target_dir}\" twice and will now exit the build. Line: ${LINENO}"
+        if ! git clone ${set_recurse} -q "${dl_url}" "${target_dir}"; then
+            fail_fn "The script failed to clone the directory \"${target_dir}\" twice and will now exit the build. Line: ${LINENO}"
         fi
     else
-        printf "%s\n\n" 'Git clone successful'
+        printf "%s\n\n" "Successfully cloned: ${target_dir}"
     fi
 
     cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}. Line: ${LINENO}"
@@ -335,7 +343,6 @@ git_2_fn()
     repo="${1}"
     if curl_cmd="$(curl -A "${user_agent}" -m 10 -sSL "https://gitlab.freedesktop.org/api/v4/projects/${repo}/repository/tags")"; then
         g_ver="$(echo "${curl_cmd}" | jq -r '.[0].name')"
-        g_ver="${g_ver#VER-}"
     fi
 }
 
@@ -750,6 +757,7 @@ if build 'libwebp' 'git'; then
 fi
 
 git_ver_fn '7950' '2'
+g_ver="${g_ver#VER-}"
 g_ver1="${g_ver//-/.}"
 if build 'freetype' "${g_ver1}"; then
     download "https://gitlab.freedesktop.org/freetype/freetype/-/archive/VER-${g_ver}/freetype-VER-${g_ver}.tar.bz2" "freetype-${g_ver1}.tar.bz2"
@@ -757,13 +765,14 @@ if build 'freetype' "${g_ver1}"; then
     execute ./autogen.sh
     execute meson setup build --prefix="${workspace}"  \
                               --buildtype=release      \
-                              --default-library=both   \
+                              --default-library=static \
                               --strip                  \
                               "${extracmds[@]}"
     execute ninja "-j${cpu_threads}" -C build
     execute ninja -C build install
     build_done 'freetype' "${g_ver1}"
 fi
+ffmpeg_libraries+=('--enable-libfreetype')
 
 git_ver_fn '890' '2'
 fc_dir="${packages}/fontconfig-${g_ver}"
@@ -890,21 +899,31 @@ if build 'jemalloc' "${g_ver}"; then
     build_done 'jemalloc' "${g_ver}"
 fi
 
-git_ver_fn 'KhronosGroup/OpenCL-Headers' '1' 'T'
-if build 'opencl-headers' '2023.12.14'; then
-    download 'https://github.com/KhronosGroup/OpenCL-Headers/archive/refs/tags/v2023.12.14.tar.gz' 'opencl-headers-2023.12.14.tar.gz'
-    execute cmake                                   \
-            -S .                                    \
-            -B build                                \
-            -DCMAKE_INSTALL_PREFIX="${install_dir}" \
-            -DCMAKE_BUILD_TYPE=Release              \
-            -DBUILD_TESTING=OFF                     \
-            -DOPENCL_HEADERS_BUILD_TESTING=OFF      \
-            -DOPENCL_HEADERS_BUILD_CXX_TESTS=OFF    \
+if build 'opencl-sdk' 'git'; then
+    download_git 'https://github.com/KhronosGroup/OpenCL-SDK.git' 'opencl-sdk-git' 'R'
+    execute cmake \
+            -S .                                      \
+            -B build                                  \
+            -DCMAKE_INSTALL_PREFIX="${workspace}"     \
+            -DCMAKE_BUILD_TYPE=Release                \
+            -DBUILD_SHARED_LIBS=ON                    \
+            -DBUILD_TESTING=OFF                       \
+            -DBUILD_DOCS=OFF                          \
+            -DBUILD_EXAMPLES=OFF                      \
+            -DOPENCL_SDK_BUILD_SAMPLES=ON             \
+            -DOPENCL_SDK_TEST_SAMPLES=OFF             \
+            -DCMAKE_C_FLAGS='-g -O3 -pipe -Wno-dev'   \
+            -DCMAKE_CXX_FLAGS='-g -O3 -pipe -Wno-dev' \
+            -DOPENCL_HEADERS_BUILD_CXX_TESTS=OFF      \
+            -DOPENCL_ICD_LOADER_BUILD_SHARED_LIBS=ON  \
+            -DOPENCL_SDK_BUILD_OPENGL_SAMPLES=OFF     \
+            -DOPENCL_SDK_BUILD_SAMPLES=OFF            \
+            -DOPENCL_SDK_TEST_SAMPLES=OFF             \
+            -DTHREADS_PREFER_PTHREAD_FLAG=ON          \
             -G Ninja -Wno-dev
     execute ninja "-j${cpu_threads}" -C build
-    execute sudo ninja -C build install
-    build_done 'opencl-headers' '2023.12.14'
+    execute ninja -C build install
+    build_done 'opencl-sdk' 'git'
 fi
 
 git_ver_fn 'uclouvain/openjpeg' '1' 'R'
@@ -981,7 +1000,6 @@ aclocal_dir="$(sudo find /usr/ -type d -name 'aclocal' | sort | head -n1)"
 git_ver_fn 'ImageMagick/ImageMagick' '1' 'R'
 if build 'ImageMagick' '7.1.1-23'; then
     download 'https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.1-23.tar.gz' 'imagemagick-7.1.1-23.tar.gz'
-    execute autoreconf -fi -I "${aclocal_dir}"
     mkdir build
     cd build || exit 1
     ../configure --prefix="${install_dir}"                                    \
@@ -1030,4 +1048,3 @@ cleanup_fn
 
 # SHOW EXIT MESSAGE
 exit_fn
-
