Update build-magick

diff --git a/shell/installers/imagemagick/build-magick b/shell/installers/imagemagick/build-magick
--- a/shell/installers/imagemagick/build-magick
+++ b/shell/installers/imagemagick/build-magick
@@ -15,9 +15,9 @@
 ##  Method: The script will search GitHub for the latest released version
 ##         and upon execution, will import the info into the script for use
 ##
-##  Updated: 06.07.23
+##  Updated: 06.15.23
 ##
-##  Script Version: 1.1
+##  Script Version: 1.2
 ##
 #################################################################################
 
@@ -34,7 +34,7 @@ fi
 #
 
 progname="${0:2}"
-script_version='1.1'
+script_version='1.2'
 cwd="$PWD"/magick-build-script
 packages="$cwd"/packages
 workspace="$cwd"/workspace
@@ -183,78 +183,80 @@ get_version_fn()
 download()
 {
     dl_path="$packages"
-    dl_file="${2:-"${1#*/}"}"
+    dl_url="$1"
+    dl_file="${2:-"${1##*/}"}"
 
     if [[ "$dl_file" =~ tar. ]]; then
-        target_dir="${dl_file%.*}"
-        target_dir="${3:-"${target_dir%.*}"}"
+        output_dir="${dl_file%.*}"
+        output_dir="${3:-"${output_dir%.*}"}"
     else
-        target_dir="${3:-"${dl_file%.*}"}"
+        output_dir="${3:-"${dl_file%.*}"}"
     fi
 
-    if [ ! -f "$dl_path/$dl_file" ]; then
-        echo "Downloading $1 as $dl_file"
-        if ! curl -Lso "$dl_path/$dl_file" "$1"; then
-            printf "\n%s\n\n%s" \
-                "Failed to download: $1" \
-                'Retrying in 10 seconds'
-                sleep 10
-            if ! curl -Lso "$dl_path/$dl_file" "$1"; then
-               fail_fn "Failed to download: $1"
+    target_file="$dl_path/$dl_file"
+    target_dir="$dl_path/$output_dir"
+
+    if [ -f "$target_file" ]; then
+        echo "The file \"$dl_file\" is already downloaded."
+    else
+        echo "Downloading \"$dl_url\" saving as \"$dl_file\""
+        if ! curl -Lso "$target_file" "$dl_url"; then
+            printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 5 seconds..."
+            sleep 5
+            if ! curl -Lso "$target_file" "$dl_url"; then
+                fail_fn "The script failed to download \"$dl_file\" twice and will now exit."
             fi
-            echo 'Download Completed'
         fi
-    else
-        echo "The file is already downloaded: $dl_file"
+        echo 'Download Completed'
     fi
 
-    if [ -d "$dl_path/$target_dir" ]; then
-        sudo rm -fr "$dl_path/$target_dir"
+    if [ -d "$target_dir" ]; then
+        sudo rm -fr "$target_dir"
     fi
 
-    mkdir -p "$dl_path/$target_dir"
-
-    if [[ "$dl_file" == *'patch'* ]]; then
-        return
-    fi
+    mkdir -p "$target_dir"
 
     if [ -n "$3" ]; then
-        if ! tar -xf "$dl_path/$dl_file" -C "$dl_path/$target_dir" &>/dev/null; then
-            fail_fn "Failed to extract: $dl_file"
+        if ! tar -xf "$target_file" -C "$target_dir" 2>/dev/null >/dev/null; then
+            sudo rm "$target_file"
+            fail_fn "Failed to extract \"$dl_file\" so it was deleted. Please run the script again."
         fi
     else
-        if ! tar -xf "$dl_path/$dl_file" -C "$dl_path/$target_dir" --strip-components 1 &>/dev/null; then
-            fail_fn "Failed to extract: $dl_file"
+        if ! tar -xf "$target_file" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
+            sudo rm "$target_file"
+            fail_fn "Failed to extract \"$dl_file\" so it was deleted. Please run the script again."
         fi
     fi
 
-    echo "Extracted $dl_file"
+    echo -e "File extracted: $dl_file\\n"
 
-    cd "$dl_path/$target_dir" || fail_fn "Unable to change the working directory to: $target_dir"
+    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir"
 }
 
 download_git()
 {
+    local dl_path dl_url dl_file target_dir
+
     dl_path="$packages"
     dl_url="$1"
-    dl_file="$2"
+    dl_file="${2:-"${1##*/}"}"
+    dl_file="${dl_file//\./-}"
     target_dir="$dl_path/$dl_file"
 
     if [ -d "$target_dir" ]; then
         sudo rm -fr "$target_dir"
     fi
 
-        echo "Downloading $dl_url as $dl_file"
+    echo "Downloading $dl_url as $dl_file"
+    if ! git clone -q "$dl_url" "$target_dir"; then
+        printf "\n%s\n\n" "The script failed to clone the git repository \"$target_dir\" and will try again in 10 seconds..."
+        sleep 10
         if ! git clone -q "$dl_url" "$target_dir"; then
-            printf "\n%s\n\n%s\n\n" \
-                "The script failed to clone the git repository: $target_dir" \
-                'Sleeping for 10 seconds before trying again.'
-            sleep 10
-            if ! git clone -q "$dl_url" "$target_dir"; then
-                fail_fn "The script failed to clone \"$target_dir\" twice and will now exit the build."
-            fi
+            fail_fn "The script failed to clone \"$target_dir\" twice and will now exit the build."
         fi
-        echo -e "Succesfully cloned the directory: $target_dir\\n"
+    else
+        echo -e "Succesfully cloned: $target_dir\\n"
+    fi
 
     cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir"
 }
@@ -271,10 +273,6 @@ installed() { return $(dpkg-query -W -f '${Status}\n' "$1" 2>&1 | awk '/ok insta
 
 install_deb_files_fn()
 {
-    printf "\n%s\n%s\n" \
-        'Installing required debian packages' \
-        '=========================================='
-
     cd "$packages"/deb-files || exit 1
 
     printf "\n%s\n%s\n" \
@@ -437,10 +435,11 @@ fi
 
 pkgs_fn()
 {
-    pkgs=("$1" alien asciidoc autoconf automake autopoint binutils bison build-essential ccache cmake curl flex gettext gimp-data git \
-          gperf jq libfreetype-dev libgc-dev libgl2ps-dev libglib2.0-dev libgraphviz-dev libgs-dev libheif-dev libpango1.0-dev libpng-dev \
-          libpstoedit-dev libraw-dev librsvg2-dev librust-bzip2-dev libsdl2-dev libtcmalloc-minimal4 libtool libzip-dev m4 meson nasm \
-          ninja-build php-cli pstoedit xmlto)
+    pkgs=("$1" alien asciidoc autoconf automake autopoint binutils bison build-essential ccache cmake
+          curl flex gettext gimp-data git gperf jq libfreetype-dev libgc-dev libgl2ps-dev libglib2.0-dev
+          libgraphviz-dev libgs-dev libheif-dev libpango1.0-dev libpng-dev libpstoedit-dev libraw-dev
+          librsvg2-dev librust-bzip2-dev libsdl2-dev libtcmalloc-minimal4 libltdl-dev libtool libzip-dev
+          m4 meson nasm ninja-build php-cli pstoedit xmlto yasm)
 
     for pkg in ${pkgs[@]}
     do
@@ -449,7 +448,7 @@ pkgs_fn()
         fi
     done
 
-    if [ -n "${missing_pkgs-}" ]; then
+    if [ -n "$missing_pkgs" ]; then
         for i in "$missing_pkgs"
         do
             sudo apt -y install $i
@@ -493,35 +492,8 @@ fi
 # FIGURE OUT WHICH COMPILERS TO USE
 #
 
-if which 'gcc-13' &>/dev/null; then
-    export CC='gcc-13'
-elif which 'gcc-12' &>/dev/null; then
-    export CC='gcc-12'
-elif which 'gcc-11' &>/dev/null; then
-    export CC='gcc-11'
-elif which 'gcc-10' &>/dev/null; then
-    export CC='gcc-10'
-elif which 'gcc-9' &>/dev/null; then
-    export CC='gcc-9'
-elif which 'gcc' &>/dev/null; then
-    export CC='gcc'
-fi
-
-if which 'g++-13' &>/dev/null; then
-    export CXX='g++-13'
-elif which 'g++-12' &>/dev/null; then
-    export CXX='g++-12'
-elif which 'g++-11' &>/dev/null; then
-    export CXX='g++-11'
-elif which 'g++-10' &>/dev/null; then
-    export CXX='g++-10'
-elif which 'g++-9' &>/dev/null; then
-    export CXX='g++-9'
-elif which 'g++' &>/dev/null; then
-    export CXX='g++'
-fi
-
-export CXXFLAGS='-g -O3 -march=native -Wno-error'
+type -P gcc &>/dev/null && export CC=gcc CXX=g++
+export CXXFLAGS='-g -O3 -march=native -mtune=native'
 
 #
 # INSTALL OFFICIAL IMAGEMAGICK LIBS
@@ -533,13 +505,7 @@ if build 'magick-libs' "$g_ver"; then
     if ! curl -Lso "magick-libs-$g_ver.rpm" "https://imagemagick.org/archive/linux/CentOS/x86_64/ImageMagick-libs-$g_ver.x86_64.rpm"; then
         fail_fn 'Failed to download the magick-libs file.'
     fi
-    sudo alien -d "magick-libs-$g_ver.rpm"
-    if ! sudo dpkg -i "imagemagick-libs_7.1.1-12_amd64.deb"; then
-        printf "\n%s\n%s\n\n" \
-            "DPKG failed to install: magick-libs-$g_ver.deb" \
-            'The script will probably stil work so keep going.'
-        read -p 'Press enter to continue.'
-    fi
+    sudo alien -d -i "magick-libs-$g_ver.rpm"
     build_done 'magick-libs' "$g_ver"
 fi
 
@@ -669,19 +635,20 @@ if build 'webp' 'git'; then
 fi
 
 if build 'c2man' 'git'; then
-    download_git 'https://github.com/fribidi/c2man.git' 'c2man-git'
-    execute ./Configure -desO -D prefix="$workspace" -D bin="$workspace"/bin -D bash='/bin/bash' -D cc='/usr/bin/cc' \
-        -D d_gnu='/usr/lib/x86_64-linux-gnu' -D find='/usr/bin/find' -D gcc="$CC" -D gzip='/usr/bin/gzip' \
-        -D installmansrc="$workspace"/share/man -D ldflags="-L$workspace/lib" -D less='/usr/bin/less' \
-        -D libpth="$workspace/lib /usr/local/lib /lib /usr/lib" \
-        -D locincpth="$workspace/include /usr/local/include /opt/local/include /usr/gnu/include /opt/gnu/include /usr/GNU/include /opt/GNU/include" \
-        -D yacc='/usr/bin/yacc' -D loclibpth="$workspace/lib /usr/local/lib /opt/local/lib /usr/gnu/lib /opt/gnu/lib /usr/GNU/lib /opt/GNU/lib" \
-        -D make='/usr/bin/make' -D more='/usr/bin/more' -D osname='Ubuntu' -D perl='/usr/bin/perl' -D privlib="$workspace"/lib/c2man \
-        -D privlibexp="$workspace"/lib/c2man -D sleep='/usr/bin/sleep' -D tail='/usr/bin/tail' -D tar='/usr/bin/tar' -D uuname='Linux' \
-        -D vi='/usr/bin/vi' -D zip='/usr/bin/zip'
+    download_git 'https://github.com/fribidi/c2man.git'
+    execute ./Configure -desO -D prefix="$workspace" -D bin="$workspace/bin" -D bash="$(type -P bash)" \
+        -D cc='/usr/bin/cc' -D d_gnu='/usr/lib/x86_64-linux-gnu' -D find="$(type -P find)" -D gcc='/usr/bin/gcc' \
+        -D gzip="$(type -P gzip)" -D installmansrc="$workspace/share/man" -D ldflags="$LDFLAGS" \
+        -D less="$(type -P less)" -D libpth="$workspace/lib /usr/lib /lib" \
+        -D locincpth="$workspace/include /usr/local/include /usr/include" -D yacc="$(type -P yacc)" \
+        -D loclibpth="$workspace/include /usr/local/lib /usr/lib" -D make="$(type -P make)" \
+        -D more="$(type -P more)" -D osname="$OS" -D perl="$(type -P perl)" -D privlib="$workspace/lib/c2man" \
+        -D privlibexp="$workspace/lib/c2man" -D sleep="$(type -P sleep)" -D tail="$(type -P tail)" \
+        -D tar="$(type -P tar)" -D uuname="$(uname -s)" -D vi="$(type -P vi)" -D zip="$(type -P zip)"
     execute make depend
-    execute make "-j$cpu_threads"
+    execute make "-j$(($cpu_threads-1))"
     execute sudo make install
+    execute make distclean
     build_done 'c2man' 'git'
 fi
 
