Update build-dl-tools

diff --git a/Bash/Installer Scripts/GitHub Projects/Download Tools/build-dl-tools b/Bash/Installer Scripts/GitHub Projects/Download Tools/build-dl-tools
--- a/Bash/Installer Scripts/GitHub Projects/Download Tools/build-dl-tools
+++ b/Bash/Installer Scripts/GitHub Projects/Download Tools/build-dl-tools
@@ -9,41 +9,48 @@
 ##  - Debian 10 / 11 / 12
 ##  - Ubuntu 22.04 / 20.04 / 18.04
 ##
-##  Updated: 07.06.23
+##  Updated: 08.16.23
 ##
-##  Added the ability to specify suffixes before compiling
-##  Added aria2c with custom max connections set from 16 to 64
+##  Added: the ability to specify suffixes before compiling
+##  Added: aria2c with custom max connections set from 16 to 128
+##  Added: openssl 3.2.0 to crate the required ssl/certs directory
 ##
 ##  Fixed: WGET bad download URL
 ##  Fixed: The success_fn displaying the new versions
 ##
-##  Script version: 3.1
+##  Script version: 4.0
 ##
 ########################################################################
 
 clear
 
-script_ver=3.1
+script_ver=4.0
+install_prefix=/usr/local
 cwd="$PWD"/dltools-build-script
 packages="$cwd"/packages
 workspace="$cwd"/workspace
-CFLAGS='-g -O3 -march=native -Wl,-s -Wl,-Bsymbolic -Wl,--gc-sections'
-LDFLAGS="-L$workspace/lib64 -L$workspace/lib -L/usr/lib/x86_64-linux-gnu"
-LDFLAGS+=' -L/usr/local/lib64 -L/usr/local/lib -L/usr/lib/gcc/x86_64-linux-gnu -L/usr/lib -L/lib'
-CPPFLAGS="-I$workspace/include -I/usr/local/include -I/usr/include"
-cert_dir=/etc/ssl/certs
-pem_file=cacert-2023-05-30.pem
+cert_dir=/usr/lib/ssl/certs
+pem_file=cacert-05.30.23.pem
 pem_target="$cert_dir/$pem_file"
 user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
 repo=https://github.com/slyfox1186/script-repo
+LDFLAGS="-L$workspace/lib64 -L$workspace/lib -L$workspace/x86_64-linux-gnu -L/usr/local/lib64 -L/usr/local/lib -L/usr/local/cuda/nvvm/lib64"
+LDFLAGS+=' -L/usr/local/cuda/targets/x86_64-linux/lib -L/usr/lib64 -L/usr/lib -L/usr/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -L/lib64 -L/lib'
+CPPFLAGS="-I$workspace/include -I/usr/local/include -I/usr/include"
+LIBS="$(pkg-config --libs libuv) $(pkg-config --libs libgcrypt) $(pkg-config --libs nettle)"
 debug=OFF
 
-# DETERMINE WHICH DOWNLOADER IS AVAILABLE
-if ! which curl &>/dev/null; then
-    dl_tool='wget --show-progress -cqO'
-else
-    dl_tool='curl -A "$user_agent" -Lso'
-fi
+#
+# SET THE C & C++ COMPILERS
+#
+
+export CC=gcc CXX=g++
+
+#
+# SET THE COMPILER OPTIMIZATION FLAGS TO TUNE THE BUILD FOR THE SPECIFIC COMPUTER RUNNING THE SCRIPT
+#
+
+export {CFLAGS,CXXFLAGS}='-g -O2 -ffunction-sections -fdata-sections -pipe -march=native -Wl,-s -Wl,-Bsymbolic -Wl,--gc-sections'
 
 #
 # CREATE OUTPUT DIRECTORIES
@@ -200,10 +207,11 @@ success_fn()
     curl_ver="$($curl_ver --version | grep -Eo '[0-9\.]+' | sed -n 1p)"
     aria2c_ver="$($aria2c_ver --version | grep -Eo '[0-9\.]+$' | sed -n 1p)"
 
-    printf "\n%s\n\n" "The updated versions are:"
-    printf "%s\n" "WGET: $wget_ver"
-    printf "%s\n" "cURL: $curl_ver"
-    printf "%s\n\n" "Aria2c: $aria2c_ver"
+    clear
+    printf "%s\n\n" "The updated versions are:"
+    printf "%s\n" "ARIA:    $aria2c_ver"
+    printf "%s\n" "CURL:    $curl_ver"
+    printf "%s\n" "WGET:    $wget_ver"
 }
 
 #
@@ -220,6 +228,7 @@ git_1_fn()
     if curl_cmd="$(curl -m 10 -sSL "https://api.github.com/repos/$github_repo/$github_url")"; then
         g_ver="$(echo "$curl_cmd" | jq -r '.[0].name' 2>/dev/null)"
         g_ver="${g_ver#cares-}"
+        g_ver="${g_ver#aria2 }"
         g_ver="${g_ver#nghttp2 v}"
         g_ver="${g_ver#nghttp3 v}"
         g_ver="${g_ver#OpenSSL }"
@@ -379,18 +388,18 @@ pkgs_fn()
 {
     local pkg pkgs missing_pkgs
 
-    pkgs=("$1" apt-transport-https apt-utils autoconf autogen automake autopoint autotools-dev
-          build-essential bzip2 ca-certificates ccache clang cmake curl gfortran git google-perftools
-          graphviz jq lcov libaria2-0 libaria2-0-dev libc-ares-dev libcppunit-dev libcunit1-dev libcurl4
-          libcurl4-gnutls-dev libdmalloc-dev libec-dev libedit-dev libev-dev libevent-dev libexiv2-27
-          libexpat1-dev libgcc-12-dev libgcrypt20-dev libgexiv2-2 libgimp2.0 libgmp3-dev libgmp-dev
-          libgnutls28-dev libgpg-error-dev libgtk-4-doc libicu-dev libticonv-dev libjemalloc-dev libkrb5-3
-          libldap2-dev libldap-dev liblttng-ust-dev liblzma-dev libmbedtls-dev libnghttp2-dev libntlm0-dev
-          libparted-dev libpng-dev libpsl-dev librtmp-dev libsqlite3-dev libssh2-1-dev libssh-dev libssl-dev
-          libtinfo5 libtinfo-dev libtool libunistring-dev libunwind8 libuv1-dev libxml2-dev libzstd-dev lzip m4
-          nettle-dev openjdk-17-jdk-headless openssh-server pkg-config python3 python3-dev python3-numpy
-          python3-packaging python3-pip python3-pytest python3-setuptools python3-wheel re2c rsync sudo unzip
-          wget zip zlib1g zlib1g-dev)
+    pkgs=("$1" apt-transport-https apt-utils autoconf autoconf-archive autogen automake autopoint
+          autotools-dev build-essential bzip2 ca-certificates ccache clang cmake curl gfortran git
+          google-perftools graphviz jq lcov libaria2-0 libaria2-0-dev libc-ares-dev libcppunit-dev
+          libcunit1-dev libcurl4 libcurl4-gnutls-dev libdmalloc-dev libec-dev libedit-dev libev-dev
+          libevent-dev libexiv2-27 libexpat1-dev libgcc-12-dev libgcrypt20-dev libgexiv2-2 libgimp2.0
+          libglib2.0-dev libgmp3-dev libgmp-dev libgnutls28-dev libgpg-error-dev libgtk-4-doc libicu-dev
+          libticonv-dev libjemalloc-dev libkrb5-3 libldap2-dev libldap-dev liblttng-ust-dev liblzma-dev
+          libmbedtls-dev libnghttp2-dev libntlm0-dev libparted-dev libpth-dev libpng-dev libpsl-dev
+          librtmp-dev libsqlite3-dev libssh2-1-dev libssh-dev libssl-dev libtinfo5 libtinfo-dev libtool
+          libunistring-dev libunwind8 libuv1-dev libxml2-dev libzstd-dev lzip m4 nettle-dev openjdk-17-jdk-headless
+          openssh-server pkg-config python3 python3-dev python3-numpy python3-packaging python3-pip python3-pytest
+          python3-setuptools python3-wheel re2c rsync sudo unzip wget zip zlib1g zlib1g-dev libncurses-dev libncurses5-dev)
 
     for pkg in ${pkgs[@]}
     do
@@ -399,11 +408,14 @@ pkgs_fn()
         fi
     done
 
+   printf "\n%s\n%s\n" \
+        'Installing required apt packages' \
+        '================================================'
+
     if [ -n "$missing_pkgs" ]; then
-        printf "\n%s\n%s\n" \
-            'Installing required apt packages' \
-            '================================================'
         sudo apt -y install $missing_pkgs
+        sudo apt -y autoremove
+        printf "%s\n" 'The required APT packages were installed.'
     else
         printf "%s\n" 'The required APT packages are already installed.'
     fi
@@ -413,63 +425,68 @@ pkgs_fn()
 # DETERMINE WHAT VERSION OF LINUX WE ARE ON
 #
 
-ubuntu_os_check_fn()
+if [ -f /etc/os-release ]; then
+    source /etc/os-release
+    OS="$NAME"
+    VER="$VERSION_ID"
+elif type lsb_release >/dev/null 2>&1; then
+    OS="$(lsb_release -si)"
+    VER="$(lsb_release -sr)"
+elif [ -f /etc/lsb-release ]; then
+    source /etc/lsb-release
+    OS="$DISTRIB_ID"
+    VER="$DISTRIB_RELEASE"
+elif [ -f /etc/debian_version ]; then
+    OS=Debian
+    VER="$(cat /etc/debian_version)"
+else
+    OS="$(uname -s)"
+    VER="$(uname -r)"
+fi
+
+debian_os_check_fn()
 {
-    ubuntu_os="$(lsb_release -r 2>/dev/null | grep -Eo '[0-9\.]+$')"
-    case "$ubuntu_os" in
-        23.04|22.04)
-                        pkgs_fn 'libnghttp3-dev libgsasl-dev libngtcp2-dev language-pack-en libcurl4-gnutls-dev'
-                        http3_flag='true'
-                        ;;
-        *)              fail_fn 'Could not detect the Ubuntu version.';;
+    case "$VER" in
+            10|11|12)
+                            pkgs_fn 'libnghttp3-dev libgsasl-dev libngtcp2-dev libcurl4-gnutls-dev'
+                            http3_flag=true
+                            ;;
+            *)              fail_fn 'Could not detect the Ubuntu version.';;
     esac
 }
 
-linux_ver()
+ubuntu_os_check_fn()
 {
-    if [ -f /etc/os-release ]; then
-        source /etc/os-release
-        OS="$NAME"
-    elif type lsb_release >/dev/null 2>&1; then
-        OS="$(lsb_release -si)"
-    elif [ -f /etc/lsb-release ]; then
-        source /etc/lsb-release
-        OS="$DISTRIB_ID"
-    elif [ -f /etc/debian_version ]; then
-        OS=Debian
-    else
-        OS="$(uname -s)"
-    fi
+    case "$VER" in
+            23.04|22.04)
+                            pkgs_fn 'libnghttp3-dev libgsasl-dev libngtcp2-dev language-pack-en libcurl4-gnutls-dev'
+                            http3_flag=true
+                            ;;
+            *)              fail_fn 'Could not detect the Ubuntu version.';;
+    esac
 }
-linux_ver
 
 #
 # TEST THE OS AND ITS VERSION
 #
 
 case "$OS" in
-    'Debian GNU/Linux')
-                            pkgs_fn 'libnghttp3-dev libgsasl-dev libngtcp2-dev libcurl4-gnutls-dev'
-                            http3_flag='true'
-                            ;;
-    'Ubuntu')               ubuntu_os_check_fn;;
-    *)                      fail_fn 'Could not detect the OS architecture.';;
+    Debian*)    debian_os_check_fn;;
+    Ubuntu)     ubuntu_os_check_fn;;
+    *)          fail_fn 'Could not detect the OS architecture.';;
 esac
 
 #
-# SET THE C & C++ COMPILERS
+# INSTALL OPENSSL TO SET THE CA CERT SSL DIRECTORY
 #
 
-if ! which gcc &>/dev/null; then
-    fail_fn 'Please install "gcc" to continue.'
+if [ ! -d "$cert_dir" ]; then
+    if ! "$(type -P bash)" <(curl -A "$user_agent" -sSL \
+        'https://raw.githubusercontent.com/slyfox1186/script-repo/main/Bash/Installer%20Scripts/GitHub%20Projects/build-openssl'); then
+        fail_fn 'Failed to install OpenSSL.'
+    fi
 fi
-export CC=gcc CXX=g++
-
-#
-# SET THE COMPILER OPTIMIZATION FLAGS TO TUNE THE BUILD FOR THE SPECIFIC COMPUTER RUNNING THE SCRIPT
-#
-
-export {CFLAGS,CXXFLAGS}='-g -O2 -flto -ffunction-sections -fdata-sections -pipe -march=native'
+clear
 
 #
 # INSTALL CA CERTS FROM CURL'S OFFICIAL WEBSITE
@@ -479,7 +496,7 @@ if [ ! -f "$pem_target" ]; then
     printf "%s\n%s\n\n" \
         'Download the latest security certificate' \
         '================================================'
-    execute $dl_tool "$packages/$pem_file" "https://curl.se/ca/$pem_file"
+    execute curl -A "$user_agent" -Lso "$packages/$pem_file" "https://curl.se/ca/$pem_file"
     execute sudo cp -f "$packages/$pem_file" "$pem_target"
 fi
 
@@ -490,7 +507,7 @@ fi
 git_ver_fn 'madler/zlib' '1' 'T'
 if build 'zlib' "$g_ver"; then
     download "$g_url" "zlib-$g_ver.tar.gz"
-    execute ./configure --prefix="$workspace"             \
+    execute ./configure --prefix="$workspace"              \
                          --libdir="$workspace"/lib         \
                          --includedir="$workspace"/include \
                          --sharedlibdir="$workspace"/lib
@@ -529,7 +546,7 @@ git_ver_fn 'c-ares/c-ares' '1' 'R'
 g_ver="${g_ver//cares-/}"
 g_tag="${g_ver//\./_}"
 if build 'c-ares' "$g_ver"; then
-    download "https://codeload.github.com/c-ares/c-ares/tar.gz/refs/tags/cares-$g_tag" "c-ares-$g_ver.tar.gz"
+    download "$g_url" "c-ares-$g_ver.tar.gz"
     execute autoupdate
     execute autoreconf -fi
     execute ./configure --prefix="$workspace"  \
@@ -555,20 +572,20 @@ fi
 
 git_ver_fn 'jemalloc/jemalloc' '1' 'T'
 if build 'jemalloc' "$g_ver"; then
-    download "https://codeload.github.com/jemalloc/jemalloc/tar.gz/refs/tags/$g_ver" "jemalloc-$g_ver.tar.gz"
+    download "$g_url" "jemalloc-$g_ver.tar.gz"
     execute ./autogen.sh
     execute ./configure --prefix="$workspace"  \
-                         --enable-autogen      \
-                         --enable-lazy-lock    \
-                         --enable-static       \
-                         --enable-xmalloc      \
                          --disable-debug       \
                          --disable-doc         \
                          --disable-fill        \
                          --disable-log         \
-                         --disable-shared      \
                          --disable-prof        \
-                         --disable-stats
+                         --disable-shared      \
+                         --disable-stats       \
+                         --enable-autogen      \
+                         --enable-lazy-lock    \
+                         --enable-static       \
+                         --enable-xmalloc
     execute make "-j$cpu_threads"
     execute make install
     execute make clean
@@ -580,7 +597,7 @@ if build 'brotli' "$g_ver"; then
     download "$g_url" "brotli-$g_ver.tar.gz"
     mkdir build
     cd build || exit 1
-    execute ./configure-cmake --prefix="$workspace"
+    execute ../configure-cmake --prefix="$workspace"
     execute make "-j$cpu_threads"
     execute make test
     execute make install
@@ -603,15 +620,16 @@ if build 'wget' 'latest'; then
         execute sudo update-ca-certificates
     fi
     execute autoconf
-    ./configure --prefix=/usr/local  \
-                 --enable-threads    \
-                 --with-cares        \
-                 --with-metalink     \
-                 --with-openssl=auto \
+    ./configure --prefix="$install_prefix" \
+                 --enable-threads          \
+                 --with-cares              \
+                 --with-metalink           \
+                 --with-openssl=auto       \
                  --with-ssl=gnutls "$wsuffix"
     execute make "-j$cpu_threads"
     execute sudo make install
     execute make clean
+    build_done 'wget' 'latest'
 fi
 
 #
@@ -644,13 +662,14 @@ if build 'curl' "$g_ver"; then
     curl_with_opts=(--with-{gnutls=/usr/include,libssh2,nghttp2=/usr/include})
     curl_with_opts+=(--with-{ca-bundle="$pem_target",ca-fallback,ca-path="$cert_dir",secure-transport})
     execute autoreconf -fi
-    ./configure --prefix=/usr/local        \
+    ./configure --prefix="$install_prefix"  \
                  "${curl_disable_opts[@]}"  \
                  "${curl_enable_opts[@]}"   \
                  "${curl_with_opts[@]}" "$csuffix" "$http3_flag"
     execute make "-j$cpu_threads"
     execute sudo make install
     execute make clean
+    build_done 'curl' "$g_ver"
 fi
 
 #
@@ -662,22 +681,37 @@ if [ -n "$aria2c_suffix" ]; then
     asuffix="--program-suffix=$aria2c_suffix"
 fi
 
-# ARIA2C FAILS TO BUILD USING GCC
-export CC=clang CXX=clang++
-
+git_ver_fn 'aria2/aria2' '1' 'T'
 if build 'aria2' '1.36.0'; then
     download 'https://github.com/aria2/aria2/releases/download/release-1.36.0/aria2-1.36.0.tar.xz'
     # INCREASE THE MAX NUMBER OF CONNECTIONS FROM 16 TO 128
-    sed -i 's/1, 16/1, 128/g' src/OptionHandlerFactory.cc
-    ./configure --prefix=/usr/local        \
-                         --disable-nls     \
-                         --disable-shared  \
-                         --disable-werror  \
-                         --enable-libaria2 \
-                         --enable-static   \
-                         --with-libuv      \
-                         --with-jemalloc   \
-                         --with-ca-bundle="$pem_target" "$asuffix"
+    sed -i 's/1, 16/1, 128/g' 'src/OptionHandlerFactory.cc'
+    mkdir build
+    cd build || exit 1
+    ../configure --prefix="$install_prefix"                     \
+                 --{build,host,target}="$pc_type"               \
+                 --disable-nls                                  \
+                 --disable-shared                               \
+                 --disable-werror                               \
+                 --enable-libaria2                              \
+                 --enable-static                                \
+                 --with-ca-bundle="$pem_target"                 \
+                 --with-libgcrypt=/usr                          \
+                 --with-libiconv-prefix=/usr                    \
+                 --with-libintl-prefix=/usr                     \
+                 --with-libuv                                   \
+                 --with-jemalloc                                \
+                 --with-openssl                                 \
+                 --with-pic                                     \
+                 --without-gnutls                               \
+                 ARIA2_STATIC=yes                               \
+                 LIBS="$LIBS"                                   \
+                 LIBUV_CFLAGS='-I/usr/include'                  \
+                 EXPAT_LIBS="$(pkg-config --libs expat)"        \
+                 CPPFLAGS='-I/usr/local/include -I/usr/include' \
+                 PKG_CONFIG="$(type -P pkg-config)"             \
+                 PKG_CONFIG_PATH="$PKG_CONFIG_PATH"             \
+                 LDFLAGS="$LDFLAGS"
     execute make "-j$cpu_threads"
     execute sudo make install
     build_done 'aria2' '1.36.0'
