Update build-tilix

diff --git a/Bash/Installer Scripts/Tilix Terminal/build-tilix b/Bash/Installer Scripts/Tilix Terminal/build-tilix
--- a/Bash/Installer Scripts/Tilix Terminal/build-tilix
+++ b/Bash/Installer Scripts/Tilix Terminal/build-tilix
@@ -204,30 +204,25 @@ installed() { return $(dpkg-query -W -f '${Status}\n' "${1}" 2>&1 | awk '/ok ins
 # INSTALL APT PACKAGES
 #
 
-pkgs_fn()
-{
-    local pkg pkgs missing_pkgs
+pkgs=(autoconf autogen automake build-essential ccache curl gettext git gtk-doc-tools libgtk-3-dev libgtk-4-dev
+      libgtkd-3-dev libhwy-dev libtool libtool-bin m4 ninja-build pkg-config python3-nautilus tilix tilix-common)
 
-    pkgs=(autoconf autogen automake build-essential ccache curl gettext git gtk-doc-tools libgtk-3-dev libgtk-4-dev
-          libgtkd-3-dev libhwy-dev libtool libtool-bin m4 ninja-build pkg-config python3-nautilus tilix tilix-common)
-
-    for pkg in ${pkgs[@]}
-    do
-        if ! installed "${pkg}"; then
-            missing_pkgs+=" ${pkg}"
-        fi
-    done
-
-    if [ -n "${missing_pkgs}" ]; then
-        if sudo apt -y install ${missing_pkgs}; then
-            echo 'The required APT packages were installed.'
-        else
-            fail_fn "These required APT packages failed to install: ${missing_pkgs}"
-        fi
-    else
-        echo 'The required APT packages are already installed.'
+for pkg in ${pkgs[@]}
+do
+    if ! installed "${pkg}"; then
+        missing_pkgs+=" ${pkg}"
     fi
-}
+done
+
+if [ -n "${missing_pkgs}" ]; then
+    if sudo apt -y install ${missing_pkgs}; then
+        echo 'The required APT packages were installed.'
+    else
+        fail_fn "These required APT packages failed to install: ${missing_pkgs}"
+    fi
+else
+    echo 'The required APT packages are already installed.'
+fi
 
 #
 # DOWNLOAD D COMPILER
